e_msoft.h
general.h
main.c
options.c
options.h
read.h
routines.c

After #200 has been merged, there are still some leftovers of those old unmaintained platforms. This patch cleans up those leftovers.

Cleanup leftovers of unmaintained platforms

---

Units/zephir-return-hint.d/args.ctags
Units/zephir-return-hint.d/expected.tags
Units/zephir-return-hint.d/input.zep
Units/zephir-simple.d/args.ctags
Units/zephir-simple.d/expected.tags
Units/zephir-simple.d/input.zep
parsers.h
php.c

Support for [Zephir](http://zephir-lang.com/), from parsers changes I made [a while back](https://github.com/geany/geany/pull/270).

Add Zephir support

---

Units/verilog-basic.d/expected.tags
Units/verilog-basic.d/input.v
Units/verilog-sv-basic.d/expected.tags
Units/verilog-sv-basic.d/input.sv
verilog.c

DISCLAIMER: I have no clue about Verilog, so this requires reviewing.
This is based on the work of a (mostly anonymous) Geany user from some time ago.
Also, we may need to write a test of our own, because I grabbed this one from SO, and while no one will ever care this might violate their copyright.
@vhda could you check this out and comment?

verilog: Generate tags for `genvar` statements

---

Units/cxx11enum.cpp.d/expected.tags
Units/d-size_t-wchar_t-alias.d/expected.tags
Units/simple.d.t/expected.tags
ctags.h
docs/f-xcmd.rst

core: Revert PROGRAM_NAME to "Exuberant Ctags"

---

Units/simple.d.t/expected.tags
Units/simple.d.t/input.d
c.c

I.e. class, struct, interface, union.

D: Parse function & aggregate declaration templates

---

Units/cxx11enum.cpp.d/expected.tags
Units/cxx11enum.cpp.d/input.cpp
c.c
docs/tracking.rst

This time, the PR directly includes Geany's commit, cherry-picked from their repo by b4n (and again by me from his). I added a commit to update the cxx11enum.cpp unit to test enum class/struct's, and another to update docs/tracking.rst regarding features imported from Geany.

C++: support C++11 enum class/struct

---

Units/parser-ada.r/ada-partial-bug2.d/input.adb
Units/parser-ada.r/ada-partial-type.d/expected.tags
Units/parser-ada.r/ada-partial-type.d/input.ads
ada.c

Fix two bugs in the Ada parser found by `make noise`.

Ada noise fixes

---

beta.c

Found by Miloslav Nenadál (@nenadalm) running `make fuzz VG=1`.

beta: Fix a below-bounds buffer access

---

EXTENDING.html

Found some typo in the example code. I also added a hint for debugging,
I would found it useful.

small changes in EXENDING.html

---

win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

clojure missing from vs2013 configuration

---

configure.ac
lxcmd.c

Based on a patch by Lubos Kosco, thanks!
Closes #268.

lxcmd: Fix build on Solaris

---

Units/make.comment-in-rule.d/expected.tags
Units/make.comment-in-rule.d/input.mak
Units/make.gnumake-pattern-rules.d/expected.tags
Units/make.gnumake-pattern-rules.d/input.mak
Units/make.multi-target.d/expected.tags
Units/make.multi-target.d/input.mak
Units/make.target-with-parentheses.b/expected.tags
Units/make.target-with-parentheses.b/input.mak
Units/make.target-with-parentheses.d/expected.tags
Units/make.target-with-parentheses.d/input.mak
Units/make.variable-on-cmdline.b/expected.tags
Units/make.variable-on-cmdline.b/input.mak
Units/make.variable-on-cmdline.d/expected.tags
Units/make.variable-on-cmdline.d/input.mak
Units/simple.mak.t/expected.tags
make.c

A follow up to #264 fixing all bugs I know in Make support, and adding a few features.  Fixes all our current tests, and adds a few.

make: Various fixes and improvements

---

readtags.c

readtags: add help(-h) option

---

Makefile.in
docs/build.rst
docs/exuberant-ctags.rst

Utilize sparse semantic parser for C as fussy syntax checker

---

README.md

There is no easy way to find the basic steps how to build this project. This PR fixes that.

Add basic information how to build and install to README

---

Units/clojure.d/expected.tags
Units/clojure.d/input.clj
Units/cork-etags.d/expected.tags-e
Units/cork-etags.d/input.clj
Units/cork-xref.d/expected.tags-x
Units/cork-xref.d/input.clj
docs/internal.rst
docs/output-tag-stream.svg
docs/units.rst
main/entry.c
main/entry.h
main/parse.c
main/parse.h
misc/units
parsers/clojure.c

See "docs: write about cork API" about API.
New API is just applies to clojure.c. If this patch set is accepted, I will work on the other
parsers.

Cork, new API for holding and recording scope information (resubmitting)

---

parsers/clojure.c
parsers/objc.c
parsers/ocaml.c
parsers/perl.c
parsers/python.c
parsers/rust.c
parsers/sml.c
parsers/verilog.c

Closes #324.
---
This is the naive approach fixing every call site.

Do not generate tags for disabled kinds

---

Units/fortran-extends-qualifier.d/expected.tags
Units/fortran-extends-qualifier.d/input.f90
parsers/fortran.c

Recognize Fortran 2003 type extension feature which introduces OOP for Fortran language.

Fortran: recognize extends qualifier

---

docs/developers.rst

Per https://github.com/universal-ctags/ctags/issues/340#issuecomment-108553629

Adding myself to developers.rst

---

docs/osx.rst
docs/universal-ctags.rst

Per https://github.com/universal-ctags/ctags/issues/340#issuecomment-108603580

Initial pass at OS X documentation

---

Units/dotted-names.d/expected.tags
Units/dotted-names.d/input.json
main/vstring.c
main/vstring.h
parsers/json.c

json: Fix handling of tags containing a dot

---

docs/developers.rst

I'm a Fortran programmer and would like to be one of the developers of universal-ctags.

Add Qingming He to docs/developers.rst

---

main/keyword.c

Problem 1:
There are nearly 1000 keywords from all the used languages and the size
of the table is 128 so there are too many synonyms.
Problem 2:
Even after increasing the number to 2048 the hashing function behaves
poorly causing too many unnecessary synonyms. Using the string hashing
function used in glib improves the situation (also using the prime
modulus).
Problem 3:
Many languages use the same keywords (do, import, try, etc.) and these are
synonyms in the hash table. Incorporate the language to the hashing function
so identical keywords from different languages are placed at different
indexes in the table.
This patch significantly reduces the number of synonyms and the length
of synonym sequences. For the Go parser the lookup function performs twice
as fast (the lookup takes around …

Make the hash table used in keywords.c work like a hash table

---

Units/nim-test_input1.d/expected.tags
Units/nim-test_input1.d/input.nim
Units/nim-test_input2.d/expected.tags
Units/nim-test_input2.d/input.nim
Units/nim-test_input3.d/expected.tags
Units/nim-test_input3.d/input.nim
Units/nim-test_input4.d/expected.tags
Units/nim-test_input4.d/input.nim
main/parsers.h
mk_mingw.mak
mk_mvc.mak
parsers/nim.c
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

I use it daily, I hope others can get benefit too from this parser.

add nim language parser

---

Units/parser-fortran.r/fortran-abstract-interface.d/args.ctags
Units/parser-fortran.r/fortran-abstract-interface.d/expected.tags
Units/parser-fortran.r/fortran-abstract-interface.d/input.f90
parsers/fortran.c

+ Parse abstract interface
+ Parse import statement inside interface
+ Parse class statement

Fortran abstract interface

---

Units/parser-fortran.r/fortran-associate.d/expected.tags
Units/parser-fortran.r/fortran-associate.d/input.f90
Units/parser-fortran.r/fortran-block.d/expected.tags
Units/parser-fortran.r/fortran-block.d/input.f90
Units/parser-fortran.r/fortran-forall.d/expected.tags
Units/parser-fortran.r/fortran-forall.d/input.f90
parsers/fortran.c

Parse **forall**, **associate**, **block** secondary keywords.

Fortran: more secondary keywords

---

Units/parser-fortran.r/fortran-square-parens.d/expected.tags
Units/parser-fortran.r/fortran-square-parens.d/input.f90
parsers/fortran.c

Import from Geany https://github.com/geany/geany/commit/1c0fa99e1d84b0331d65e56dcab4002f0006ccb1

Fortran 2003 array syntax and Fortran 2008 coarray

---

Units/parser-objectivec.r/objectivec_protocol.h.d/expected.tags
parsers/objc.c

here is the first property and protocol conflict bug.
later I may write some unittest for the second, parse property bug.

fix property Protocol type error

---

Makefile.in

The output of tmain target is not so polished but the target itself is helpful.

Run tmain under travis (2days)

---

Makefile.in
Units/gdbinit-simple.d/args.ctags
Units/gdbinit-simple.d/expected.tags
Units/gdbinit-simple.d/input.gdb
data/optlib/gdbinit.ctags
misc/tinst

Gdbinit parser(2 days)

---

main/options.h
main/parse.h

main: Fix double inclusion of OptionLoadingStage typedef

---

.travis.yml
README.md

Enable coveralls

---

.travis.yml

See: http://docs.travis-ci.com/user/migrating-from-legacy/

Make Travis-CI faster(1 day)

---

Units/perl6-bunch1.d/expected.tags
Units/perl6-bunch1.d/input.pm
Units/perl6-bunch2.d/expected.tags
Units/perl6-bunch2.d/input.pm
docs/guessing.rst
main/parse.c
main/parse.h
main/parsers.h
main/selectors.c
main/selectors.h
parsers/perl.c
parsers/perl6.c
source.mak

This request is instead of request #479. As discussed in the other pull request, the following changes were made:
1. selection logic and Perl 6 parser have been separated into two commits.
2. New function type has been renamed to selectLanguage.
3. If selectLanguage does not return a value (it really should, though), we fall back to arbitration.
4. docs/guessing.rst has been updated.
5. Whitespace has been cleaned up.
Once merged, issue #473 should be closed.

Selection logic and Perl 6 support.

---

main/parse.c
main/parse.h
main/read.c

main, refactor: reuse makeFileTag in read.c(3 days)

---

Units/parser-scheme.r/scheme-simple-setbang.d/expected.tags

units: add missing expected.tags for scheme language (0 day)

---

.gitignore

gitignore: ignore file generated by genhtml of lcov (3 days)

---

Makefile.in
misc/units

tmain: remove generated files when doing make clean

---

Tmain/lxcmd-accept-reserved-kind.d/run.sh
Tmain/lxcmd-backend-not-found.d/run.sh
Tmain/lxcmd-backend-premature-death.d/run.sh
Tmain/lxcmd-broken-kind.d/run.sh
Tmain/lxcmd-disabled-kind.d/run.sh
Tmain/lxcmd-exit-status-override.d/run.sh
Tmain/lxcmd-list-kinds.d/run.sh
Tmain/lxcmd-reject-reserved-kind.d/run.sh
Tmain/utils.sh
Tmain/xcmd-dont-run-setgid-executable.d/run.sh
Tmain/xcmd-dont-run-setuid-executable.d/run.sh
docs/tmain.rst

Check coproc feature in xcmd related test cases

---

README.md
main/get.h

This is a trial to solve an issue reported in #494.
Let's see what happens on AppVeyor.

Fix a bug found in AppVeyor

---

Units/dts-simple.d/args.ctags
Units/dts-simple.d/expected.tags
Units/dts-simple.d/input.dts
main/parse.c
parsers/dts.c

See the each commit log and the change in the test case.

Tag macros and header files in dts

---

Makefile.in
configure.ac

Use mkdir-p without checking its availablity

---

main/options.c
main/options.h

main: remove unused Option.kindLong field and --kind-long option(incompatible change)

---

ctags.1.in

man: sort the list of field characters in alphabetical order

---

Tmain/sorted-help-message.d/run.sh

Don't require bash in tmain sorted help message

---

main/lxcmd.c

* Remove unused parameter
* Add some missing parens

Code cleanup

---

parsers/perl.c

Do not assert on malformed input.

---

main/args.h
main/ctags.h
main/debug.h
main/entry.h
main/field.h
main/flags.h
main/general.h
main/get.h
main/htable.h
main/keyword.h
main/kind.h
main/main.h
main/nestlevel.h
main/options.h
main/parse.h
main/parsers.h
main/read.h
main/routines.h
main/selectors.h
main/sort.h
main/strlist.h
main/vstring.h
misc/src-check

Dont use reserved char in header guard

---

docs/news.rst

docs: update the organization of news

---

main/parse.c
main/parse.h

main: hide CTagsSelfTestParser from the output of --list-languages

---

main/xtag.h

main: fix the comment of isEnabled field of xtagDesc

---

docs/news.rst
docs/other-projects.rst

(Use the output of --list-languages directly.)

docs: update the list of supported languages

---

Units/awk-simple.d/expected.tags
Units/awk-simple.d/input.awk

awk, units: add a test case

---

Makefile.in
Units/readtags.r/backslash-at-the-end-of-pattern.d/expected.tags
Units/readtags.r/backslash-at-the-end-of-pattern.d/input.c
misc/roundtrip
readtags.c

Roundtrip test

---

main/field.c
main/read.c
main/xtag.c
parsers/c.c
parsers/flex.c
parsers/fortran.c
parsers/jscript.c
parsers/perl6.c
parsers/php.c
parsers/ruby.c
parsers/sml.c
parsers/sql.c
parsers/tex.c
parsers/verilog.c

refactor: use ARRAY_SIZE macro

---

Units/parser-c.r/macros.c.d/args.ctags
Units/parser-c.r/macros.c.d/expected.tags
main/get.c

c: add signature field to C preprocessor macros

---

parsers/php.c

Update the comments releated to
2c4744da31d9425da12563f03a820eb5029a98b4.

php: update comments

---

docs/autotools.rst

docs, buildsys: update the sentences about autogen.sh

---

docs/tmain.rst

docs: fix a typo in an exapmle of tmain

---

Tmain/maxdepth.d/run.sh
Tmain/maxdepth.d/src/a.c
Tmain/maxdepth.d/src/subdir/b.c
Tmain/maxdepth.d/stdout-expected.txt
docs/news.rst
main/main.c
main/options.c
main/options.h

Close #743.
This extends the commit requested in #743.
* add a test case
* update news.rst

Maxdepth with test caas and doc

---

Tmain/list-fields.d/stdout-expected.txt
Tmain/list-roles.d/stdout-expected.txt
Units/parser-make.r/make.include.d/expected.tags
Units/sh-source.d/expected.tags
main/kind.h
parsers/make.c
parsers/sh.c

Revise names newly introduced  these days.

Fix kind and role names

---

parsers/python.c

python: fix indentations and replace spaces with tabs

---

main/entry.c
main/general.h
main/main.c
main/options.c
main/options.h
main/routines.c

main: use stderr instead of errout

---

misc/optlib2c

misc/optlib2c: handle correctly .ctags file without --xcmd-*

---

main/parse.c

main: compile doesParserUseKind only when DEBUG is defined

---

README.md
docs/units.rst

Add an exapmle to run more than one test cases under Units.

docs: improve the examples about how to run specified cases under Units

---

main/lregex.c
main/lxcmd.c

Fix wrong memory allocations

---

parsers/ant.c
parsers/dbusintrospect.c
parsers/glade.c
parsers/maven2.c

 Rearrange the style of indentation of Xpath tables

---

autogen.sh
configure.ac
misc/optlib2c

optlib2c: rewrite in perl

---

main/read.c

Fix a typo in local variable name

---

README.md
appveyor.yml

https://ci.appveyor.com/project/kozo2/ctags/build/1.0.2

add artifacts to appveyor.yml

---

Units/parser-ruby.r/ruby-geany-sf-bug-302.d/expected.tags
Units/parser-ruby.r/ruby-geany-sf-bug-302.d/input.rb
Units/parser-ruby.r/ruby-geany-sf-bug-542.d/expected.tags
Units/parser-ruby.r/ruby-geany-sf-bug-542.d/input.rb
parsers/ruby.c

While trying to merge U-CTags changes back into Geany, I realized we had 2 fixes that didn't make it here.  Here they are now, finally.

ruby: Import Geany changes

---

docs/news.rst
docs/parsers.rst

I would like to add notes about php later.

Docs adding parsers section

---

Tmain/broken-tagname.d/run.sh
Tmain/broken-tagname.d/stderr-expected.txt
main/entry.c
main/entry.h
main/field.c
main/main.c
main/parse.c
main/read.c
main/sort.c
main/sort.h

Based on the commits proposed in #789, unacceptable changes are fixed.
Close #789.

Revise jonathon reinhart minimize entry visibility

---

Units/review-needed.r/bug1691412.java.t/expected.tags
Units/review-needed.r/bug1777340.java.t/expected.tags
parsers/c.c

Java: introduce annotation kind

---

docs/input-text-stream.svg
docs/internal.rst
docs/output-tag-stream.svg

docs: update for mio

---

misc/review

misc/review: add command to show args.ctags

---

main/debug.h
main/lxpath.c
main/mio.c
main/mio.h
main/parse.c
main/parse.h
main/read.c
main/read.h
main/selectors.c
main/vstring.c
main/vstring.h

File name was passed to a parser provided by libxml2.
This patch set changes it to mio object.

Xml with memory stream

---

docs/news.rst

Write about parser own fields

---

main/lxpath.c
main/mio.c
main/mio.h
main/parse.c
main/read.c
main/read.h
main/selectors.c

Reuse stream opend in language guessing stage

---

Units/simple-javaproperties.d/expected.tags
Units/simple-javaproperties.d/input.properties
docs/news.rst
main/parsers.h
parsers/jprop.c
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

Introduce JavaProperties parser

---

Tmain/list-fields-with-prefix.d/stdout-expected.txt
Tmain/list-fields.d/stdout-expected.txt
Units/parser-vim.r/3214129.vim.d/expected.tags
Units/parser-vim.r/3548393.vim.d/expected.tags
Units/parser-vim.r/end-field.vim.d/args.ctags
Units/parser-vim.r/end-field.vim.d/expected.tags
Units/parser-vim.r/end-field.vim.d/input.vim
Units/parser-vim.r/simple.vim.d/expected.tags
docs/parser-vim.rst
docs/parsers.rst
parsers/vim.c

Include s prefix in vim parser

---

Units/parser-make.r/make.parenthesis.d/expected.tags
Units/parser-make.r/make.parenthesis.d/input.mk
parsers/make.c

make: fix a typo in parenthesis handling

---

Units/parser-c.r/c-large-i-option-handling.b/args.ctags
Units/parser-c.r/c-large-i-option-handling.b/expected.tags
Units/parser-c.r/c-large-i-option-handling.b/input.c

Units, C: add new case testing -I option

---

dsl/es-lang-c-stdc99.c

Supress warnings while compiling

---

Tmain/langmap-option-including-patterns.d/stdout-expected.txt
Tmain/list-roles.d/stdout-expected.txt
Tmain/map-lang-option.d/stdout-expected.txt
Units/simple-automake.d/args.ctags
Units/simple-automake.d/expected.tags
Units/simple-automake.d/input.am
docs/news.rst
dsl/es-lang-c-stdc99.c
main/htable.c
main/htable.h
main/parsers.h
parsers/make.c

Parser for makefile am

---

Units/parser-cxx.r/extern.d/args.ctags
Units/parser-cxx.r/extern.d/expected.tags
Units/parser-cxx.r/extern.d/input.cpp
parsers/cxx/cxx_parser_block.c

Fixes handling of extern "C" declarations.

Fix bug #931

---

Units/parser-cxx.r/operators.cpp.d/expected.tags
Units/parser-cxx.r/operators.cpp.d/input.cpp
parsers/cxx/cxx_parser_function.c

Add support for C++ new, new[], delete and delete[] operators.

CXX: Support new and delete operators.

---

Units/parser-cxx.r/typedefs.cpp.d/expected.tags
Units/parser-cxx.r/typedefs.cpp.d/input.cpp
parsers/cxx/cxx_parser_typedef.c

Handle multiple typedefs in one declaration.
Fix bug #966.

Fix bug #966

---

Units/parser-cxx.r/bug-github-pull-972.cpp.d/args.ctags
Units/parser-cxx.r/bug-github-pull-972.cpp.d/expected.tags
Units/parser-cxx.r/bug-github-pull-972.cpp.d/input.cpp
parsers/cxx/cxx_parser_template.c
parsers/cxx/cxx_token_chain.c

Add a test case, fix indentation and a couple of minor related details.

Followup for pull 972

---

.travis.yml
Units/parser-c.r/macros.c.d/expected.tags
Units/parser-cxx.r/bug-github-pull-972.cpp.d/expected.tags
Units/parser-cxx.r/cxx-shift-operators-in-template-parameters.d/expected.tags
Units/parser-cxx.r/cxx11-delete.d/expected.tags
Units/parser-cxx.r/functions.cpp.d/expected.tags
Units/parser-cxx.r/signature.cpp.d/expected.tags
Units/parser-cxx.r/template-specializations.d/expected.tags
Units/parser-cxx.r/variables-prototypes-2.cpp.d/expected.tags
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_token_chain.h

Normalize spacing in function signatures

CXX: Normalize spacing in function signatures

---

dsl/es-lang-c-stdc99.c

dsl: suppress wanrings from compiler

---

main/get.c

PR on behalf of @erikd, forwarding geany/geany#1074

get: Avoid unnecessary and hard-to-read use of the comma operator

---

Tmain/list-fields-with-prefix.d/stdout-expected.txt
Tmain/list-fields.d/stdout-expected.txt
Units/parser-cxx.r/namespace.cpp.d/args.ctags
Units/parser-cxx.r/namespace.cpp.d/expected.tags
Units/parser-cxx.r/namespace.cpp.d/input.cpp
main/entry.h
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_parser_namespace.c
parsers/cxx/cxx_tag.c
parsers/cxx/cxx_tag.h

- Fixes issue #992
- Adds support for namespace alises
- Adds support for inline namespaces (marked in properties)

CXX: Improve namespace handling, add support for namespace aliases.

---

docs/autotools.rst
docs/chop.rst

You asked me to take a look at the docs; here's some trivial suggestions.
Let me know if you want me to continue with the rest of the files and I can add them here and eventually squash it into a single update if you like.

docs: some trivial copy editing

---

main/options.c

main: ignore .pyc and .pyo

---

main/ptag.h

main: remove duplicated ptagsDesc typedefs

---

Units/simple-protobuf.d/args.ctags
Units/simple-protobuf.d/expected.tags
Units/simple-protobuf.d/input.proto
docs/news.rst
docs/tracking.rst
main/keyword.c
main/keyword.h
main/lcpp.c
main/parsers.h
parsers/c.c
parsers/eiffel.c
parsers/flex.c
parsers/fortran.c
parsers/go.c
parsers/jscript.c
parsers/php.c
parsers/protobuf.c
parsers/sql.c
parsers/tex.c
parsers/vhdl.c
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

I took this patch written by Ivan Krasilnikov from https://sourceforge.net/p/ctags/patches/74/
Following tests are passed:
make noise
make chop
make fuzz
make units VG=1

Add Protobuf parser

---

Units/parser-javascript.r/js-function-in-arglist.d/expected.tags
Units/parser-javascript.r/js-function-in-arglist.d/input.js
parsers/jscript.c

* altered version of #1024
* cleanups
* better handling of regular expression literals
Nothing too fancy, but a few improvements.

JavaScript: Misc fixes and cleanups

---

docs/contributions.rst
docs/index.rst
docs/news.rst

docs: copy editing

---

main/parse.c

Suggested by @tmm1 and @b4n in #1011

Main: remove double const

---

parsers/clojure.c

Add clojurescript files (cljs) and conditional clojure files (cljc) to the extension list.

Include clojurescript and conditional clj files

---

win32/ctags_vs2013.vcxproj.filters

Fix unbalanced xmltag in a win32 build script

---

Units/main-xcmd.r/xcmd-coffeetags.d/expected.tags
Units/main-xcmd.r/xcmd-etags.d/expected.tags-e
Units/main-xcmd.r/xcmd-xref.d/expected.tags-x

It seems that the behavior of CoffeeTags is changed.
https://github.com/lukaszkorecki/CoffeeTags/issues/58

CoffeeScript, Units: update expected tags for the latest CoffeeTags

---

main/entry.c
main/main.c
main/options.c
main/output-ctags.c
main/output-etags.c
main/output-json.c
main/output-xref.c
main/output.h

output: introduce a structure type for representing a tag writer

---

Units/parser-javascript.r/js-methods.b/expected.tags
Units/parser-javascript.r/js-methods.b/input.js

As said in #1068 I want to contribute tests. For #1068 there is already a test in the commit of @b4n. So, I created a test for #780 instead.

Javascript ES6 methods, test for #780

---

Units/review-needed.r/jsFunc_tutorial.js.t/expected.tags
main/keyword.c
main/keyword.h
parsers/eiffel.c
parsers/flex.c
parsers/fortran.c
parsers/jscript.c
parsers/php.c
parsers/protobuf.c
parsers/python.c
parsers/sql.c
parsers/tex.c
parsers/vhdl.c

Noticed when I tried to optimize the new Python parser as it seemed a bit slow.

Fix case insensitive keyword lookup use and optimize it

---

Units/parser-cxx.r/1117-using-in-c.b/input.c

Test case for crash described in #1117.

CXX: c namespace crash test

---

Tmain/disable-languages.d/run.sh
Tmain/languages-and-language-force-options.d/run.sh
Tmain/lxcmd-reject-invalid-notAvailableStatus.d/run.sh
Tmain/wildcard-in-lang-of-fields-option.d/run.sh

Tmain: don't load ~/.ctags

---

main/routines.c
parsers/cxx/cxx_parser_function.c
parsers/m4.c

Misc: Replace true/false with TRUE/FALSE

---

Units/parser-cxx.r/variable-declarations.cpp.d/expected.tags
Units/parser-cxx.r/variable-declarations.cpp.d/input.cpp
parsers/cxx/cxx_keyword.c
parsers/cxx/cxx_keyword.h
parsers/cxx/cxx_parser_function.c

Improve variable parsing a little bit more.
Fixes #1149

CXX: Yet more variable parsing

---

main/options.c
main/options.h
parsers/c.c
parsers/cxx/cxx_parser_tokenizer.c

Rewrite the ignore option to use a data structure and a htable.

CXX: Rewrite the ignore option to use a data structure and a htable

---

main/output-json.c

json-output: remove unused static functions

---

parsers/ansibleplaybook.c
parsers/autoconf.c
parsers/iniconf.c
parsers/m4.c
parsers/meta-iniconf.h
parsers/meta-m4.h
parsers/meta-yaml.h
parsers/pythonloggingconfig.c
parsers/yaml.c

Meta parsers misc fix suggested in #1137

---

main/read.c
parsers/cxx/cxx_parser.c
parsers/rpmspec.c

Found with make CC=/rest/inst/gcc-6.1.0/usr/local/bin/gcc CFLAGS="-Wall -pedantic".
Signed-off-by: Thomas Braun <thomas.braun@virtuell-zuhause.de>

Fix coding issues (for merging changes in #1162 partially)

---

main/args.c
main/entry.c
main/lcpp.c
main/lregex.c
main/lxcmd.c
main/mio.c
main/options.c
main/parse.c
main/read.c
main/read.h
main/routines.c
main/strlist.c

These are small things I discovered while working on https://github.com/geany/geany/pull/1263. Nothing terribly interesting except the bugs introduced by me which got fixed: https://github.com/universal-ctags/ctags/commit/42207a4ce6ccbdf91e2472b9d79cf5e1cf7ca6f2 and https://github.com/universal-ctags/ctags/commit/5331fb1b3c76dd6275bdf67c73e44633eb2f14e0 (in the later patch I'm not sure if the copyFile() is needed at all as none of the integration tests has triggered it so maybe the code isn't needed at all).

Geany sync 2

---

parsers/cxx/cxx_parser_block.c

cxx: remove duplicated break keyword

---

parsers/cxx/cxx_parser_tokenizer.c

Cxx: fix obsolete field access in debug build

---

.gitignore

Git: gitignore generated rst file

---

Units/review-needed.r/simple.js.t/expected.tags
parsers/jscript.c

Fixes #1193.
---
I'm not totally sure what should be emitted here, but at least it makes more sense now.

Fix handling assignment to a member of an array element

---

Units/parser-cxx.r/complex-macros.d/args.ctags
Units/parser-cxx.r/complex-macros.d/expected.tags
Units/parser-cxx.r/complex-macros.d/input.cpp
Units/parser-cxx.r/foreach.d/args.ctags
docs/developers.rst
docs/news.rst
parsers/c.c
parsers/cpreprocessor.c
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_tokenizer.c
parsers/cxx/cxx_tag.c
parsers/meta-cpreprocessor.h

Support real macros just like gcc does, including token pasting, stringification and variable arguments.

CXX: Better preprocessor macros - take 2

---

Units/parser-asm.r/gas.s.d/args.ctags
Units/parser-asm.r/gas.s.d/expected.tags
Units/parser-asm.r/gas.s.d/input.s
parsers/asm.c

Asm: add end: field support for macro kind

---

Units/parser-c.r/bug1198.c.d/args.ctags
Units/parser-c.r/bug1198.c.d/expected.tags
Units/parser-c.r/bug1198.c.d/input.c
parsers/cxx/cxx_parser_function.c

Fix issue #1198.
Improve the signature lookup algorithm and try to make it more readable by refactoring and commenting.

CXX: Fix issue 1198

---

main/lxcmd.c
misc/src-check
parsers/c.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_lambda.c
parsers/cxx/cxx_token_chain.c
parsers/flex.c
parsers/go.c
parsers/jscript.c
parsers/objc.c
parsers/php.c
parsers/sql.c
parsers/tex.c
parsers/verilog.c
parsers/vhdl.c

This wrong code pattern is spotted by @b4n.
I don't touch parsers/cxx. I will make another PR for it.

Use vStringPut instead of vStringCatS

---

Tmain/list-fields-with-prefix.d/stdout-expected.txt
Tmain/list-fields.d/stdout-expected.txt
Tmain/list-roles.d/stdout-expected.txt
Units/parser-cuda.r/cuda-sample.d/args.ctags
Units/parser-cuda.r/cuda-sample.d/expected.tags
Units/parser-cuda.r/cuda-sample.d/input.cu
docs/news.rst
main/parsers.h
parsers/cxx/cxx.c
parsers/cxx/cxx_keyword.c
parsers/cxx/cxx_keyword.h
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser.h
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_parser_lambda.c
parsers/cxx/cxx_parser_tokenizer.c
parsers/cxx/cxx_tag.c
parsers/cxx/cxx_tag.h
parsers/cxx/cxx_token.c
parsers/cxx/cxx_token.h
parsers/cxx/cxx_token_chain.c
parsers/cxx/cxx_token_chain.h

Add basic CUDA support as a cxx parser sub-language.

[CXX] CUDA support (take 3)

---

Units/parser-javascript.r/js-methods.b/expected.tags
Units/parser-javascript.r/js-methods.d/expected.tags
Units/parser-javascript.r/js-methods.d/input.js
parsers/jscript.c

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions

jscript: Support ES6 methods shorthand syntax

---

Units/parser-sql.r/sql_pgSQL_dollar_quote.d/expected.tags
Units/parser-sql.r/sql_pgSQL_dollar_quote.d/input.sql
Units/parser-sql.r/sql_pgSQL_dollar_quote_complicated.d/expected.tags
Units/parser-sql.r/sql_pgSQL_dollar_quote_complicated.d/input.sql
Units/parser-sql.r/sql_pgSQL_with_function_x.d/expected.tags
Units/parser-sql.r/sql_pgSQL_with_function_x.d/input.sql
parsers/sql.c

Supersedes #1237, closes #1235.

SQL: PostgreSQL fixes

---

Units/parser-asm.r/unbalanced-end-macro.d/input.S
parsers/asm.c

Asm: fix crashing when encountering extra .endm

---

Tmain/interactive-mode.d/run.sh
Tmain/interactive-mode.d/stdout-expected.txt
Tmain/interactive-mode.d/test.c
Tmain/interactive-mode.d/test.rb
Tmain/utils.sh
docs/interactive-mode.rst
docs/news.rst
main/error.c
main/interactive.h
main/main.c
main/options.c
main/options.h
main/parse.c
main/parse.h
misc/mk-interactive-request.sh
source.mak

See #1071.
What I did:
1. refactor getFileLanguage
2. rename --interactive to --_interactive ( I would like to go more feed back about this new interface.)
@tmm1, could you look at this?

Add  --_interactive mode (take3?)

---

Units/parser-cxx.r/function-return-type-via-macro.d/args.ctags
Units/parser-cxx.r/function-return-type-via-macro.d/expected.tags
Units/parser-cxx.r/function-return-type-via-macro.d/input.cpp
parsers/cxx/cxx_parser_function.c

CXX: Handle the special case of MACRO(ret_type) function()

---

main/tokeninfo.c

main: fix wrong resource destruction in tokenReadFull

---

main/tokeninfo.c
main/tokeninfo.h
parsers/ldscript.c

I have been writing dtd parser based on tokeninfo API.
I have refined the API during writing the parser.

More tokeninfo api update

---

main/strlist.c

Suggested by @codebrainz in #1255.

main, refactor: remove unnecessary cast operations to bool

---

parsers/cxx/cxx_parser_function.c

Small fix. Fix unbalanced trace calls.

CXX: Fix unbalanced trace calls

---

Tmain/generate-anon-ids.d/input0.c
Tmain/generate-anon-ids.d/input1.c
Tmain/generate-anon-ids.d/run.sh
Tmain/generate-anon-ids.d/stdout-expected.txt
Units/parser-yacc.r/c-anon-ids.d/README
Units/parser-yacc.r/c-anon-ids.d/args.ctags
Units/parser-yacc.r/c-anon-ids.d/expected.tags
Units/parser-yacc.r/c-anon-ids.d/input.y
Units/parser-yacc.r/not-union.d/expected.tags
Units/parser-yacc.r/not-union.d/input.y
main/parse.c
main/parse.h
main/ptrarray.c
main/ptrarray.h
parsers/cxx/cxx_token.c
parsers/jscript.c
parsers/yacc.c

Call anonReset in main part

---

Units/parser-cxx.r/bug1252.cpp.d/expected.tags
Units/parser-cxx.r/bug1252.cpp.d/input.cpp
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_variable.c

CXX: Handle yet another special case for macros

---

win32/appveyor.bat

appveyor: install libiconv to cygwin_build

---

Units/parser-cxx.r/typedef-of-function-ptr-with-macro.d/expected.tags
Units/parser-cxx.r/typedef-of-function-ptr-with-macro.d/input.cpp
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_typedef.c
parsers/cxx/cxx_token_chain.c
parsers/cxx/cxx_token_chain.h

Cxx: handle typedef for function pointer with using a macro like WINAPI

---

main/options.c
main/parse.c
main/parse.h
misc/units

Normalize anonnames in units

---

Tmain/list-subparsers-all.d/stdout-expected.txt
Units/parser-tcl.r/namespace.d/args.ctags
Units/parser-tcl.r/namespace.d/expected.tags
Units/parser-tcl.r/namespace.d/input.tcl
main/entry.c
main/parsers.h
parsers/itcl.c
parsers/tcl.c
parsers/tcl.h
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

http://stackoverflow.com/questions/43365441/ctags-is-not-directing-to-the-methods-for-namespaces-in-tcl
itcl subparser is added just for passing the old test case.

Tcl namespace

---

autogen.sh

Build: verify existence of autoconf and pkg-config in autogen.sh

---

Units/parser-man.r/double-quoted.d/args.ctags
Units/parser-man.r/simple.d/args.ctags
optlib/man.c
optlib/man.ctags

man: enable man parser by default

---

parsers/tcl.c

* add "expect" as a an alias to tcl parser,
* add "exp" as an extension to tcl parser

Handle expect script in tcl parser

---

Tmain/list-regex-flags.d/stdout-expected.txt
docs/optlib.rst
main/entry.h
main/flags.c
main/lregex.c
main/options.c
main/options.h
main/parse.c

Many small fixes about kind handling.

Random fix about kind related code

---

win32/ctags_vs2013.vcxproj.filters

Win32,TclOO: Fix wrong filter spec

---

Units/parser-cxx.r/alignas-in-struct.d/expected.tags
Units/parser-cxx.r/alignas-in-struct.d/input.cpp
parsers/cxx/cxx_parser.c

Cxx: handle alignas specifier in struct

---

Units/parser-robot.r/dashes-in-identifiers.d/README
Units/parser-robot.r/dashes-in-identifiers.d/expected.tags
Units/parser-robot.r/dashes-in-identifiers.d/input.robot
parsers/robot.c

Robot: handle dashes in identifiers

---

makefiles/testing.mak

build-sys: remove duplicated CPPCHECK_UNDEFS

---

main/parse.c

main: add an assertion that kindIndex is greater than or equal 0

---

man/ctags.1.rst.in

docs(man): fix styles of definition list

---

docs/news.rst
man/Makefile
man/ctags.1.rst.in

Man  misc fix

---

main/promise.c

main: put promises array to the default trashbox

---

main/options.c
main/parse.c

main: mark CTAGS_ATTR_UNUSED to unused parameters

---

Tmain/langmap-option-including-patterns.d/stdout-expected.txt
Tmain/map-lang-option.d/stdout-expected.txt
parsers/automake.c

automake: add .am as an extension

---

Units/regex-multiline-flag-dos.d/args.ctags
Units/regex-multiline-flag-dos.d/expected.tags
Units/regex-multiline-flag-dos.d/input.mlt
dictfiles/english.list
dictfiles/local-vars.list
dictfiles/personal-names.list
main/read.c

Multiline dos

---

Units/parser-ocaml.r/github-451-improved.d/args.ctags
Units/parser-ocaml.r/github-451-improved.d/expected.tags
Units/parser-ocaml.r/github-451-improved.d/input.ml
Units/parser-ocaml.r/ocamlAllKinds.ml.t/expected.tags
Units/parser-ocaml.r/ocamlCommentInStringAllowed.ml.d/expected.tags
Units/parser-ocaml.r/ocaml_empty.ml.d/expected.tags
Units/parser-ocaml.r/ocaml_empty.ml_xref.d/expected.tags-x
Units/parser-ocaml.r/ocaml_only_str.ml.d/expected.tags
Units/parser-ocaml.r/ocaml_string_tests.ml.d/expected.tags
parsers/ocaml.c

This pull request is the revised version of #451 originally submitted by @toroidal-code.
The most of all changes in the original pull request about styling and non-logical are already in our master branch. This pull request is made by extracting the logical changes in the original pull request.
Though I don't review carefully, but test csaes including newly added by me are passed with VG=1.
Close #451.
TODO: usage of kind in building and managing scope information doesn't look good. I'm looking for better way.

OCaml: merge #451

---

Units/unit-example-multi-inputs.d/args.ctags
Units/unit-example-multi-inputs.d/expected.tags
Units/unit-example-multi-inputs.d/input-0.h
Units/unit-example-multi-inputs.d/input-1.sh
Units/unit-example-multi-inputs.d/input-2.c
Units/unit-example-multi-inputs.d/input-3.c
Units/unit-example-multi-inputs.d/input.c
docs/units.rst
misc/units

input-[0-9].* and input-[0-9]-*.* are passed
after input.* to the target ctags binary.

units: support multiple input files

---

main/error.c
main/lxpath.c
main/main.c
main/options.c

This fixes only important indentation mistakes.
(Many minor mistakes still remain.)

Fix indent

---

main/options.c

main: fix the wrong order of options in --help message

---

docs/optlib.rst

Suggested by @shaehn in #1526.

docs: update an example in "Multiline pattern match"

---

Units/regex-with-scope-nested.d/args.ctags
Units/regex-with-scope-nested.d/expected.tags
Units/regex-with-scope-nested.d/input.foo
main/dependency.c
main/lregex.c
main/lregex.h
main/options.c
main/parse.c
main/parse.h

including bug fix and feature enhancement.

Refactor regex parsers

---

Units/parser-javascript.r/js-async1.d/expected.tags
Units/parser-javascript.r/js-async1.d/input.js
Units/parser-javascript.r/js-async2.d/expected.tags
Units/parser-javascript.r/js-async2.d/input.js
parsers/jscript.c

http://www.ecma-international.org/ecma-262/8.0/#sec-functions-and-classes
Fixes #1537.

jscript: Fix parsing async functions and methods

---

circle.yml
configure.ac
makefiles/testing.mak

Using bmake as make

---

configure.ac
makefiles/testing.mak

units: fix wrong option arugment for --with-timeout=

---

Units/parser-tex.r/cleveref-label.d/expected.tags
Units/parser-tex.r/cleveref-label.d/input.tex
parsers/tex.c

Tex: tag <label> in \label[shortdesc]{<label>} of cleveref package

---

main/inline.h
main/vstring.h
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

@codebrainz, could you take over this branch?
This one is based on your comment.
At least I would like you to put your copyright notice.
If you make your new pull request, I will close this one.
BTW, I sent invitation. Did you get?

Introduce CTAGS_INLINE macro

---

Units/parser-puppetManifest.r/puppet-tag.b/README
Units/parser-puppetManifest.r/puppet-tagged.b/README

Suggested by @b4n.
Close #1539.

Units,puppetManifest: add README about .b test cases

---

docs/units.rst
misc/units

Docs:  write about cateogries of units target

---

dsl/es-lang-c-stdc99.c
dsl/qualifier.c
main/dependency.c
main/entry.c
main/entry_private.c
main/entry_private.h
main/error.c
main/field.c
main/kind.c
main/mio.c
main/options.h
main/parse.c
main/portable-scandir.c
main/seccomp.c
parsers/ada.c
parsers/cpreprocessor.c
parsers/cpreprocessor.h
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_internal.h
parsers/dtd.c
parsers/ldscript.c
parsers/php.c
parsers/pythonloggingconfig.c

Miscellaneous small fixes, mostly reported by GCC

Misc fixes

---

Units/parser-autoit.r/simple-au3.d/expected.tags
Units/parser-autoit.r/simple-au3.d/input.au3
docs/news.rst
main/parsers.h
parsers/autoit.c
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

Cloes #1598.
This is basedon #1598. I added two more commits.
@Skif-Off, could you take a look the two commits?
If you are o.k., I will squash the all commits including your and mine into one.

AutoIt parser based on @Skif-off work

---

Tmain/list-subparsers-all.d/stdout-expected.txt
Units/parser-qtmoc.r/simple-qt.d/args.ctags
Units/parser-qtmoc.r/simple-qt.d/expected.tags
Units/parser-qtmoc.r/simple-qt.d/input.h
docs/news.rst
main/debug.c
main/dependency.c
main/entry.c
main/entry.h
main/parse.h
main/parsers.h
main/subparser.h
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_qtmoc.c
parsers/cxx/cxx_subparser.c
parsers/cxx/cxx_subparser.h
parsers/cxx/cxx_subparser_internal.h
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

Close #1346.
Changes for Cxx parser core is minimized.

QtMoc subpasrser running on C++ base parser

---

docs/index.rst
docs/reporting.rst

I need this web content now. So I will merge it soon.
Any fixes are welcome.

docs(web): write about how to report a parser bug

---

Units/parser-fortran.r/fortran-submodule.d/README
Units/parser-fortran.r/fortran-submodule.d/args.ctags
Units/parser-fortran.r/fortran-submodule.d/expected.tags
Units/parser-fortran.r/fortran-submodule.d/input.f90
parsers/fortran.c

fortran: Support submodule

---

Tmain/ptag-kind-desc.d/run.sh
Tmain/utils.sh
Tmain/w32-slash-in-exclude-option.d/input.d/capture_me/input.c
Tmain/w32-slash-in-exclude-option.d/input.d/dont_capture_me/input.c
Tmain/w32-slash-in-exclude-option.d/input.d/input.c
Tmain/w32-slash-in-exclude-option.d/run.sh
Tmain/w32-slash-in-exclude-option.d/stdout-expected.txt
main/options.c
main/strlist.c
main/vstring.c
main/vstring.h

Convert slash to backslash in exclude option

---

parsers/tcl.c

parsers/tcl.c: initialize variable

---

main/read.c

main/read.c: reduce calls of getInputLanguage

---

read/readtags-cmd.c

For helping us debugging readtags on AppVeyor.

Adding debug option to readtags

---

Makefile.am
circle.yml
makefiles/testing.mak
misc/roundtrip
misc/travis-check.sh

Improve roundtrip test harness  generic part of b4n s work

---

parsers/ocaml.c

OCaml: fix a memory leak

---

Units/parser-ldscript.r/ld-hello.d/LICENSE
Units/parser-ldscript.r/ld-hello.d/README
Units/parser-ldscript.r/ld-hello.d/expected.tags
Units/parser-ldscript.r/ld-hello.d/input.ld
parsers/ldscript.c

See "3.6.5 Output section data" of
https://sourceware.org/binutils/docs-2.10/ld_3.html#SEC28
.

LdScript: add keywords to put data

---

Units/parser-cxx.r/brackets.cpp.d/expected.tags
Units/parser-cxx.r/brackets.cpp.d/input.cpp
Units/parser-cxx.r/variable-declarations.cpp.d/expected.tags
Units/parser-cxx.r/variable-declarations.cpp.d/input.cpp
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_variable.c

Cleanup some corner cases encountered while parsing the Qt headers.

CXX: Improve qt header parsing

---

Units/parser-cxx.r/bug-github-1671.cpp.d/expected.tags
Units/parser-cxx.r/bug-github-1671.cpp.d/input.cpp
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_parser_template.c

Better handling for class/struct/union template specialization nastiness.
Fixes #1671

CXX: Fix #1671

---

misc/gencxxtypedumper.sh
parsers/cpreprocessor.c
parsers/cxx/cxx_debug_type.c
parsers/cxx/cxx_parser.c

Cleanup cxx mem leaks 3

---

main/fmt.c

A format string was chosen every time when printing a tag.
However, it can be done earlier.

xref-format: memorize format strings when parsing --xformat option

---

parsers/python.c

Python: add .wsgi to the extension list

---

Tmain/kinddef.d/run.sh
Tmain/kinddef.d/stdout-expected.txt
Tmain/lregex-reject-reserved-kind.d/run.sh
Tmain/lregex-reject-reserved-kind.d/stderr-expected.txt
Tmain/nested-subparsers.d/plugin.ctags
Tmain/nested-subparsers.d/stdout-expected.txt
docs/news.rst
docs/optlib.rst
main/lregex.c
main/parse.c
man/ctags-incompatibilities.7.rst.in
man/ctags-optlib.7.rst.in
man/ctags.1.rst.in
parsers/cobol.c

@k-takata, can I ask you to review this.

[INCOMPATIBLE] docs(man): add initial version of ctags-optlib(7)

---

man/ctags.1.rst.in

docs(man): write about --list-extras in --extras-<LANG> description

---

Tmain/input-encoding-option.d/run.sh
Tmain/invalid-encoding-option.d/run.sh
Tmain/no-input-encoding-option.d/run.sh
Tmain/output-encoding-option.d/run.sh
Units/parser-javascript.r/js-unicode-escape-iconv.d/features
docs/news.rst
main/options.c

Using the name "multibyte" is exaggeration.

[SELF INCOMPATIBLE]: rename the feature "multibyte" to "iconv"

---

Units/parser-puppetManifest.r/varname.d/expected.tags
Units/parser-puppetManifest.r/varname.d/input.pp
optlib/puppetManifest.c
optlib/puppetManifest.ctags

puppetManifest: accept a underscore char in a variable name

---

docs/extending.rst
docs/news.rst
docs/running-multi-parsers.rst

docs(web): fix broken links

---

autogen.sh
circle.yml

build-sys: use bmake in autogen.sh if make is not found

---

circle.yml

circleci: run tests on centos:latest

---

man/ctags-optlib.7.rst.in

docs(man): reorder the steps in "Overview for defining a parser"

---

man/ctags-optlib.7.rst.in

Suggested by @gonsolo in #1741.

docs(man): fix a typo

---

Tmain/input-encoding-option.d/tags-expected.txt
Tmain/list-pseudo-tags.d/stdout-expected.txt
Tmain/output-encoding-option.d/tags-expected.txt
Tmain/output-format-option.d/run.sh
Tmain/output-format-option.d/stdout-expected.txt
Tmain/output-input-field-with-no-escape.d/run.sh
Tmain/output-input-field-with-no-escape.d/stdout-expected.txt
Tmain/ptag-kind-desc.d/stdout-expected.txt
Tmain/tags-pseudo-tags.d/stdout-expected.txt
Tmain/xref-ptag-in-list-extras.d/run.sh
Units/parser-php.r/php-full-qualified-tags-no-esc.d/args.ctags
Units/parser-php.r/php-full-qualified-tags-no-esc.d/expected.tags
configure.ac
docs/format.rst
docs/news.rst
main/entry.h
main/field.c
main/main.c
main/options.c
main/ptag.c
main/ptag.h
main/writer-ctags.c
main/writer.c
main/writer.h

Reverts universal-ctags/ctags#1736
I merged it mistakenly. The branch is not ready to merge. At least more documentations are needed.

Revert "format-3: update (merge the master branch)"

---

parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_tokenizer.c

Cxx,refactor: use cxxTokenChainDestroyLast more

---

Units/parser-cxx.r/cxx11-lambdas.d/expected.tags
Units/parser-cxx.r/cxx11-lambdas.d/input.cpp
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_lambda.c

Improve lambda parsing. Fix #1763.

CXX: Improve lambda parsing. Fix #1763.

---

Units/parser-cxx.r/variables-in-control-statements.d/expected.tags
Units/parser-cxx.r/variables-in-control-statements.d/input.cpp
parsers/cxx/cxx_parser.c

CXX: Fix #1767

---

docs/parser-puppetManifest.rst
docs/parsers.rst

docs(web): add a page for puppetManifest parser

---

Units/parser-cxx.r/bug-github-1781.cpp.d/args.ctags
Units/parser-cxx.r/bug-github-1781.cpp.d/expected.tags
Units/parser-cxx.r/bug-github-1781.cpp.d/input.cpp
parsers/cxx/cxx_parser_function.c

Fix bug #1781 and add related unit test.

CXX: Fix bug 1781

---

Units/parser-cxx.r/variable-declarations.cpp.d/expected.tags
Units/parser-cxx.r/variable-declarations.cpp.d/input.cpp
Units/parser-cxx.r/variables-in-control-statements.d/input.cpp
parsers/cxx/cxx_keyword.c
parsers/cxx/cxx_keyword.h
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_parser_variable.c

Deal with more special cases of variable declarations.
Fixes #1787 and #1788 .

Fix 1787 and 1788

---

.travis.yml
Makefile.am
circle.yml
docs/optlib.rst
misc/units

buildsys: add .ctags.d/*.ctags to EXTRA_DIST

---

misc/optlib2c

Fix optlib2c handling of regex escaped backslash

---

man/Makefile
man/ctags.1.rst.in

Also added some comments in the Makefile for the man pages.
And added some inline questions in the man page, as comments using `.. Q:`.

Docs: update the man page doc

---

main/trace.c

main: add missing condition checking whether tracing is enabled or not

---

Tmain/list-fields-with-prefix.d/stdout-expected.txt
Tmain/list-fields.d/stdout-expected.txt
Tmain/list-roles.d/stdout-expected.txt
Units/parser-autoit.r/simple-au3.d/args.ctags
Units/parser-autoit.r/simple-au3.d/expected.tags
Units/parser-autoit.r/simple-au3.d/input.au3
parsers/autoit.c

See #1598, #1599 and https://github.com/geany/geany/pull/1752.
@Skif-off @masatake I'm not sure of what I'm doing here as I have no clue about AutoIt, but well :smile: 
@masatake please check the usage of roles here, I have no idea if it's correct.  Well, I should check the docs, but still.

Improvements on the AutoIt parser

---

Units/option-file-tags-no.d/args.ctags
Units/option-file-tags.d/args.ctags
Units/option-file-tags.d/expected.tags
main/options.c

Close #1869.
The bool value specified with --file-tags=yes was not stored to
proper place.

Fix issue 1869

---

main/entry.c

main: put #ifdef DEBUG around the code only used in Assert macro

---

docs/extending.rst
docs/optlib.rst

This is a first pass at updating the optlib.rst doc (and minor stuff for extending.rst).
There's still more to do, but I thought this is a big enough change to get some feedback on.
There are also a few open questions I had, which I added as comments in optlib.rst, marked `.. Q:`.
Feedback would be great. Even if it's: "this is crap".

Update the docs: extending.rst and optlib.rst sections

---

Units/parser-java.r/imported-role.d/expected.tags
Units/parser-java.r/imported-role.d/input.java
Units/xformat-option.r/format-aim.d/expected.tags-x
Units/xformat-option.r/format-aim.d/input.java

They are invalid java programs.

Units,Java: fix invalid test input

---

main/trace.c

main: fix a typo in code for tracing

---

main/entry.c
main/field.c
main/kind.c
main/lregex.c
main/parse.c
main/promise.c
main/vstring.c
main/xtag.c
parsers/fypp.c
parsers/go.c

Unify makeSimpleRefTag and makeSimpleTag

---

parsers/ada.c

Ada: suppress compiler warning

---

misc/optlib2c

optlib2c: escape left braces in regex patterns

---

parsers/rpmspec.c

A regex parser defines patterns and associated callback
functions.
The regex meta parser of ctags calls readLineFromInputFile.  Matching
the patterns and calling callbacks are done as the side effect of
calling readLineFromInputFiles. Callback functions of a regex parser
should not call readLineFromInputFile directly. If calling
readLineFromInputFile from a callback function can cause a bug; matching
patterns and calling callbacks are done in unexpected order.

Rpmspec: don't do readahead from regex callbacks

---

optlib/puppetManifest.c
optlib/puppetManifest.ctags

See #1912.
About 3 times faster than before.

PuppetManifet: optimizing for #1912

---

Units/regex-with-scope-autoFQTag.d/args.ctags
Units/regex-with-scope-autoFQTag.d/expected.tags
Units/regex-with-scope-autoFQTag.d/input.foo
docs/news.rst
docs/optlib.rst
main/parse.c
misc/optlib2c

Introduce autoFQTag

---

Units/parser-clojure.r/simple-clojure.d/expected.tags
Units/parser-clojure.r/simple-clojure.d/input.clj
parsers/clojure.c

Followup of https://github.com/universal-ctags/ctags/pull/1922

Allow fullqualified namespace definition

---

README.md

- Created new repo to run from docker/alpine
(see [ctags-docker](https://github.com/universal-ctags/ctags-docker))
- Link in README

Add link to docker build repo

---

README.md

circleci: update the link to the budge

---

Units/parser-cxx.r/inline-variables.cpp.d/args.ctags
Units/parser-cxx.r/inline-variables.cpp.d/expected.tags
Units/parser-cxx.r/inline-variables.cpp.d/input.cpp
parsers/cxx/cxx_keyword.c
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_variable.c

CXX: Add support for C++17 inline variables

---

README.md

Signed-off-by: Gavin Guo <gavin.guo@canonical.com>

Add the description about the Snap to README.md

---

main/colprint.c
main/entry.c
main/lregex.c
main/mio.c
main/numarray.c
main/numarray.h
main/portable-scandir.c
main/promise.c

Various small fixes for various things detected by some mean GCC warning options.

Various warnings

---

source.mak

build-sys,fix: add missing lregex_p.h to source.mak

---

Tmain/excmd-combine-backward.d/input.cpp
Tmain/excmd-combine-backward.d/run.sh
Tmain/excmd-combine-backward.d/stdout-expected.txt
Tmain/excmd-combine.d/input.cpp
Tmain/excmd-combine.d/run.sh
Tmain/excmd-combine.d/stdout-expected.txt
docs/news.rst
main/entry.c
main/options.c
main/options_p.h
main/writer-ctags.c
man/ctags.1.rst.in

main: implement --excmd=combined locator option

---

optlib/man.c
optlib/man.ctags

Man: add more extensions for man pages for perl module and systemtap

---

Tmain/list-fields-with-prefix.d/stdout-expected.txt
Tmain/list-fields.d/stdout-expected.txt
Units/parser-objectivec.r/objectivec_implementation.m.d/args.ctags
Units/parser-objectivec.r/objectivec_implementation.m.d/expected.tags
Units/parser-objectivec.r/objectivec_implementation.m.d/input.m
Units/parser-objectivec.r/objectivec_interface.h.d/args.ctags
Units/parser-objectivec.r/objectivec_interface.h.d/expected.tags
Units/parser-objectivec.r/objectivec_interface.h.d/input.h
main/vstring.c
main/vstring.h
parsers/automake.c
parsers/ctags-aspell.c
parsers/cxx/cxx_qtmoc.c
parsers/objc.c

About category of Objective-C, see https://medium.com/ios-os-x-development/an-introduction-to-categories-in-objective-c-d6d55d91569f
Close #1487

ObjectiveC: support cateogries

---

Units/parser-go.r/go-interface.d/README
Units/parser-go.r/go-interface.d/args.ctags
Units/parser-go.r/go-interface.d/expected.tags
Units/parser-go.r/go-interface.d/input.go
Units/parser-go.r/go-interface.d/src/ext/iface.go
Units/parser-go.r/go-torture.d/expected.tags
parsers/go.c

 Go: parse method specifications and inheriting interfaces in an interface

---

Units/parser-cxx.r/operators.cpp.d/expected.tags
Units/parser-cxx.r/operators.cpp.d/input.cpp
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_token_chain.c

Improve parsing of complex operator.
Fixes #1998

CXX: Improve parsing of complex operators

---

Tmain/list-map-extensions.d/stdout-expected.txt
parsers/ldscript.c

LdScript: add .ldi as an extension

---

Units/parser-php.r/nullable-return-type-decl.d/args.tags
Units/parser-php.r/nullable-return-type-decl.d/expected.tags
Units/parser-php.r/nullable-return-type-decl.d/input.php
Units/parser-php.r/php-return-type-declaration.d/args.ctags
Units/parser-php.r/php-return-type-declaration.d/expected.tags
Units/parser-php.r/php-return-type-declaration.d/input.php
parsers/php.c

PHP: fill the typeref field for function kind tags

---

Units/parser-javascript.r/js-computed-propname.d/expected.tags
Units/parser-javascript.r/js-computed-propname.d/input.js
parsers/jscript.c

JavaScript: capture dynamically computed property names

---

Units/parser-dbusinspect.r/node-as-root-with-dtd.d/expected.tags
Units/parser-dbusinspect.r/node-as-root-without-dtd.d/expected.tags
Units/parser-dbusinspect.r/simple-dbusinspect.d/expected.tags
main/lxpath.c
main/lxpath.h
main/lxpath_p.h
main/parse.c
main/parse_p.h
parsers/ant.c
parsers/dbusintrospect.c
parsers/glade.c
parsers/maven2.c
parsers/plist.c
parsers/relaxng.c
parsers/svg.c
parsers/xslt.c

Through revising DBusIntrospect parser, I found some ways to improve the interface provided from lxpath meta parser. Now the interface is simpler than before.

Revise the interface provided by lxpath meta parser

---

Makefile.am
misc/optlib2c
optlib/RSpec.c
optlib/cmake.c
optlib/ctags-optlib.c
optlib/elm.c
optlib/gdbinit.c
optlib/man.c
optlib/markdown.c
optlib/passwd.c
optlib/pod.c
optlib/puppetManifest.c
optlib/qemuhx.c
optlib/systemtap.c

Update optlib2c based on dreamtigers work

---

misc/optlib2c

optlib2c: use 'for my $var' idiom

---

Units/parser-asciidoc.r/one-character-title.d/expected.tags
Units/parser-asciidoc.r/one-character-title.d/input.adoc
parsers/asciidoc.c

Asciidoc: capture ONE character title

---

.travis.yml

Could be done also from CircleCI maybe?

ci: upload coverage also to codecov

---

Units/parser-cxx.r/bug-github-pull-972.cpp.d/expected.tags
Units/parser-cxx.r/template-nested-triangle-brackets.d/expected.tags
Units/parser-cxx.r/template-nested-triangle-brackets.d/input-0.hpp
Units/parser-cxx.r/template-nested-triangle-brackets.d/input-1.hpp
Units/parser-cxx.r/templates4.b/input.cpp
parsers/cxx/cxx_parser_template.c
parsers/cxx/cxx_parser_variable.c
parsers/cxx/cxx_token.h

Close #2060.
Only the last commit is related to #2060.
@pragmaware, if I should submit the commits in separated pull requests, let me know. I will withdraw this and do as your request.
In this pull request, I use a strlist instead of corkQueue level symbol table. The corkQueue level one is still in design.

C++ template minor improvements

---

docs/README.md
docs/development-process.rst
docs/index.rst

@ksamborski, could you look at this?
Does this help you?
Questions are welcome. I will answer by updating the document.
Fixing wrong sentences is more welcome:-)
The guideline has been applied to my self past 2 or 3 years.
Someone may feel 1 day and 3 days in the rules are a bit too short.

Developer guideline

---

Tmain/list-mline-regex-flags.d/stdout-expected.txt
Tmain/list-mtable-regex-flags.d/stdout-expected.txt
Tmain/list-regex-flags.d/stdout-expected.txt
Units/regex-flag-anonymous.d/args.ctags
Units/regex-flag-anonymous.d/expected.tags
Units/regex-flag-anonymous.d/input.foo
docs/optlib.rst
main/lregex.c
main/parse.c
main/parse.h

lregex: introduce {anonymous} flag for making an anonymous tag

---

Units/parser-cxx.r/functions.cpp.d/expected.tags
Units/parser-cxx.r/functions.cpp.d/input.cpp
parsers/cxx/cxx_parser_function.c

Masatake's algorithm for multidimensional array parameters.
Fixes #2128

CXX: Generate tags for multidimensional array parameters

---

Tmain/kind-long.d/stdout-expected.txt
Tmain/list-kinds-full.d/stdout-expected.txt
Tmain/nested-subparsers.d/stdout-expected.txt
Units/parser-cpreprocessor.r/capture-params-in-macro-defs.d/args.ctags
Units/parser-cpreprocessor.r/capture-params-in-macro-defs.d/expected.tags
Units/parser-cpreprocessor.r/capture-params-in-macro-defs.d/input.h
Units/parser-cxx.r/bug639644.cpp.d/expected.tags
Units/parser-cxx.r/complex-macros.d/expected.tags
Units/parser-cxx.r/cxx11enum.cpp.d/expected.tags
Units/parser-cxx.r/namespace.cpp.d/expected.tags
parsers/asm.c
parsers/c.c
parsers/cpreprocessor.c
parsers/cpreprocessor.h
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_tag.c
parsers/cxx/cxx_tag.h
parsers/dts.c
parsers/ldscript.c
parsers/protobuf.c

CPreProcessor: make tags for macro parameters

---

misc/units

units(shrink): add an example command line to the help messages

---

main/ptrarray.c
main/ptrarray.h

main: make ptrArrayRemoveLast return the removing item

---

win32/ctags_vs2013.vcxproj.filters

win32: Remove extra CR

---

docs/developers.rst

* Sort the list in alphabetical order.
* Add myself.

docs: Update developers

---

mk_mingw.mak
mk_mvc.mak

buildsys,mvc: Support packcc

---

win32/appveyor.bat
win32/gen-repoinfo.bat

Explicitly state that it is GPL 2 or later.

win32: Update copyright and license information

---

gnu_regex/regcomp.c
misc/packcc/packcc.c
mk_mingw.mak

* Import the latest packcc.
* Fix regex.

Support VC2015

---

circle.yml
docs/autotools.rst

Distro packages

---

Units/parser-typescript.r/ts-class-white.d/expected.tags
Units/parser-typescript.r/ts-class-white.d/input.ts
Units/parser-typescript.r/ts-class.d/expected.tags
Units/parser-typescript.r/ts-class.d/input.ts
Units/parser-typescript.r/ts-function-white.d/expected.tags
Units/parser-typescript.r/ts-function-white.d/input.ts
Units/parser-typescript.r/ts-function.d/expected.tags
Units/parser-typescript.r/ts-function.d/input.ts
parsers/typescript.c

Both issues are related to functions but in different way. I added test cases for them and this PR should now fix all of them.  @masatake please take a look if you have a moment

Typescript: fixes #2175, #2176

---

.travis.yml

~~To understand the comment of https://github.com/universal-ctags/ctags/pull/2170/commits/6371d75c2f5ecebe2edf1179ab8ac6dc03d9f125~~

travis: install python3-docutils to verify the generation of man pages [EDITED]

---

README.md

This reverts commit e40fbfcb83db872e6a2da98459dca4d51449efa4.

Revert "Remove link to snap repo"

---

main/lregex.c

Refactoring code parsing kind specification in --regex-<LANG> option

---

Units/parser-go.r/go-crash-issue-2220.d/args.ctags
Units/parser-go.r/go-crash-issue-2220.d/expected.tags
Units/parser-go.r/go-crash-issue-2220.d/input.go
parsers/go.c

Go: fix #2220

---

docs/contributions.rst
docs/optlib.rst
docs/osx.rst
docs/other-projects.rst
docs/running-multi-parsers.rst
docs/tracking.rst
docs/windows.rst
man/ctags-optlib.7.rst.in
man/ctags.1.rst.in

* Use https if available.
* Add slashes for consistency.

docs,man: Update URLs

---

misc/dist-test-cases

buildsys: Fix dist-test-cases

---

README.md

Now docs.ctags.io supports https.

README.md: Use https

---

Units/parser-cxx.r/bug-github-2263.cpp.d/args.ctags
Units/parser-cxx.r/bug-github-2263.cpp.d/expected.tags
Units/parser-cxx.r/bug-github-2263.cpp.d/input.cc
parsers/cxx/cxx_parser_template.c

CXX: handle '>>>' as the end of template parameter list

---

circle.yml
configure.ac
makefiles/testing.mak
misc/units.py
win32/appveyor.bat

Create a replacement for `misc/units` by python.
This speeds up `make units` especially on Cygwin/MSYS2.
Related: #2238

units: Add misc/units.py

---

parsers/typescript.c

Clang warns this:
```
../parsers/typescript.c:740:18: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Wvarargs]
va_start (args, skipUnparsed);
^
../parsers/typescript.c:732:56: note: parameter of type 'bool' is declared here
static bool tryInSequence(tokenInfo *const token, bool skipUnparsed, ...)
^
```
See also:
https://wiki.sei.cmu.edu/confluence/display/cplusplus/EXP58-CPP.+Pass+an+object+of+the+correct+type+to+va_start
It seems that passing `bool` to `va_start` has undefined behavior.
I think that the first argument after `skipUnparsed` is mandatory.
So, I added `parser` argument after `skipUnparsed`. Then, this causes
type mismatch between `parseComment()` function. So, I also updated the
function to match with `Parser` …

typescript: Suppress clang warning

---

man/README

Write about updating the files in ../docs/man/.
Related: #2289

man: Update README

---

docs/man/ctags.1.rst

It should have been updated after #2259.
Also related to #2289.

docs(web): Update docs

---

misc/units

make fuzz is revised.
You can enjoy make fuzz reports some inpunt patterns that can crash ctags if you have enough first PC.
Next I will fix the crashes.

Revise fuzz test harness

---

misc/optlib2c

optlib2c: reject "all" as a name of language

---

docs/autotools.rst

Ubuntu is the most used distribution. Mention it might be better.

docs(web): Mention about Ubuntu

---

misc/units.py

Close #2321.
It seems that I forgot to implement this feature. Implement it.

units: Fix that units.py doesn't respect LANGUAGES

---

parsers/cpreprocessor.h

CPreProcessor: fix typos in comments

---

parsers/rst.c

ReStructuredText: write the origin of the source code as comment

---

misc/units.py

No need to use a list comprehension here.
A generator expression is better, no need to create an actual list.

units: Remove unnecessary brackets

---

.editorconfig
docs/man/ctags-optlib.7.rst
man/ctags-optlib.7.rst.in
misc/optlib2c

Making optlib2c --kinddef handling more strict

---

man/Makefile

buildsys: Generate sed rules based on (IN_)SOURCE_FILES

---

docs/man/ctags.1.rst
docs/news.rst
man/ctags.1.rst.in

* Fix markup of backslash.
* Write about TAG_OUTPUT_FILESEP ptag
* Add more description about TAG_OUTPUT_MODE
* Write about --list-subparsers
* Fix typos.

docs,man: Update docs and man pages

---

docs/guessing.rst
docs/man/ctags.1.rst
docs/news.rst
man/ctags.1.rst.in

docs(web): remove some "IN MAN PAGE" markers

---

optlib/passwd.c

Though I changed passwd.ctags in 379bf2260064ee76571eceacf966c67ae1de06ac,
I forgot to commit its associated .c file converted by optlib2c.

passwd: regenerate .c file

---

misc/optlib2c

Optlib2c: more strict fielddef and extradef

---

main/options.c

main: update --help message (s/--extra-/--extras-/)

---

docs/man/ctags.1.rst
man/ctags.1.rst.in

doc(man): add "extra" as a selection which --totals takes

---

main/tokeninfo.c

main: initialize type field of tokenInfo properly

---

main/options.c

main: include given argument for --excmd option in error message

---

main/entry.c
main/writer_p.h

Reduce unnecessary strlen calls.

main: Minor optimizations for building pattern in tags

---

Units/parser-cxx.r/template-nested-triangle-brackets.d/expected.tags
Units/parser-cxx.r/template-nested-triangle-brackets.d/input-3.hpp
parsers/cxx/cxx_parser_template.c

CXX: Handle another template termination condition

---

mk_mingw.mak

mk_mingw.mak does not have a way to build with +yaml or +xml

Add WITH_XML, WITH_YAML and WITH_JSON to mk_mingw.mak

---

Tmain/input-encoding-option.d/tags-expected.txt
Tmain/json-output-format.d/stdout-expected.txt
Tmain/list-pseudo-tags.d/stdout-expected.txt
Tmain/output-encoding-option.d/tags-expected.txt
Tmain/ptag-kind-desc.d/stdout-expected.txt
Tmain/tags-pseudo-tags.d/stdout-expected.txt
main/options.c
main/options_p.h
main/ptag.c
main/ptag_p.h

main: intrdouce a pseudo tag for the length limit of pattern truncation

---

Tmain/list-fields-with-prefix.d/stdout-expected.txt
Tmain/list-fields.d/stdout-expected.txt
Units/parser-cxx.r/bug-github-2263.cpp.d/expected.tags
Units/parser-cxx.r/bug1563476.cpp.d/expected.tags
Units/parser-cxx.r/template-nested-triangle-brackets.d/args.ctags
Units/parser-cxx.r/template-nested-triangle-brackets.d/expected.tags
Units/parser-cxx.r/template-nested-triangle-brackets.d/input-2.hpp
Units/parser-cxx.r/template-specializations.d/args.ctags
Units/parser-cxx.r/template-specializations.d/expected.tags
Units/parser-cxx.r/template-specializations.d/input.cpp
Units/parser-cxx.r/templates.d/expected.tags
Units/parser-cxx.r/templates2.d/expected.tags
Units/parser-cxx.r/templates3.d/expected.tags
Units/parser-cxx.r/templates4.d/expected.tags
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_parser_lambda.c
parsers/cxx/cxx_parser_namespace.c
parsers/cxx/cxx_parser_template.c
parsers/cxx/cxx_parser_tokenizer.c
parsers/cxx/cxx_parser_variable.c
parsers/cxx/cxx_tag.c
parsers/cxx/cxx_tag.h
parsers/cxx/cxx_token_chain.c
parsers/cxx/cxx_token_chain.h

- Don't break template arguments when template specializations are found
- Add support for specialization field
- Slightly refined template angle bracket matching
- Gracefully handle some non-prefix template keyword instances
- Emit types of template parameters
- Add some unit tests

CXX: More work on templates

---

Units/parser-c.r/attr-attached-to-array.d/expected.tags
Units/parser-cxx.r/variable-declarations.cpp.d/expected.tags
parsers/cxx/cxx_parser_variable.c

Fix type when multiple variables are extracted from a statement and an array is present.

CXX: Fix type when multiple variables are extracted from a statement

---

Units/parser-c.r/end-field-of-var.d/expected.tags

Fix an unit test that was broken between out-of-order merges.

C: fix an unit test that was broken between merges

---

Tmain/list-roles.d/stdout-expected.txt
Units/parser-rpmspec.r/simple-rpmspec.d/expected.tags
Units/parser-rpmspec.r/simple-rpmspec.d/input.spec
parsers/rpmspec.c

RpmSpec: capture patch file names as decl role of patch kind

---

Tmain/readtags-list-pseudo-tags.d/run.sh
Tmain/readtags-qualifier-op-downcase.d/input.cpp
Tmain/readtags-qualifier-op-downcase.d/output.tags
Tmain/readtags-qualifier-op-downcase.d/run.sh
Tmain/readtags-qualifier-op-downcase.d/stdout-expected.txt
dsl/qualifier.c

readtags: add downcase operator

---

Tmain/tmain-example.d/stdout-expected.txt
Units/parser-ruby.r/simple.rb.d/expected.tags
Units/parser-ruby.r/simple.rb.d/input.rb
parsers/ruby.c

Ruby: introduce "constant" kind

---

Units/parser-ruby.r/simple.rb.d/args.ctags
Units/parser-ruby.r/simple.rb.d/expected.tags
parsers/ruby.c

Ruby: fill the "end:" field

---

parsers/moose.c

Moose: fix typos

---

Units/parser-typescript.r/ts-const.d/args.ctags
Units/parser-typescript.r/ts-const.d/expected.tags
Units/parser-typescript.r/ts-const.d/input.ts
parsers/typescript.c

A fix for #2488 for better variables parsing. Especially when they contain regexes (/.../) or division (/).

[typescript] #2488

---

Units/parser-ruby.r/ruby-signature-field-complicated.b/args.ctags
Units/parser-ruby.r/ruby-signature-field-complicated.b/expected.tags
Units/parser-ruby.r/ruby-signature-field-complicated.b/input.rb
Units/parser-ruby.r/ruby-signature-field.d/args.ctags
Units/parser-ruby.r/ruby-signature-field.d/expected.tags
Units/parser-ruby.r/ruby-signature-field.d/input.rb
parsers/ruby.c

Ruby: fill signature fields

---

Units/parser-ruby.r/ruby-alias.d/expected.tags
Units/parser-ruby.r/ruby-alias.d/input.rb
Units/parser-ruby.r/ruby-attr.d/expected.tags
Units/parser-ruby.r/ruby-attr.d/input.rb
Units/parser-ruby.r/ruby-library.d/expected.tags
Units/parser-ruby.r/ruby-library.d/input.rb
parsers/ruby.c

Ruby: accept a string literal with single quote chars

---

Tmain/readtags-escaping.d/run.sh
Tmain/readtags-escaping.d/stdout-expected.txt
readtags-cmd/readtags-cmd.c

readtags: rename --escape option to --escape-output

---

extra-cmds/printtags.c
extra-cmds/readtags-cmd.c

readtags: use stdio functions in tagsPrint when NULL is passed as procs

---

Units/parser-go.r/go-funcs.d/args.ctags
Units/parser-go.r/go-funcs.d/expected.tags
parsers/go.c

Go: capture the name of receivers

---

circle.yml
parsers/autoconf.h

Fix for fedora32

---

Tmain/readtags-alias.d/run.sh
Tmain/readtags-alias.d/stdout-expected.txt
dsl/dsl.c

@AmaiKinono reports typos in the original pull request.

Tmain,dsl: fix typos

---

.gitignore
Makefile.am
configure.ac
docs/man-pages.rst
docs/man/ctags-client-tools.7.rst
docs/man/ctags.1.rst
docs/man/readtags.1.rst
docs/man/tags.5.rst
man/Makefile
man/ctags-client-tools.7.rst.in
man/ctags.1.rst.in
man/readtags.1.rst.in
man/tags.5.rst

docs(man): add a stab for readtags(1)

---

docs/man/readtags.1.rst
docs/news.rst
man/readtags.1.rst.in

Minor changes for the new readtags(1) man page.

readtags: minor changes for the man page

---

main/entry.c
main/field.c

main: suppress warnings reported by gcc 10

---

docs/man/ctags.1.rst
man/ctags.1.rst.in

docs(man): write about anonymous extra tag

---

Units/parser-php.r/php-7-4-typed-props.d/args.ctags
Units/parser-php.r/php-7-4-typed-props.d/expected.tags
Units/parser-php.r/php-7-4-typed-props.d/input.php
parsers/php.c

See https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.typed-properties

PHP: fill the typeref field for variable kind tags appeared as class properties

---

docs/contributions.rst
docs/man/ctags.1.rst
docs/optlib.rst
man/ctags.1.rst.in

docs,man: Fix codeblocks

---

Units/parser-vim.r/vim-signature.d/args.ctags
Units/parser-vim.r/vim-signature.d/expected.tags
Units/parser-vim.r/vim-signature.d/input.vim
parsers/vim.c

vim: fill signature fields

---

configure.ac

buildsys: remove unused code from configure.ac

---

Tmain/readtags-qualifier-op-length.d/input.el
Tmain/readtags-qualifier-op-length.d/output.tags
Tmain/readtags-qualifier-op-length.d/run.sh
Tmain/readtags-qualifier-op-length.d/stdout-expected.txt
dsl/dsl.c

readtags: add length op

---

Makefile.am
Tmain/list-fields-with-prefix.d/stdout-expected.txt
Tmain/list-fields.d/stdout-expected.txt
Units/parser-python.r/cython_sample2.d/expected.tags
Units/parser-python.r/matrix-multiplication-operator.d/expected.tags
Units/parser-python.r/python-dot-in-import.d/expected.tags
Units/parser-python.r/python-import.d/expected.tags
Units/parser-python.r/python3-function-annotations.d/expected.tags
Units/parser-python.r/simple.py.d/expected.tags
Units/parser-python.r/typehint.d/args.ctags
Units/parser-python.r/typehint.d/expected.tags
Units/parser-python.r/typehint.d/input.py
Units/parser-python.r/variable-annotations.d/expected.tags
configure.ac
docs/man-pages.rst
docs/man/ctags-client-tools.7.rst
docs/man/ctags-lang-python.7.rst
docs/man/ctags.1.rst
man/Makefile
man/README
man/ctags-client-tools.7.rst.in
man/ctags-lang-python.7.rst.in
man/ctags.1.rst.in
parsers/python.c

Python: fill typeref fields

---

Units/parser-verilog.r/systemverilog-struct.d/expected.tags
Units/parser-verilog.r/systemverilog-struct.d/input.sv
parsers/verilog.c

struct and union was not supported.   (They are supported only in typedef declaration.)
This pull-request implement it and provide its test-cases.

SystemVerilog: Implement struct/union support

---

main/read.c
main/vstring.h
parsers/cpreprocessor.c
parsers/css.c
parsers/jscript.c
parsers/ocaml.c
parsers/perl.c
parsers/powershell.c
parsers/r.c
parsers/robot.c

Instead, use macros and functions for the purpose.

Don't access private fields of vString directly

---

docs/man/ctags-client-tools.7.rst
man/ctags-client-tools.7.rst.in

docs(man,web): fix the shape of nested items

---

Tmain/extras-field-for-pseudo-tags.d/run.sh
Tmain/input-encoding-option.d/run.sh
Tmain/json-output-format.d/run.sh
Tmain/list-pseudo-tags.d/stdout-expected.txt
Tmain/output-encoding-option.d/run.sh
Tmain/ptag-kind-sep.d/run.sh
main/ptag.c

main: enable TAG_PROC_CWD pseudo tag by default

---

parsers/verilog.c

The original code implemented set or sequence of tokenInfos with using `scope' member
of tokenInfo. `scope' member is for representing scope, not for set or sequence.
For representing a sequence, ptrArray is suitable.

SystemVerilog,refactor: convert the type of `tagContents' file private variable to ptrArray

---

parsers/verilog.c

The fixes in #2722 were not enough.  Obviously the fix of readWordTokenNoSkip() was not smart.
I thought it wasn't necessary to ask @masatake san  for a review of #2722, but I regret that I should do.
Now readWordTokenNoSkip() returns "c", and skipToNewLine() takes an argument "c" as other character input functions do.
As the result of refactoring in this a few weeks,  vUngetc() is called only twice.  vUngetc() which often caused nasty bugs.
So please review this time.

SystemVerilog,refactor: readWordTokenNoSkip() returns "c"

---

Units/parser-php.r/coverage.d/args.ctags
Units/parser-php.r/coverage.d/expected.tags
Units/parser-php.r/coverage.d/input.php
Units/parser-php.r/php-classes.d/args.ctags
Units/parser-php.r/php-classes.d/expected.tags
Units/parser-php.r/php-classes.d/input.php
Units/parser-php.r/xml.d/input.php
parsers/php.c

This mostly adds tests to improve code coverage, plus 2 code changes:
1. Improve handling of `<?=` short echo tag so it doesn't risk generating spurious tags;
2. Remove redundant handling of CRLF line endings that the read.c already normalizes.

PHP: tests and corner cases

---

Units/parser-verilog.r/systemverilog-illegal.d/expected.tags
Units/parser-verilog.r/systemverilog-illegal.d/input-0-2724.sv
Units/parser-verilog.r/systemverilog-illegal.d/input-1-2738.sv
Units/parser-verilog.r/systemverilog-illegal.d/input.sv
parsers/verilog.c

Fix for #2738.
I reviewed all loop and refactored some of them.

SystemVerilog: fix for processDesignElementL() not to go into infinite-loop (fix for #2738)

---

Units/parser-verilog.r/systemverilog-class.d/expected.tags
Units/parser-verilog.r/systemverilog-class.d/input.sv
Units/parser-verilog.r/systemverilog-constraint.d/args.ctags
Units/parser-verilog.r/systemverilog-constraint.d/expected.tags
Units/parser-verilog.r/systemverilog-constraint.d/input.sv
Units/parser-verilog.r/systemverilog-net-var.d/expected.tags
Units/parser-verilog.r/systemverilog-net-var.d/input.sv
Units/parser-verilog.r/systemverilog-parameter.d/expected.tags
Units/parser-verilog.r/systemverilog-parameter.d/input.sv
Units/parser-verilog.r/systemverilog-task-function.d/expected.tags
Units/parser-verilog.r/systemverilog-task-function.d/input.sv
parsers/verilog.c

- implement life_time (static, automatic) on class
- new tags
- constraint: 'O', 'constraint
- nettype: 'N', 'nettype'
- support array manipulation methods
- skip class_type
- Units
- add test for void function
- fix comments for "virtual"

SystemVerilog: Misc Fixes

---

README.md

GitHub Actions: add the badge for GitHub Actions

---

circle.yml

circleci: update the name of repos enabling in centos_make job

---

circle.yml
m4/ax_prog_cc_for_build.m4

Close #2776.
@leleliu008, could you look at #2776?
My fix for this issue is cf828d2. Can I ask you to review the commit?

build-sys: fix non-cross building packcc 

---

circle.yml

circleci: add centos6 as a new platform fo building ctags executable

---

Makefile.am
Tmain/unreadable-input.d/run.sh
Tmain/unreadable-input.d/stderr-expected.txt
makefiles/testing.mak

build-sys: improve building in separated build directory

---

Units/parser-typescript.r/ts-class-white.d/expected.tags
Units/parser-typescript.r/ts-class-white.d/input.ts
Units/parser-typescript.r/ts-class.d/expected.tags
Units/parser-typescript.r/ts-class.d/input.ts
parsers/typescript.c

Typescript: Fixed not recognizing the initial value of class property

---

Makefile.am
circle.yml

build-sys: rebuild packcc when packcc.c is updated

---

circle.yml
makefiles/testing.mak
misc/roundtrip

roundtrip: skip too large tag files

---

parsers/perl.c

Perl: add 'cperl' as an alias

---

docs/man/ctags-incompatibilities.7.rst
docs/man/ctags.1.rst
man/ctags-incompatibilities.7.rst.in
man/ctags.1.rst.in

This PR is the fixes for #1889 and #2792.
I also fixed markups of ctags-incompatibilities(7).

docs: fixes for open issues (#1889, #2792)

---

Tmain/disable-fixed-field.d/run.sh
Tmain/disable-fixed-field.d/stderr-expected.txt
Tmain/fixed-field-handling-in-json-format.d/input.c
Tmain/fixed-field-handling-in-json-format.d/run.sh
Tmain/fixed-field-handling-in-json-format.d/stdout-expected.txt
Units/fq-json.d/args.ctags
main/field.c
main/field_p.h
main/fmt.c
main/options.c
main/options_p.h
main/writer-ctags.c
main/writer-json.c
main/writer.c
main/writer_p.h

main: relax the order of options (--output-format=json and --fields=)

---

main/field.c
main/field_p.h
main/lregex.c
main/lregex_p.h
main/options.c
main/parse.c
main/parse_p.h
misc/optlib2c

Minor fixes I have made during developing optscript.

main: minor fixes

---

docs/man/ctags-lang-verilog.7.rst
man/ctags-lang-verilog.7.rst.in
misc/man-test.py

docs: man page with non-ASCII character (#2901, #2903, #2905) 

---

docs/_ext/ctags_optlib_highlighter.py
docs/_ext/lexers.py
docs/conf.py
docs/man/ctags-optlib.7.rst
docs/option-file.rst
docs/optlib.rst
man/ctags-optlib.7.rst.in

docs: introduce 'ctags' highlighter

---

docs/promise.svg

docs: fix typos in the figure about promise

---

docs/man/ctags.1.rst
docs/optlib.rst
man/ctags.1.rst.in

docs: minor fixes: emphasize lines option, etc.

---

main/entry.c
main/entry.h
main/htable.c
main/htable.h
main/xtag.c
main/xtag_p.h
source.mak
win32/ctags_vs2013.vcxproj

64098b1 ... extends hashTable API.
5b34d8b ... fix a potential crash. A test case covering the code changed is in the optscript branch.

some fixes made during developing optscript

---

Units/parser-markdown.r/yaml-in-code-block.d/README
Units/parser-markdown.r/yaml-in-code-block.d/args.ctags
Units/parser-markdown.r/yaml-in-code-block.d/expected.tags
Units/parser-markdown.r/yaml-in-code-block.d/input.md
optlib/markdown.c
optlib/markdown.ctags

Markdown: give a higher priority to patterns for code blocks than that for sections

---

configure.ac
man/Makefile

buildsys: fix rst2man: command not found

---

docs/man/ctags-client-tools.7.rst
man/ctags-client-tools.7.rst.in

There was a section for this already.

docs: ctags-client-tools(7): describe MULTIPLE-LANGUAGES FOR AN INPUT FILE (#2976)

---

Tmain/broken-json-output.d/run.sh
Tmain/client-vista-vim-fields-expectation.d/run.sh

Tmain: add missing --options=NONE to run.sh for making the cases environment independent

---

main/seccomp.c

main: add newfstatat to seccomp rules

---

Units/parser-markdown.r/gaps-in-section-hierarchy.d/args.ctags
Units/parser-markdown.r/gaps-in-section-hierarchy.d/expected.tags
Units/parser-markdown.r/scope-field-markdown.d/args.ctags
Units/parser-markdown.r/scope-field-markdown.d/expected.tags
Units/parser-markdown.r/simple-markdown.d/args.ctags
Units/parser-markdown.r/simple-markdown.d/expected.tags
Units/parser-markdown.r/yaml-in-code-block.d/args.ctags
Units/parser-markdown.r/yaml-in-code-block.d/expected.tags
optlib/markdown.c
optlib/markdown.ctags

Markdown: adjust end fields to avoid overlapping sections

---

docs/_ext/lexers.py

Close #3012.
Tested-by: fpliu <leleliu008@gmail.com>

docs: as a highlighter, specify CtagsOtplibLexer class in sphinx-4

---

circle.yml

circleci: hide THIS_WILL_BE_FAILED_fedora34_CANARY

---

docs/_ext/ctags_optlib_highlighter.py
docs/_ext/lexers.py

docs(web): fix the name of highlighter

---

Makefile.am
misc/packcc/README.md
misc/packcc/build/clang/Makefile
misc/packcc/build/gcc/Makefile
misc/packcc/build/mingw-clang/Makefile
misc/packcc/build/mingw-gcc/Makefile
misc/packcc/src/packcc.c
misc/packcc/tests/.gitignore
misc/packcc/tests/ascii.d/ascii.bats
misc/packcc/tests/ascii.d/expected.txt
misc/packcc/tests/ascii.d/input.peg
misc/packcc/tests/ascii.d/input.txt
misc/packcc/tests/calc.d/calc.bats
misc/packcc/tests/code_generation.d/generation.bats
misc/packcc/tests/dump.d/dump.bats
misc/packcc/tests/dump.d/expected.txt
misc/packcc/tests/style.d/style.bats
misc/packcc/tests/test.sh
misc/packcc/tests/utils.sh

Close #3044
See also
- https://github.com/arithy/packcc/issues/37
- https://github.com/arithy/packcc/commit/43934f35254c08f0827801f80bbbec0e03c69fe0

Updating packcc for AIX

---

docs/man/ctags-lang-sql.7.rst

docs(web): update SQL man page

---

circle.yml
docs/index.rst
docs/testing-readtags.rst
makefiles/testing.mak
misc/roundtrip

minitrip: limited version of the roundtrip target for CI/CD environments

---

Units/parser-cxx.r/using-in-template.d/args.ctags
Units/parser-cxx.r/using-in-template.d/expected.tags
Units/parser-cxx.r/using-in-template.d/input.cpp
parsers/cxx/cxx_debug.c
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_parser_typedef.c
parsers/cxx/cxx_parser_using.c
parsers/cxx/cxx_scope.c
parsers/cxx/cxx_scope.h

C++: extract template parameters in a template alias

---

.github/workflows/testing-alpine.yml
.github/workflows/testing-cygwin.yml
.github/workflows/testing-freebsd.yml
.github/workflows/testing-gnulinux.yml
.github/workflows/testing-mac.yml
.github/workflows/testing-msys2.yml
.github/workflows/testing-netbsd.yml
.github/workflows/testing-openbsd.yml

GitHub Actions: pass GITHUBACTIONS=1 when running make-targets for testing

---

docs/contributions.rst

Describes how to test a PR locally before being merged.

docs: Testing a PR locally before being merged

---

Units/parser-moose.r/wrong-position.d/args.ctags
Units/parser-moose.r/wrong-position.d/expected.tags
Units/parser-moose.r/wrong-position.d/input.pl
main/entry.c
main/entry.h
parsers/perl-moose.c

Moose: adjust the position of a tag for a method

---

docs/news.rst

docs(web): add RpmMacros as a new parser

---

.github/workflows/run-citre-tests.yml

See https://github.com/universal-ctags/citre/issues/58

ci: run Citre tests

---

autogen.sh

This may help us inspect platform specific issues.

build-sys: print versions of the tools used in autogen.sh

---

Units/parser-sql.r/sql_pgSQL_guest.d/expected.tags
Units/parser-sql.r/sql_pgSQL_guest.d/input.sql
parsers/sql.c

SQL: fix a typo in the code deciding a promise area

---

docs/man/ctags-lang-python.7.rst
man/ctags-lang-python.7.rst.in

man(Python): fix a ciritcal typo

---

man/Makefile.am

clean-docs is also invoked by make clean
fix for #3131

build-sys: man: add update-docs to default target

---

Units/parser-verilog.r/systemverilog-package.d/expected.tags
Units/parser-verilog.r/systemverilog-package.d/input.sv
parsers/verilog.c

- a bug fix for #3150
- a unit testcase is also added

SystemVerilog: support multiple package-import-declarations

---

Tmain/list-params.d/stdout-expected.txt
Units/parser-cpreprocessor.r/if0-false-with-param.c.d/args.ctags
Units/parser-cpreprocessor.r/if0-true-with-param.c.d/args.ctags
Units/parser-cpreprocessor.r/macroexpand.d/args.ctags
Units/parser-cpreprocessor.r/macros-specified-with-param.c.d/args.ctags
Units/parser-fypp.r/run-alt-guest.d/args.ctags
Units/parser-itcl.r/force-use.d/args.ctags
Units/parser-itcl.r/force-use.d/expected.tags
Units/parser-itcl.r/force-use.d/input.tcl
Units/parser-ldscript.r/ld-symtab.d/args.ctags
Units/parser-tcloo.r/force-use.d/args.ctags
Units/parser-tcloo.r/force-use.d/expected.tags
Units/parser-tcloo.r/force-use.d/input.tcl
docs/man-pages.rst
docs/man/ctags-lang-tcl.7.rst
docs/man/ctags.1.rst
docs/output-tags.rst
docs/parser-cxx.rst
main/options.c
main/parse.c
man/Makefile.am
man/ctags-lang-tcl.7.rst.in
man/ctags.1.rst.in
parsers/itcl.c
parsers/tcloo.c

ITcl,TclOO: introduce forceuse parameters

---

configure.ac
main/args.c

Cherry picking changes from #3161

---

.github/workflows/cross-compile-android-ndk.yml
.github/workflows/cross-compile-mingw-w64.yml
.github/workflows/testing-mac.yml

Reference: https://github.com/actions/virtual-environments

GitHub Actions: add the macos-11 virtual environment.

---

.editorconfig
Makefile.am
docs/contributions.rst
makefiles/testing.mak
misc/src-check
win32/Makefile
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters
win32/ctags_vs2013.vcxproj.filters.in
win32/ctags_vs2013.vcxproj.in

temporary push to test on CI env.

build-sys: generate win32/ctags_vs2013.vcxproj* from source.mak

---

.github/workflows/run-citre-tests.yml

GitHub Actions: install GLOBAL! for testing with citre

---

Tmain/list-kinds-full.d/stdout-expected.txt
parsers/cxx/cxx_tag.c

Cxx: don't set referenceOnly flag to the kind using for definition tags

---

parsers/gdscript.c

GDScript: delete an unused parameter

---

docs/man/ctags-lang-gdscript.7.rst
man/Makefile.am
man/ctags-lang-gdscript.7.rst.in

docs(man): add a page for GDScript parser

---

Units/parser-fortran.r/fortran-abstract-interface.d/expected.tags
Units/parser-fortran.r/fortran-bind-c.d/expected.tags
Units/parser-fortran.r/fortran-enum.d/expected.tags
Units/parser-fortran.r/fortran-interface.d/expected.tags
Units/parser-fortran.r/fortran-signature.d/expected.tags
Units/parser-fortran.r/fortran-submodule.d/expected.tags
Units/parser-fortran.r/numlib.f90.d/expected.tags
Units/parser-fortran.r/recursive.f95.d/expected.tags
Units/parser-fortran.r/structure.f.d/expected.tags
Units/parser-fypp.r/run-guest.d/expected.tags
parsers/fortran.c

Close #3237.
* The order of commits were rearranged, and
* s/fortran/Fortran/ in commit headers.

Fortran: minor changes for merging #3237

---

parsers/ada.c

setjmp() and longjmp() may cause memory leaks and are better to avoid.
The ada parser actually doesn't seem to use them normally, there are proper
checks for EOF in the code, and longjmp() is used only when something
goes wrong after 1000 hits of EOF.
I went through all the loops and all of them seem to check for EOF so
there should be no need for setjmp()/longjmp().
We currently don't use the ada parser in Geany but since ada is supported, it might be interesting for us in the future and we try to avoid setjmp()/longjmp() because Geany is a long-running process and leaks caused by setjmp/longjmp may accumulate over time.

ada: remove setjmp() longjmp()

---

Units/parser-rust.r/rust-test_input.d/expected.tags
Units/parser-rust.r/rust-test_input.d/input.rs
parsers/rust.c

Will fix https://github.com/geany/geany/issues/2692

rust: Add support for constant parsing

---

parsers/yaml.c

Yaml: accept "yaml" as file extension

---

win32/appveyor.bat

Fixes: universal-ctags/ctags-win32#14
Fix that autotools were not installed.

packaging,win32: Install autotools

---

parsers/cxx/cxx_parser_tokenizer.c

Cxx: delete redundant code

---

docs/conf.py
main/ctags.h
win32/ctags.rc

Only done in user facing strings.

Raise copyright year

---

Units/parser-protobuf.r/version-2-3-files.d/args.ctags
Units/parser-protobuf.r/version-2-3-files.d/expected.tags
Units/parser-protobuf.r/version-2-3-files.d/input-0.proto
Units/parser-protobuf.r/version-2-3-files.d/input.proto
parsers/protobuf.c

* write more about the original issue in the commit log, 
* add a test case, and
* rebase on the master trunk.
Close #3300.

Taking over: @chrismwendt's pull request #3300, reset protobuf syntax

---

Units/parser-php.r/run-guest-with-bom.d/args.ctags
Units/parser-php.r/run-guest-with-bom.d/expected.tags
Units/parser-php.r/run-guest-with-bom.d/input.php
Units/parser-php.r/run-guest.d/args.ctags
Units/parser-php.r/run-guest.d/expected.tags
Units/parser-php.r/run-guest.d/input.php
main/read.c
misc/addbom
misc/hasbom
parsers/php.c

PHP: run HTML parser as a guest

---

.github/workflows/testing-alpine.yml

Reference:
https://alpinelinux.org/
https://hub.docker.com/_/alpine
https://endoflife.date/alpine

GitHub Actions: update AlpineLinux versions

---

.github/workflows/testing-freebsd.yml

GitHub Actions: update freebsd vm

---

.github/workflows/testing-alpine.yml

https://github.com/actions/checkout/issues/760

GitHub Actions: fix testing-alpine.yml git issue

---

parsers/perl6.c

See https://en.wikipedia.org/wiki/Raku_(programming_language)

perl6: Add more file name extensions

---

main/mini-geany.c

These are small mini-geany updates reflecting what changes we have in Geany master now:
* in addition to enabling kinds, we also need to be able to enable roles
* we need to be able to set and clear CPreprocessor "ignore" list - this is configurable in a Geany config file
* we need to be able to detect anonymous tags

mini-geany updates

---

.github/workflows/testing-freebsd.yml
.github/workflows/testing-netbsd.yml
.github/workflows/testing-openbsd.yml

GitHub Actions: add debug vagrant support

---

Units/parser-c.r/func-after-typedef-for-fptr-returning-enum.d/args.ctags
Units/parser-c.r/func-after-typedef-for-fptr-returning-enum.d/expected.tags
Units/parser-c.r/func-after-typedef-for-fptr-returning-enum.d/input.c
Units/parser-c.r/func-after-typedef-for-fptr-returning-struct.d/args.ctags
Units/parser-c.r/func-after-typedef-for-fptr-returning-struct.d/expected.tags
Units/parser-c.r/func-after-typedef-for-fptr-returning-struct.d/input.c
parsers/cxx/cxx_parser.c

Cxx: add missing code for resetting typedef parsing state

---

Units/parser-gemspec.r/simple-gemspec.d/expected.tags
Units/parser-gemspec.r/simple-gemspec.d/input-0.gemspec
parsers/gemspec.c

GemSpec: extract the name passed to add_dependency

---

parsers/markdown.c

Markdown,comment: fix a typo

---

Units/parser-rake.r/xtasks.d/expected.tags
Units/parser-rake.r/xtasks.d/input-0.rake
parsers/rake.c

Rake: extract test tasks represented with string literals

---

Units/extra-anonymous.d/expected.tags
Units/extra-disabling-anonymous.d/expected.tags
Units/parser-javascript.r/js-arraylist.d/expected.tags
Units/parser-javascript.r/js-complex-return.d/expected.tags
Units/parser-javascript.r/js-fields.d/expected.tags
Units/parser-javascript.r/js-null-tag-for-broken-input4.d/expected.tags
Units/review-needed.r/simple.js.t/expected.tags
Units/review-needed.r/simple.js.t/input.js
parsers/jscript.c

javascript: split ParseStatement into multiple functions

---

docs/man-pages.rst
docs/man/ctags-lang-javascript.7.rst
man/GNUmakefile.am
man/ctags-lang-javascript.7.rst.in

I'll add more when I think of something.

javascript: create man page

---

parsers/powershell.c

PowerShell: delete an unused variable

---

circle.yml

circleci: update yum repo names for ubi8

---

Tmain/list-aliases.d/stdout-expected.txt
parsers/sh.c

Sh: add dash as an alias

---

.github/workflows/testing-bsds.yml.bak
.github/workflows/testing-freebsd.yml
.github/workflows/testing-netbsd.yml
.github/workflows/testing-openbsd.yml

Reference: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
Thanks to `Masatake YAMATO` comment in https://github.com/universal-ctags/ctags/pull/3491#issuecomment-1260089341

GitHub Actions: vagrant box using cache

---

Tmain/list-roles.d/stdout-expected.txt
Tmain/list-subparsers-all.d/stdout-expected.txt
Units/parser-bats.r/bats-simple.d/args.ctags
Units/parser-bats.r/bats-simple.d/expected.tags
Units/parser-bats.r/bats-simple.d/input.bats
docs/news.rst
main/parsers_p.h
parsers/bats.c
parsers/sh.c
parsers/sh.h
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

Reference:
*   https://bats-core.readthedocs.io/en/stable/writing-tests.html

Bats: Sh parser based new sub parser

---

Tmain/list-roles.d/stdout-expected.txt
Units/parser-meson.r/modules.d/args.ctags
Units/parser-meson.r/modules.d/expected.tags
Units/parser-meson.r/modules.d/input.meson
optlib/meson.c
optlib/meson.ctags

Meson: extract imported modules as reference tags

---

Units/parser-powershell.r/class-powershell.d/expected.tags
Units/parser-powershell.r/class-powershell.d/input.ps1
parsers/powershell.c

PowerShell: parse a colon following the class name

---

makefiles/testing.mak
misc/tlib

tlib: report failures correctly

---

dsl/optscript.c
main/parse.c
main/script.c
main/selectors.c
main/writer-ctags.c
parsers/rake.c
parsers/ruby.c
parsers/verilog.c

cosmetic: delete redundant semicolons

---

main/sort.c

main: don't do NULL check for values returned from vStringNew (sort.c)

---

Units/parser-cxx.r/properties-constexpr.d/args.ctags
Units/parser-cxx.r/properties-constexpr.d/expected.tags
Units/parser-cxx.r/properties-constexpr.d/input.cc
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_parser_variable.c
parsers/cxx/cxx_tag.c
parsers/cxx/cxx_tag.h

CXX: add constexpr to "properties:" field

---

libreadtags/.github/workflows/msys2.yml
libreadtags/NEWS.md
libreadtags/configure.ac
libreadtags/readtags.c
misc/packcc/src/packcc.c
misc/packcc/tests/dump.d/expected.txt

Pull subtrees

---

docs/releasing.rst

docs(man): write more about how to make a release

---

docs/man/readtags.1.rst
extra-cmds/readtags-cmd.c
man/readtags.1.rst.in

readtags: add --version option

---

Units/parser-powershell.r/enum-powershell.d/args.ctags
Units/parser-powershell.r/enum-powershell.d/expected.tags
Units/parser-powershell.r/enum-powershell.d/input.ps1
parsers/powershell.c

PowerShell: introduce enum kind

---

.github/workflows/testing-mac.yml

GitHub Actions: fix testing-mac.yml Homebrew upgrade python@3.10 and python@3.11 failed problem

---

.github/workflows/testing-openbsd.yml

GitHubActions: fix testing-openbsd.yml automake version broken issue

---

NEWS.md
misc/news.bash

build-sys: release note for 6.1

---

main/trace.h

See https://github.com/universal-ctags/ctags/issues/3516

main,debug: don't use __func__ directly

---

configure.ac

build-sys: check whether libm should be linked

---

.github/workflows/testing-alpine.yml

Reference: https://endoflife.date/alpine

GitHub Actions: update Alpine Linux versions

---

main/mini-geany.c
misc/tlib

Close #3880
Suggested by @dataf3l.

main,tlib: fix wording

---

.github/workflows/testing-alpine.yml

add dependent libraries: pcre2-dev jansson-dev yaml-dev libxml2-dev

GitHub Actions: update testing-apline.yml

---

Units/parser-rake.r/simple-rake.d/expected.tags
Units/parser-rake.r/simple-rake.d/input.rake
parsers/rake.c

The original code considered only "task :m".

Rake: extract m in "task (:m)" as a task

---

docs/man/ctags-lang-i18nrubygem.7.rst
docs/news/6-1-0.rst
docs/testing-parser.rst
man/ctags-lang-i18nrubygem.7.rst.in
misc/man-test.py

docs(man),man-test: require "yaml" feature in the man-test of I18nRubyGem

---

Units/parser-vim.r/vim-class.d/args.ctags
Units/parser-vim.r/vim-class.d/expected.tags
Units/parser-vim.r/vim-class.d/input-0.vim
Units/parser-vim.r/vim-class.d/input-1.vim
Units/parser-vim.r/vim-class.d/input.vim
docs/man/ctags-lang-vim.7.rst
man/ctags-lang-vim.7.rst.in
parsers/vim.c

implements, ~extends,~ and specifies are not supported yet.

Vim: extract classes

---

Units/parser-cxx.r/variable-templates.d/args.ctags
Units/parser-cxx.r/variable-templates.d/expected.tags
Units/parser-cxx.r/variable-templates.d/input-0.cpp
Units/parser-cxx.r/variable-templates.d/input-1.cpp
Units/parser-cxx.r/variable-templates.d/input.cpp
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_variable.c
parsers/cxx/cxx_scope.c
parsers/cxx/cxx_token_chain.c
parsers/cxx/cxx_token_chain.h

Close #3963
Close #3962
Test inputs are taken from https://cpprefjp.github.io/

C++: recognize definitions of variable templates

---

Units/parser-cxx.r/using.cpp.d/expected.tags
Units/parser-cxx.r/using.cpp.d/input.cpp
parsers/cxx/cxx_parser_using.c
parsers/cxx/cxx_token_chain.c
parsers/cxx/cxx_token_chain.h

C++: extract operators specified in using declarations

---

.github/workflows/testing-gnulinux.yml

Use codecov/codecov-action instead of the codecov CLI.

CI: use codecov/codecov-action

---

Units/parser-cxx.r/export-2.d/expected.tags
Units/parser-cxx.r/export-3.d/expected.tags
Units/parser-cxx.r/export-3.d/input.cpp
Units/parser-cxx.r/export-namespace-alias.d/args.ctags
Units/parser-cxx.r/export-namespace-alias.d/expected.tags
Units/parser-cxx.r/export-namespace-alias.d/input.cpp
Units/parser-cxx.r/export-namespace-alias.d/validator
Units/parser-cxx.r/export-using.d/expected.tags
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_namespace.c
parsers/cxx/cxx_parser_typedef.c
parsers/cxx/cxx_parser_using.c
parsers/cxx/cxx_parser_variable.c
parsers/cxx/cxx_scope.c
parsers/cxx/cxx_scope.h
parsers/cxx/cxx_token.c
parsers/cxx/cxx_token.h

Cxx:  fix file field for exported objects

---

Units/parser-fortran.r/dollars-in-names.d/args.ctags
Units/parser-fortran.r/dollars-in-names.d/expected.tags
Units/parser-fortran.r/dollars-in-names.d/input.f
Units/parser-fortran.r/dollars-in-names.d/validator
circle.yml
misc/validators/gfortran-common.sh
misc/validators/validator-fortran+dollar-ok
parsers/fortran.c

Fortran: accept $ as parts of names

---

.github/workflows/cross-compile-android-ndk-on-ubuntu.yml

clean code and add ubuntu-24.04 runner

GitHub Actions: refactor cross-compile-android-ndk-on-ubuntu.yml

---

.github/workflows/cross-compile-android-ndk-on-mac.yml

GitHub Actions: refactor cross-compile-android-ndk-on-mac.yml

---

.github/workflows/cross-compile-for-openbsd-on-ubuntu.yml

clean code and add more OpenBSD versions

GitHub Actions: refactor cross-compile-for-openbsd-on-ubuntu.yml

---

.github/workflows/cross-compile-for--netbsd-on-ubuntu.yml

clean code and add more NetBSD versions

GitHub Actions: refactor cross-compile-for--netbsd-on-ubuntu.yml

---

.github/workflows/building-with-pegof.yml

improve readability of building-with-pegof.yml

GitHub Actions: refactor building-with-pegof.yml

---

.github/workflows/testing-on-netbsd.yml

remove unsed package
add dependent libraries
use readelf to display executable file info

GitHub Actions: refactor testing-on-netbsd.yml

---

.github/workflows/testing-on-openbsd.yml

add dependent libraries
use readelf to display executable file info

GitHub Actions: refactor testing-on-openbsd.yml

---

.github/workflows/testing-on-freebsd.yml

add dependent libraries
use readelf to display executable file info

GitHub Actions: refactor testing-on-freebsd.yml

---

Makefile.am
Tmain/readtags-alias.d/run.sh
Tmain/readtags-canonicalize-input-names.d/run.sh
Tmain/readtags-default-field-val.d/run.sh
Tmain/readtags-error-in-sorter.d/run.sh
Tmain/readtags-formatter-op-regex-extraction.d/run.sh
Tmain/readtags-formatter.d/run.sh
Tmain/readtags-qualifier-begin.d/run.sh
Tmain/readtags-qualifier-broken-exp.d/run.sh
Tmain/readtags-qualifier-end-field.d/run.sh
Tmain/readtags-qualifier-nth-field.d/run.sh
Tmain/readtags-qualifier-op-downcase-upcase.d/run.sh
Tmain/readtags-qualifier-op-length.d/run.sh
Tmain/readtags-qualifier-op-regexp-quote.d/run.sh
Tmain/readtags-qualifier-op-string-append.d/run.sh
Tmain/readtags-qualifier-regex.d/run.sh
Tmain/readtags-qualifier-sf-cond.d/run.sh
Tmain/readtags-qualifier.d/run.sh
Tmain/readtags-sorter-cmp_or-sform.d/run.sh
Tmain/readtags-sorter-if-sform-order.d/run.sh
Tmain/readtags-sorter-if-sform.d/run.sh
Tmain/readtags-sorter.d/run.sh
Tmain/readtags-stdin.d/run.sh
extra-cmds/readtags-cmd.c
main/htable.c
main/mio.c
mk_mvc.mak
source.mak

Just for testing with GitHub Actions

 build-sys: eliminate READTAGS_DSL condition 

---

Units/parser-meson.r/simple-meson.d/README
Units/parser-meson.r/simple-meson.d/expected.tags
Units/parser-meson.r/simple-meson.d/input-5.meson
Units/parser-meson.r/simple-meson.d/input-6.meson
optlib/meson.c
optlib/meson.ctags

Meson: extract benchmark langage objects correctly

---

Units/parser-tcl.r/nulltags.d/args.ctags
Units/parser-tcl.r/nulltags.d/expected.tags-x
Units/parser-tcl.r/nulltags.d/input.tcl
main/options.c
parsers/tcl.c

Tcl: extract null tags

---

Tmain/list-roles.d/stdout-expected.txt
Units/parser-selinux-type-enforcement.r/simple.d/expected.tags
optlib/selinux-type-enforcement.c
optlib/selinux-type-enforcement.ctags

"aliased" role is added to the "type" kind.

SELinuxTypeEnforcement: fill typeref: field for alias kind objects

---

Units/parser-cuda.r/param-with-default-value.d/args.ctags
Units/parser-cuda.r/param-with-default-value.d/expected.tags
Units/parser-cuda.r/param-with-default-value.d/input.cuh
parsers/cxx/cxx_parser_function.c

CUDA: support function parameters with default values

---

.github/workflows/code-coverage-on-ubuntu.yml
.github/workflows/testing-on-ubuntu.yml

1.move code coverage reporting function to a separate GitHub Actions workflow file.
2.impove readability

GitHub Actions: refactor testing-on-ubuntu.yml

---

main/entry.c
main/entry.h
main/options.c
main/parse.c
main/parse_p.h
main/promise.c
main/read.c
main/read_p.h
main/tokeninfo.h

These commits are stable parts of #4212.

main/read: refactor step1

---

docs/man/ctags.1.rst
man/ctags.1.rst.in
optlib/man.c
optlib/man.ctags
parsers/v.c
peg/toml.peg

The TOML parser is broken at a more fundamental level. So I don't provide a text case for the change for the parser in this pull request.

Some minor fixes

---

docs/man/ctags-lang-javascript.7.rst
man/ctags-lang-javascript.7.rst.in

Mainly for versioning.
This is an additional change to #4269.

docs(man),JavaScript: write about newly added properties: field
