Units/bug1777340.java.t/expected.tags
c.c
read.h

Change the value of `STRING_SYMBOL` and `CHAR_SYMBOL` for them not to conflict with legitimate high bytes.
Alter C# and Java-specific checks allowing for high characters to exclude any non-byte value (anything above 0xFF).
Note: the test *bug1777340.java.t* still isn't correct.
Part of #211.

c#, java: Don't mistake string and character constants for high bytes

---

misc/units

This is important for scripting, and especially for Make integration so
failures are recognized.

units: Exit with an error if `fuzz` failed

---

Units/py-skipped-string.d/expected.tags
Units/py-skipped-string.d/input.py
python.c

This fixes missing or too much entries in the tags file.

python: do not ignore the character after a skipped string

---

NEWS.fishman
TRACKING
Units/README
data/optlib/README
misc/units

The "f-" prefix has been discarded in git commit
f439b71b949adadba4c83df7ae033a8f8a7015ec on 2014-12-23.

Fix filename references to files in docs/

---

NEWS.exuberant

Merge with head of git-svn.
Apparently most changes were already implemented by commit e15bdf5a, but the change to the NEWS file was missing.

Sourceforge

---

entry.c

Possibly fixes issue: ctags might fail silently if /tmp is full #202

Check file error flag in makeTagEntry function

---

Units/variables-prototypes.cpp.b/args.ctags
Units/variables-prototypes.cpp.b/expected.tags
Units/variables-prototypes.cpp.b/input.cpp

Patch #77 fixes an important number of issues with the way variables
(local and global) and prototypes are parsed in C and above all C++.
This commit adds a new unit (marked as known bug) based on the test file
provided with patch #77, removing some cases which weren't valid C++ and
duplicating all the identifiers as global variables, on top of local
variables.
The expected.tags file has been generated with a version of ctags where
patch #77 has been applied, with the following modifications:
- An issue with an invalid character in signatures has been worked
around by the patch author @lyokha, see issue #234
- I removed the support for MS.Net, so that identifiers such as
int x4(5 ^ 4); are effectively recognized as variables (it was
just a matter of uncommenting a "case '^':" in the …

Add a unit based on patch sf.patch:77's  test.cpp

---

fnmatch/fnmatch.c

warning C4273: '_errno' : inconsistent dll linkage
...\12.0\vc\include\errno.h(31) : see previous definition of '_errno'
If _CRT_ERRNO_DEFINED is defined then do not define it again.

vs2013 errno defined twice

---

win32/ctags_vs2013.vcxproj

Linker error: ada.obj : warning LNK4075: ignoring '/EDITANDCONTINUE' due
to '/SAFESEH' specification
So for debug mode I changed in Linker settings /SAFESEH to false.
In release mode it can stay true, since it does not create warnings.
Any comments are welcome, I mostly use gcc. All I can say the warning gone and you can still debug.
https://msdn.microsoft.com/en-us/library/9a89h429.aspx

change vs2013 debug configuration

---

ada.c

Do not call strlen 8 times, call only once.
Fix: ada.c(645): warning C4018: '<' : signed/unsigned mismatch

refactor ada.c cmp function

---

entry.c

The original code introducing ferror doesn't check errors in endTagsFile, closeTagsFile and writePseudoTag.

check the file output error more frequently

---

Makefile.in

(It seems that macosx at travis doesn't have timeout command.)

Set timeout value to 0 if timeout command is not available in a test environment

---

Makefile.in

Fixes `make units` on MSYS 1.0.
Note: `which timeout` succeeds even for MS timeout (c:\windows\system32\timeout.exe), which is not compatible.
(Follows on from #254).

Use `timeout --version` to check for GNU timeout

---

libexec/drivers/coffeetags

Due to the way executables are installed by rbenv, `type coffeetags`
returns true if coffeetags executable is missing in the current ruby
version but is available in one of the other installed rubies.
This commit fixes this issue by explicitly checking rbenv for the
availability of the coffeetags executable within the current ruby
version.

Auto-detect missing coffeetags under rbenv

---

main.c

_NSGetEnviron() returns a pointer to the environ variable, not the
environ variable itself.
---
Issue #93 lead to 1f00f07bbfabfaa275ad8ac1dffc6084415c3724, but [a recent successful Travis OSX build](https://travis-ci.org/fishman/ctags/jobs/52533979#L162) shows a very suspicious compiler warning:
```
main.c:467:4: warning: incompatible pointer types assigning to 'char **' from 'char ***'; dereference with * [-Wincompatible-pointer-types]
e = _NSGetEnviron();
^ ~~~~~~~~~~~~~~~
*
```
I couldn't find the canonical documentation for `_NSGetEnviron()`, but all other use of it I saw indeed dereference the return value<sup>[1](https://git.gnome.org/browse/glib/tree/glib/genviron.c#n307), [2](http://www.open-mpi.org/community/lists/devel/2007/05/1596.php), …

Fix environ retrieval on OSX

---

Makefile.in

Regenerate the build system out of its sources when it changed, to keep
it automatically up to date.  This allows to simply run `make` after
configure.ac has been altered without having to worry about manually
running `autoreconf`.  This is particularly useful when configure.ac
has been updated by a VCS pull, as one is likely not to have noticed
the change.

Regenerate the build system whenever its sources changed

---

vstring.c

Fix invalid memory access when vStringStripTrailing() is called on a
zero-length string.
See https://github.com/fishman/ctags/pull/272#commitcomment-10592939

vstring: Fix invalid memory access with empty strings

---

Makefile.in

Followup for #271 to also regenerate config.h, and so avoid issues like https://github.com/fishman/ctags/pull/270#issuecomment-90525057

Regenerate config.h automatically

---

Makefile.in

At the moment the directory ``autom4te.cache`` is not removed when ``make maintainclean`` is used.
This PR fixes that.

Add removal of autom4te.cache to maintainerclean target

---

Units/d-accessmod.d/args.ctags
Units/d-accessmod.d/expected.tags
Units/d-accessmod.d/input.d
Units/simple.d.t/expected.tags
Units/simple.d.t/input.d
c.c

So previously ctags would think D was C++ and look for `public:`.
That actually doesn't work in D.
D uses Java/C# style modifiers where each method/var has its own:
`private int a() { ... }`
It also does its own thing:
`private {
void a() {
...
}
void b {
...
}
}`

Fix D access modifiers

---

Makefile.in
configure.ac
install-sh
source.mak

Though *.c files are moved to subdirectories, *.o files are generated
on the top src directory when running make.
This patch is mostly based on @b4n's comment at #286 for fixing the
above issue.

buildsys: don't use VPATH

---

main/Makefile
parsers/Makefile

This tries to address @techee's comment https://github.com/fishman/ctags/pull/298#issuecomment-97243973  @techee, does this actually solves your issue?
Note that the code here is particularly adapted for running against #298 (as it asks for `parsers/$@` and not `$@`, e.g. object files in sub-directories), but also work fine on current master, as currently asking for e.g. `parsers/go.o` will involve the rule `.c.o` on `parsers/go.c`, rule that will generate `go.o` (and not the asked `parsers/go.o`, but that's what we want).

Allow to run make from "main" and "parsers" sub-directories

---

Units/variables-prototypes.cpp.b/args.ctags

variables-prototypes.cpp unit: syntax error in args.ctags

---

data/optlib/m4.ctags
docs/news.rst
main/lregex.c

With {exclusive} flag, line oriented comments can be
ignored effectively. Here is an example taken from
m4 optlib:
--m4-regex=/^dnl.*$//c,comments/x
Negative side of this feature is that a kind must be
introduced even for ignoring comments. In above example
`c,comments' is introduced. The kind in the definition
can be empty. In such case 'r,regex' is assigned instead.
This default assignment is not suitable for comments.
As the name field in the definition is empty(//), comments captured
by the regex are not recorded to tags file. However, the
kind is appeared when --list-kinds option is used
like:
$ ./ctags --data-dir=./data --options=m4 --list-kinds=m4
>   c  comments
d  definition
I  inclusion  [off]
u  undefinition
The kind is not for recording but for ignoring. So appearing in
the …

lregex: Introduce kind ghost

---

Makefile.in
source.mak

Features for debugging provided by debug.[ch] is quite useful for development.
We have no plan to release, so there is no reason disabling the features.

Enable debug.[ch]

---

parsers/verilog.c

This functionality is already implemented in vGetc() function.
I did not submit this at the time because I thought I might still need skipToEOL() and did not want to remove it immediately. But to keep the code clean it's just better to submit this and reintroduce the function later if necessary.

verilog: Remove redundant comment skip functions

---

Units/parser-c.r/c-include.d/args.ctags
Units/parser-c.r/c-include.d/expected.tags
Units/review-needed.r/jbrown.vr.t/args.ctags
Units/review-needed.r/jbrown.vr.t/expected.tags
main/get.c
main/get.h
main/parse.h
parsers/c.c

In c917dc681cf44ebdbe21bcb9d2400f4fa9e0eb34, I introduced
'I' kind to C parser to record the name of included header files.
For containing more information separators around the file names (<,
", >) are recorded. After thinking this is too aggressive as default
behavior.
With this patch the separators are recorded only if
--extra=+q. By default only the names of header files without
separators are recorded. If --extra=+q is given both type of tags are
recorded: only a name of header file and a name of header file with
separators.

c: add <> and "" to include kinds only if --extra=+q is given

---

main/get.c

The character following an '@' was dropped if it didn't start a string literal.
This could lead to unexpected problems if '@' was valid in other situations.
---
This change has currently no effect, but could come in handy if at some point anyone is interested with the character following an `@` when the language `hasAtLiteralStrings`.

C#: Don't ignore the character following an '@'

---

Units/fortran-procedure.d/expected.tags
Units/fortran-procedure.d/input.f90
parsers/fortran.c

Recognize Fortran statement such as:
```Fortran
procedure(subprogram_to_point_to), pointer :: my_pointer
```
Import from Geany https://github.com/geany/geany/commit/194ef6010d25e04bf69f705cf94818f68a55f3fa.

recognize Fortran procedure pointers as variables

---

Units/fortran-pointer.d/expected.tags
Units/fortran-pointer.d/input.f90
parsers/fortran.c

Handling Fortran pointer association as:
```Fortran
procedure(ProcOne), pointer :: MyProc => null()
```
Both of the code and test case are imported from Geany.

Fortran: fix handling of pointer association operator

---

Units/go-funcs.d/expected.tags
Units/go-funcs.d/input.go
parsers/go.c

The whole <- token representation has to be inserted into the prototype,
not just the single character <.
@b4n This is the fix to the problem you observed in Geany.

go: fix missing '-' from '<-' in function prototype

---

main/entry.c

This is called immediately earlier in this method.

Remove redundant setDefaultTagFileName()

---

MAINTAINERS
README.md
configure.ac
docs/developers.rst
docs/news.rst
docs/optlib.rst
docs/tracking.rst
docs/universal-ctags.rst
docs/windows.rst
docs/xcmd.rst

I am aware that we are still not using github's organization, so I'm basically using this PR as a way of asking for status information this migration.
In issue #101 we arrived at the conclusion that we should keep "Exuberant Ctags" name.

Move to Github organization

---

main/ctags.h
mk_mingw.mak

There are still quite some places left where the Exuberant should be renamed, but some of those files need to go into the website, others we might delete anyway because they are outdated. But for now these two are here to stay, so they need the rename.
And the PROGAM_URL is likely to change again in the near future

Couple more exuberant renames

---

.ctags
.gitignore
Makefile.in
misc/tinst
mkinstalldirs

Both test facilities units and tmain focused on ctags behavior before installing.
In other hand tinst focuses on something after  installing.
Currently tinst checks files and directories are placed as expected.
As default behavior tinst installs ctags into $(pwd)/tinst-root and check
files and directories under tinst-root.

tinst: installation test facility

---

parsers/fortran.c

parseFunctionSubprogram and parseSubroutineSubprogram do the same thing.
Unify them into one and call it parseSubprogram.

refactor, fortran: replace parseFunctionSubprogram and parseSubroutineSubprogram with parseSubprogram

---

Units/fortran-procedure-qualifiers.d/expected.tags
Units/fortran-procedure-qualifiers.d/input.f90
parsers/fortran.c

Fortran 2003 introduces **pass**, **nopass**, **deferred**, **non_overridable** as procedure qualifiers. This PR provides a patch to parse these keywords.

Fortran: parse Fortran 2003 procedure qualifier keywords

---

main/options.c

Add .gitignore, .hgignore and *~ emacs backup files to the built-in exclusion list

---

parsers/python.c

Now that nestlevel is available separately in main/ the Python parser can use that one.

Python: Remove local nestlevel in favor of global one

---

Units/parser-fortran.r/fortran-bind-c.d/args.ctags
Units/parser-fortran.r/fortran-bind-c.d/expected.tags
Units/parser-fortran.r/fortran-bind-c.d/input.f90
parsers/fortran.c

BIND(C) attribute enables Fortran to interoperate with C. This is a Fortran 2003 feature. See also https://gcc.gnu.org/onlinedocs/gfortran/Interoperability-with-C.html

Fortran: parse bind c attribute

---

Units/python-comments.d/expected.tags
Units/python-comments.d/input.py
parsers/python.c

If there was two hashes (#) in an inline comment, only the content
between the two was considered a comment.
Found while reviewing #383.

python: Fix handling of inline comments

---

parsers/python.c

Most of the time there's no start of a string which means all the 10
strcmp()s are done for every character of the input. This is very expensive:
before this patch this function alone takes 55% of the parser time.
When comparing by character (and avoiding further comparison if the first
character doesn't match), this function takes only 11% of the parser time
so the performance of the parser nearly doubles.

python: optimize skipEverything()

---

parsers/fortran.c

See http://gcc.gnu.org/onlinedocs/gfortran/GNU-Fortran-and-GCC.html
See also http://fortranwiki.org/fortran/show/File+extensions

Support Fortran file extensions .f03, .f08 and .f15

---

Units/parser-fortran.r/fortran-signature.d/args.ctags
Units/parser-fortran.r/fortran-signature.d/expected.tags
Units/parser-fortran.r/fortran-signature.d/input.f90
parsers/fortran.c

Parse signature of Fortran subprogram and prototype. The signature of Fortran language has three forms:
1. No function arguments at all
```Fortran
subroutine suba
end subroutine
```
2. No function arguments but with parens
```Fortran
subroutine suba()
end subroutine
```
3. With function arguments
```Fortran
subroutine suba(a, b)
interger :: a, b
end subroutine
```
In the first and second case, signature will set to NULL and will not write to tags file. In the last case, signature will be written with **--fields=+S** options.

Fortran: support --fields=+S

---

main/options.c

Background:
$ ctags -o - main.c --list-kinds
Both the result of parsing main.c and the list of kinds go to stdout.
A tool consuming output may be confused.
As far as reading option.c ctags doesn't allow such dangerous order of
option specification.
A boolean, NonOptionEncountered becomes true when the command line parser handles
an input file name initially.
checkOptionOrder checks the order for short options.
initOnly field of parametricOption and booleanOption structures provides
the way to declare an order sensitive long options.
These facilities were just ignored.
I am afraid this behavior was introduced by me when working on optlib.
However, exuberant ctags shipped as part of Fedora also ignores the order.
These patches for fxing the facilities.
This breaks the compatibility between …

Revive strict args order

---

parsers/tex.c

ctags warns when following input gives:
\section{}
because a zero length name is passed to makeTagEntry.
This patch makes the tex parser not pass such
zero length names.

tex: don't make a tag for a zero length name

---

.gitignore
Makefile.in
docs/tips.rst

Usage:
After doing make clean, you can build coverage measuring ready
ctags by make COVERAGE=1. At this time *.gcno files are generated
by the compiler. *.gcno files can be removed with make clean.
After building ctags, you can run run-gcov target.  When running
*.gcda files.  The target runs ctags withh all input files under
Units/**/input.*; and call gcov. Human readable result is printed. The
detail can be shown in *.gcov. files. *.gcda files and *.gcov files
can be removed with make clean-gcov.

Enable gcov

---

Units/cxx11-final.d/args.ctags
Units/cxx11-final.d/expected.tags
Units/cxx11-final.d/input.cpp
Units/cxx11-noexcept.d/args.ctags
Units/cxx11-noexcept.d/expected.tags
Units/cxx11-noexcept.d/input.cpp
Units/cxx11-override.d/args.ctags
Units/cxx11-override.d/expected.tags
Units/cxx11-override.d/input.cpp
Units/cxx14-combined.d/args.ctags
Units/cxx14-combined.d/expected.tags
Units/cxx14-combined.d/input.cpp
parsers/c.c

Add support for some C++11 things:
* `final` contextual keywords on classes and structs
* `final` and `override` contextual keywords on methods (see also #405)
* `noexcept`
See also https://github.com/geany/geany/pull/544.  Note that some Geany commits referenced there are not yet merged into master, as I PR this here first to get comments and avoid further divergence.

C++11 stuff (override, final and noexcept)

---

main/debug.c
main/debug.h
main/general.h

If an assertion occurs during parsing of a file, print the location in the parsed input where the assertion occurred.
Closes #420.

debug: Print currently parsed file and line number on asserting

---

Units/parser-objectivec.r/objectivec_property.h.d/expected.tags
parsers/objc.c

there have two bugs: 
first, in `ObjcKinds`, `Protocol` and `property` type both used token `p`, this may cause some conflict. 
I changed the protocol to upper case `P`.
second, in `parseProperty` function, it never set next operation, so if entering parsing property, it won't stop parsing property,  and after other type will parse fail.
here I fix it and set next to the `parseMethods` func, where parseProperty be used from.

fix objc property error

---

docs/news.rst

See: https://github.com/universal-ctags/ctags/pull/419#issuecomment-119602430

Fix typos in news.rst

---

docs/building.rst
docs/other-projects.rst
docs/readme.rst
docs/testing.rst

This is done by:
move universal-ctags.rst to readme.rst
replace include sentences with links
Following discussions in: https://github.com/universal-ctags/ctags/issues/437

Reorganize docs folder to make it more readable

---

docs/Makefile
docs/generate_docs.sh
docs/readme.rst

After https://github.com/universal-ctags/ctags/pull/440
we cannot generate pdf and html documents directly,
This script make we can.
Problem:
command
> rst2pdf readme.rst universal-ctags.pdf -e inkscape
always run into error when deal with svg picture, I cannot test it locally.
But command
> rst2pdf readme.rst universal-ctags.pdf
can generate pdf without svg image.
rst2html only work by calling rst2html.py. This works very good.

add generate_docs.sh to reformat rst files, and generate pdf and html

---

Units/parser-m4.r/m4-comment.d/args.ctags
Units/parser-m4.r/m4-multi-undef.b/args.ctags
Units/parser-m4.r/m4-simple.d/args.ctags
data/optlib/m4.ctags

You can turn it on with --languages=+m4.
I will add more small regex based parsers for rather minor languages.
These are for making hyper text with pygments. Many part of users may not have interests 
tags for such minor langauges, I disable it by default.

m4: make the parser optional (2 days)

---

main/options.c

The output of `ctags --help` was not sorted in alphabetical order after
the support of encoding options.

Sort --help output

---

misc/budge
misc/budge.ctags

How ctags source code is coverted by ctags?
This script shows the ratio of the number of files handled by ctags to
the number of all files of ctags source directory.
Usage(simple):
$  bash misc/budge
[ctags|87%]
Usage(verbose):
$ VERBOSE=1 dash misc/budge
README.md: NONE
ctags.1.in: NONE
.indent.pro: NONE
COPYING: NONE
docs/output-tag-stream.svg: NONE
.travis.yml: NONE
old-docs/FAQ: NONE
old-docs/INSTALL.oth: NONE
old-docs/website/FORMAT: NONE
old-docs/website/ctags.xcf: NONE
old-docs/website/ctags.png: NONE
old-docs/INSTALL: NONE
old-docs/NEWS.exuberant: NONE
old-docs/README.exuberant: NONE
old-docs/MAINTAINERS: NONE
.gdbinit: NONE
Eiffel/Ace.ace: NONE
ctags.spec: NONE
configure.ac: NONE
win32/ctags_vs2013.vcxproj: NONE
win32/ctags_vs2013.vcxproj.filters: NONE
win32/ctags_vs2013.sln: …

a prototype of our own budge (7 days)

---

main/e_msoft.h
main/lxcmd.c
main/mbcs.c
main/parse.c
mk_mvc.mak

* VC2015 has snprintf.
* VC doesn't have unistd.h.
* __USE_GNU is already defined in makefiles.
* Definition of isLanguageKindEnabled was different from its
declaration.
* Couldn't link with libiconv. Imported @koron's patch:
https://github.com/koron/ctags/commit/f09817755ac218425e7e5c265f70b808a835f46b

Fix build errors and warnings with VC2015 (7 days)

---

parsers/beta.c

It seems that coverall (or lcoveralls command) expects source code
files are encoded in UTF-8.

beta: convert the encoding to utf-8(1 day)

---

Units/review-needed.r/simple.rb.t/expected.tags
Units/ruby-block-call.d/expected.tags
Units/ruby-block-call.d/input.rb
Units/ruby-class-method-in-lt-lt-self.d/expected.tags
Units/ruby-class-method-in-lt-lt-self.d/input.rb
Units/ruby-doc.d/expected.tags
Units/ruby-doc.d/input.rb
Units/ruby-namespaced-class.d/expected.tags
Units/ruby-namespaced-class.d/input.rb
Units/ruby-scope-after-anonymous-class.d/expected.tags
Units/ruby-scope-after-anonymous-class.d/input.rb
parsers/ruby.c

* Fix handling of documentation contents
* Fix matching keywords (https://github.com/geany/geany/issues/587)
* Fix parsing qualified identifiers (#452)
* Fix scope after anonymous classes
* Report correct scope type (instead of always "class")
* Report methods inside an anonymous class (inside a class) as singletons (#455)
Disclaimer: I don't know Ruby (at all).  The fixes here are based on reports, inspection of some Ruby resources (quick look at some more or less formal definitions) and inspecting the interpreter behavior (e.g. for what's valid).

Various Ruby fixes

---

ctags.1.in

Related: #460 
@masatake's comment from https://github.com/k-takata/ctags/commit/15ac5bb6891e4778d077b46d44f6ca5d9eb25a07#commitcomment-12359250:
> A script in linux kernel source tree runs ctags. The script expects "exuberant" in --version.
> https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/scripts/tags.sh#n276
> 
> I would like to use u-ctags when reading the kernel.
> 
> I would like to discuss about the output of --version with the other members.

Rename to Universal Ctags(5 days)

---

Units/parser-fortran.r/fortran-enum.d/expected.tags
Units/parser-fortran.r/fortran-enum.d/input.f90
parsers/fortran.c

Fortran 2003 enums is:
```Fortran
enum, bind(c)
enumerator [::] name1 [= val], ...
end enum
```
See https://books.google.com.hk/books?id=40UkLNQuAeoC&pg=PA114&lpg=PA114&dq=fortran+enumerator+type&source=bl&ots=WTou0LNC5z&sig=kV-2jyz4T2qUlCQ3T4jx3WeRJkc&hl=zh-CN&sa=X&ei=JZeSVbSSH5DYoAShrI6gDA&ved=0CEcQ6AEwBTgK#v=onepage&q=fortran%20enumerator%20type&f=false page 114
and http://www-01.ibm.com/support/knowledgecenter/SSGH4D_10.1.0/com.ibm.xlf101a.doc/xlflr/enum.htm%23enum
We shoud note that
+ bind(c) is mandatory
+ enum shoud have no name
+ enumerator should have no qualifier
The implementation of Geany is different https://github.com/geany/geany/commit/9520e7f7d7b7a9570db2feb165653ef1d68e547a which is based on
http://docs.cray.com/books/S-3692-51/html-S-3692-51/z970507905n9123.html. The …

Parse Fortran 2003 enum

---

Tmain/input-encoding-option.d/tags-expected.txt
Tmain/output-encoding-option.d/tags-expected.txt
main/ctags.h
main/entry.c
main/options.c

Close #472.
We are afraid that bugs about our code go to Darren.
So in this commit I remove his mail address from both
--version output and pseudo tags.
However, I embed/keep pointers to the original great work.
Here are new results:
$ ./ctags --version
Universal Ctags Development, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
Compiled: Aug  1 2015, 15:34:40
URL: https://ctags.io/
Optional compiled features: +wildcards, +regex, +multibyte, +debug, +option-directory, +coproc
$ ./ctags /dev/zero
$ cat tags
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	// …

Remove Darren's mail address from --version output and pseudo tags(3 days)

---

parsers/perl.c

This bug in findPerlTags() might become less benign should the
implementation of fileReadLine() change.

Fix a benign-for-now off-by-one bug in Perl parser

---

Tmain/lregex-list-kinds.d/run.sh
data/optlib/gdbinit.ctags
data/optlib/m4.ctags
docs/optlib.rst
main/lregex.c

{optional} long is redundant. It can be replaed with --kind-<LANG>=-
option.
Note about compatibilities:  I introduced it and exuberant ctags doesn't have it.

main, lregex: remove {optional} long flag (3 days)

---

main/lxcmd.c
main/parse.c

This commit suppresses following messages warned when coproc is not available:
main/parse.c: In function ‘createTagsWithXcmd’:
main/parse.c:1784:20: warning: implicit declaration of function ‘invokeXcmd’ [-Wimplicit-function-declaration]
tagFileResized = invokeXcmd (fileName, language);
^
main/parse.c: At top level:
main/parse.c:1777:16: warning: ‘createTagsWithXcmd’ defined but not used [-Wunused-function]
static boolean createTagsWithXcmd (
^

main: rearrange the locations of #ifdef/#endif for xcmd related code(1 day)

---

win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

The new Perl6 parser is not yet added to the Visual Studio project files.

Add Perl6 parser to VS project files as well (1day)

---

Makefile.in

If `configure` was executed in a different directory form the srcdir, `make check` didn't work.
E.g.
```sh
$ cd $srcdir   # cd to the top of the u-ctags srcdir
$ mkdir build
$ cd build
$ ../configure
...
$ make check
...
/bin/sh: misc/units: No such file or directory
Makefile:439: recipe for target 'tmain' failed
make: *** [tmain] Error 127
```
Note: This PR enables to run `make check` in a different builddir, but the results of `make check` are still stored under `$(srcdir)/Unit` or `$(srcdir)/Tmain`. It would be prefer to store the results in the builddir.

Fix that make check couldn't run in a different builddir

---

main/options.c

MinGW64 defines asprintf when __USE_MINGW_ANSI_STDIO is defined.
MSYS2 makepkg-mingw system automatically defines this macro. Without
this change, makepkg-mingw fails because asprintf is redefined in
options.c.

options.c: Avoid redefining asprintf

---

Units/cxx11-delete.d/args.ctags
Units/cxx11-delete.d/expected.tags
Units/cxx11-delete.d/input.cpp
parsers/c.c

In C++03 '= 0' was only valid if the member function was virtual, but in
C++11 '=' may be used for non-virtual member functions, too.
Without the change, the 'Del::operator =' declaration is not found in
the testcase.

c++: Handle C++11 '= delete'

---

Units/rust-test_input.d/expected.tags
Units/rust-test_input.d/input.rs
Units/rust-test_input2.d/expected.tags
Units/rust-test_input2.d/input.rs
parsers/rust.c

- Update Rust examples to compile with modern Rust
- Handle some syntax changes (`where` bounds) that were made close to the 1.0 release.

Rust parser and test updates

---

parsers/fortran.c

A temporary vString was being created unnecessarily.

fortran: Cleanup parseNumeric() function

---

configure.ac

MinGW has stat.st_ino but it doesn't contain a valid value. Disable it.
Some tests fail on MSYS2 without this fix.

Fix that isSameFile() in routines.c didn't work on MSYS2

---

.travis.yml
misc/travis-check.sh

Add new environment variable TARGET to separate normal Unix compilation
from mingw32 and exclude the combination clang + mingw32 from the test
matrix.

travis: Compile mingw32 separately

---

misc/units

Also fixes valgrind checking.
See: https://github.com/universal-ctags/ctags/issues/494#issuecomment-133634328
Note: When running on MSYS2, `MSYSTEM` is set to "MSYS", "MINGW32" or "MINGW64".

units: Add dos2unix checking when running on MSYS2

---

misc/units

MSYS2 wrongly handles regex options as Unix style path, and convert it to MS-DOS style path.
Setting `MSYS2_ARG_CONV_EXCL` avoids it.
See: http://sourceforge.net/p/msys2/wiki/Porting/#filesystem-namespaces
Related: #494

units: Avoid unexpected pathname conversion on MSYS2(masatake: till Aug 23)

---

Makefile.in

In out-of-source builds, ctags.1 is created in the build directory, not
in the directory that contains the source files.

Makefile.in: copy ctags.1 from build directory

---

configure.ac
main/e_msoft.h
main/entry.c
main/routines.c
main/sort.c
main/sort.h

There were two problems with tempfile handling on MSYS2.
1. MinGW-w64 has mkstemp(), but it deletes a tempfile automatically when the file descriptor is closed. However u-ctags expects that the file remains.
2. tempdir was set to '/tmp', but it's not prefer for Windows. Use `TMP` environment for the temporary directory.
Related: #494

Fix that writing tags to stdout didn't work with MSYS2(masatake: till Aug 23)

---

main/parse.c

These commits make the code choosing a language more flat.
Flatted code may help people understand the code.

Choose default language in upper layer

---

Makefile.in
misc/tinst
parsers/eiffel.c

3 patches are included in this PR.
The 1st and 2nd are for cleaning up Makefile.in.
With the 3rd one, you can run "make tinst" in a separated builddir.

Run tinst in separated builddir

---

main/parse.c
main/strlist.c
main/strlist.h

The leak is found in option-corpora-conflicts.d test
case with VG=1.

main: fix a memory leak in language map operation

---

Units/parser-r.r/r-extended.d/expected.tags
Units/parser-r.r/r-extended.d/input.r
Units/parser-r.r/r-simple.d/expected.tags
Units/parser-r.r/r-simple.d/input.r
main/parsers.h
parsers/r.c
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

Based on this StackOverflow question:
http://stackoverflow.com/questions/32206608/ctags-and-r-regex

R: Add regular expression R parser

---

appveyor.yml
win32/appveyor.bat

[AppVeyor](http://www.appveyor.com/) is a CI service for Windows.
This PR enables to check three configurations on AppVeyor:
1. VC12 with msbuild (ctags_vs2013.sln), iconv disabled
2. VC12 with nmake (mk_mvc.mak), iconv enabled
3. MinGW (mk_mingw.mak), iconv disabled
This only checks compilation error, because the makefiles for Windows don't have tests.
(I tried to use autotools with MinGW, but it didn't work on AppVeyor.)
Result: https://ci.appveyor.com/project/k-takata/ctags/build/1.0.46

Utilise AppVeyor

---

win32/appveyor.bat

Some tests were skipped on Cygwin on AppVeyor because Cygwin version of
dos2unix was not installed. (Another version of dos2unix which comes
with Git is already installed but it doesn't work well when we run our
tests.)

AppVeyor: Install dos2unix on Cygwin

---

configure.ac

Redundant TMPDIR environment variable tests are exists in configure.ac.

configure.ac: Remove redundant $TMPDIR environment variable test.

---

configure.ac

Message printing autoconf macros were used inappropriately.
(revised #556)

Fix configure message printing macro usage, rev1

---

Makefile.in
mk_mingw.mak

This was only implemented in the main Makefile and mk_mingw.

make: Simplify compiler echo string during make

---

configure.ac

AC_TRY_COMPILE() and AC_TRY_RUN() are obsolete. Succeeding AC_COMPILE_IFELSE() and AC_RUN_IFELSE() should be used.

Fix configure use obsolete detecting macros

---

configure.ac

When checking header file contains string "yes" such as "_Bool prompt_yes_or_no(void);", CHECK_HEADER_DEFINE() returned wrong result.

Fix configure convenience macro

---

source.mak

Header file main/tg.h is missing in source.mak.

build: Add missing main/tg.h to MAIN_HEADERS in source.mak

---

misc/units

The program name(ctags by default) is used as prefix in warning
messages.  So comparing expected output and actual output of stderr
can be failed when using a ctags binary is built with
--program-transform-name is used.
To avoid the failures, with this commit tmain target rearranges the
actual output; substitute "^ctags" with the transformed progoram name
before comparing.
The issue is reported by @viccuad on #568.
Close #568.

tmain: handle transformed program name ( 3 days )

---

configure.ac

In configure.ac, some m4 builtins are used directory.
autoconf provides 'm4_'-prefixed alias macros for m4 builtin macros, and original non 'm4_'-prefixed macros are not recommended. Equivalent AS_TR_CPP provided by autoconf is more suitable rather than complex these m4 builtins.
AS_TR_CPP first appeared in autoconf-2.50a (2001-06-26).
autoreconf-2.59 and autoreconf-2.69 with '-Wall' report no warnings.

Replace complex m4 builtins in configure.ac with suitable AS_TR_CPP

---

Makefile.in

Renaming makefile-variables:
`datadir` to `pkgdatadir`, and
`pkgconfdir` to `pkgsysconfdir`.
fix #576.

Arrange makefile variables to improve consistency

---

Units/dts-simple.d/expected.tags
Units/regex-with-scope.d/args.ctags
Units/regex-with-scope.d/expected.tags
Units/regex-with-scope.d/input.foo
docs/optlib.rst
main/entry.c
main/entry.h
main/flags.c
main/flags.h
main/lregex.c
main/options.c
main/parse.c
main/parse.h
parsers/dts.c

Introduce scope long flag to allow a regex based parser attaching scope information to tags.
e.g.
```
$ cat /tmp/input.pp
class foo {
include bar
}
$ cat /tmp/pp.ctags
--langdef=pp
--map-pp=+.pp
--regex-pp=/^class[[:blank:]]*([[:alnum:]]+)[[[:blank:]]]*\{/\1/c,class,classes/{scope=push}
--regex-pp=/^[[:blank:]]*include[[:blank:]]*([[:alnum:]]+).*/\1/i,include,includes/{scope=ref}
--regex-pp=/^[[:blank:]]*\}.*//{scope=pop}{exclusive}
$ ~/var/ctags/ctags --options=/tmp/pp.ctags -o - /tmp/input.pp
bar	/tmp/input.pp	/^    include bar$/;"	i	class:foo
foo	/tmp/input.pp	/^class foo {$/;"	c
```

Regex with scope

---

configure.ac

Refactoring.
As calling AH_TEMPLATE macros for NEED_PROTO_* are similar and having auto-generatable form, call AH_TEMPLATE([NEED_PROTO_*]...) from CHECK_PROTO().
Comparison:
```
$ git show $(git merge-base --fork-point master):configure.ac | wc -lc;  git show HEAD:configure.ac | wc -lc
632   18532
599   16907
```
reduced 33 (~5.2%) lines, 1625 (~8.8%) bytes.

build: Refactor configure CHECK_PROTO macro.

---

main/kind.h
main/lregex.c
main/lxcmd.c

Quoted comments by @b4n from
https://github.com/universal-ctags/ctags/commit/3525c8f14fd74282810974a7791a9adcb261cb35#commitcomment-13459230
Removal of const modifier annoys me, because we assign to string
literals and I'm a fervent user of -Wwrite-strings, which gives me
endless warnings like those:
parsers/c.c:307:15: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
{ TRUE,  'c', "class",      "classes"},
^
parsers/c.c:307:24: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
{ TRUE,  'c', "class",      "classes"},
^
parsers/c.c:308:15: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
{ TRUE,  'd', "macro",      "macro definitions"}, …

main: Revive const modifiers in kindOption

---

Makefile.in
configure.ac

Add '--with-ctags-datadir', '--with-ctags-sysconfdir', and '--with-ctags-libexecdir' configure options to control universal-ctags specific installation directories.
fix #580.

build: Add '--with-ctags-{data,sysconf,libexec}dir' configure options

---

Tmain/allow-null-tag.d/stdout-expected.txt
main/entry.c

Revisit #492, #590.
As suggested by @b4n in #590, a tag for an empty string is not useful.
With this commit ctags doesn't record such tags even if AllowNullTag is TRUE.
In other word, AllowNullTag field just controls  the warning about
the tags for empty strings; ctags doesn't warn if it is TRUE.

main: don't make a tag for an empty string even if AllowNullTag is TRUE

---

appveyor.yml
win32/appveyor.bat

Now MSYS2 is preinstalled on AppVeyor. Use preinstalled version.

appveyor: Use preinstalled MSYS2

---

Tmain/tmain-skip-example.d/run.sh
misc/units

* Default shell is now /bin/sh.
Defaulting to $SHELL would not work if "make units" was called from tcsh.
* Small typo fix in misc/units.

tmain: Various small fixes

---

Units/parser-fortran.r/bug629.d/args.ctags
Units/parser-fortran.r/bug629.d/expected.tags
Units/parser-fortran.r/bug629.d/input.c
parsers/fortran.c

When parsing C enum, Fortran parse try to find an "end" token in
parseEnumBlock. There is no such key word at end of C enum statement and
the parser falls into infinite loop. To solve it, add an end-of-file
test when trying to find "end" token. If reach end of file, jump out of
the loop.

fix #629 infinite loop with fortran parser on C file

---

Units/afl-fuzz.r/github-issue-628-vera.d/input.vr
Units/fuzz-hitting-assertions.r/vera-fha-0.d/expected.tags
Units/vera-interface.d/expected.tags
Units/vera-interface.d/input.vr
parsers/c.c

Close #628.
#628 reports interface kind of vera is implemented
incompletely.
This commit implements it. As the result the assertion
failure reported in #628 is fixed.
To implement interface kind, signal kind is also
defined. (signals are declared inside interface.)
TODO: scope field for signal kind is not implemented yet.

vera: implement interface kind

---

parsers/c.c

The condition "st->declaration == DECL_NAMESPACE" in "else if" in tagCheck
is duplicated: the same condition is also checked in isContextualStatement:
static boolean isContextualStatement (const statementInfo *const st)
{
boolean result = FALSE;
if (st != NULL) switch (st->declaration)
{
...
case DECL_NAMESPACE:
...
result = TRUE;
...
return result;

c-family: remove a duplicated if-conditions

---

Units/parser-c.r/c-label.d/input.c
parsers/c.c

A switch case label containing more than two tokens,
C parser mistakenly detects it as a  goto label.
e.g.
switch (i)
{
case X|Y:
break;
Here Y was captured as a goto label.
This commit adds an extra condition for avoiding the above case.
Only if a label candidate is not in the switch statement, c parser
makes a "goto label" kind tag for the candidate.

 C: don't make a tag for switch/case label

---

Units/extra-total-lines.d/args.ctags
main/parse.c

I extended --extra option(.) for printing the total number of lines of
input file in c5d6954569123.
However, I injected a bug in 98392b01.  When specifying `.' with `f',
the total number of lines is not printed. This commit fixes it.

main: Don't ignore `.' extra entry when `f' is specified together

---

Tmain/omit-long-patterns.d/gen.sh
Tmain/omit-long-patterns.d/input.sh
Tmain/omit-long-patterns.d/run.sh
Tmain/omit-long-patterns.d/stdout-expected.txt
Units/parser-flex.r/flex_only_mxml.mxml.d/expected.tags
Units/perl6-bunch1.d/expected.tags
Units/review-needed.r/3526726.tex.t/expected.tags
Units/review-needed.r/simple.asp.t/expected.tags
Units/review-needed.r/simple.vim.t/expected.tags
docs/news.rst
main/entry.c
main/options.c
main/options.h

Too long input lines may make tags file larger.
This commits omits the length of pattern field printed to a tags file.
If a making pattern is longer than the value of Option.patternLengthLimit,
the pattern is omitted; instead of including whole the input line, the
rest of substring after nth byte of Option.patternLengthLimit is is
printed as \.\{N}. Here N is the length of the substring.
As far as testing vim accepets \.\{N} as part of a pattern.
Close #163.

main: omit patterns for long input lines

---

Units/python-disable-member-kind.d/args.ctags
Units/python-disable-member-kind.d/input.py
parsers/python.c

In makeFunctionTag function, tags both member and function kinds are
made. If the kinds are disabled, the tags should not be made.
At the head of makeFunctionTag, the enablement of function kind is
checked but that of member is not checked. As the result, an assertion
is made failure as reported in #648 by @yevhen-m.
This commit fixes this; the enablement of "member" kind is also
checked in makeFunctionTag.
Close #648.

python: check the enablement of "member" kind in makeFunctionTag

---

Units/parser-verilog.r/systemverilog-github646.d/expected.tags
Units/parser-verilog.r/systemverilog-github646.d/input.sv
parsers/verilog.c

verilog: Don't unget character if end-of-file was reached

---

main/entry.c
main/entry.h
main/read.c

Making a pattern takes long time for long input line.  This commit
shortens the time. See the second commit about evaluation of my technique.

Optimize pattern generation

---

Tmain/tmain-example.d/stdout-expected.txt
parsers/ruby.c

(This is about a bug spotted in #453 by @mislav and in #11 by
@NewAlexandria.)
Kinds C and d are for Rspec.
Parts of code related to above kinds assume a ruby string
comes after Rspec keywords (describe or context).
This is a wrong assumption. A class name can be used there.
It is nice if ctags can handle these rspec code well, but we
don't have enough resource to make it now.
So in this commit I delete rspec related code temporary. I
just reserve a kind letter 'd' for rspec for the future. 'C'
is completely deleted because (1) describe and context have
the same meaning in rspec, and (2) we would like to assign
'C' for Ruby constant as ripper-tags does.

Ruby: delete rspec related kinds

---

docs/units.rst
misc/units

Just for improving the appearance of units output, I removed 'r' suffix
from categories of units test cases. This is just inconvenient when
one wants to access to a result of a failed test case.

units: don't remove 'r' suffix from category name when displaying the name

---

Makefile.in
win32/appveyor.bat

Instead of referring an environment variable APPVEYOR described in http://www.appveyor.com/docs/environment-variables, I define it in appveyor.bat explicitly as same as we defined TRAVIS
in misc/travis-check.sh.

appveyor: show diff output of failure test cases

---

main/main.c

These two are used in environment-modules package of fedora.

main: Allow passing BASH_FUNC_module and BASH_FUNC_scl as environment variables

---

main/field.c
main/kind.c
main/kind.h

To avoid circular header file inclusion, tagEntryInfo was defined in
multiple headers. The one of definition is needed in a parameter of
prototype declaration of renderRole function. However, the parameter
is not used in the function now.
This commit removes both the parameter and the one of tagEntryInfo type
info definition.
This is needed to build ctags on RHEL5.11.
Close #699.

main: remove unused parameter from renderRole function

---

docs/conf.py

Based on RTD FAQ and the RTD-theme install instruction
http://read-the-docs.readthedocs.org/en/latest/faq.html
https://github.com/snide/sphinx_rtd_theme (`git or download` section in README)
If the RTD theme is not found the default theme of Sphinx theme is use (as before)

Docs: Use the RTD theme if it is installed locally

---

mk_mingw.mak
mk_mvc.mak

maintainer.mak has been already removed with the commit
5dc45359a022626d4f5f3aa89f8d232cda69bcfc, and the dctags target has been
also removed. It is better to remove the dctags target also from
mk_mingw.mak and mk_mvc.mak.
If you want to build debug version, use the following commands:
MinGW: make -f mk_mingw.mak DEBUG=1
MSVC:  nmake -f mk_mvc.mak DEBUG=1

Remove dctags target from all makefiles

---

main/parse.c

e.g.
$ ./ctags --verbose main/kind.h
...
Get file language for main/kind.h
pattern: kind.h
#candidates: 2
0: C++ (*.h)
1: ObjectiveC (*.h)
Selector: 0x415260
selection: C++
...

main: print the result of parser guessing in more detail

---

Units/parser-cpp.r/namespace-and-scope.b/args.ctags
Units/parser-cpp.r/namespace-and-scope.b/expected.tags
Units/parser-cpp.r/namespace-and-scope.b/input.cpp

"class" is used as the kind of parent scope where "namespace" should
be used.

Units, C++: add a case reproducing a bug about wrong scope kind

---

makefiles/testing.mak
misc/units

Allow to run units and tmain targets on zsh.
Issue reported by @tarzanek on #721.

units: allow to run test cases on zsh

---

Makefile.am
main/repoinfo.c

repoinfo.h was general even when building ctags from tarball.  As
reported by @hauleth in #727, code snippet in Makefile.am made broken
repoinfo.h. This commit improves the situation.
The code snippet in Makefile.am in this commit make an empty repoinfo.h.
Instead CTAGS_REPOINFO is defined as NULL in repoinfo.c if CTAGS_REPOINFO
is not defined.

buildsys: make an empty repoinfo.h when building ctags from tarball

---

Tmain/list-fields-with-prefix.d/run.sh
Tmain/list-fields-with-prefix.d/stdout-expected.txt
docs/news.rst
main/ctags.h
main/entry.c
main/field.c
main/field.h
main/options.c
main/options.h

We want to add more fields to tags output.
e.g. "returnType:" of a function declaration,
"decorator:" or "annotation:" attached to a name.
In other hand there are many tags generators. .e.g.  coffeetags and
ripper-tags. The authors of these tools may want to add the
generator(and its target language) own new fields to the output.
There is concern about confliction of field names.
For providing a workaround of the confliction, this
commit introduce --put-field-prefix option.
When --put-field-prefix is given, "UCTAGS" is prefixed to the name of
all fields newly introduced in universal ctags.
Example output(--list-fields):
[yamato@x201]~/var/ctags-github% ./ctags --put-field-prefix --list-fields | grep UC
r	UCTAGSrole	role	format-char	off
Z	UCTAGSscope	Include the "scope:" key in scope …

main: Introduce an option to add "UCTAGS" as prefix to field names

---

Tmain/list-roles.d/stdout-expected.txt
Units/parser-java.r/imported-role.d/args.ctags
Units/parser-java.r/imported-role.d/expected.tags
Units/parser-java.r/imported-role.d/input.java
parsers/c.c

Packages imported with keyword `import' are tagged as reference tags
with this commit. The wild-card(*) used in package specification is
recorded asis.
Example output:
[yamato@x201]~/var/ctags-github% cat foo.java
import java.util.Map;
import java.util.*;
package X;
[yamato@x201]~/var/ctags-github% ./ctags --fields=+r --extra=+r -o - foo.java
X	foo.java	/^package X;$/;"	p
java.util.*	foo.java	/^import java.util.*;$/;"	p	role:imported
java.util.Map	foo.java	/^import java.util.Map;$/;"	p	role:imported

Java: implement `imported' role

---

Makefile.am
configure.ac
misc/travis-check.sh

-DDEBUG option was passed by default.  This flag slows ctags down;
whole the buffer area of a vString object is filled with 0 every
vStringClear call.
With this commit -DDEBUG is not passed by default.  To enable it,
--enable-debugging must be passed when running configure.

buildsys: add --enable-debugging option and disable debugging by default

---

parsers/c.c

Add a missing entry in the declString array. Fixes debug mode runs.

C++: add missing array entry in declString

---

main/e_msoft.h

There's no longer a reason to use stdout instead of stderr, as djgpp (if you still support DOS at all, I guess this is what you're using) provides `redir` expressly for the purpose of manipulating
standard error and `CMD.EXE` supports `2>` directly.

Use stderr for MS-DOS/Windows.

---

Units/parser-cpp.r/bug852368.cpp.d/input.cpp
Units/parser-fortran.r/bug726712.f90.d/input.f90
Units/parser-fortran.r/lanus.for.d/input.for
Units/parser-fortran.r/misc_types.f.d/input.f
Units/parser-verilog.r/verilog-sf_bug108_1.d/input.v
Units/php-mode.d/input.php
Units/review-needed.r/3214129.vim.t/input.vim
Units/review-needed.r/3526726.tex.t/input.tex
Units/review-needed.r/bug612019.pas.t/input.pas
Units/review-needed.r/jsFunc_tutorial.js.t/input.js
Units/review-needed.r/mode.php.t/input.php
Units/review-needed.r/moniker.x68.t/input.x68
docs/semifuzz.rst
gnu_regex/regcomp.c
gnu_regex/regex.c
gnu_regex/regex_internal.c
gnu_regex/regexec.c
main/parse.h
main/read.c
mk_mingw.mak
parsers/jscript.c
parsers/sql.c
parsers/vim.c

All credit goes to the authors of codespell.
(Well except for 'sentance', which somehow isn't detected.)
However, I have verified and correct them all by myself and am now going blind -- err, I mean, I won't do the rest by hand.
Some of these corrections may need special attention, most importantly:
This sounds like it was taken from a third-party script, and that script should be fixed, too.
This caused downstream bug: https://github.com/geany/geany/pull/849
These are the codespell results that look like a true positive, but were ignored by me for some reason:
(ignored, because these are "ancient" changelogs)
./old-docs/NEWS.exuberant:142: accomodate  ==> accommodate
./old-docs/website/quotes.html:678: alot  ==> a lot, allot
./old-docs/NEWS.exuberant:833: indentical  ==> identical …

Fix a lot of typos

---

Makefile.am
misc/optlib2c
optlib/CoffeeScript.c

See c5dc92b.
Close #753.
An issue about program transformation is reported in #753.
I didn't considered that the name of xcmd drivers are also transformed.
Instead of changing Makefile.am as proposed in #753 by @jonthn, I fixed optlib2c.

Fix broken program transformation in optlib

---

Units/parser-python.r/nested-parenthesis.d/args.ctags
Units/parser-python.r/nested-parenthesis.d/expected.tags
Units/parser-python.r/nested-parenthesis.d/input.py
parsers/python.c

Close #763 reported by @m-novikov.
Bug: any signatures that contain inside parenthesis made
python parser confused.
This commit fixes this bug.

Python: allow nested parenthesis in arglists

---

Units/parser-sh.r/function-identifiers-bash.d/expected.tags
Units/parser-sh.r/function-identifiers-bash.d/input.bash
parsers/sh.c

Recognize all the crazy stuff Bash allows as function identifiers when
using the `function` keyword.

sh: Add support for extra Bash function identifiers

---

Units/parser-python.r/toplevel-funcall-with-keyword-args.d/expected.tags
Units/parser-python.r/toplevel-funcall-with-keyword-args.d/input.py
parsers/python.c

Close #765.
A bug description quoted from #765 reported by @m-novikov:
Function calls with multi-line keyword arguments results in
keyword arguments parsed as variables. Given:
foo(
arg1=1,
arg2=2
)
def bar():
pass
In the example arg1 and arg2 are captured as tags.
This commit fixes this bug.
Python parser processes input file line by line.  Line may include a
tag or not. Python parser applies rules for capturing a tag to the
each input line. This commit introduces a fallback rule which calls
skipParens. As the result foo (...) in the above example are skipped.

Python: fix a bug about multi-line keyword arguments

---

Units/parser-cpp.r/cxx11-raw-strings.d/expected.tags
Units/parser-cpp.r/cxx11-raw-strings.d/input.cpp
main/get.c
main/get.h
main/read.c
main/read.h
parsers/c.c
parsers/dts.c

See http://en.cppreference.com/w/cpp/language/string_literal
---
This contains a pretty ugly hack to fetch the previous character, in
order not to get fooled by string concatenation hidden behind a macro,
like in `FOUR"five"`, which is not a raw string literal but simply the
identifier `FOUR` followed by the string `"five"`.
While this may sound uncommon, it is not and lead to complaints [2][3]
when Scintilla [1] broke this when they introduced C++11 raw string
literal support themselves.
The implementation here still contains a bug with line continuations: a
raw literal of the form:
```c
const char *str = R\
"xxx(...)xxx";
```
is not properly recognized as such, although it's perfectly valid (yet
probably very uncommon).  For the record, Scintilla has also suffers
from this but nobody …

c++: Fix parsing of C++11 raw string literals

---

misc/budge.ctags

No extra option for running the budge script is
needed now.

budge: make budge.ctags empty

---

Units/parser-python.r/python-dot-in-import.d/args.ctags
Units/parser-python.r/python-dot-in-import.d/expected.tags
Units/parser-python.r/python-dot-in-import.d/input.py
parsers/python.c

import statements including periods were not parsed well.
e.g.
```
import A.B
```
Only B was captured as a reference tag.
This commit fixes the bug.

Accept period as module name in python

---

Units/parser-python.r/triple-quotes-in-class.b/expected.tags
Units/parser-python.r/triple-quotes-in-class.b/input.py

From #781:
```
% cat /tmp/t.py
class Foo():
bar=dedent("""
baz
""")
class Bar():
pass
% ctags -f - /tmp/t.py
Foo	/tmp/t.py	/^class Foo():$/;"	c	language:Python
bar	/tmp/t.py	/^    bar=dedent("""$/;"	v	language:Python	class:Foo
```
`Bar` is missing.
This is possibly related to the code at https://github.com/universal-ctags/ctags/blob/master/parsers/python.c#L1110-L1118 and/or https://github.com/universal-ctags/ctags/blob/master/parsers/python.c#L866.

Failing test for #781: triple quotes used with attrib

---

Units/parser-java.r/java-catch-block.d/args.ctags
Units/parser-java.r/java-catch-block.d/expected.tags
Units/parser-java.r/java-catch-block.d/input.java
parsers/c.c

Close #797, a bug reported by @mrate.

Java: add catch as a keyword

---

parsers/ant.c
parsers/dbusintrospect.c
parsers/glade.c
parsers/maven2.c

Missing curly braces when initializing union members in tagXpathTable structs:
- recurSpec
- makeTagSpec
Fix for #798

Fix union syntax errors in parser files.

---

Units/parser-cxx.r/cxx-shift-operators-in-template-parameters.b/expected.tags
Units/parser-cxx.r/cxx-shift-operators-in-template-parameters.b/input.cpp

The order of lines and patterns were broken.

Units, C++: fix broken test case for #807

---

parsers/c.c

Handle this case as well:
```
template <int P> class c {};
c< 8 > bVar;
c< 1<<8 > aVar;
```

Add another case to handle shift operators in template parameters

---

Tmain/readtags-qualifier.d/run.sh
Tmain/readtags-qualifier.d/stdout-expected.txt
docs/news.rst
dsl/qualifier.c

To handle the tags file in which uncommon fields are used, this commit introduces generic field accessor.

readtags: implement $, generic extension field accessor

---

makefiles/testing.mak

These days failures are reported frequently
because of timeout.

units: extend the timeout value

---

Units/parser-php.r/php-full-qualified-tags.d/expected.tags
main/entry.c
main/kind.c

makeQualifiedTagEntry() builds a full qualified tag for
a given tag. It uses scope information; put a separator
between upper item and the current item specified with
the given tag.
This commit handles the case when there is no scope information.  If
such case a root separator must be put as prefix to the current item.
e.g.
input:
<?php
namespace foo;
>
the output with --extra=+q:
\\foo	input.php	/^namespace foo;$/;"	n
foo	input.php	/^namespace foo;$/;"	n

main, php: add a root separator to top level items

---

Units/parser-sql.r/sql_pgSQL_empty_decl.d/expected.tags
Units/parser-sql.r/sql_pgSQL_empty_decl.d/input.sql
parsers/sql.c

The original code expects a semicolon in a declare block.  However,
as a test case shows, a block can have a token other than a semicolon
at least in pgSQL.
This commit adds an additional rule to stop finding the semicolon for
handling the situation. When 'begin' or 'end' is found, the sql parsr
stops finding the semicolon and exits from declare block handling.

SQL: handle unexpected tokens in declare block

---

main/vstring.c

Fix #831.
The way to reproduce:
$ echo x > a.xml
$ valgrind --leak-check=full --track-origins=yes -v ./ctags ./a.xml
...
==28216== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
==28216==
==28216== 1 errors in context 1 of 1:
==28216== Conditional jump or move depends on uninitialised value(s)
==28216==    at 0x416C0F: vStringNCatS (vstring.c:142)
==28216==    by 0x416FE4: vStringNewFile (vstring.c:282)
==28216==    by 0x415EEE: xmlParseFILE (selectors.c:309)
==28216==    by 0x415EEE: selectByDTD (selectors.c:372)
==28216==    by 0x411239: pickLanguageBySelection (parse.c:760)
==28216==    by 0x411239: getSpecLanguageCommon (parse.c:860)
==28216==    by 0x4113E5: getPatternLanguage (parse.c:892)
==28216==    by 0x4113E5: getFileLanguageInternal (parse.c:936)
==28216== …

main: Don't access uninitialised buffer area in vStringNCatS

---

docs/index.rst

I forgot updating the top level toctree.

docs: move the section about C++/C to the chapter for parsers

---

Units/parser-php.r/php-use.d/expected.tags
Units/parser-php.r/php-use.d/input.php
parsers/php.c

Fixes #847.
As it's similar to a C typedef, report the source type in `typeRef[1]`.  `typeRef[0]` is filled sensibly when possible, but most generally not, because it's impossible to know whether it'll be a class, interface or namespace.  In that case, `unknown` is used instead.

PHP: parse `use` aliases

---

parsers/cxx/cxx_tag.c

C++, refactor: don't use integer literal for accessing an element of g_aCXXAccessStrings

---

parsers/cxx/cxx_token_chain.h

In file included from parsers/cxx/cxx.c:15:
parsers/cxx/cxx_token_chain.h:22: error: redefinition of typedef 'CXXTokenChain'
parsers/cxx/cxx_token.h:62: note: previous declaration of 'CXXTokenChain' was here

Fix build error GCC 4.4.7

---

Tmain/extra-field.d/run.sh

Close #866.
To make the test output independent from the environment where
the test is run, --quiet --options=NONE is added.

Tmain: add --quiet --options=NONE to the command line of run.sh of extra-field.d

---

main/main.c
parsers/cxx/cxx.c
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser.h

cxxParserCleanup was called directly from main function.
Ideally main part should not have any knowledge about parser.

C++, C: use per parser finalizer

---

docs/tips.rst
misc/review

Usage:
misc/review list
misc/review inspect
"list" shows all failed result under *.d and *.t marked cased.
*.b is not listed.
"inspect" can be used for inspecting the results of each Units
test cases. It is menu driven.

misc: add "review" script for reviewing Units results

---

parsers/php.c

Otherwise, it is not possible to disable generating this kind of tags
via the --php-kinds option.

PHP: Check if alias kind is enabled.

---

docs/autotools.rst

Missing dependency on Debian environments should be documented. Would fix #888.

Update autotools.rst to include pkg-config

---

main/entry.c

Old behavior: Assertion failure when a parser calls makeTagEntry with
a tagEntryInfo which associated kind is disabled.
That means a parser must verify "enabled/disabled" of the kind
associated to a tagEntryInfo before calling makeTagEntry.
However, people may forget writing such verification.
With this commit, makeTagEntry just skips the entry silently; it
doesn't emit the passed tagEntryInfo if its kind is disabled.
In some case checking "enabled/disabled" of the kind is still
meaningful for optimization purpose; if a kind is disabled, parser
doesn't have to take time to record the information categorized to the
group.

main: allow parsers calling makeTagEntry with a tag with disabled kind

---

Tmain/list-fields-with-prefix.d/stdout-expected.txt
Tmain/list-fields.d/stdout-expected.txt
Units/parser-cxx.r/functions.cpp.d/expected.tags
Units/parser-cxx.r/properties.cpp.d/args.ctags
Units/parser-cxx.r/properties.cpp.d/expected.tags
Units/parser-cxx.r/properties.cpp.d/input.cpp
Units/parser-cxx.r/template-specializations.d/args.ctags
Units/parser-cxx.r/template-specializations.d/expected.tags
Units/parser-cxx.r/template-specializations.d/input.cpp
Units/parser-cxx.r/variables-in-control-statements.d/input.cpp
main/entry.h
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_parser_lambda.c
parsers/cxx/cxx_parser_typedef.c
parsers/cxx/cxx_parser_variable.c
parsers/cxx/cxx_tag.c
parsers/cxx/cxx_tag.h
parsers/cxx/cxx_token.h
parsers/cxx/cxx_token_chain.c
parsers/cxx/cxx_token_chain.h

- Extract a set of properties for functions and variables: static, inline, extern, mutable, virtual, pure...
- Try to detect template specializations in various forms
- Fix a couple of corner cases in variable extraction (i.e. do NOT extract variables from things like if(a & b)).

CXX: Yet more work on the cxx parser

---

parsers/eiffel.c

This adds support for Eiffel's [across loop](https://www.eiffel.org/doc/eiffel/ET%3A%20Instructions#A%20closer%20look%20at%20the%20%27%27iteration%27%27%20form) instruction.

eiffel: Add support the across loop

---

misc/optlib2c
optlib/ctags-optlib.c
optlib/gdbinit.c
optlib/m4.c
optlib/man.c
parsers/asm.c
parsers/cobol.c
parsers/dosbatch.c
parsers/dts.c
parsers/eiffel.c
parsers/flex.c
parsers/fortran.c
parsers/go.c
parsers/html.c
parsers/jscript.c
parsers/json.c
parsers/matlab.c
parsers/objc.c
parsers/ocaml.c
parsers/php.c
parsers/rexx.c
parsers/slang.c
parsers/sql.c
parsers/tex.c
parsers/vhdl.c
parsers/yacc.c

This was originally submitted by @siegel in #903.
I rearranged the commits into one.

Fixed "duplicate const" compiler warnings when building on OS X using clang

---

Tmain/xcmd-dont-run-setgid-executable.d/run.sh
Tmain/xcmd-dont-run-setuid-executable.d/run.sh

As far as testing on msys2-64bit + autotools,
xcmd-dont-run-set[ug]id-executable were failed because there are not
set[gu]id on the platform. On such platform
xcmd-dont-run-set[ug]id-executable don't make sense.

tmain: Run xcmd-dont-run-set[ug]id-executable only on the platform where set[gu]id is available

---

Makefile.am
configure.ac
dsl/es-lang-c-stdc99.c
dsl/es-lang-c-stdc99.h
dsl/qualifier.c
main/mio.c
readtags.c
source.mak

open_memstream and fmemopen were used to parse a query string.
Quoted from man fmemopen(3):
fmemopen(), open_memstream(), open_wmemstream():
Since glibc 2.10:
_POSIX_C_SOURCE >= 200809L
Before glibc 2.10:
_GNU_SOURCE
It seems that open_memstream and fmemopen become parts of POSIX in
2008. MIO may be more portable than them.

readtags: use mio in query dsl implementation

---

main/parse.c
main/read.c
main/read.h

231e40e is critical.
The call sequence fopen `->` fread assumes the fopen doesn't return NULL.

Misc fix about mio

---

Units/parser-python.r/simple.py.d/args.ctags
Units/parser-python.r/simple.py.d/expected.tags

Units, python: don't refer pseudo tags when testing

---

main/entry.c
main/field.c
main/get.c
main/options.c
main/read.c
main/vstring.c
main/vstring.h

This new function simplifies writing the following idiom:
static vString *tmp;
if (tmp)
vStringClear (tmp);
else
tmp = vStringNew (tmp);

refactor: Introduce vStringNewOrClear utility function

---

misc/units

The parameter expansion ${V:n:m} for getting substring of
${V} is not available in /bin/dash.
May close #932.

units: don't use bash own parameter expansion

---

Units/parser-java.r/accented-latin1-identifiers.java.d/README
Units/parser-java.r/accented-latin1-identifiers.java.d/expected.tags
Units/parser-java.r/accented-latin1-identifiers.java.d/input.java
Units/parser-java.r/bug1447756.java.d/expected.tags
Units/parser-java.r/bug1447756.java.d/input.java
Units/parser-java.r/bug1691412.java.d/expected.tags
Units/parser-java.r/bug1691412.java.d/input.java
Units/parser-java.r/bug1777340.java.d/expected.tags
Units/parser-java.r/bug1777340.java.d/input.java
Units/parser-java.r/bug1777344.java.b/expected.tags
Units/parser-java.r/bug1777344.java.b/input.java
Units/parser-java.r/bug2049723.java.d/expected.tags
Units/parser-java.r/bug2049723.java.d/input.java
Units/parser-java.r/bug2117073.java.d/expected.tags
Units/parser-java.r/bug2117073.java.d/input.java
Units/parser-java.r/bug814263.java.d/expected.tags
Units/parser-java.r/bug814263.java.d/input.java
Units/parser-java.r/enum.java.d/expected.tags
Units/parser-java.r/enum.java.d/input.java
Units/parser-java.r/infinite_loop.java.d/expected.tags
Units/parser-java.r/infinite_loop.java.d/input.java
Units/parser-java.r/java_enum.java.d/expected.tags
Units/parser-java.r/java_enum.java.d/input.java

Moved all tests to parser-java.r
Marked bug1777344.java as a known failure with an updated expected.tags.
Renamed unicode8.java to accented-latin1-identifiers.java to better
reflect what is actually being tested and is functionally supported.
Updated enum.java with some constructors.
Fixes issue #940.

Units, Java: review tests under review-needed.r

---

parsers/vim.c

This is just a minimal fix but I believe it's in keeping with the general style of the file.

Units, Vim: fix vimball.vim valgrind test failure

---

Units/parser-c.r/bug950.c.d/args.ctags
Units/parser-c.r/bug950.c.d/expected.tags
Units/parser-c.r/bug950.c.d/input.c
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_parser_tokenizer.c

Extract multiple function prototypes in a single declaration.
Fixes bug #950.

Fix bug #950

---

parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_template.c
parsers/cxx/cxx_token_chain.c

```
template <typename T = void, bool B1 = true> // (1) fail if there are multiple params with default values
class A : public T
{
public:
typedef A<T, B1> this_type;
A(int i ) : m_i(i)
{
}
static A create(int i)
{
return this_type(i); // (2) fail here
}
static int g_i;
private:
int m_i;
};
template <typename T, bool B1>
int A<T, B1>::g_i; // (3) fail during parsing static member definition
```

Fixing parsing failures in following test case:

---

Units/parser-cxx.r/typedefs.cpp.d/expected.tags
Units/parser-cxx.r/typedefs.cpp.d/input.cpp
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_parser_typedef.c
parsers/cxx/cxx_token.c
parsers/cxx/cxx_token.h
parsers/cxx/cxx_token_chain.c
parsers/cxx/cxx_token_chain.h

Handle const/volatile prefixes in struct/union/enum (typedef) declarations.
Fix bug #971

Fix bug #971

---

main/vstring.c

The original code didn't consider zero-length strings.

main: verify the length of buffer when stripping newline at the end

---

parsers/cxx/cxx_parser_lambda.c
parsers/cxx/cxx_parser_tokenizer.c

Optimize lambda lookups. Reintroduce a limit on the size of the token chain.

Fix issue #980

---

README.md
appveyor.yml
win32/appveyor.bat

This PR creates zip packages of MSVC builds (x86 and x64) on AppVeyor.
The zip packages contains ctags.exe, readtags.exe, iconv.dll and documents.
The build matrix is changed for testing both MSVC x86 and x64 binaries using bash on msys2.
The tests of MinGW-w64 binary are skipped instead.
Here is an example:
https://ci.appveyor.com/project/k-takata/ctags/build/1.0.129
Zip packages:
https://ci.appveyor.com/api/buildjobs/5fsf7doq4mhrh2n2/artifacts/ctags-787f95a-x64.zip
https://ci.appveyor.com/api/buildjobs/l3t1el9hkpdpu0g4/artifacts/ctags-787f95a-x86.zip
(When a tag is built, the zip filename becomes `ctags-<tagname>-<arch>.zip`.)
Unfortunately this makes the tests about 10 minutes longer.

appveyor: Create MSVC packages

---

parsers/cxx/cxx_token.c

Valgrind reports memory errors for following cases:
$ make units VG=1 LANGUAGES=C
...
Summary (see CMDLINE.tmp to reproduce without test harness)
------------------------------------------------------------
#passed:                                52
#FIXED:                                 0
#FAILED (unexpected-exit-status):       0
#FAILED (unexpected-output):            0
#TIMED-OUT (10s)                        0
#skipped (features):                    0
#skipped (languages):                   0
#known-bugs:                            0
#valgrind-error:                        3
parser-c.r/bug1491666.c
parser-c.r/bug556646.c
parser-c.r/using-cxx-keyword-in-c-code
This is because a token type is specified when generating an anonymous
identifier.
Signed-off-by: Masatake YAMATO …

Cxx: fix anon identifier related memleak

---

parsers/cxx/cxx_scope.c

Building with setting  CXX_DEBUGGING_ENABLED 1, gcc reports an error when
compiling cxx_scope.c.

Cxx: fix debuggging build

---

Tmain/output-format-option.d/input.c
Tmain/output-format-option.d/run.sh
Tmain/output-format-option.d/stdout-expected.txt
main/entry.c
main/entry.h
main/error.c
main/error.h
main/main.c
main/main.h
main/options.c
main/options.h
main/output-ctags.c
main/output-etags.c
main/output-xref.c
main/output.h
main/parse.c
main/routines.c
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

This is for #994.
Interface for three hooks (plug able areas) are introduced.
* handler for printing a tag entry
```
typedef int (* writeEntryFunc) (MIO * mio, const tagEntryInfo *const tag, void *data);
typedef void * (* preWriteEntryFunc) (MIO * mio);
typedef void (* postWriteEntryFunc)  (MIO * mio, const char* filename, void *data);
extern void setTagWriter (writeEntryFunc func,
preWriteEntryFunc preFunc,
postWriteEntryFunc postFunc);
```
* function for main loop
```
typedef void (* mainLoopFunc) (cookedArgs *args, void *data);
extern void setMainLoop (mainLoopFunc func, void *data);
```
* handler for printing an error message
```
typedef boolean (* errorPrintFunc) (const errorSelection selection, const char *const format,
va_list ap, void *data);
extern void setErrorPrinter …
```

Make more areas plug able

---

Units/parser-vim.r/vim-let-in-function.d/expected.tags
Units/parser-vim.r/vim-let-in-function.d/input.vim
parsers/vim.c

Don't match local variables without a scope prefix named g* as global
variables.

Vim: fix matching of global variables in functions

---

main/parse.c

The invisible flag was introduced for implementing internal hidden test parser.
This PR includes 3 minor fixes about the invisible flag.

Revise the usage of invisible flag

---

configure.ac

As [requested](https://github.com/universal-ctags/ctags/pull/1005/files/3d771976b29b1ea06987237b17385ead746bf5a4..0664f8396cd64edc59ecfb9a75b9433b52c949cc#r69405469) by @masatake, put C compiler into C99 mode (if that's not the default).
There's probably some other stuff that could be removed from Autoconf, like checking for `stdlib.h` and `stdbool.h` and other stuff that is required by some C standard, but I didn't want to mess with it.

buildsys: enable c99 mode in C compiler

---

Units/iso8859-1-restructuredtext.d/expected.tags
Units/iso8859-1-restructuredtext.d/input.rst
Units/utf8-restructuredtext.d/expected.tags
Units/utf8-restructuredtext.d/input.rst
parsers/rst.c

…and add a note that heading width computation isn't actually accurate (according to Docutils' *rst2html* at least), but that's way too tricky to fix just now, and possibly ever (requires full Unicode character width understanding).

Improve reStructuredText coverage

---

Tmain/list-roles.d/run.sh
Tmain/list-roles.d/stdout-expected.txt
main/options.c

`:` is used. It is changed to `.` to be consistent with format notation
in which `.` is used as separator.

main: change the separator between parser name and kind name in --_list-roles

---

misc/review

@b4n, have you ever tried my misc/review script?
I hope this one helps your work.
It can be run with "misc/review inspect" from the at top src dir.
This tool helps us in following work flow:
1. edit c code
2. run "make units"
3. see DIFF.TMP 
4. move FILTERD.TMP to expected.tags
5. remove the both TMP files
6. go to 3 with another test case or exit.
The script focus on steps from 3 to 6.
Currently it supports only Units test cases and their result.
When trying, I recommend you to install colordiff and pygments but the script works well without them.
I will merge this as soon as possible.

Improve review tool

---

Units/parser-eiffel.r/inherit-rename.e.d/expected.tags
Units/parser-eiffel.r/inherit-rename.e.d/input.e
parsers/eiffel.c

Liberty Eiffel uses the "insert" keyword for non-conforming inheritance.

Eiffel: add support for Liberty Eiffel's "insert"

---

Tmain/list-fields-with-prefix.d/stdout-expected.txt
Tmain/list-fields.d/stdout-expected.txt
Tmain/xformat-common-fields.d/input.py
Tmain/xformat-common-fields.d/run.sh
Tmain/xformat-common-fields.d/stdout-expected.txt
main/field.c
main/fmt.c

This is fixing for following crash.
```
[yamato@x201]~/var/ctags-github% cat /tmp/foo.py 
class Foo:
def doIt():
pass
[yamato@x201]~/var/ctags-github% ./ctags -x --_xformat=%p /tmp/foo.py
zsh: segmentation fault (core dumped)  ./ctags -x --_xformat=%p /tmp/foo.py
```

Fix empty field handling in xformat

---

main/gcc-attr.h
main/general.h
main/mio.c
main/mio.h
main/mybool.h
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

Close #1035.
To make readtags.c stand-alone, we cannot include
general.h to make readtags command.
Though, in following chain, general.h is included
from readtags-cmd.c.
In file included from ./main/general.h:16:0,
from ./main/mio.h:24,
from ./dsl/es-lang-c-stdc99.h:30,
from ./dsl/qualifier.h:18,
from read/readtags-cmd.c:21:
The other *.c files being part of readtags command don't
include general.h. They are guarded with
'#ifndef QUALIFIER/#endif.
This becomes an issue in #1035.  configure script running on solaris
sets _FILE_OFFSET_BITS in config.h. config.h is included from
general.h. That means the value of _FILE_OFFSET_BITS is different
between *.c files including general.h and *.c files not including it.
readtags-cmd.c should not include general.h.
This commit introduces two sub …

readtags: don't use general.h

---

Tmain/list-kinds-full.d/stdout-expected.txt
main/lcpp.c
parsers/c.c
parsers/cxx/cxx_tag.c
parsers/dts.c

"header" kinds for OldC, Cxx, DTS, Vera were disabled by default.
However, a tag for the kinds is printed always because lcpp calls
makeTagsEnty without verifying the value of `enabled' field of the
kind.
This commit does two things:
(1) verifying the value of the `enabled' field of the "header" kind in lcpp, and
(2) enabling the "header" kinds by default.

lcpp, OldC, Cxx, DTS, Vera: enable header kind by default

---

Units/parser-eiffel.r/attributes.e.d/expected.tags
Units/parser-eiffel.r/attributes.e.d/input.e
Units/parser-eiffel.r/obsolete.e.d/input.e
parsers/eiffel.c

Erroneous "attribute" tags were being created and the rest of the file
then consumed in most cases.

Eiffel: add support for self-initializing attributes

---

main/entry.c

Even a kind is disabled, a tag with the kind could be printed in the case
the parser making the tag didn't verify the kind was enabled.
This commit adds the code for the verification to the main part side.
So even if a parser don't verify it, ctags doesn't print a tag of
disabled kind.
That means a parser doesn't have to verify the enablement.
However, verifying in a parser is still meaningful: it avoids
unnecessary performance overhead.

main: don't print a tag of disabled kind

---

main/entry.c

This commit is inspired by 102b735b2e50664888e5f1c61bfb6ec4052c9b27 and
88202471d37f29037744b3c358202a50b105d130.
Rule: when reference extra tag feature enabled with --extra=+r is
disabled, a tag attached with a role other than ROLE_INDEX_DEFINITION
should not be printed.
This change forces the rule in the main part level. A lazy parser developer
can ignore the rule in her/his parser; the main part drops the tag emission.
However, it will be better to follow the rule in the parser level because it
will gain the performance when ctags is called without --extra=+r.

main: Only generate reference tags when they are enabled

---

Tmain/warn-reusing-kind-letter.d/run.sh
Tmain/warn-reusing-kind-letter.d/stdout-expected.txt
main/lregex.c

u-ctags doesn't allow using a same letter for different log names.
e.g. (taken from #1062)
--langdef=pascal
--regex-pascal=/(uses|interface|implementation)[[:space:]]*/\1/s,Section/
--regex-pascal=/unit[[:space:]]+([a-zA-Z0-9_<>,][a-zA-Z0-9_<>, ]+)[;(]/\1/s,unit/
In both "Section" and "unit" `s' is used as a kind letter. u-ctags
threw later one, "unit", away silently.
As reported in #1062, user can reuse a letter accidentally.
With this commit ctags can make warnrnings when detecting such reuses.

main: warn when a kind letter is reused in a regex parser definition

---

main/lxpath.c
main/parse.h
parsers/plist.c

According to c11 6.7.9p9 http://www.iso-9899.info/n1570.html#6.7.9p9
[Initialization] Except where explicitly stated otherwise, for the
purposes of this subclause unnamed members of objects of structure and
union type do not | participate in initialization. Unnamed members of
structure objects have indeterminate value even after initialization.
This is also mentioned in #999.

Fix compilation error in CentOS 6.

---

Units/parser-python.r/dotted-variable-leftovers.d/expected.tags
Units/parser-python.r/dotted-variable-leftovers.d/input.py
parsers/python.c

python: Fix crash with dotted variables missing an explicit initializer

---

Tmain/list-fields-with-prefix.d/stdout-expected.txt
Tmain/list-fields.d/stdout-expected.txt
Tmain/list-language-fields.d/stdout-expected.txt
Tmain/wildcard-in-lang-of-fields-option.d/stdout-expected.txt
Tmain/xformat-and-parser-own-field.d/stdout-expected.txt
docs/news.rst
main/field.c

Now we can specify a field with not only field char but also field
name. "XFMTCHR" used in the column header of --list-fields output
is suitable name for the column. This commit changes it to "XFMT".

main: update column header of --list-fields output

---

main/options.c

@masatake As discussed here: https://github.com/universal-ctags/ctags/commit/9135e21d4833d104ddf50b7fbc0a77ab9d21e766#commitcomment-18866858

Fix typo in help string for --fields option

---

misc/units

Close #1100.
It seems that a subshell launched in units test
harness exits with zero even if it receives
INT signal. As the result though a user presses
^C from the terminal where "make units VG=1" runs,
the execution of test cases continues. (The execution of
the current test case is stopped but the next one is
started by the test harness.)
This change makes the subshell exits with non-zero when
the subshell receives INT signal.

units: trap INT signal in subshell

---

Units/parser-python.r/multiline-class-def.d/expected.tags
Units/parser-python.r/multiline-class-def.d/input.py
parsers/python.c

The token's indentation was set to the line indentation even inside
continuation lines, which leads to incorrect indentation recorded in
the token, breaking hierarchy if the incorrect indentation is on a
token used to create a scope and greater than the indentation of the
scope's body.
Fixes #1103.

python: Fix recorded indentation after a continuation line

---

parsers/c.c
parsers/eiffel.c
parsers/flex.c
parsers/fortran.c
parsers/go.c
parsers/jscript.c
parsers/php.c
parsers/python.c
parsers/rpmspec.c
parsers/sql.c
parsers/tex.c
parsers/vhdl.c

Clang warns when comparing an enumeration type with a value not found
in this enumeration:
```clang
warning: comparison of constant VALUE with expression of type 'TYPE' is
always false [-Wtautological-constant-out-of-range-compare]
```
If then the compiler then decides to optimize the test away because it
assumes the test is indeed always false, it can lead to pretty subtle
and nasty issues.
Closes #1115.

Don't compare foreign values to enumeration type

---

Tmain/xcmd-tag-relative-option.d/input.dog
Tmain/xcmd-tag-relative-option.d/run.sh
Tmain/xcmd-tag-relative-option.d/stdout-expected.txt
Tmain/xcmd-tag-relative-option.d/xcmd-dog
main/lxcmd.c

Close #1122.
--tag-relative option passed to ctags command was ignore when
xcmd is used because ctags prints the name of input files (%{input})
returned from the xcmd directly. (ctags doesn't pass --tag-relative option
to the xcmd).
This commit is for reflecting the specification of --tag-relative option
to tags files; instead of using the value returned from xcmd directly,
use the path arranged by ctags main side.

lxcmd: use path arranged by ctags main side as %{input}

---

Tmain/json-output-format.d/stdout-expected.txt
Tmain/xformat-common-fields.d/stdout-expected.txt
main/field.h

FIELD_BUILTIN_LAST must be specifies the last member of fieldType.
But it was not updated when FIELD_END was added to fieldType.

main: update the value for FIELD_BUILTIN_LAST

---

Units/parser-cxx.r/functions.cpp.d/expected.tags
Units/parser-cxx.r/functions.cpp.d/input.cpp
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_variable.c
parsers/cxx/cxx_token_chain.c
parsers/cxx/cxx_token_chain.h

Attempt to fix bug #1012 about functions returning function pointers.
It's not 100% perfect since the return type is not extracted. However it's still far better than emitting a wrong tag.

CXX: Fix bug 1012

---

parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_lambda.c
parsers/cxx/cxx_parser_typedef.c
parsers/cxx/cxx_parser_variable.c
parsers/cxx/cxx_tag.c
parsers/cxx/cxx_tag.h

Attempt to filter out types that contain too many macros or other oddities gathered by mistake.

CXX: Mitigate problem with preprocessor macros when emitting types.

---

Units/simple-jsx.d/expected.tags
Units/simple-jsx.d/input.jsx
parsers/jscript.c

Fixes #1086. I've tested it and as far as I can see, the jscript parser Just Works with .jsx files.

Support JSX files

---

Tmain/lregex-list-kinds-uniquely.d/run.sh
Tmain/lregex-list-kinds-uniquely.d/stdout-expected.txt
main/lregex.c

Close #1138.
When printing kinds in --list-kinds output, kinds hashtable of patternSet
should be traversed. However, mistakenly, patterns array was traversed.
As the result the same kind of a language is printed repeatedly.

main: Don't print the same kinds repeatedly in --list-kinds output

---

main/objpool.c
main/objpool.h
main/ptrarray.c
main/ptrarray.h
main/strlist.c
main/strlist.h
parsers/cxx/cxx_token.c
parsers/python.c
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

More details are in the individual commits.
To demonstrate the use of pool, I used it in the python parser for strings and tokens. The performance increase isn't much visible at this point because the bottlenecks are somewhere else (#1091, #1095) but once these are in, the pool increases the parser speed from 40MB/s to 46MB/s on my machine for django sources.

Add pointer array and pool data structures

---

Units/parser-cxx.r/variable-declarations.cpp.d/expected.tags
Units/parser-cxx.r/variable-declarations.cpp.d/input.cpp
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_lambda.c
parsers/cxx/cxx_parser_variable.c

Handle C++11
type var {};
type var[] { ... };
bracket initializers.
Fixes issue #1149 .
(PS. Commit messages should contain 'type var' instead of 'var type'... but I'm too lazy to redo them :D)

CXX: Improve variable parsing

---

parsers/fortran.c
parsers/go.c
parsers/jscript.c
parsers/php.c
parsers/python.c

I went through the more common languages, profiled them and checked if pool helps there - it seems to help for php and javascript. The numbers in the commit messages are after https://github.com/universal-ctags/ctags/pull/1091 is used.
On the way I noticed some more things that can be done - avoid common allocation of string in Fortran parser, apparently forgotten (or lost during rebase) use of isIdentifierChar() macro for the python parser.
Finally, the go patch doesn't bring any improvement - it just makes copyToken() work like in other parsers and makes it easier to adopt object pool if ever needed in the future.

Some more uses of pool and other optimizations

---

autogen.sh

For recuding dependencies, use shell-builtin instead of
external command.

buildsys: use type instead of which to detect perl command

---

main/vstring.c
main/vstring.h

Found with make CC=/rest/inst/gcc-6.1.0/usr/local/bin/gcc CFLAGS="-Wall -pedantic".

Convert vStringPut macro to inline function (Was: Fix coding issues)

---

configure.ac

It seems that older libxml2 doesn't have xmlPreviousElementSibling which
is used in PlistXML parser. libxml2 shipped as part of RHEL5 is such old
library. (See #1165).
To avoid build error, configure should check the existence of xmlPreviousElementSibling
in libxml2.

buildsys: check the existence of xmlPreviousElementSibling in libxml2

---

Tmain/list-roles.d/stdout-expected.txt
Units/parser-cpreprocessor.r/simple-cpreprocessor.d/args.ctags
Units/parser-cpreprocessor.r/simple-cpreprocessor.d/expected.tags
Units/parser-cpreprocessor.r/simple-cpreprocessor.d/input.c
Units/parser-dts.r/dts-simple.d/args.ctags
Units/parser-dts.r/dts-simple.d/expected.tags
main/lcpp.c
main/parsers.h
parsers/dts.c
parsers/protobuf.c

@pragmaware, how do you think about this?
You wan to put more code to lcpp.c.
Before doing much, I think it is better to take efforts for making lcpp.c more extendable.
More of my work about main part if for parser. lcpp.c is not a parser. It is semi-meta-parser.
This commit converts lcpp.c to a parser and meta parser.
That means lcpp.c now gets its own parserDefinition. So we can add more things.
For exapmle per parser options name space `--opt-<LANG>=...` can be attached to lcpp.c.

Standalone cpreprocessor parser

---

.dir-locals.el
docs/contributions.rst

Though .editorconfig was introduced, it is not enough for GNU emacs users to make
the coding style consistent with existing code of ctags.
The default style of cc-mode of GNU emacs is "gnu". The "gnu" style adds
extra indentation in block opening:
________if (...)
__________{
The style is not consistent with the existing code.
This commit introduces .dir-locals.el file which forces the style
to "linux". With "linux" style the block opening is handled as follows:
________if (...)
________{
The difficulties is that the basic indent size of "linux" is 8.
It is different from .editorconfig.
So in the updated document, I wrote the way to apply .editorconfig
configuration after installing "linux" style.

docs, style: add dir-locals file for setting the style to linux in GNU emacs

---

Units/parser-cxx.r/cxx11-override.d/expected.tags
Units/parser-cxx.r/cxx11-override.d/input.cpp
parsers/cxx/cxx_parser_block.c

Implement @masatake 's fix for the 'const override {' and similar sequences.

CXX: Properly handle the 'const override {' sequence

---

Units/parser-yacc.r/not-union.d/README
Units/parser-yacc.r/not-union.d/args.ctags
Units/parser-yacc.r/not-union.d/expected.tags
Units/parser-yacc.r/not-union.d/input.y
main/parse.c
parsers/yacc.c

Just finding '}' is used as the end marker of %union.
However '}, can be appeared in variety cases; at the end of function definition and
at the end of C struct definition. More strict condition is needed.
This commit handles '}' the end marker of %union only after finding %union.

Yacc: fix leave-%union handling

---

main/lxcmd.c
main/read.c
main/read.h

As both of them now use mio_gets() we can factor-out the common line
reading code into a separate function (readLine()) and use it for both
functions. The line-reading code from iFileGetLine() was used as it's
a bit simpler and requires less MIO operations.
The first patch was necessary since the line-reading function calls mio_eof() and as the positions are read in makePatternStringCommon(), it can happen that a pattern string is read for a tag at the end of file first and this sets the EOF flag which causes that subsequent calls of readLineRaw() will to a wrong thing as they think EOF has been reached.

Use the same line-reading code both for iFileGetLine() and readLineRaw()

---

Tmain/list-params.d/stdout-expected.txt
Units/parser-cxx.r/complex-macros.d/args.ctags
Units/parser-cxx.r/complex-macros.d/expected.tags
Units/parser-cxx.r/complex-macros.d/input.cpp
Units/parser-cxx.r/foreach.d/args.ctags
Units/parser-cxx.r/foreach.d/expected.tags
Units/parser-cxx.r/foreach.d/input.cpp
docs/news.rst
main/options.c
main/options.h
parsers/c.c
parsers/cpreprocessor.c
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_tokenizer.c
parsers/cxx/cxx_token_chain.c
parsers/cxx/cxx_token_chain.h
parsers/meta-cpreprocessor.h

rebased version of #1161 
Instead of extending -I, we would like to introduce -D option.
However, the specification of arguments for -D is not well defined yet. See my comment in #1161 about `,`.
After defining the spec of -D, we have to do
* update args.ctags of test cases
* update news.rst at least (write about debugging level, too)

CXX Better macros handling (take 2)

---

parsers/cxx/cxx_parser.c

A test case, cxx11enum.cpp.d, reports memory leaks.

Cxx: free the value returned from cxxTagSetProperties

---

parsers/cxx/cxx_parser_function.c

Added trivial check for null pointer to avoid later corrupted memory access.

CXX: Fix a bad pointer access

---

main/options.c

Close #1206.
-d option didn't work well because I didn't consider that the
option takes an argument.

main: mark -d as a compound option

---

Units/parser-javascript.r/generators.d/expected.tags
Units/parser-javascript.r/generators.d/input.js
parsers/jscript.c

Add support for them `function*` generator syntax, and report such generators as a separate kind.
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*)

JavaScript: Add support for generators

---

Tmain/json-output-format.d/input.go
Tmain/json-output-format.d/stdout-expected.txt
main/entry.c
main/field.c
main/writer-ctags.c
main/writer-json.c
main/writer.h

The responsibility for rendering pattern field was not clear.
json and ctags writers did their own way.
This commit moves the rendering code to field.c and make the
writers use functions exported from field.c.

main: revise the code for rendering pattern field

---

Units/parser-c.r/directives-2.c.d/args.ctags
Units/parser-c.r/directives-2.c.d/expected.tags
Units/parser-c.r/directives-2.c.d/input.c
parsers/cpreprocessor.c
parsers/cxx/cxx_parser_block.c
parsers/meta-cpreprocessor.h

Switch to single preprocessor conditional branch mode when nested {} block level at entry and exit of the first conditional is different. Fixes bug #1188 .

CPP/CXX: More preprocessor work

---

Units/regex-multiline-flag.d/args.ctags
Units/regex-multiline-flag.d/expected.tags
Units/regex-multiline-flag.d/input.java
docs/optlib.rst
main/lregex.c
main/parse.c
main/parse.h
main/read.c
main/read.h

Close #219
A pattern marked with `_multiline` is applied to whole file contents, not line by line.
Next example is based on an issue #219 posted by @andreicristianpetcu::
$ cat input.java
@Subscribe
public void catchEvent(SomeEvent e)
{
return;
}
@Subscribe
public void
recover(Exception e)
{
return;
}
$ cat spring.ctags
--langdef=javaspring
--langmap=javaspring:.java
--regex-javaspring=/@Subscribe([[:space:]])*([a-z ]+)[[:space:]]*([a-zA-Z]*)\(([a-zA-Z]*)/\3-\4/s,subscription/{_multiline=3}
--excmd=mixed
--fields=+ln
$ ./ctags -o - --options=./spring.ctags input.java
Event-SomeEvent	input.java	/^public void catchEvent(SomeEvent e)$/;"	s	line:2	language:javaspring
recover-Exception	input.java	/^    recover(Exception e)$/;"	s	line:10	language:javaspring
* `{_multiline=N}`
This tells the …

main: support multiline regex parser

---

Tmain/case-insensitive-pattern.d/run.sh
Tmain/case-insensitive-pattern.d/stdout-expected.txt
Tmain/utils.sh
main/options.c
main/strlist.c

ctags uses file name (glob) patterns and extensions to choose a
proper parser for given input.
extensions work well in case insenstive environment.
However, patterns don't. This commit fixes this.
GNU implementation provides FNM_CASEFOLD.
I didn't use it to keep portability.

main: implement case insenstive glob matching

---

main/lxpath.h
main/parse.c
main/parse.h
main/selectors.c
main/selectors.h
main/types.h
parsers/ant.c
parsers/dbusintrospect.c
parsers/maven2.c
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

The logic for selecting a xpath based parser was hard-coded in selectByDTD.
This commit set tries converting the logic to more declarative data structures defined in each xpath based parser.

Revise lxpath

---

Tmain/omit-long-patterns-etags.d/input.sh
Tmain/omit-long-patterns-etags.d/run.sh
Tmain/omit-long-patterns-etags.d/stdout-expected.txt
main/writer-etags.c

Close #1247.
Like javascript and css optimized by tools, there are source files that are made
up of one very long line. Such input files can make TAGS file much larger.
As we did in tags output, this commit truncates hints in TAGS output if they are
longer than the value specified with --pattern-length-limit option.
TODO: json output, xref output.

etags-writer: truncate too long hints (step 1)

---

main/lregex.c

lregex: fix uninitialized memory access

---

Units/parser-sh.r/function-identifiers-no-function-keyword-bash.d/expected.tags
Units/parser-sh.r/function-identifiers-no-function-keyword-bash.d/input.bash
parsers/sh.c

Close #1261.
bash accepts many non isalnum characters as function identifiers even when
not using the `function` keyword.
If `function` keyword is used, ctags has a chance to switch check_char
var to a function specialized to bash. For the case `function` keyword
is not used, this commit change the default value of check_char var to
isBashFunctionChar.

sh: use isBashFunctionChar as default check_char func

---

parsers/cxx/cxx.c

In case-sensitive platform/environment (in other word #ifndef CASE_INSENSITIVE_FILENAMES),
using C (upper case) as extension for C source code is not popular.
Like C, using CUDA (upper case) as extension for CUDA source code is not popular.
What is popular is using C as extension for C++ source code.

C,CUDA: remove unnecessary CASE_INSENSITIVE_FILENAMES block

---

main/vstring.c

Don't move the whole string several times if there are more than one
byte to strip; instead count the bytes to strip and move accordingly in
one go.
Also, use memmove() that is highly likely to be more efficient but on
very tiny buffers.
---
**DISCLAIMER**: I did **not** do performance tests on this.  I changed it because I saw the implementation and it hurt my eyes.  I'm pretty confident it'll be a lot faster when stripping more than one byte (because the move will happen only once), or when the string is longer than *[insert some small number here]* (because `memmove()` is a *lot* faster at actually moving the bytes in any current architecture, so the question is only whether calling cost outweights the benefits).

vString: Implement vStringStripLeading() in a more efficient way

---

Tmain/interactive-mode.d/run.sh
Tmain/output-input-field-with-no-escape.d/run.sh

Using `--fields=+ln` in `~/.ctags` caused these tests to fail for me.

tests: use --options=NONE with more tests

---

configure.ac

This enforces explicit feature usage regardless of the libraries
available on the build system. This avoids automagic dependencies which
can cause issues for source-based distros [1].
[1]: https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies

buildsys: add configure options to control xml, json, and yaml support

---

main/entry.c
mk_mingw.mak

(Ideally this should be c99.)
Inspired by https://github.com/universal-ctags/ctags/pull/1281#discussion_r97571242
See what happens.

main, buildsys: Specify -std=gnu99 in building on mingw

---

main/parse.c
main/read.c
main/routines.c

A memory object allocated with xMalloc, xRealloc, or xCalloc should be
free'ed with eFree.

main: use eFree instead of free

---

main/parse.c
main/parse.h
main/promise.c
main/promise.h
main/read.c
main/read.h
parsers/html.c

mio_seed used behind promise API expects long values.

main: use long type to represent byte offsets of area in promise API

---

main/entry.c
main/entry.h
main/writer-etags.c
main/writer.h
parsers/cpreprocessor.c
parsers/fortran.c

For handing too long source input lines, Universal ctags
has been extend the way to trancate them. As the result
the field name, truncateLine in tagEntryInfo struct is
too ambiguous to know what happens if it is true.
This commit rename it to truncateLineAfterTag to represnet
the intent of the field.

main, refactor: rename truncateLine field of tagEntryInfo

---

main/lregex.c

This was missed when _multiline flag was introduced.

main: add _multiline to the output of --list-regex-flags option

---

parsers/cxx/cxx_keyword.c
parsers/cxx/cxx_keyword.h
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_parser_namespace.c
parsers/cxx/cxx_parser_tokenizer.c
parsers/cxx/cxx_parser_typedef.c
parsers/cxx/cxx_parser_using.c

Try to handle C++ keywords as identifiers when they are found in unexpected places and C++ language isn't confirmed yet (as happens in headers).
Fixes #1299 .

CXX: Improve handling of C++ keywords when C++ language isn't confirmed

---

Units/simple-rpmspec.d/expected.tags
Units/simple-rpmspec.d/input.spec
parsers/rpmspec.c

This commit makes ctags capture `PACKAGE` in `%package -n PACKAGENAME`.
`-n` option in the line prevented ctags capturing PACKAGE.

Rpmspec  n option in package directive

---

Units/parser-cxx.r/functions.cpp.d/expected.tags
Units/parser-cxx.r/functions.cpp.d/input.cpp
parsers/cxx/cxx_parser_function.c

Handle function signatures with pointers declared as `type ((something)(something))`
Fixes #1309

CXX: Handle yet one more special case of function pointers

---

Units/parser-c.r/c-struct-var-with-initializer.d/args.ctags
Units/parser-c.r/c-struct-var-with-initializer.d/expected.tags
Units/parser-c.r/c-struct-var-with-initializer.d/input.c
parsers/cxx/cxx_parser.c

Close #1311.
Though s in
struct {
int h;
} s ;
was tagged well,
s in
struct {
int h;
} s = { 1 };
was not.
This commit makes ctags recognize `=' (CXXTokenTypeAssignment)
as the end marker of struct variable; an expression after the
marker is just skipped.

Cxx: handle struct var with initializer

---

Units/parser-cxx.r/k-and-r.d/args.ctags
Units/parser-cxx.r/k-and-r.d/expected.tags
Units/parser-cxx.r/k-and-r.d/input.c
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_internal.h

Handle K&R-style functions when they have enum/struct/union variables in the signature.
Also refactor a little bit to simplify handling of K&R functions in general.
Based on masatake's patch "fix handling struct keyword in k&r parameter decls".

CXX: K&R-style functions with enum/struct/union variables in the signature

---

README.md

Without this, the man page isn't built automatically and it is unclear why unless you happen to see this.

Clarifying where rst2man comes from

---

win32/ctags_vs2013.vcxproj

Fixes loading the solution in VS 2015 for me.

Remove redundant gcc-attr.h vcxproj entry

---

win32/ctags_vs2013.vcxproj.filters

Do the same as 248b3fecb9d2cbf898af194a6011377bb2808362.

Win32: Remove redundant gcc-attr.h vcxproj.filters entry

---

Units/parser-cxx.r/typedefs.cpp.d/expected.tags
Units/parser-cxx.r/typedefs.cpp.d/input.cpp
parsers/cxx/cxx_parser.c

CXX: Handle 'typedef struct X (Y)()' and similar forms

---

Tmain/list-subparsers-all.d/stdout-expected.txt
Units/parser-m4.r/m4-autoconf-and-optlib.d/README
Units/parser-m4.r/m4-autoconf-and-optlib.d/args.ctags
Units/parser-m4.r/m4-autoconf-and-optlib.d/expected.tags
Units/parser-m4.r/m4-autoconf-and-optlib.d/input.m4
docs/running-multi-parsers.rst
main/dependency.c
main/parse.c
main/subparser.h
parsers/iniconf.c
parsers/m4.c
parsers/make.c
parsers/yaml.c

A base parser expects subparers implement methods which the base parser
declared in *.h file. However, a subparer written in optlib isn't
satisfied the expectation. This causes a segment violation.
This commit provides the way to skip optlib based subparser in
foreachSubparser to avoid the segment violation.

Extend foreach subparser macro

---

parsers/cxx/cxx_parser_function.c

With enabling tracing feature, following input didn't
satisfy an assertion:
void x (int i);

Cxx: remove `pParamInfo' from CXX_DEBUG_ASSERT in cxxParserLookForFunctionSignatureCheckParenthesisAndIdentifier()

---

Units/xformat-option.r/format-NlKkFnP.d/filter

Partially close #1348.
Input file names can include ../ with following case:
$ mkdir objdir
$ cd objdir
$ ../configure --prefix=$HOME/apps/ctags --program-prefix=u_
$ make -j4
$ make check
The ../ causes a trouble in input file name comparison. 

unit: handle ../ included in input file names

---

Tmain/interactive-resource-management.d/input.c
Tmain/interactive-resource-management.d/run.sh
Tmain/interactive-resource-management.d/stdout-expected.txt
Tmain/output-file-resource-management.d/input.c
Tmain/output-file-resource-management.d/run.sh
Tmain/output-file-resource-management.d/stdout-expected.txt
Tmain/utils.sh
main/entry.c

Close #1350.
In both -o - and --sort=no is given, ctags should be able to
run without a temorary file.

main: don't use a temporary file if possible

---

Units/parser-c.r/cxx-keywords-simple.d/args.ctags
Units/parser-c.r/cxx-keywords-simple.d/expected.tags
Units/parser-c.r/cxx-keywords-simple.d/input.h
Units/parser-c.r/cxx-scope-keywords.d/args.ctags
Units/parser-c.r/cxx-scope-keywords.d/expected.tags
Units/parser-c.r/cxx-scope-keywords.d/input.h
Units/parser-cxx.r/cxx-keywords-as-c-identifiers.b/args.ctags
misc/units
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_tokenizer.c

C: deal with C++ scope keywowrds as identifiers
In *.h file if [: \t] don't follows after protect|private|public,
deal with the token as an identifier, not a keywowrd.
TODO: The language for each tag entry is still C++. It should be C.

C improve c++ scope keywords handling in c

---

Units/parser-cxx.r/complex-macros.d/args.ctags
Units/parser-cxx.r/complex-macros.d/expected.tags
Units/parser-cxx.r/complex-macros.d/input.cpp
parsers/cpreprocessor.c
parsers/cxx/cxx_parser_tokenizer.c

Fix a bug in macro handling.
Support unbalanced brackets as macro parameters.
Add related unit test.
Fixes #1357

CXX: Improve macro handling

---

parsers/html.c

See the comments in the individual patches for more info. Each of the patches applied separately fixes the crash reported in #1361 for me.

Fix HTML parser crash caused by too many open tags

---

Tmain/case-insensitive-pattern.d/run.sh
Tmain/kinddef.d/run.sh
Tmain/lxcmd-reject-specifying-in-dot-ctags.d/README
Tmain/tag-relative-option-in-etags.d/run.sh
Tmain/tag-relative-option.d/run.sh
Tmain/tmain-skip-example.d/run.sh
Tmain/utils.sh

~/.ctags affected the result of Tmain.
These commits make test cases not read ~/.ctags.

Tmain: ignore ~/.ctags when running the test cases

---

README.md
mk_mvc.mak
win32/appveyor.bat

Add `PDB=yes` flag to mk_mvc.mk.
If `PDB=yes` is specified, `ctags.pdb` and `readtags.pdb` will be created, and they will be packed into a zip file named `ctags-VER-ARCH.pdb.zip`.
See: #1361

Create *.pdb on AppVeyor

---

.editorconfig

Files under the win32 directory should have CRLF EOL.

Change EditorConfig setting for win32 files

---

parsers/make.c

"makefile" is the name of mode for editing Makefile in emacs.

Make: add "makefile" as an alias

---

Units/parser-javascript.r/js-default-export.d/expected.tags
Units/parser-javascript.r/js-default-export.d/input.js
Units/parser-javascript.r/js-export.d/expected.tags
Units/parser-javascript.r/js-export.d/input.js
parsers/jscript.c

This is just a cherry pick of the relevant changes from @b4n's [branch](https://github.com/b4n/fishman-ctags/commits/jscript/es7) which hasn't seen much action lately. It's based off @masatake's suggestion on the issue thread.
http://www.ecma-international.org/ecma-262/7.0/#sec-exports
Closes #1068.

Javascript tags for ES6 exports

---

misc/gencxxtypedumper.sh
parsers/cxx/cxx_debug_type.c
parsers/cxx/cxx_parser.c

The original version was not consider the data type is
implemented as bit fields.

Cxx: decode type bit fields in cxxDebugTypeDecode

---

misc/gencxxtypedumper.sh
parsers/cxx/cxx_debug_type.c

I introduced a bug when allowing cxxDebugTypeDecode to handle
type bits. It deals with EOF in a wrong way.
This commit fixes it.

Cxx: fix a bug about handling EOF in debug-type decoder

---

Units/parser-itcl.r/fq-with-namespace.b/args.ctags
Units/parser-itcl.r/fq-with-namespace.b/expected.tags
Units/parser-itcl.r/fq-with-namespace.b/input.tcl
Units/parser-itcl.r/simple-itcl.d/args.ctags
Units/parser-itcl.r/simple-itcl.d/expected.tags
Units/parser-itcl.r/simple-itcl.d/input.tcl
Units/parser-tcl.r/simple.tcl.d/expected.tags
Units/parser-tcl.r/simple.tcl.d/input.tcl
docs/news.rst
main/entry.c
parsers/itcl.c
parsers/tcl.c
parsers/tcl.h

ITcl assumed a method is defiend at the top level.
It seems that this is wrong. A method is defined in a class.
With this commit ITcl parser captures methods defined in a class;
"method" used in the top level is ignored.
In addition variables and commons defined in a class are captured.
TODO: A separator used between a ITcl class and Tcl namespace should
be :: but . is used. This is a bug.

ITcl: improve handling method 

---

main/entry.c
main/entry.h
main/field.c
main/htable.c
main/htable.h
main/lxcmd.c
main/parse.c
main/read.c
main/read.h

In the last commit I introduced following code
```
pushLanguage(getNamedLanguage(x.language, 0));
```
for flushing the cork queue in which tags generated by a subparser are stored.
pushLanguage expects a language id. However, the tag holds only the name of language.
Therefore getNamedLanguage is needed for converting. getNamedLanguage is rather slow because it uses liner search internally.
With this commit a tag entry holds language id instead of language name.
So ctags doesn't have to call getNamedLanguage when flushing the queue.
However, xcmd interface has to the function instead.
To avoid the liner search in xcmd, introduce a hashtable as a backend for getNamedLanguage.

Use langid in tagentryinfo

---

mk_mingw.mak

optlib and parsers/cxx were not cleaned by mk_mingw.mak.

buildsys: Fix cleaning optlib and parsers/cxx

---

mk_mvc.mak
win32/gen-repoinfo.bat

Do the same thing as `misc/gen-repoinfo`, when `mk_mvc.mak` is used.

win32: Generate repoinfo.h on VC2013

---

Units/parser-autoconf.r/no-string-literal.d/expected.tags
Units/parser-autoconf.r/no-string-literal.d/input.ac
parsers/autoconf.c
parsers/m4.c

The original code makes m4 base parser skip shell-oriented string
literals like `...`, '...', and "...".
However, it casues failure of capturing HAVE_CONFDB in following configure.ac:
AC_DEFINE_UNQUOTED(UUID_FILE,"$localstatedir/lib/heartbeat/hb_uuid", I'm a bad boy.)
AC_DEFINE_UNQUOTED(HAVE_CONFDB, $HAVE_confdb, Have the old herarchial Corosync config API)
Lines after the single quote in "I'm a bod boy" are ignored.
It seems that handling such characters something speciall is not a good idea.
1 parent 823ed35 commit aba1da58c0ed65b54ba51b8ee69c1f975a9d130c

Autoconf:  do nothing special about shell-oriented string literals

---

main/entry.c
main/options.c
main/parse.c
main/routines.c
main/routines.h
mk_mvc.mak
parsers/cpreprocessor.c
parsers/cxx/cxx_parser_tokenizer.c

VC shows the following warnings:
```
main\entry.c(860) : warning C4550: expression evaluates to a function which is missing an argument list
main\entry.c(861) : warning C4550: expression evaluates to a function which is missing an argument list
main\options.c(2522) : warning C4114: same type qualifier used more than once
main\parse.c(918) : warning C4090: 'initializing' : different 'const' qualifiers
main\routines.c(383) : warning C4028: formal parameter 1 different from declaration
main\routines.c(397) : warning C4028: formal parameter 1 different from declaration
main\routines.c(559) : warning C4090: 'return' : different 'const' qualifiers
parsers\cpreprocessor.c(1260) : warning C4028: formal parameter 1 different from declaration
parsers\cxx\cxx_parser_tokenizer.c(1064) : warning …
```

Fix VC warnings

---

parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_parser_namespace.c
parsers/cxx/cxx_parser_template.c
parsers/cxx/cxx_parser_tokenizer.c
parsers/cxx/cxx_parser_typedef.c
parsers/cxx/cxx_parser_using.c

Cxx: reduce blocks when parsing values for array/union initialization

---

configure.ac

Currently iconv is disabled by default, and needs to be explicitly enabled if someone wants to use it.
This is different from other libraries like jansson, libxml2 and libyaml.
I think there are no needs to disable iconv by default.

buildsys: Enable iconv by default

---

appveyor.yml
win32/appveyor.bat

Create html docs on AppVeyor.
I put the html docs in `docs/html/`, but I'm not sure this is the right directory structure.
```
.
├── COPYING
├── COPYING.MinGW-w64-runtime.txt
├── ctags.exe
├── docs
│   ├── *.rst
│   └── html
│       └── *.html
├── iconv.dll
├── README.md
└── readtags.exe
```

appveyor: Create html docs

---

Units/parser-perl.r/simple.pl.d/args.ctags
Units/parser-perl.r/simple.pl.d/expected.tags
parsers/perl.c

In 5022e63a I mistakenly deleted the code making
full qualified tags.

Perl: fix a bug about making full qualified tags

---

main/sort.c

internalSortTags() sorted lines including the last '\n'. This caused
unexpected results.
This is based on a fix written by Masatake YAMATO.
https://github.com/universal-ctags/ctags/issues/1411#issuecomment-304450502

main: Replace last '\n' with '\0' before sorting (Fix #1411)

---

README.md
appveyor.yml
docs/windows.rst
win32/appveyor.bat
win32/license/Copyright.libxml2
win32/license/LICENSE.janssen
win32/license/LICENSE.libyaml

* Use MSYS2 to create zip packages and stop using VC for it.
* Enable following libraries with MSYS2:
jansson, libxml2, libyaml.
* Enable static link with MSYS2.

appveyor: Use MSYS2 for packaging

---

main/parse.c
main/parse.h

On armv7l, char type is actually unsigned. So doing a switch on an unsigned value kindIndex with a negative case value actually does not work. My suggestion is to fix the type of kindIndex specifically to signed char. All unit tests pass if I make that change as well.
make units is passed.
Created an issue: https://github.com/universal-ctags/ctags/issues/1423
I am contributing the code under the terms of the General Public License version 2 or any later version.

Incorrect handling of types causes a segfault on arm

---

configure.ac

mingw-w64-{i686,x86_64}-python3-docutils packages in MSYS2 provide
rst2man3 and rst2man3.py commands instead of rst2man.  Detect them.

buildsys: Detect rst2man3

---

Makefile.am
configure.ac
makefiles/testing.mak
mk_mingw.mak
mk_mvc.mak
source.mak

We use Automake, so we can use `make dist` to create a tarball and `make distcheck` to create and check it.
However, `make distcheck` fails because of some reasons.
* Source files are not properly listed. We also need to care about Windows specific source files.
* Creating a tarball fails because of very long filenames.
See: https://www.gnu.org/software/automake/manual/html_node/List-of-Automake-options.html
`tar-v7` supports file names with up to only 99 characters.
However we have some files which names are longer than that.
So we should use `tar-ustar` or `tar-pax`.
* `make distclean` leaves some files in build directory. So the following error will be shown:
```
ERROR: files left in build directory after distclean:
./Units/conflib-recursive.d/BUNDLES …
```

buildsys: Fix `make distclean`

---

win32/appveyor.bat

Include `man/ctags.1.rst` in zip package. See: https://github.com/universal-ctags/ctags/pull/1426#issuecomment-305165075

appveyor: Include man page in zip package

---

man/README
man/ctags.1.rst.in

Remove `:' after "or". A newline between "or" and a quoted
block is needed; without it rst processor recognizes or as
a title of section.
Use `.. code-block::' instead of `::'. However, LANGUAGE
after `.. code-block::' cannot be specified; this may be
a limitation of rst2man.

docs(man): fix style of block quotations

---

win32/appveyor.bat

ctags-incompatibilities.7 and ctags-optlib.7 are newly added.
Include them in zip package.

appveyor: Include new man pages

---

man/Makefile
man/README
man/ctags.1.rst.in

Restructured text can recognize options list in an
input file. However, the notation for the options list
is not enough flexible for describing all options of
ctags. As the result, the HTML output converted from
crags.1.rst by rst2html becomes ugly.
So in this chage, use definition list with
``--two-single-quotes`` to describe options
instead of using options list.
Partially close #1435.

docs(man): use two single quotes for describing options

---

win32/appveyor.bat

* Exit immediately when nmake fails.
* Remove an unnecessary line.
* Update MSYS2 packages before build, if %compiler% is "msys2".
Now MSYS2 is used for building static-linked Windows binaries, not only for testing.
Libraries should be kept up to date to avoid security risks.
* Include `man/*.html` instead of `man/*.rst`. (See #1440)

AppVeyor fixes

---

parsers/yaml.c

On Windows, the following warning is shown:
https://ci.appveyor.com/project/k-takata/ctags/build/1.0.176/job/i3gcx6qr2wieq3tl#L500
> ```
> parsers/yaml.c:148:37: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'size_t {aka long long unsigned int}' [-Wformat=]
>   verbose("yaml token:%s<%d>@Line:%lu\n", tokenTypeName[token.type], token.type,
>                                     ^
> ```
Include `inttypes.h` and use `PRIuPTR` to fix the warning.
Note that `long` is 32-bit and `size_t` is 64-bit on 64-bit Windows.

parser: Use inttypes.h to fix printf warning

---

README.md
win32/appveyor.bat

* It is not recommended to update only specified packages. (ArchWiki says so.)
Use `pacman -Suy` as usual.
* Use `checkupdates` to check if there are any updates.
* Remove unused toolchain before updating so that reduce the time for updating.
(Unfortunately, it takes about 3 ~ 5 minutes even with this workaround.)
* Use default setting when updating Cygwin packages.
* Stop building msys2 binary before testing MSVC binary. This reduces about 30 sec.
* Use 64-bit Cygwin instead of 32-bit version. 64-bit version is about 1 minute faster.

appveyor: Additional fixes for #1445

---

dictfiles/english.list
misc/spelling.ctags

This helper script should be add when merging
self-spell-checking branch.

cspell: add a missing misc/spelling.ctags

---

configure.ac
win32/gen-repoinfo.bat

If this repository is added as a git-submodule of another repository,
`.git` becomes a normal file. Detect it properly.

Detect .git on git-submodule

---

README.md

Win32 daily builds are now available at the ctags-win32 project.
Closes #1455.

readme: Add a link to the ctags-win32 project

---

main/seccomp.c

free() may call munmap under the hood.

whitelist munmap for seccomp.

---

Units/parser-ocaml.r/ocaml_two_files.d/args.ctags
Units/parser-ocaml.r/ocaml_two_files.d/expected.tags
Units/parser-ocaml.r/ocaml_two_files.d/input-0.ml
Units/parser-ocaml.r/ocaml_two_files.d/input.ml
main/entry.c
main/writer-json.c
parsers/ocaml.c

Close #1498 in the last commit.
During inspecting the bug reported in #1498, valgrind some memory related bugs.
I fixed them, too.
As wrote in 5b447b1, this one has no test case because units harness has no ability to handle more than one source file.

Fix 1498 (fix memory leaks in --interactive and ocaml's variable initialization bug) 

---

autogen.sh

To reproduce the problem I was having create the following makefile:
```make
.PHONY: ctags
ctags:
./autogen.sh
```
Then call it, you should see output as following:
```
./autogen.sh
autoreconf is /usr/bin/autoreconf
pkg-config is /usr/bin/pkg-config
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:262: installing './compile'
configure.ac:23: installing './config.guess'
configure.ac:23: installing './config.sub'
configure.ac:11: installing './install-sh'
configure.ac:11: …
```

Allows `./autogen.sh to` be called from another Makefile

---

docs/news.rst
man/Makefile
man/README
man/ctags-incompatibilities.7.rst.in
man/ctags.1.rst.in

I wrote my understanding about "tag", "kind", "field", "extra" and "role", the core concept of ctags.
I was attracted them 2 or 3 years ago. Since then I have tried to understand the meaning of them evenryday.
@k-takata, can I ask you to review the changes as usual?
Of couse, I'm happy if other people give me feed-back, especially who wants "releasing".

Man  tag concept

---

configure.ac

The original code defines `HAVE_MBLEN=1` when mblen is not found.
It should be defined only when the function is found.
AC_CHECK_FUNCS defines the macro automatically when it is defiend
explicitly in the parameter list. So just specifying the name of
function is enough.

build-sys: fix wrong usage of AC_CHECK_FUNCS used in checking mblen

---

win32/appveyor.bat

Replace it with '_' when creating package files.
(I just want to use this in the ctags-win32 project.)

Allow using '/' as a part of tag name

---

main/e_msoft.h
main/main.c
main/options.c
main/routines.c

They were used in MS-DOS. We don't need them anymore.

main: Remove dir.h and findfirst()

---

circle.yml

Randomly following error has been reporeted in "Install build tools" step:
BDB1539 Build signature doesn't match environment
failed loading RPMDB
Though the error is reported packges which are needed for building
ctags bunary are ready to be used. So this change makes the build
step ignore the error.

circleci: ignore errors in "install build tools" step

---

.travis.yml

It seems that strings passed to color_formatter.rb are frozen in new ruby implementation.
As the result, destructive operations on the strings cause errors like:
Finished .info-file creation
/home/.../lcoveralls/color_formatter.rb:46:in `capitalize!': can't modify frozen String (RuntimeError)
This change rewrites the lines not to use capitalize!.
The change is reported to https://github.com/pcolby/lcoveralls/pull/6

travis: rearrange installed lcoveralls scripts

---

docs/interactive-mode.rst
docs/internal.rst
docs/news.rst
docs/optlib.rst
docs/parser-asm.rst
docs/running-multi-parsers.rst
docs/semifuzz.rst
docs/tips.rst
docs/windows.rst
man/ctags.1.rst.in

Found using [mwic](http://jwilk.net/software/mwic) and [anorack](https://github.com/jwilk/anorack).

docs: fix typos

---

Units/parser-objectivec.r/objectivec_protocol.h.d/expected.tags
parsers/objc.c

ObjectiveC: don't add a protocol itself to its scope

---

autogen.sh

@KazuakiM, this change may help us to fix https://github.com/universal-ctags/homebrew-universal-ctags/issues/23.
----
The are enabled to make remote debugging of build-system easier.

build-sys: set both -x and -e options in autogen.sh

---

.gitignore
Units/parser-cxx.r/namespace.cpp.d/expected.tags
Units/parser-cxx.r/namespace.cpp.d/input.cpp
parsers/cxx/cxx_parser_namespace.c

Be more tolerant when parsing namespaces.
Fixes parsing of stl headers which contain a macro after the namespace name.
Fixes #1539 .

CXX: Improve namespace parsing

---

circle.yml

The contents of rawhide look broken.

circleci: use fedora:latest instead of fedora:rawhide

---

Units/parser-make.r/make.variable-set-if-undefined.d/expected.tags
Units/parser-make.r/make.variable-set-if-undefined.d/input.mak
parsers/make.c

Make parser mistakenly captures http as a target in
following input:
URL ?= \
http://ctags.io
Here http is in value of URL.
This change fixes this behavior.

Make: ignore colon in a value as a target marker

---

autogen.sh

This fixes the remaining BSD build issues after the recent bmake fixes
were merged into master. Discussed in #1554. Closes #1554.

Remove non-posix make flag --no-print-directory from autogen.sh

---

configure.ac
main/e_msoft.h
main/options.c

Some platforms (like Solaris 10) lack asprintf.  The implementation made
for Windows works fine there, so use autoconf to determine whether
asprintf exists, and if not, enable compiling the replacement
implementation.
These are the relevant build messages:
```
main/options.c: In function ‘parseConfigurationFileOptionsInDirectory’:
main/options.c:3383:6: warning: implicit declaration of function ‘asprintf’ [-Wimplicit-function-declaration]
if (asprintf (&leafname,".%s",(Option.configFilename)?Option.configFilename:"ctags") == -1)
^
main/ctags-options.o: In function `parseConfigurationFileOptionsInDirectory':
/net/ptah/export/gentoo/working-repos/ctags/main/options.c:3383: undefined reference to `asprintf'
main/ctags-options.o: In function `parseConfigurationFileOptions': …
```

buildsys: add check for asprintf to enable alt implementation

---

docs/chop.rst
makefiles/help.mak
makefiles/testing.mak
misc/units

slap target is derived from chop target. While chop target truncates
the existing input files from tail, the slap target does the same
from head.

slap: new test harness derived from chop

---

autogen.sh

This is the same problem that 637f3d8da5abc60a26b03d7cb1dfbbf171522e7f fixed, but with a cross platform solution.
It was my mistake for using a GNU specific flag.

Fixes invoking autogen.sh from a makefile again

---

Tmain/clear-aliases.d/stdout-expected.txt
Units/parser-tcl.r/comments.tcl.d/args.ctags
Units/parser-tcl.r/comments.tcl.d/expected.tags
Units/parser-tcl.r/comments.tcl.d/input.tcl
main/tokeninfo.c
main/tokeninfo.h
parsers/itcl.c
parsers/tcl.c
parsers/tcl.h
parsers/tcloo.c

`#` at the middle of line in tcl script is not a comment starter.
But ctags recognized it as a comment starter.
The changes in this pull request fixes the wrong recognition about comment starter.

Tcl fix commnet handling

---

parsers/cxx/cxx_parser.c
parsers/cxx/cxx_token.c
parsers/cxx/cxx_token.h

In commit:
Cxx: reduce blocks when parsing values for array/union initialization
I introduced a loop to delete tokens to make memory usage during parsing
a large array smaller.
Newly introduced function cxxTokenReduceBackward is generalized version
of the loop. So you can apply to another place in the parser.

Cxx,refactor: introduce generic function for reducing tokens

---

parsers/rust.c

Rust parser directly accesses vString data structure.
Using vStringAPI increases the number of typing. However, it helps us to read the source code of the parser.

Rust: use vString API

---

Units/parser-go.r/go-anonmember.d/expected.tags
Units/parser-go.r/go-anonmember.d/input.go
Units/parser-go.r/go-funcs.d/expected.tags
Units/parser-go.r/go-funcs.d/input.go
parsers/go.c

The code right now isn't very easy to read. This patch tries to improve
that by being more explicit what is being parsed - memberCandidate
isn't reused for cases which have nothing to do with being member
candidate and type parsing is performed the same way both for
anonymous and non-anonymous members (right now tag is generated only
for the anonymous case).

go: Make struct parsing a little easier to read

---

main/parse.c

Close #1625.
Inspired by @jannick0.
CTagsSelfTest calls getppid for testing the sandbox feature.
Calling getppid dones't make sense if ctags is built at
a platform where the sandbox feature is not available.

CTagsSelfTest: call getppid only when HAVE_SECCOMP is defined

---

main/debug.c

The bug fixed by this change:
$ ./configure --enable-debugging; make; make -j 9
$ ./ctags -d 2 main/main.c
ctags: main/parse.c:271: getLanguageKind: Assertion `0 <= language && language < (int) LanguageCount' failed.
ctags: main/parse.c:271: parsing main/main.c:704 as C
zsh: abort (core dumped)  ./ctags -d 2 main/main.c

main,debug: fix wrong lang field access when dumping a tag entry in debug mode

---

main/fmt.c

Spotted by @b4n.
`tag->parserFields [findex].ftype` is used in printTagField().
What it specifies is the same as what `f->type` specifies.
I forgot replacing it in 4e9e52c2d6903ac4704c84358d40b56b28c55d10.

main,refactor: simplify the usage of loccal variable for specifying fied

---

main/routines.c

main: print file name when failing to open temporary file

---

docs/news.rst

docs(web): fix a typo in option name

---

parsers/yacc.c

Calling readLineFromInputFile from callback functions of regex causes a trouble as reported in
#1631 and #1640.
NOTE: rpmspec has the same issue.

Yacc: don't call readLineFromInputFile from callback functions

---

parsers/ada.c

Suggested by @Silky in #1653.
The condtion `token != NULL` in storeAdaTags is redundant
because its callers checks the same condtion before calling
it.
To avoid potential programming mistake, I put Assert instead.

Ada,refactor: delete redundant condition

---

Units/parser-cxx.r/enum-in-a-struct--with-q-extra.d/README
Units/parser-cxx.r/enum-in-a-struct--with-q-extra.d/args.ctags
Units/parser-cxx.r/enum-in-a-struct--with-q-extra.d/expected.tags
Units/parser-cxx.r/enum-in-a-struct--with-q-extra.d/input.cc
parsers/cxx/cxx_token_chain.c

Fix NULL check

---

Units/parser-cxx.r/broken-input.d/input.cc
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_tokenizer.c

When a mismatched subchain terminator is found, discard the whole subchain so no broken output is produced. When handling `__attribute__` attempt to resume parsing after failure so certain invariants are
preserved. Fixes #1659.

CXX: Fix 1659

---

Units/parser-c.r/broken-input-cxx-operator.d/input.c
parsers/cxx/cxx_parser.c

Scopes are supported only by C++. In other languages we silently
skip them.
Fixes #1664.

CXX: Ignore scopes when the current language is not C++

---

main/lregex.c

lregex: fix a typo about wrong short flag for extras

---

docs/interactive-mode.rst

I just spent around 10 minutes wondering why `ctags --_interactive` wouldn't work and figured out that jansson is required only by looking at the source code.
Hopefully this change will make it a little clearer if someone is confused as I was.

docs: note that jansson is required for interactive mode

---

Units/parser-cxx.r/class.cpp.d/expected.tags
Units/parser-cxx.r/class.cpp.d/input.cpp
Units/parser-cxx.r/operators.cpp.d/expected.tags
Units/parser-cxx.r/operators.cpp.d/input.cpp
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_scope.c
parsers/cxx/cxx_scope.h

C++ friend declarations are messy. Sometimes they act as a forward declaration and sometimes they do not. Their scope is not easy to find out and certainly is not the one we were emitting until now. It is better to ignore them.
There is one special exception: the friend function definition form for which the scope is clear (it's the enclosing namespace). We can handle that.

CXX: Improve friend declarations

---

Units/parser-cxx.r/bug-github-1675.cpp.d/expected.tags
Units/parser-cxx.r/bug-github-1675.cpp.d/input.cpp
parsers/cxx/cxx_parser.c

Try to detect common macro/compiler builtins when parsing structures.
Fix #1675 .

CXX: Improve struct parsing

---

parsers/ocaml.c

Since the whole `stack` array isn't completely cleared by the
`initStack` routine ctags would sometimes segfault after reading stale
or invalid data off the topmost item.
Writing a test is slightly complicated by the fact you have to "poison" the stack first.

Fix an off-by-one error in the tag stack traversing

---

main/field.c
main/parse.c

isalnum was used to check the acceptable characters as field name.
This commit switches it to isalpha to follow the rule in format.rst:
A tagfield has a name, a colon, and a value: "name:value".
* The name consist only out of alphabetical characters.  Upper and lower case
are allowed.  Lower case is recommended.  Case matters ("kind:" and "Kind:
are different tagfields).
I also check a client implementation, vim-7.4.160:
parse_match() of src/tag.c:
while (ASCII_ISALPHA(*p))
{
if (STRNCMP(p, "kind:", 5) == 0)
{
vim uses isalpha alike function to detect a field name.

main: don't allow to use number ([0-9]) as part of a field name

---

docs/internal.rst
docs/running-multi-parsers.rst
man/ctags.1.rst.in

It seems that it is wrong English.

docs: don't put "the" before "both"

---

parsers/ocaml.c

"match" and "beginEnd" kinds were introduced accidentally.
The kind is refereed when making a tag entry in prepareTag() via calling
contextDescription.
contextDescription() converts the type of context pushed on `stack' to
kind index. The kind index is refereed as a value representing parent
scope when making a tag entry.
A parent scope must have a name. getLastNamedIndex() finds a NAMED
parent context. Such context is converted by contextDescription().
A context having `ContextMatch' or `ContextBlock' as its type has
no name; when calling a function pushing a context having such type to `stack',
NULL is passed as the context name.
ContextMatch:
case OcaKEYWORD_function:
toDoNext = &matchPattern;
pushSoftContext (&matchPattern, NULL, ContextMatch);
break;
case OcaKEYWORD_with: …

OCaml: remove unused kinds

---

Tmain/kinddef.d/run.sh
Tmain/kinddef.d/stdout-expected.txt
main/kind.c
main/lregex.c
main/parse.c
main/vstring.c
main/vstring.h
man/ctags-optlib.7.rst.in

These are some small fixes.
The exception is the last one.
I'm thinking about adding flags to `--kinddef-<LANG>` option. For the case, I would like to reserver the char `{`.

 [SELF INCOMPATIBLE] main: reserver '{' in kind description as a meta character

---

Tmain/kinddef.d/run.sh
Tmain/kinddef.d/stdout-expected.txt

Tmain: don't use two backslashes(\\) in the test case

---

parsers/cxx/cxx_qtmoc.c

This bug fixed by this commit appears when running ctags built with -O0 as
CFALGS. The result of Tmain/extra-field.d is different from what
ctags built with -O2 prints.

QtMoc: fix using wrong struct for defining qtMocSubparser

---

Tmain/broken-extradef.d/run.sh
Tmain/broken-extradef.d/stderr-expected.txt
Units/option-extradef.d/args.ctags
docs/news.rst
docs/optlib.rst
main/options.c
main/parse.c
man/ctags-optlib.7.rst.in
misc/optlib2c
optlib/qemuhx.ctags

I would like to delay writing the documents for this option.

[SELF INCOMPATIBLE]: mark --extradef option "experimental" by renaming it to --_extradef

---

main/options.c

For hiding options for experimental features from
the output of --help option. Instead, --help-full
option printing all options including the experimental
features is introduced.

main: introduce --help-full option

---

Units/parser-ruby.r/ruby-block-assign.d/expected.tags
Units/parser-ruby.r/ruby-block-assign.d/input.rb
parsers/ruby.c

Simplyfy the commits in #1732.

Ruby: assign blocks (originally submitted by @tambeta)

---

parsers/c.c
parsers/json.c
parsers/ttcn.c

All "boolean" were replaced with "bool" in
the commit "Prefer stdbool.h over mybool.h" (ce990805).
String literals for recognizing "boolean" keywords in Java and TTCN
parsers were also replaced. This should not be done.
About JSON parser, "boolean" was used as a name for a kind.  Changing
back from "bool" to "boolean" is not must. However, "boolean" may be
more popular word than "bool" for JSON users to represent a boolean
object. Actually geany'c json.c chooses "boolean" as the kind name.
(This change is not needed to be ported to geany's ctags.
geany uses "boolean" correctly in the all places.)

Java,JSON,TTCN: use "boolean" instead of "bool"

---

Units/parser-cxx.r/function_try_block.d/args.ctags
Units/parser-cxx.r/function_try_block.d/expected.tags
Units/parser-cxx.r/function_try_block.d/input.cxx
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_function.c
parsers/cxx/cxx_parser_internal.h
parsers/cxx/cxx_parser_tokenizer.c
parsers/cxx/cxx_tag.c
parsers/cxx/cxx_tag.h

Improved solution for #1746.
-  catch() is part of the function-try-block:
-- the variables declared inside now have proper scope
-- the function ends after the last catch()
- variables declared in the catch() parenthesis are extracted
- function-try-blocks are reported as properties

CXX: Improve parsing of function-try-blocks and try/catch in general

---

Tmain/parser-own-fields.d/stderr-expected.txt

As @hnakamur reported on #655, parser-own-field.d is failed
when runnint it on "Ubuntu PPA build". stderr output of the
case is needed to make the root cause clear.

Tmain: verify the stderr output of parser-own-field test case

---

Tmain/parser-own-fields.d/run.sh

"V" variable was introduced as a placeholder that is used when I want
to run the test case under valgrind; the valgrind command line is set
to "V".
It seems that "Ubuntu PPA build" environment defines V as an environment
variable with value "1". See #1761.
As the result, the test case doesn't work well on the environment.
This commit clears the value for "V" to allow the test case works
on the environment.

Tmain: initialize "V" variable explicitly

---

Units/parser-ruby.r/ruby-block-assign.d/expected.tags
Units/parser-ruby.r/ruby-block-assign.d/input.rb
parsers/ruby.c

When assigning blocks in Ruby, handle assignment to variables prefixed by `@`, `@@` or `$`.
This is an improvement to #1734.

Ruby block assign: handle variables with sigils

---

main/debug.h
main/trace.h

ctags requires c99 compiler.
In that case, `__func__` is more portable than `__PRETTY_FUNC__`.

 main: use __func__ instead of __PRETTY_FUNC__

---

parsers/python.c

When making a reference tag of "unknown" kind,
PYTHON_MODULE_IMPORTED is used to assign a role for the tag.
PYTHON_UNKNOWN_IMPORTED should be used instead.
Our test cases could not detect the mistake because, The integer
representation of PYTHON_UNKNOWN_IMPORTED role enumerator and that of
PYTHON_MODULE_IMPORTED role enumerator are the same (== 1). In other
hand the string representation of the roles are the same (==
"imported"), too.
The API for defining and assigning roles must be improved in the
future.

Python: fix wrong role assignments

---

Tmain/interactive-mode.d/stdout-expected.txt
Tmain/json-output-format.d/stdout-expected.txt
Tmain/json-output-to-file.d/stdout-expected.txt
Tmain/sandbox-with-eager-guessing.d/stdout-expected.txt
Tmain/sandbox.d/stdout-expected.txt
Units/xformat-option.r/format-CfSt.d/expected.tags-x
main/field.c
main/writer-ctags.c

typeref: field has sub-fields "typeref prefix" and "typeref name" in tags format.
":" combines the two sub-fields and makes the field value.
e.g.
typename:int
struct:S
In xref and json output formats, only "typeref name"
sub field was printed when printing typeref: field.
This change fixes this inconsistent.
This is self-incompatible change.
If you want, "typerefPrefix" and "typerefName" fields can be introduced.
Open an issue in that case.
This change is needed to solve #1772.

[SELF-INCOMPATIBLE] xformat-writer,json-writer: make typeref: field in xref and json output formats as same as that in tags

---

Units/review-needed.r/matlab_test.m.t/expected.tags
Units/review-needed.r/matlab_test.m.t/input.m
parsers/matlab.c

Recognize the definition of a class, and allow for functions not to be
defined in the first column but to be indented by white space.

Add support for Matlab classes

---

Units/parser-fortran.r/fortran-protected.d/expected.tags
Units/parser-fortran.r/fortran-protected.d/input.f90
parsers/fortran.c

The protected attribute in Fortran is used to make a module variable readable, but not editable from outside. However, public module variables marked with the protected attribute were omitted when the file was parsed. Therefore, I added the protected attribute.

Introduced protected attribute for Fortran

---

parsers/cxx/cxx_subparser.c

C++,QtMoc: initialize uninitialized local variable

---

main/numarray.c
main/numarray.h
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

numArray is derrived from ptrArray.  ptrArray is for storing pointers.
numArray is for store numbers like int and long.
numArray is implemented in macro. You can use it after expanding the
macro by giving actual data type. The declaration and implementation
for char, unsigned char, int, unsigned int, long and unsigned long are
expanded already.

main: add numArray template data structure

---

main/trace.c
main/trace.h

TRACE_PRINT prints a line at once; it inserts a prefix at the start and a newline at the end.
Sometimes I want to print a trace line incrementally.
TRACE_PRINT_{PREFIX|FMT|NEWLINE} are for the purpose.
TRACE_PRINT_PREFIX just prints a prefix.
TRACE_PRINT_FMT does the same as TRACE_PRINT but it doesn't print a prefix and a newline.
TRACE_PRINT_NEWLINE just prints a newline.
You can use them like:
TRACE_PRINT_PREFIX();
#ifdef DO_TRACING
if (ctx->if_tracker)
{
for (int i = 0; i < intArrayCount (ctx->if_tracker); i++)
TRACE_PRINT_FMT("%d ", intArrayItem(ctx->if_tracker, i));
}
#endif	/* DO_TRACING */
TRACE_PRINT_NEWLINE();

main: introduce TRACE_PRINT_{PREFIX|FMT|NEWLINE} macros

---

Units/parser-cxx.r/cxx11-constexpr-variable.d/expected.tags
Units/parser-cxx.r/cxx11-constexpr-variable.d/input.cpp
parsers/cxx/cxx_keyword.c

C++: tag constexpr variable declarations

---

Units/parser-asciidoc.r/anchor-asciidoc.d/expected.tags
Units/parser-asciidoc.r/anchor-asciidoc.d/input.asciidoc
Units/parser-asciidoc.r/simple-asciidoc.d/expected.tags
Units/parser-asciidoc.r/simple-asciidoc.d/input.asciidoc
Units/parser-asciidoc.r/utf8-asciidoc.d/expected.tags
Units/parser-asciidoc.r/utf8-asciidoc.d/input.asc
docs/news.rst
main/parsers.h
parsers/asciidoc.c
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

This ports the Asciidoc parser from geany, fixes a bug in it, and adds tagging of anchors. (other than anchors inline in one-line titles)

Asciidoc: new parser

---

Tmain/list-mline-regex-flags.d/stdout-expected.txt
Tmain/list-mtable-regex-flags.d/run.sh
Tmain/list-mtable-regex-flags.d/stdout-expected.txt
Tmain/list-regex-flags.d/stdout-expected.txt
Tmain/mtable-stats.d/args.ctags
Tmain/mtable-stats.d/input.foo
Tmain/mtable-stats.d/run.sh
Tmain/mtable-stats.d/stderr-expected.txt
Tmain/mtable-stats.d/stdout-expected.txt
Tmain/optlib-message-flag.d/args.ctags
Tmain/optlib-message-flag.d/input0.foo
Tmain/optlib-message-flag.d/input1.foo
Tmain/optlib-message-flag.d/input2.foo
Tmain/optlib-message-flag.d/input3.foo
Tmain/optlib-message-flag.d/run.sh
Tmain/optlib-message-flag.d/stderr-expected.txt
Tmain/optlib-message-flag.d/stdout-expected.txt
main/lregex.c
main/main.c
main/options.c
main/options.h

This PR adds a new option and a couple new flags to help users debug and optimize optlib multi-table regex parsers. It also does some code cleanup along the way.
Documentation for the new option and flags will be added to `optlib.rst` after PR #1826 is merged into master. (otherwise I'll get conflicts with that one)

optlib: Add option/flags to help users develop multi-table regex parsers

---

Units/parser-asciidoc.r/anchor-invalid-asciidoc.d/expected.tags
Units/parser-asciidoc.r/anchor-invalid-asciidoc.d/input.adoc
parsers/asciidoc.c

asciidoc: check for invalid trailing inline anchors before recording tag

---

main/vstring.c

We don't need the extra strncpy() semantic in stringCat() as we always
know the length we want, so it's slightly faster to use memcpy(), about
2% in some cases.
Additionally, this would improve support for NUL bytes embedded in a
vString, avoiding an extra truncation.  However, no consumer currently
rely on NUL byte support so it currently has no impact on this end.

vstring: Use memcpy() instead of strncpy()

---

parsers/flex.c
parsers/jscript.c
parsers/sql.c
parsers/verilog.c
parsers/vhdl.c

This avoids computing the length that is already known.

Use vStringCat() instead of vStringCatS() when possible

---

Units/parser-go.r/go-anonmember.d/expected.tags
Units/parser-go.r/go-anonmember.d/input.go
Units/parser-go.r/go-scope.d/expected.tags
Units/parser-go.r/go-torture.d/expected.tags
parsers/go.c

An example output:
$ cat foo.go
type P struct  {
x, y int
}
$ u-ctags -o - foo.go
P     foo.go  /^type P struct  {$/;"  s
x     foo.go  /^     x, y int$/;"     m       struct:P        typeref:typename:int
y     foo.go  /^     x, y int$/;"     m       struct:P        typeref:typename:int

Go:  fill the typeref field for struct "memeber" kind

---

parsers/robot.c

Removing empty expression .{0} fixes unit test on FreeBSD due to FreeBSD libc regcomp not liking the following (a|b|.{0}).   Even though .{0} is valid removing it shouldn't create any issues.

Robot: remove empty expression .{0} in parsers/robots.c to fix unit test tmain and units on FreeBSD

---

docs/units.rst
misc/units

Java language expects a class and the file where the class is defined
have a same name. On the othre hand, the language doesn't allow to use
`-` in a class name.
This means that we cannot write a test input file as a valid Java program.
This change solves this situation.

unit: accept input_[0-9].* and input_[0-9]_*.* as input file names

---

Tmain/list-fields-with-prefix.d/stdout-expected.txt
Tmain/list-fields.d/stdout-expected.txt
Tmain/list-roles.d/stdout-expected.txt
Units/parser-go.r/go-import.d/args.ctags
Units/parser-go.r/go-import.d/expected.tags
Units/parser-go.r/go-import.d/input-0.go
Units/parser-go.r/go-import.d/input-1.go
Units/parser-go.r/go-import.d/input-2.go
Units/parser-go.r/go-import.d/input-3.go
Units/parser-go.r/go-import.d/input-4.go
Units/parser-go.r/go-import.d/input-5.go
Units/parser-go.r/go-import.d/input-6.go
Units/parser-go.r/go-import.d/input-7.go
Units/parser-go.r/go-import.d/input.go
parsers/go.c

In addition, add following items:
* "packageName" kind representing 'f' in 'import f "aPackage"'
* "package" field for "packageName" kind
* "packageName" field for "package" kind
* "howImported" field for "imported" role of "package" kind
The "howImported" field takes "init" or "inline".

Go: introduce "imported" role to "package" kind

---

parsers/sql.c

In 6e74a9bbb, I added a fprintf call to our source tree unexpected.

SQL: remove unexpected introduced debug-print code

---

docs/optlib.rst

The text refers to the 3rd line of this file
```
/* BLOCK COMMENT
var dont_capture_me;
*/
var a /* ANOTHER BLOCK COMMENT */, b;
```
On the 3rd line the the characters are  `*/`
I think there is a typo.

Fix a typo in docs.

---

parsers/cxx/cxx_debug.c
parsers/cxx/cxx_scope.h

To checkout the argument of cxxDebugScopeDecode() whether it has an
acceptable value, sizeof operator is used. It is wrong. clang reports
this. In stead, I should use the count of enum elements.

Cxx: don't use the size of array when checking the argument in debug code

---

parsers/tex.c

This was introduced in 5d5afe64ca5517c50897164f72db174428961e9f which started accepting as an identifier character any byte with a value that cast as unsigned char is greater than or equal to 0x80.  The common value for the EOF constant being -1, which cast to unsigned char gives a value of 0xff, hence leading to accepting EOF as an identifier character.
Fix the loop accordingly to explicitly guard against EOF.
Fixes #1896.

tex: Fix infinite loop parsing an identifier at EOF

---

parsers/cxx/cxx_token.c
parsers/cxx/cxx_token_chain.c

No need to allocate `sizeof(CXXToken) * sizeof(CXXToken)` bytes for a single token structure when `1 * sizeof(CXXToken)` bytes is enough.
This fixes ctags memory usage issue mentioned here: https://github.com/oracle/opengrok/issues/2364

Fix xMalloc usage

---

Tmain/map-removing.d/stdout-expected.txt
parsers/ada.c

This extension is used in a lot of old Ada source files which contain multiple compilation units.

Add the common ".ada" as an accepted file extension.

---

docs/optlib.rst

docs(web): Fix a typo in .ctags search path on Windows

---

Units/parser-yacc.r/bom.d/expected.tags
main/mio.c
main/mio.h
main/parse.c
parsers/yacc.c

Consider for instance the following HTML code where a subparser is called
on the contents of the <script> tags.
```
<script language="Javascript" src="./test.js"></script>
<script language="JavaScript">
...
</script>
```
Since the first <script> is empty, mio_new_mio() is called with 0 size
but with the current semantics of the API it creates MIO until the end of
the file so the whole source file to EOF is parsed. While it seems
no extra tags are generated in this case, the parsing happens
unnecessarily.
Instead of using 0, make size signed and use -1 when we want to create a
MIO till the end of the source MIO.
---
I actually noticed this problem in Geany rather than in ctags where tags started getting duplicated because of the multiple parsing. I haven't investigated enough to learn why …

 Allow mio_new_mio() to have size 0

---

parsers/cxx/cxx_parser_lambda.c

Consider for instance
Foo a[] = {
{foo1, bar1, baz1},
{foo2, bar2, baz2},
...
}
where the number of entries is very large - check for instance this file
for real-world example:
https://kernel.googlesource.com/pub/scm/linux/kernel/git/mchehab/linux-media/+/media/v4.7-2/drivers/gpu/drm/amd/powerplay/inc/fiji_pwrvirus.h
At the moment the cxxParserOpeningBracketIsLambda() function checks if {
is a beginning of lambda body by going back and finding some sentinel.
In this case, however, none of the checked sentinels is found and
with initializations like the above it has to go thousands of tokens
backwards for { on every line which leads to quadratic complexity.
I believe {} shouldn't appear within lambda declaration so it should
be safe to add this as an additional sentinel.
@pragmaware Does …

cxx: Fix performance problem when parsing long array initializations

---

Units/parser-c.r/cxx-scope-keywords.d/expected.tags
Units/parser-c.r/cxx-scope-keywords.d/input.h
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_parser_tokenizer.c
parsers/cxx/cxx_qtmoc.c

Improve parsing of public/protected/private keywords so it does not need specialized code in token extraction path. This makes it a bit faster and additionally fixes a bug that caused corrupted inheritance information for base classes with names starting with an underscore (a common case in STL).

CXX: Improve parsing of private/public/protected

---

main/field.c
main/field.h
main/field_p.h
main/fmt.c
main/kind.c
main/lregex.c
main/main.c
main/options.c
main/parse.c
main/writer-ctags.c
main/writer-json.c
main/writer-xref.c
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

This is the last PR for splitting the header files into two categories.
One is for parsers (public).
Another is for the main part (private).

Defining interface for parsers (part 6 of 6)

---

Units/parser-cxx.r/signature.cpp.d/expected.tags
Units/parser-cxx.r/signature.cpp.d/input.cpp
main/field.c
main/vstring.h
parsers/cpreprocessor.c
parsers/cpreprocessor.h
parsers/cxx/cxx_parser_tokenizer.c

Close #1967.
The change doesn't handle whitespaces in string and char literals. 
```
void f(char c = '\t', char d='	', char e = 'a')
{
}
void g(const char *s = "a\tb	c")
{
}
```

Cxx capture parameter s default value as part of signature

---

parsers/cpreprocessor.c
parsers/cxx/cxx_parser_tokenizer.c

ctags seemed to have some support for $ in identifiers, like it would index $BAR from `#define $BAR` but not `$name` from `extern int $name;`. Similarly it wouldn't let me define replacement macros e.g., `'-D$my$struct=struct` and then have foo from  `$my$struct foo` indexed. This minipatch appears to fix these issues.

more complete support for $ in C/C++ identifiers

---

main/entry.c
main/writer-ctags.c
main/writer-json.c
main/writer-xref.c
main/writer.c
main/writer_p.h

The methods were introduced for making full qualified tags automatically
when corkAPI is enabled. However, it is nothing to do with tagWriter
backends. This change pulls up the code for making the cache to
tagEntryInfo layer.

main,refactor: remove buildFqTagCache method of tagWriter

---

Tmain/readtags-qualifier.d/run.sh
Tmain/readtags-qualifier.d/stdout-expected.txt
dsl/qualifier.c

Currently, if "or" finds an non-false value in operands, it returns #t.
Its upper context may want the value, not #t.
Actually, a scheme interpreter returns the value.
$ gosh
gosh> (or #f #f 3)
3

dsl: return passed value instead of #t in "or" operator

---

Units/parser-go.r/go-funcs.d/expected.tags
Units/parser-go.r/go-scope.d/expected.tags
Units/parser-go.r/go-torture.d/expected.tags
Units/parser-go.r/go-vars.d/args.ctags
Units/parser-go.r/go-vars.d/expected.tags
Units/parser-go.r/go-vars.d/input.go
main/htable.c
main/htable.h
parsers/go.c

This is revised version of #1878.
In #1878, I tried to make names for scope field shorten.
In this pull request, I don''t do so; this change focuses only on fillling more fields of  Go parser tag entries.
If shorter scope names are better, I expect users may let us know. I will rework if we get such request.

Go: fill more fields (revisied)

---

Units/parser-php.r/php-semi-reserved-keywords.d/expected.tags
Units/parser-php.r/php-semi-reserved-keywords.d/input.php
parsers/php.c

https://wiki.php.net/rfc/context_sensitive_lexer
Based on a patch from @masatake; closes #1986.
Fixes #1985.

php: Do not get fooled by keywords used in class context

---

Units/parser-objectivec.r/crash-in-parsing-protocol.d/README
Units/parser-objectivec.r/crash-in-parsing-protocol.d/args.ctags
Units/parser-objectivec.r/crash-in-parsing-protocol.d/expected.tags
Units/parser-objectivec.r/crash-in-parsing-protocol.d/input-0.h
Units/parser-objectivec.r/crash-in-parsing-protocol.d/input.h
main/entry.c
parsers/objc.c

This fix a bug I introduced to the objc parser in these days.
I will merge in soon.

ObjectiveC: fix about memory management for the parser specific dyanamic fields

---

Units/parser-php.r/php-anonymous-classes.d/args.ctags
Units/parser-php.r/php-anonymous-classes.d/expected.tags
parsers/php.c

anonGenerate function defined in main part is for generating names
for anonymous tags. Unlike the current particular implementation
in php.c, the name generated by anonGenerate function is unique in
a tags file. The unique names may help a client tool implement
interesting features.
In addition to using the function, this change marks tags for
anonymous classes XTAG_ANONYMOUS. So a user can enable or disable
the emission of tags for anonymous classes with --extras='-{anonymous}'
option.

PHP: use anonGenerate function

---

Makefile.am
Tmain/pretend-option.d/run.sh
Tmain/pretend-option.d/stdout-expected.txt
autogen.sh
configure.ac
main/general.h
main/mio.c
main/options.c
main/options_p.h
main/parse.c
main/parse_p.h
main/vstring.c
main/vstring.h
makefiles/help.mak
makefiles/list-optlib2c-input.mak
makefiles/list-translator-input.mak
makefiles/optlib2c_input.mak
makefiles/testing.mak
misc/units
mk_mingw.mak
mk_mvc.mak
source.mak

This pull request is a spin-off of #1847.
In #1847, I  tried to introduce packcc parser generator to implement new java parser.
However, what the result I got is that the parser is too slow. So I wonder whether I should introduce the parser generator or not to ctags.
However, the partial results of introducing the parser generator are useful even if I don't introduce it.
* build scripts are improved to utilize another code generator than optlib2c.
* `_prepend-<NEWLANG>=<OLDLANG>` option helps us reimplement or improve existing parser.

Support more translators

---

Units/parser-go.r/go-dont-solve-type-for-underscore-var.d/expected.tags
Units/parser-go.r/go-dont-solve-type-for-underscore-var.d/input.go
parsers/go.c

To solve a type for a variable later, go parser stores the cork id of
the variable to integer array. However, the cork id for "_" variable
becomes CORK_NIL because makeTagFull() doesn't record "_" as a tag.
The original code has a bug that that go parser stores the CORK_NIL
for "_" to the intger array. The parser should not do so. When resolving
the type for the variable, go parser does (1) pick a cork id from the
intger array, (2) get a tagEntry for the cork id, then (3) access
the internal of the tagEntry. If the cork id is CORK_NIL here, ctags
crash at (3) because getEntryInCorkQueue returns NULL when receiving
CORK_NIL as a cork id.

Go: don't try to solve the type for "_" variable

---

Tmain/e-ctags-output.d/input_file.cc
Tmain/e-ctags-output.d/input_scope.rst
Tmain/e-ctags-output.d/input_space.rst
Tmain/e-ctags-output.d/input_tab.rst
Tmain/e-ctags-output.d/run.sh
Tmain/e-ctags-output.d/stdout-expected.txt
main/field.c
main/field.h
main/field_p.h
main/writer-ctags.c

The original code rejects printing a tagEntryInfo that includes whiespace or tab chars
in e-ctags output mode.
This is reported as a bug in #2014 by @elecalion.
I myself also reported in #1969.
What we should reject is just tab char.
NOTE: This char doesn't fix the original bug perfectly.  If --sort=no
is given, e-ctags output mode doesn't reject a tagEntryInfo including
'\t'. The code for rejecting depends on wrong assumption that the
output stream (to tags file) is rewindable. This is not true if the
output is connected to stdout directly. The options combination, "-o
-" and "--sort=no" breaks my assumption.

main: accept whiespace in tagEntryInfo even in e-ctags output mode

---

read/readtags.c

I measured performance of readtags by giving large tags file and found
strcmp in parseExtensionFields is a bottle neck.
This change reduces the number of calling strcmp in the function.
Without this change:
[yamato@slave]~/var/ctags-github% time readtags -t ~/.spelunker.d/kernel76/kernel76.tags  -l   > /dev/null (5 times)
<gs -t ~/.spelunker.d/kernel76/kernel76.tags  -l   > /dev/null
readtags -t ~/.spelunker.d/kernel76/kernel76.tags -l > /dev/null  3.62s user 0.29s system 99% cpu 3.918 total
readtags -t ~/.spelunker.d/kernel76/kernel76.tags -l > /dev/null  3.62s user 0.30s system 99% cpu 3.924 total
readtags -t ~/.spelunker.d/kernel76/kernel76.tags -l > /dev/null  3.64s user 0.28s system 99% cpu 3.930 total
readtags -t ~/.spelunker.d/kernel76/kernel76.tags -l > /dev/null  3.60s user 0.27s …

readtags: optimize the way to read fields

---

misc/optlib2c

Hello, I'm interested in picking up the elixir branch (`elixir-optlib`) of this repo, and noticed that said branch has two commits: the first one, is this one I'm doing the pull request for, in which @masatake added the code to escape a double quote char in a string, and the second one, which has the code to parse elixir code.
I noticed that the first commit isn't actually related to Elixir (or at least isn't in a way I could see), so it shouldn't be in the elixir branch, and it's useful enough to be merged into master. That's the reason I took this commit and rebased it to `master`, fixing a small conflict in the process. So now optlib should be able to parse the double quote char in a description string, and I should be free to hack on `elixir-optlib` after rebasing it to `master`.
I'm …

optlib2c: escape a double quote char in a description string w backslash

---

Tmain/e-ctags-output.d/run.sh
Tmain/e-ctags-output.d/stdout-expected.txt
Tmain/tab-in-parser-specific-field.d/foo.ctags
Tmain/tab-in-parser-specific-field.d/input.foo
Tmain/tab-in-parser-specific-field.d/run.sh
Tmain/tab-in-parser-specific-field.d/stdout-expected.txt
main/entry.c
main/field.c
main/parse.c
main/writer-ctags.c

During working on #2015, I found some broken code for handling tab chars in parser specific fields.
It was not well considered.
The test code in this PR explains how the code was broken.
~~"--sort=no" issue I reported in #2015 is not fixed in this PR yet.~~
I also fixed the bug found in the option combination in "-o - --sort=no --output-format=e-ctags".
Close #1969 and #2014.

Fix the behavior in "-o - --sort=no --output-format=e-ctags" combination (was: Overhaul the code handling tab chars in parser specific fields)

---

Makefile.am

This should fix a Out-of-source or nested build.
Related to #2029.

Locate packcc in build directory instead of the source

---

.travis.yml

See the last comment in #2031 submitted by @k-takata .

travis-ci: adjust lcoveralls --root argument for out-of-tree building

---

Units/parser-elixir.r/elixir-functions.d/expected.tags
Units/parser-elixir.r/elixir-functions.d/input.ex
optlib/elixir.c
optlib/elixir.ctags

Quick fix for #2043 
* Removed unnecessary atom in the regex for the function kind.
* Expanded `elixir-functions` test case to include case present in the issue above.
The removed atom was there to deal with a problem present when parsing operators, but I forgot to remove it when the operators problem was fixed.
A quick run of the tests shows them all passing, as before.

Fix bug in elixir function tag missing a char

---

Makefile.am
main/mio.c
read/readtags-cmd.c
read/readtags.c
read/readtags.h
source.mak

I'm thinking about adding "--sort expr" option to the readtags command.
This PR cleans up the code for adding the new feature.

readtags: refactor for adding sorter

---

README.md

Now we use git-subtree for packcc. (#2035)

doc: Remove description about git-submodule for packcc

---

.travis.yml

This uses the newer Ubuntu Xenial, instead of Trusty.

ci: Travis: use dist=xenial

---

main/read.c
main/read.h
parsers/flex.c
parsers/jscript.c
parsers/sql.c

/* ... */ style comment syntax is used variety languages.
Each parser implements code skipping comments.
This change introduces skipToCharacterInInputFile2 helper function for
unifying the implementations.
The original code handles '\0' char specially.
skipToCharacterInInputFile2 doesn't do so. I don't understand the need.
(About C and C++ parsers they are handled in CPreProcessor parser.
They are out of scope of this change.)

main,Flex,JavaScriupt,SQL,refactor: introduce a helper function to skip two character sequence

---

Tmain/gcov-sandbox.d/run.sh
Tmain/sandbox-crash.d/run.sh
Tmain/sandbox-default-req.d/run.sh
Tmain/sandbox-no-eager-guessing.d/run.sh
Tmain/sandbox-unknown-submode.d/run.sh
Tmain/sandbox-with-eager-guessing.d/run.sh
Tmain/sandbox.d/run.sh

The sandbox tests pass the --_interactive option to ctags, which is only present if ctags was built with json support. Add check for the interactive feature in the tests skipping the tests if the feature is not present.
Closes: #2072

Check for interactive feature in sandbox tests

---

Tmain/fixed-field-handling.d/input.c
Tmain/fixed-field-handling.d/run.sh
Tmain/fixed-field-handling.d/stdout-expected.txt
main/field.c
main/writer-ctags.c
main/writer-etags.c
main/writer-json.c
main/writer-xref.c
main/writer.c
main/writer_p.h

Close #2065.
The tags format must include name, input, and pattern fields.
When running ctags, disabling them are not allowed. To implement
this rule, "fixed" fields were introduced to field.c.
However, this rule is applicable only to the ctags writer. The
other writer like json-writer doesn't need to follow the rule.
The fixed field is implemented in field.c. Now, it moves to writer-ctags.c.
As the result, json-writer can print the result with disabling
"name", "input", and/or "pattern".

main,json-writer: allow the writer to disable "fixed" fields

---

Units/parser-typescript.r/ts-class-fq.d/args.ctags
Units/parser-typescript.r/ts-class-fq.d/expected.tags
Units/parser-typescript.r/ts-class-fq.d/input.ts
docs/developers.rst
parsers/typescript.c

I've changed manually handling scopes as strings in favor of CORK indexes. Parser code is now shorter and more clear. I've also introduced myself in developers.rst

TypeScript: use CORK for scopes

---

README.md

It seems that the snap repo is not maintained.

Remove link to snap repo

---

main/options.c

parseConfigurationFileOptionsInDirectoryWithLeafname() is only used
by the code protected by the ifdefs so when the code inside ifdefs
isn't compiled, we get a warning about unused function. Move it inside
the ifdef section.

Fix warning about unused function

---

Tmain/list-fields-with-prefix.d/stdout-expected.txt
Tmain/list-fields.d/stdout-expected.txt
Tmain/list-subparsers-all.d/stdout-expected.txt
Units/simple-moose.d/args.ctags
Units/simple-moose.d/expected.tags
Units/simple-moose.d/input.pl
docs/news.rst
main/parse.c
main/parsers_p.h
parsers/moose.c
parsers/perl.c
parsers/perl.h
parsers/tcloo.c
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

Moose subparser based on perl parser

---

main/unwindi.c
main/unwindi.h
parsers/typescript.c

Typescript parser was originally about 10x slower than other parsers. Main performance bottlenecks seemed to be memory related. Here is what I did:
- parser states are now merged into one union type
- multiple single char parsers are merged into one
- unwinding markers stack implementation is changed to use only one `ptrArray` so there is much less allocation and deallocation of memory
- accepting any char is done now by simple ignore flag instead of using special parser
- white chars are skipped outside of the parsers
After applying all of those changes typescript parser is now 5x slower than others. @masatake could you look at this?

Typescript: performance improvements

---

main/main.c
main/options.c
main/portable-dirent_p.h
main/portable-scandir.c
main/routines_p.h

At the moment, when you comment-out HAVE_SCANDIR or HAVE_DIRENT_H in
config.h (which is the configuration we use in Geany because we don't
need this functionality), one gets a compilation error.
This patch enables all possible combinations of HAVE_SCANDIR and
HAVE_DIRENT_H:
1. It removes the error from portable-dirent.h when neither HAVE_DIRENT_H
is defined nor _MSC_VER is used (the header does nothing in this case).
2. Inside portable-scandir.c, the checks are more precise - scandir() from
dirent.h is only used when both HAVE_SCANDIR and HAVE_DIRENT_H are
defined and the scandir() implementation is only compiled when
HAVE_DIRENT_H is available or _MSC_VER (which implies dirent from
portable-dirent is used) is defined. This means we have
scandir() -- either the system one or the ctags one …

Allow compilation when either scandir() or dirent.h aren't available

---

Tmain/list-roles-with-kind-names.d/stdout-expected.txt
Tmain/list-roles.d/stdout-expected.txt
Units/parser-flex.r/as-first-token.d/expected.tags
Units/parser-flex.r/as-first-token.d/input.as
Units/parser-flex.r/classes.d/args.ctags
Units/parser-flex.r/classes.d/expected.tags
Units/parser-flex.r/classes.d/input.as
Units/parser-flex.r/const.d/args.ctags
Units/parser-flex.r/const.d/expected.tags
Units/parser-flex.r/const.d/input.as
Units/parser-flex.r/const2.d/expected.tags
Units/parser-flex.r/const2.d/input.as
Units/parser-flex.r/flex_only_mxml.mxml.d/expected.tags
Units/parser-flex.r/flex_with_actionscript.mxml.d/expected.tags
Units/parser-flex.r/method-attributes.d/expected.tags
Units/parser-flex.r/method-attributes.d/input.as
Units/parser-flex.r/packages.d/expected.tags
Units/parser-flex.r/packages.d/input.as
Units/parser-flex.r/sampler.d/args.ctags
Units/parser-flex.r/sampler.d/expected.tags
Units/parser-flex.r/sampler.d/input.as
Units/review-needed.r/flex_override.mxml.t/expected.tags
parsers/flex.c

The Flex parser has 2 parts: ActionScript (which is close to JavaScript) and MXLM (which is an XML dialect).  The Flex parser was built around an older version of the JavaScript parser, before the latter got a lot of fixes and overhauls.
This means I had to port a *lot* of fixes over from the JavaScript parser, so the approach I took in https://github.com/universal-ctags/ctags/commit/8bbb9d0d4177c07985ab4af12d746c33707dcaaa was to simply compare the two parsers at their current state and sync what can be.  This was a lot less painful than applying every single fix, with the conflicts due to the divergence and such.  So if one want to review the changes, it's interesting to check against jscript.c as well (and good luck).
After that "synchronizing" commit (it's actually sill different in …

ActionScript: Fix and improve the parser

---

main/parse.c
main/parse_p.h

Allow applications which use ctags as a library provide their own
list of parsers. This list has to be declared as a define called
EXTERNAL_PARSER_LIST inside an external header. ctags will use the
EXTERNAL_PARSER_LIST_FILE define to detect the presence of such a
header and it should contain path to the header. When not defined,
internal parsers are used.
I've tested this against Geany and it seems to work.

main: allow specifying alternative parser list

---

parsers/cxx/cxx_parser.c

This patch fix some spelling typo in DEBUG messages.

C++: Fix typos in cxx_parser.c

---

Units/parser-inko.r/methods.d/expected.tags
Units/parser-inko.r/methods.d/input.inko
optlib/inko.c
optlib/inko.ctags

Inko allows you to use certain special characters for method names. For
example: +, -, /, [], and []=. This adds support for creating tags for
such methods, which would previously not be tagged.

Add support for special Inko method names

---

docs/optlib.rst

Fix some spelling typo and double words "of of".

Fix typo and double words in optlib.rst 

---

main/parse.c

This patch fix some spelling typos in parse.c

main: Fix spelling typos in parse.c

---

Units/simple-markdown.d/input.md
optlib/markdown.c
optlib/markdown.ctags

This is a bug fix discussed in https://github.com/Shougo/denite.nvim/issues/434.
@delphinus explain me the bug at the issue page.

Markdown: ignore GFM codeblock

---

Units/parser-cpreprocessor.r/backslash-in-parameters.d/args.ctags
Units/parser-cpreprocessor.r/backslash-in-parameters.d/expected.tags
Units/parser-cpreprocessor.r/backslash-in-parameters.d/input.h
parsers/cpreprocessor.c

Close #2118 partially.
Such backslashes can cause emitting a tag having newlines in its
signature field.

CPreProcessor: handle backslash escaping in a parameter list of a macro

---

Tmain/list-roles.d/stdout-expected.txt
Units/parser-perl.r/perl-module.d/args.ctags
Units/parser-perl.r/perl-module.d/expected.tags
Units/parser-perl.r/perl-module.d/input.pl
Units/simple-moose.d/args.ctags
Units/simple-moose.d/expected.tags
Units/simple-moose.d/input-0.pl
parsers/moose.c
parsers/perl.c
parsers/perl.h

Close  #2103.
The design discussion was done at #2070.
To support Moo extension in Moose parser, I made perl parser captures module names specified in use build-in function and no built-in function. (I don't touch `require` in this commits because it is not needed to support Moo. However, we can add it to our TODO list.)
Module names are captured as reference tags. So if we don't pass --extras=+r and --kinds-Perl=+m options, the module names are never printed.

Perl,Moose: support Moo extension in Moose parser

---

man/ctags.1.rst.in

This patch fix some spelling typo in ctags.1.rst.in

docs : Fix typos in ctags.1.rst.in

---

parsers/json.c

Suggested by @hanwen in #2111.

JSON: don't use macros to limit recursions

---

circle.yml
main/entry_private.c
main/tokeninfo.c
main/trace.c
makefiles/testing.mak
misc/src-check
parsers/typescript.c

make codecheck runs misc/src-check.
I added a function detecting CRCRLF sequence at the eof win32 build scripts to misc/src-check.
I made the codecheck target is run on fedora_bmake combination run at circlci,

Check eof chars of vcxproj files at circleci

---

parsers/nsis.c

Close #2144.
Quoted from #2144:
============================================================
@masatake commented 18 hours ago
------------------------------------------------------------
@eht16, I imported your NSIS parser from Geany to Universal-ctags.
After merging, I noticed the version of GPL was not written explictly:
*   This source code is released for free distribution under the terms of the
*   GNU General Public License.
Can I change this to
*   This source code is released for free distribution under the terms of the
*   GNU General Public License version 2 or (at your option) any later version.
?
@eht16 commented 6 hours ago
------------------------------------------------------------
Yes, that's fine by me.
Thanks for taking care.

NSIS,comment: write the version of GPL explicitly

---

win32/appveyor.bat

* Reduce time to install packages.
* Make CI fail if fail to generate docs.
(Both are mainly for ctags-win32 project.)

Refine AppVeyor

---

mk_mingw.mak

They are not needed anymore.
Also update the `clean` target.

buildsys,mingw: Remove git-submodule commands

---

win32/ctags_vs2013.vcxproj

VC2013 or later has stdbool.h. No need to define `bool` by ourself.
This suppresses the following warnings:
```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdbool.h(10): warning C4005: 'bool' : macro redefinition [C:\projects\ctags\win32\ctags_vs2013.vcxproj]
command-line arguments :  see previous definition of 'bool'
```

win32: Remove boolean definitions

---

win32/appveyor.bat

Creating PDF fails on AppVeyor:
https://ci.appveyor.com/project/universalctags/ctags-win32/builds/26091558
Only html files are needed.

appveyor: Make only html for the man pages

---

makefiles/testing.mak
misc/mini-geany.expected

Close #2143.
To GEANY team:
`D/macroparam` is added to C and CPreprocessor parsers.
See geany/geany/2227.

[GEANY] tlib: fix the way to detect a failre of test case

---

.travis.yml

travis: specify libxml2-dev explicitly as a required package

---

Units/parser-typescript.r/ts-class-white.d/args.ctags
Units/parser-typescript.r/ts-class-white.d/expected.tags
Units/parser-typescript.r/ts-class-white.d/input.ts
Units/parser-typescript.r/ts-class.d/args.ctags
Units/parser-typescript.r/ts-class.d/expected.tags
Units/parser-typescript.r/ts-class.d/input.ts
parsers/typescript.c

Typescript parser now handles properly multiple interface names in `implements` part of class declaration. Additionally outputs `inherits` field with all class and interface names used by the class.
Fixes #2178 
@masatake Class declarations using templates like `class A<T> implements I<T>` IMHO should output only class/interface name without parameters. They can be very complicated and long and I can't think of anything they could be used for (when putting them also in  `inherits` field).

Typescript: parsing multiple interface names in implements part

---

Units/parser-typescript.r/ts-function-variable-white.d/expected.tags
Units/parser-typescript.r/ts-function-variable-white.d/input.ts
Units/parser-typescript.r/ts-function-variable.d/expected.tags
Units/parser-typescript.r/ts-function-variable.d/input.ts
parsers/typescript.c

Typescript: fixed parsing variables with `as` keyword

---

Units/parser-cxx.r/functions.cpp.d/expected.tags
Units/parser-cxx.r/functions.cpp.d/input.cpp
Units/parser-cxx.r/template-specializations.d/expected.tags
Units/parser-cxx.r/template-specializations.d/input.cpp
parsers/cxx/cxx_parser_block.c
parsers/cxx/cxx_parser_function.c

Improve matching of template specializations.
Avoid matching throw statements even if state is wrong.
Fixes #2181

CXX: Improve function signature matching

---

Units/parser-css.r/css-simple.d/expected.tags
Units/parser-css.r/css-simple.d/input.css
parsers/css.c

`~' is a combinator as described in
https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_combinator

CSS: accept ~ char as a part of a selector

---

win32/appveyor.bat

The rst2html3 command from the python3-docutils package was renamed to
rst2html a few weeks ago. No need to set RST2HTML variable anymore.
An error occurs without this fix:
https://ci.appveyor.com/project/universalctags/ctags-win32/builds/27311853/job/bu0ignl4x15w473g#L1177

appveyor: Use rst2html instead of rst2html3

---

main/routines.c

absoluteFilename() always returned C: drive when compiled with MinGW.
MinGW also has _getdrive(), so use it.

main,win32: Use _getdrive() also on MinGW

---

docs/tips.rst
makefiles/testing.mak
misc/travis-check.sh

Close #2057.
Specifying --enable-coverage-gcov option when running configure is
enough.
Suggested by @blueyed.

buildsys: remove COVERAGE make parameter

---

docs/optlib.rst

Close #2033.
The old document refers PRELOAD_OPTLIB variable in Makefile.in.
OPTLIB2C_INPUT in makefiles/testing.mk makes the variable obsolete.
Suggested by @dreamtigers in #2033.

Update the way to incorporate an optlib parser to ctags build process

---

circle.yml

circleci: enable AppStream repository when buindling on CentOS8

---

Tmain/list-fields-with-prefix.d/stdout-expected.txt
Tmain/list-fields.d/stdout-expected.txt
Units/parser-c.r/macrodef.d/args.ctags
Units/parser-c.r/macrodef.d/expected.tags
Units/parser-c.r/macrodef.d/input.c
Units/parser-cpreprocessor.r/macrodef.d/args.ctags
Units/parser-cpreprocessor.r/macrodef.d/expected.tags
Units/parser-cpreprocessor.r/macrodef.d/input.h
main/entry.h
parsers/asm.c
parsers/c.c
parsers/cpreprocessor.c
parsers/cpreprocessor.h
parsers/cxx/cxx_parser.c
parsers/cxx/cxx_tag.c
parsers/cxx/cxx_tag.h
parsers/dts.c
parsers/ldscript.c
parsers/protobuf.c

Currently, saveMacro feature can be used from command line (-D option).
I'm thinking about using it from CPreProcessor parser itself.
This is the first step to implement the idea.
With this patch, entries for macros can have "signature" and "macrodef" fields.
It is enough to make arguments passed to saveMacro.

Cxx: add a field for recording macro definition to macro kind

---

win32/appveyor.bat

Copy man/*.rst to docs/man/ before building html files, because Git for
Windows doesn't handle symlinks by default.

appveyor: Copy man/*.rst before building html files

---

docs/windows.rst

These packages are needed to build a full-featured version for Cygwin.

docs: Write about Cygwin packages

---

Tmain/lregex-unexpected-regex-kind.d/X.ctags
Tmain/lregex-unexpected-regex-kind.d/Y-r-regex-with-kinddef.ctags
Tmain/lregex-unexpected-regex-kind.d/Y-r-regex.ctags
Tmain/lregex-unexpected-regex-kind.d/Y-r.ctags
Tmain/lregex-unexpected-regex-kind.d/Y-regex.ctags
Tmain/lregex-unexpected-regex-kind.d/Yempty1.ctags
Tmain/lregex-unexpected-regex-kind.d/Yempty2.ctags
Tmain/lregex-unexpected-regex-kind.d/Ynokind.ctags
Tmain/lregex-unexpected-regex-kind.d/input.yyy
Tmain/lregex-unexpected-regex-kind.d/run.sh
Tmain/lregex-unexpected-regex-kind.d/stderr-expected.txt
Tmain/lregex-unexpected-regex-kind.d/stdout-expected.txt
main/lregex.c

Close #2202.
If a kind is not specified explicitly in --regex-<LANG> option, r/regex kind is used.
This feature comes from Exuberant-ctags.
Universal-ctags extends the option heavily. As the result, the way to handling r/regex in u-ctags had various inconsistencies.
This PR revises the code related to the fallback r/regex kind feature.

Fix unexpected regex kind in list kinds

---

Units/parser-powershell.r/simple-powershell.d/args.ctags
Units/parser-powershell.r/simple-powershell.d/expected.tags
Units/parser-powershell.r/simple-powershell.d/input.ps1
docs/news.rst
main/parsers_p.h
parsers/powershell.c
source.mak
win32/ctags_vs2013.vcxproj
win32/ctags_vs2013.vcxproj.filters

This pull request adds one of the extra parsers we have in Geany except
those defined in c.c and except the markdown parser which is readLine()
based and not really superior to the regex-based parser ctags uses
(we should probably use the ctags parser in Geany instead).
The added a parser is for PowerShell (https://en.wikipedia.org/wiki/PowerShell)
The original version is written for Geany by Enrico Tröger <enrico.troeger@uvena.de>:
commit 8a6fbd978691fa324bd5c5ff171bcd508e3b466c
Author: Enrico Tröger <enrico.troeger@uvena.de>
Date:   Sat Apr 25 16:17:03 2015 +0200
Add PowerShell tag parser
@masatake did when merging:
* edit this message,
* replace -1, the value representing unknown kind with
KIND_GHOST_INDEX, and
* extend the original test case for testing signature.
Known issue:
* …

PowerShell: new parser imported from Geany

---

man/ctags.1.rst.in

The parameter `=N` was missing from the `--maxdepth` option.

man: Add a missing parameter

---

win32/ctags_vs2013.vcxproj.filters

Reported by @k-takata in #2228.

win32: fix the wrong entry for powershell.c in ctags_vs2013.vcxproj.filters

---

misc/dist-test-cases

Use `git ls-tree` and `git ls-files .` and stop using `sed`.
This makes the script faster especially on Cygwin/MSYS2.
Note that fork(2) is very slow on Cygwin/MSYS2, so reducing the
execution of processes from a script makes it much faster.
Before:
$ time ./misc/dist-test-cases
real    1m3.455s
user    0m15.465s
sys     0m38.575s
After:
$ time ./misc/dist-test-cases
real    0m19.584s
user    0m2.973s
sys     0m8.444s

buildsys: Make dist-test-cases simpler and faster

---

misc/units

`units` is really slow on Cygwin/MSYS2.
This makes it faster. (About 3.5x on my environment.)
* Reduce execution of external processes.
* Run `units` and `tmain` in parallel.
- Use `&` and `wait`.
- Use temporary files to store the results.
- Display the result in a single command to avoid the output being mixed.
* Use bash's pattern matching instead of echo + grep. (Not sure this is accepted.)
Additionally, this supports `make units CATEGORIES=ROOT`.

units: Make units faster

---

Units/parser-cxx.r/cxx-keywords-as-c-identifiers.b/input.c

`parser-cxx.r/cxx-keywords-as-c-identifiers` had two input files: `input.c` and `input.h`.
This causes the test being executed twice. Actually, `input.c` is not used. So, delete it.
(Found while implementing #2240.)

units: Don't test parser-cxx.r/cxx-keywords-as-c-identifiers twice

---

win32/appveyor.bat

Currently, these features are not enabled. Enable them.

appveyor: Enable jansson, libxml2 and libyaml on Cygwin

---

Makefile.am

Packcc's documents were not included in the distribution.
Some files in man/ were also missing.

buildsys: Add some files to EXTRA_DIST
