configure.ac
Program name and version were shown on top of configure command a few
years ago. (Maybe, before #497.)
Bring them to the top again.
E.g.
Before:
$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '197609' is supported by ustar format... yes
checking whether GID '197609' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-pc-cygwin
checking host system type... x86_64-pc-cygwin …
=> buildsys: Show program name and version on top of configure command

main/main.c, main/routines.c
It seems that mkstemp() (from MinGW-w64) sometimes fails with permission
error or some other reasons, especially when running multiple commands
in parallel.
mkstemp() uses rand() but srand() was not called in our code.
Initialize srand() and retry mkstemp() several times as a workaround.
See https://github.com/universal-ctags/ctags/pull/2240#issuecomment-544528511.
=> main,win32: Work around that sometimes mkstemp() fails

configure.ac, gnu_regex/regex_internal.c, gnu_regex/regexec.c, main/e_msoft.h, main/gcc-attr.h, main/lregex.c, main/routines.c
There are several warnings when compiled with MinGW:
https://ci.appveyor.com/project/universalctags/ctags/builds/27959476/job/7xggnuxg5wf97wqh#L673
This suppress some of the warnings.
* Check the existence of direct.h for `_getdrive()`.
* Don't redefine `stat`.
* Use proper size for printf format string.
=> main,win32: Suppress MinGW warnings

misc/units
NOTE: units.py may come in soon, this change for the original units shell script is not so meaningful.
zsh expects the operand of =~ operator inside [[ ... ]] to be quoted.
bash doesn't.
To fill the gap between zsh and bash, this change stores the
regex pattern to a variable, and refers the variable as
the operand.
=> units: store regex pattern to variable

docs/units.rst
* Add headings about Test facility and Units facility.
* Fix the filename of `Units/TEST/filter`. `filter-*.*` are not supported.
=> docs: Update units.rst

misc/dist-test-cases
Creating many Makefiles slows down `./configure` especially on Cygwin/MSYS2.
Reduce the number of Makefiles to avoid it. Create only in `*.r` directories.
This has a potential risk that it may cause #1952 again.
I don't know how many files are accepted in one Makefile.
=> buildsys: Don't make Makefiles for each *.d directory

configure.ac, docs/windows.rst, win32/appveyor.bat
Support static linking on MinGW.
Actually, we can enable static linking even without this PR, however, many options are needed for that.
This PR makes it easy.
=> buildsys: Add --enable-static option to ./configure

Tmain/utils.sh, misc/units
`filter_by_column_index` function is really slow on Cygwin/MSYS2.  This
is used by the test `option-extras-enabling-all` and it takes about 15
seconds in my environment.  Use awk if available.  Now it takes less
than 2 seconds.
=> Tmain: Speed up filter_by_column_index

.editorconfig, makefiles/optlib2c_input.mak, source.mak
Makefiles were not well aligned. `source.mak` already has a modeline: `# vim: ts=8`.
So, it would be better to use tabsize=8 for all Makefiles for consistency.
Set `indent_size=8` in `.editorconfig` and align the Makefiles with that setting.
=> makefiles: Align with tabsize=8

parsers/html.c
Initialize the variables to suppress warnings.
This fixes #1496.
=> parsers: Suppress warnings

win32/appveyor.bat
Also remove `--enable-iconv`, because now it is the default.
=> appveyor: Use `make -j2` to speed up the builds

main/lregex.c
=> main: Remove dead initialisation in lregex

parsers/rust.c
=> parsers: Prevent garbage assignment

main/lregex.c
Markdown regex based parser used `guest` flag.
This fix the bug of guest flag implementation.
Markdown parser runs a guest parser for the area surrounded with
```...```. If the language for the area is specified explicitly
like the following example, ctags works fine:
```C
int main(void) { return 0; }
```
"C" is specified in the example.
However, if the language is not specified explicitly like the following
example, a core dump may occur because referring a wrongly set value:
```
int main(void) { return 0; }
```
Even if the core dump doesn't occur on a platform, valgrind reports
a wrong memory access.
(Based on #2261, @masatake wrote this commit log.)
=> lregex: fix lang_set to avoid core dump

Units/parser-cpreprocessor.r/macro-signature-with-subword-extra.d/args.ctags, Units/parser-cpreprocessor.r/macro-signature-with-subword-extra.d/expected.tags, Units/parser-cpreprocessor.r/macro-signature-with-subword-extra.d/input.h, main/entry.c, main/entry.h, parsers/cpreprocessor.c
Close #2275.
During gathering macro parameters for making the signature field of
macro, ctags can emit tags for subword extra. These subword extra tags
make the signature field broken.
Only non-extra tags should be gathered for making the signature field.
isTagExtra helper function is introduced to filter non-extra tags
from the cork queue.
=> main,CPreProcessor: don't include extra tags to macro signature field

misc/units.py
Make run_shrink() fallback to shell script version of misc/units.
Related: https://github.com/universal-ctags/ctags/pull/2240#issuecomment-547760119
=> units: Implement run_shrink()

docs/man/ctags-incompatibilities.7.rst, docs/man/ctags-optlib.7.rst, docs/man/ctags.1.rst, docs/man/tags.5.rst, man/Makefile, misc/travis-check.sh, win32/appveyor.bat
Fix the issue in https://github.com/universal-ctags/ctags/pull/2213#issuecomment-536358592.
Replace the placeholders like `@CTAGS_NAME_EXECUTABLE@` with `ctags` and
so on, so that the man pages can be shown correctly on the Web site.
The files under docs/man/ need to be updated manually:
```
$ make -C man QUICK=1 update-docs
```
So a checker for that is added to Travis CI.
Now the docs/man/ files are not symlinks, so they can be correctly
handled on Windows. A workaround on AppVeyor is not needed.
=> docs,man: Commit generated man files into docs/man/

configure.ac, main/e_msoft.h, main/general.h, main/routines.c, main/sort.c, main/stats.c, main/vstring.h
We already use C99. We can assume that C90 standard headers, macros and functions are always available.
Stop checking:
* errno.h, limits.h, stdlib.h, string.h, time.h.
Also stop checking sys/times.h because we can use time.h.
* INT_MAX from limits.h, fpos_t from stdio.h, clock_t from time.h,
size_t from stddef.h.
* fgetpos() from stdio.h, clock() from time.h, malloc() from stdlib.h,
getenv() from stdlib.h, remove() from stdio.h.
* Also remove out dated comments: AC_CYGWIN, AC_MINGW32.
Still keep checking stdbool.h (C99), because HAVE_STDBOOL_H is used in gnu_regex.
=> buildsys: Stop checking C90 standard headers

circle.yml, misc/units
Use older Fedora instead.
It seems that mk-files package required by bmake package
is not available in the latest Fedora dnf/yum repository.
We always got following error message:
dnf -y install gcc automake autoconf pkgconfig bmake aspell-devel aspell-en libseccomp-devel libxml2-devel jansson-devel libyaml-devel findutils
dnf -y install jq puppet
Last metadata expiration check: 0:00:53 ago on Wed Oct 30 14:38:43 2019.
Package gcc-9.2.1-1.fc31.x86_64 is already installed.
Package pkgconf-pkg-config-1.6.3-2.fc31.x86_64 is already installed.
Error:
Problem: conflicting requests
- nothing provides mk-files needed by bmake-20180512-4.fc31.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
Exited with code 1
=> circleci: temporary disable fedora:latest and bmake combination

docs/man/ctags.1.rst, man/ctags.1.rst.in
=> man: Fix typo

misc/units.py
Cygwin python cannot handle "c:/path" style path in os.path.realpath().
This causes `SameFileError` when try to copy bundle files.
Use os.path.samefile() to check if two directories are the same.
=> units: Fix SameFileError on Cygwin

Tmain/abnormal-output-file-names.d/run.sh, Tmain/c-anon-counter.d/run.sh, Tmain/e-ctags-output.d/run.sh, Tmain/interactive-resource-management.d/run.sh, Tmain/invalid-encoding-option.d/run.sh, Tmain/languages-and-language-force-options.d/run.sh, Tmain/lregex-unexpected-regex-kind.d/run.sh, Tmain/no-input-encoding-option.d/run.sh, Tmain/output-file-resource-management.d/run.sh, Tmain/output-file-resource-management.d/stdout-expected.txt, Tmain/sorted-help-message.d/run.sh, Tmain/sorted-list-languages.d/run.sh, Tmain/tag-relative-option-in-etags.d/run.sh, Tmain/utils.sh, misc/tlib, misc/units.py
`make distcheck` sets the source directories readonly. So, temporary files or output files should be written in $BUILDDIR. Otherwise, tests will fail with permission errors.
`make distcheck` is important when we create a release.
=> Tmain: Fix `make distcheck`

Makefile.am, circle.yml
This is an additional PR to #2297.
This fixes:
* Failed to update peg/varlink.[ch]. Generate them in the builddir instead.
* The generated peg/*.[ch] files were distributed. No need to distribute them.
* optlib/*.c were left behind after `make (dist)clean`. Delete them with `make clean`.
* Use fedora:latest to check `make distcheck`.
=> buildsys: Fix `make distcheck`

docs/news.rst
* No need to focus on Japanese. Remove the sentence.
I, as a Japanese, felt that this sentence was to specific to Japanese.
* Mention UTF-8 and some other actual encodings.
=> docs(web): Rephrase introduction about --input-encoding

Makefile.am
packcc includes initial declarations in for loops, but does not inherit EXTRA_CFLAGS (and notably -std=gnu99) as found by autotools, unlike ctags.
As such, if the compiler uses a C<99 standard by default, [packcc's build breaks](http://build-failures.rhaalovely.net/sparc64/2019-11-07/devel/universal-ctags.log)
I'm just proposing to add EXTRA_CFLAGS to packcc_CFLAGS.
=> packcc: add EXTRA_CFLAGS to packcc_CFLAGS

autogen.sh
=> buildsys: Suppress messages from type command

man/ctags.1.rst.in
There are some options missing from the man page.
This PR adds them.
Some explanations are copied from news.rst.
(@masatake This is still WIP, and I pushed this to this repository (not mine) so that you can also update this branch.)
=> man: Write about missing options

Makefile.am
When shadow builds are used on MSYS2, packcc fails to read *.peg file.
It seems that MSYS's make uses `\` for directory separator on some
conditions. In such situation, a command `./packcc ..\peg\varlink.peg`
is executed, and `\` is considered as an escape character. Then the
command is interpreted as `./packcc ..pegvarlink.peg`, and it fails.
(Derived from #2302.)
=> buildsys: Fix that packcc may fail on MSYS2

Makefile.am
No need to distribute them.
Remove them from PARSER_SRCS and PARSER_HEADS.
=> buildsys: Fix that peg/varlink.[ch] were still distributed

docs/man/ctags.1.rst, man/ctags.1.rst.in
Fix the following error:
```
RST2MAN   man/ctags.1
man/ctags.1.rst:1454: (ERROR/3) Unexpected indentation.
```
=> man: Fix error after #2259

parsers/scheme.c
Addressing #1877 by adding support for the `.rkt` extensions. Change is simple because syntax is the same. Tested locally on some Racket source.
=> scheme: Add racket support to scheme parser

parsers/c.c, parsers/cpreprocessor.h, parsers/protobuf.c
These parsers themselves don't need the corkQueue directly.
However, they call cpreproparser parser that needs the corkQueue for
capturing macro arguments. So this change sets useCork field of callers
Without setting the field, the parsers may crash with input, "#define foo(x)",
when capturing `x`. "make fuzz" can reproduce the crash.
Ideally, the setting for the parsers is done automatically.
=> Protobuf,D,C#,Vera: use cork

makefiles/testing.mak
1 second is too short for mtable parsers tagging long input.
=> fuzz: extend the timeout of execution to 10 secs

misc/units.py
@k-takata I found this problem trying the new vala parser.
I guess is related with a buggy implementation as vala parser actually SIGSEV.
=> Fix typo in units python script

Tmain/broken-langdef.d/input.c, Tmain/broken-langdef.d/run.sh, Tmain/broken-langdef.d/stderr-expected.txt, docs/man/ctags-incompatibilities.7.rst, docs/man/ctags-optlib.7.rst, main/parse.c, man/ctags-incompatibilities.7.rst.in, man/ctags-optlib.7.rst.in, misc/optlib2c
All changes about --langdef option.
The main change is for rejecting characters like @, $, % as a parser name.
=> Reject more non alnum chars in langdef

docs/man/ctags-incompatibilities.7.rst, docs/man/ctags-optlib.7.rst, docs/man/ctags.1.rst, docs/man/tags.5.rst, man/Makefile
Add links to ctags(1), ctags-incompatibilities(7), ctags-optlib(7) and
tags(5). This is only useful on ./docs/man/, not useful on ./man/, so convert them
when running `make update-docs`.
=> man(web): Add links to each man page on the Web site

docs/conf.py
`--` is used for command line options. Sphinx transforms it to an en-dash (U+2013) which is incorrect. Disable the transformation.
See:
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-smartquotes_action
=> docs(web): Don't transform `--` into an en-dash

docs/man/ctags-optlib.7.rst, docs/man/tags.5.rst, man/ctags-optlib.7.rst.in, man/tags.5.rst
Use double backquotes to quote a backslash to avoid incorrect markup.
=> docs,man: Fix markup

main/options.c
`--use-slash-as-filename-separator` has a parameter (yes or no).
Also remove unnecessary empty line.
=> main: Update help for --use-slash-as-filename-separator

man/Makefile
This revises #2347.
Use ${} instead of $() for function calls so that parentheses can be used for parameters.
Also adjust alignment and spacing.
=> buildsys: Simplify man/Makefile

man/Makefile
sed implementation in MacOS doesn't understand '\|'.
To avoid using '\|', this change expands 'A\|B' to "-e A -e B".
=> docs(web), docs(man): don't use '\|' in a pattern for sed when making hyperlinks

.gitignore, Makefile.am, configure.ac, misc/src-check, misc/travis-check.sh, mk_mingw.mak, mk_mvc.mak, win32/ctags.exe.manifest, win32/ctags.rc, win32/ctags_vs2013.vcxproj, win32/ctags_vs2013.vcxproj.filters, win32/resource.h
This adds version resource and application manifest to the win32 executable file.
`win32/ctags.rc` and `win32/resource.h` are created by VS2013 and edited manually.
The application manifest should fix the issue #1837 on Windows 10 version 1903 or later.
See: https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page
This is a relatively new feature in Windows and it might not be matured enough, but at least I confirmed that ctags.exe can handle Unicode file names on Windows 10 1909.
NOTE: the version number needs to be updated manually.
We have version numbers in several files: `configure.ac`, `docs/conf.py`, `main/ctags.h`, `win32/ctags.exe.manifest` and `win32/ctags.rc`. (The last two files are added in this PR.)
We need to update all of them, when we release a …
=> win32: Add version resource and manifest

misc/travis-check.sh
Like docs/man/\*.[0-9], code genereated by optlib2c must be added to our
git repository. This allows building ctags where optlib2c written in
perl cannot to be run. To avoid merging commits including only changes
for optlib/\*.ctags, this change introduces code for verifying
optlib/\*.c is also included in the commits.
Close #2358.
See also #2355.
=>  buildsys,travis: verify code genereated by optlib2c is added to commits 

win32/ctags.rc
Just a cosmetic change. Use copyright mark © instead of (C) in the properties dialog box.
Before this fix:
After this fix:
=> win32: Use copyright mark on properties dialog box

Makefile.am
The RST2MAN lines in the output of make were not well aligned:
```
CC       peg/libctags_a-varlink.o
AR       libctags.a
WINDRES    win32/ctags.res.o
CCLD     ctags.exe
CCLD     mini-geany.exe
RST2MAN   man/ctags.1
RST2MAN   man/ctags-incompatibilities.7
^
```
This should be:
```
CC       peg/libctags_a-varlink.o
AR       libctags.a
WINDRES    win32/ctags.res.o
CCLD     ctags.exe
CCLD     mini-geany.exe
RST2MAN    man/ctags.1
RST2MAN    man/ctags-incompatibilities.7
```
=> buildsys: Align the output of make

Units/parser-cxx.r/cxx11-attributes.cpp.d/args.ctags, Units/parser-cxx.r/cxx11-attributes.cpp.d/expected.tags, Units/parser-cxx.r/cxx11-attributes.cpp.d/input.cpp, parsers/cxx/cxx_parser_tokenizer.c
Second attempt based on @Masatake's idea.
We skip C++11 attributes at tokenizer level so they don't bother the parser at all.
By the way we decode a couple of them just like in the __attribute__(()) case.
=> CXX: Handle C++11 attributes. Fixes bug #2364

main/tokeninfo.h, parsers/tcl.c, parsers/tcloo.c
Define some new macros accessing fields of tokenInfo data type.
I found they were useful when prototyping a vala parser with tokenInfo in #621.
=> Extend tokeninfo API

man/Makefile, misc/travis-check.sh
We tracked the strange result about the code verifying the rst files under docs/man are committed.
fc7e236 is for fixing the issue.
Without fc7e236,  in some cases, "make -C man QUICK=1 update-docs" does nothing.
As the result, the code using "git diff --exit-code docs/man" reports "o.k." though it is not o.k.
I guess it is related to low resolution of timestamp of the file system. (This never happens on GNU/Linux.)
This behaviour hides '\<' used in sed command line is not portable.
c6b9a4c defines an alternative regular expression that can be used in BSD sed.
TODO: We should drop the support for BSD make. We already use enough GNU make features. We cannot go back. We can utilize autotools for fixing part of issues. However, it is impossible to put our man pages to our web site with …
=> travis: sed command line for macos

man/Makefile
It seems that older rst2man doesn't have --syntax-highlight option.
Close #2374.
=> build-sys,man: pass --syntax-highlight only if rst2man accepts

Makefile.am, configure.ac
This change is similar to 7cf97016d7e5b0b4e9cec9511fa7a60e5f76c7d1.
7cf97016d7e5b0b4e9cec9511fa7a60e5f76c7d1 is for 'make -C man QUICK=1'.
This one handles the case for QUICK != 1.
Suggested by @songouyang in #2374
Close #2374 again.
=> build-sys,docs(man): check whether --syntax-highlight option of rst2man is available or not

Tmain/list-roles.d/stdout-expected.txt, Units/parser-python.r/python-dot-in-import.d/expected.tags, Units/parser-python.r/python-import.d/expected.tags, main/kind.c, main/options.c, misc/optlib2c, parsers/python.c
Close #1711.
An assert macro is introduced for the purpose.
Python had a role name "indirectly-imported". This violated the new limitation.
So I renamed it to "indirectlyImported".
=> [INCOMPATIBLE in Python] Limit the characters that can be used in a role name

main/lregex.c
Partially close #2369.
A pointer to unsigned int variable is passed to functions expecting
a pointer to unsigned long variable.
This didn't cause a trouble because the sizes of the types are the
same on x86_64, the most popular platform. However, on s390x, they
are different, and cause a trouble as reported in #2369.
=> lregex: fix meaningless type mismatching between unsigned int and unsigned long

Units/parser-cxx.r/typedefs.cpp.d/expected.tags, Units/parser-cxx.r/typedefs.cpp.d/input.cpp, parsers/cxx/cxx_parser_typedef.c
Fixes #2394 .
typeref is currently missing. Not sure if it's worth to add it as it would require some bits of complexity.
=> CXX: Handle non-pointer function typedefs

Tmain/xref-ptag-in-list-extras.d/stdout-expected.txt, Units/ptag-xref.d/args.ctags, Units/ptag-xref.d/expected.tags-x, Units/ptag-xref.d/input.c, main/entry.h, main/field.c, main/parse.c, main/writer-ctags.c, main/writer-json.c, main/writer-xref.c, main/writer.c, main/writer_p.h, main/xtag.c
```
$ u-ctags --extras=+p -x input.c
!_TAG_FILE_FORMAT ptag          0 2                extended format; --format=1 will not append ;" to lines
!_TAG_FILE_SORTED ptag          0 1                0=unsorted, 1=sorted, 2=foldcase
!_TAG_OUTPUT_FILESEP ptag          0 slash            slash or backslash
!_TAG_OUTPUT_MODE ptag          0                  u-ctags or e-ctags
!_TAG_PROGRAM_AUTHOR ptag          0 Universal Ctags Team
!_TAG_PROGRAM_NAME ptag          0 Universal Ctags  Derived from Exuberant Ctags
!_TAG_PROGRAM_URL ptag          0 https://ctags.io/ official site
!_TAG_PROGRAM_VERSION ptag          0 0.0.0            da9919d2
main             function      1 input.c          int main (void)
```
Suggested by @amerlyq in #2407.
=> main: display pseudo tags in xref output if requested

parsers/systemdunit.c
A ".scope" is always generated dynamically.
There is no unit file for it.
".time" may be a typo. No such unit.
=> systemd: fix the list of file name extensions

Tmain/kinds-all-with-spec.d/input.c, Tmain/kinds-all-with-spec.d/run.sh, Tmain/kinds-all-with-spec.d/stderr-expected.txt, Tmain/kinds-all-with-spec.d/stdout-expected.txt, docs/man/ctags.1.rst, main/parse.c, man/ctags.1.rst.in
The option accepted only '*'.
With this change, you can print all parser files like:
$ ./u-ctags --kinds-all=F --extras=+f -o - -R ./
.dir-locals.el	./.dir-locals.el	1;"	F	language:Lisp
.dir-locals.el	./cxx-token-based-backtrack/.dir-locals.el	1;"	F	language:Lisp
.gdbinit	./.gdbinit	1;"	F	language:Gdbinit
...
=> main: allow to specify F/file kind as an argument for --kinds-all option

Units/parser-go.r/github-issue-2430.d/README, Units/parser-go.r/github-issue-2430.d/args.ctags, Units/parser-go.r/github-issue-2430.d/input.go, parsers/go.c
Close #2430.
Nowadays, Go parser accesses corkIndex various way to fill fields.
On the other hand, makeTagFull checks whether the kinds of Go
is enabled or disabled; if a given kind is disabled, the
function doesn't make a tag for the kind. As the result it returns
CORK_NIL. So CORK_NIL is not suitable for filling the fields.
The main part of ctags has generic layer for doing the same as
the parser; the main part also checks whether a kind assigned to
a tagEntryInfo is enabled or not. For the optimization purpose,
early checking in a parser is good. However, it makes the code
for using cork indexes in parser sides complicated; a parser
must check the value returned from getEnryFromCorkIndex().
=> Go: don't check whether kinds is enabled or no at the parser side

Units/parser-markdown.r/scope-field-markdown.d/expected.tags, Units/parser-markdown.r/simple-markdown.d/expected.tags, misc/optlib2c, optlib/markdown.c, optlib/markdown.ctags
Close #2434.
I introduced " as the scoped separator mistakenly. This should be  "".
NOTE: Using full qualified tag names in scope fields is still debatable.
=> Markdown: use two dquotes as scope separator

misc/units.py
A cmdline template including the original input file was passed to shrinker.
It prevented the shrinker from working.  The shrinker doesn't need it
because it generates temporary input files and uses them.
=> units.py: don't include the input file name to the cmdline template passed to shrinker

main/htable.c, main/htable.h
These are spin-off code developed during studying symbol tables before introducing rbtree.
These are not used anywhere, however, they may be useful in the future for u-ctags development.
* a callback function passed to hashTableForeachItem can break the interation.
* a new function hashTableForeachItemOnChain is for handling entries having the same key.
=> main: extend hashtable api

Tmain/list-roles.d/stdout-expected.txt, Units/parser-rpmspec.r/simple-rpmspec.d/expected.tags, Units/parser-rpmspec.r/simple-rpmspec.d/input.spec, main/entry.c, main/entry.h, parsers/autoconf.c, parsers/autoconf.h, parsers/rpmspec.c, source.mak, win32/ctags_vs2013.vcxproj, win32/ctags_vs2013.vcxproj.filters
Autconf parser captures:
ctags-libexecdir in "AC_ARG_WITH([ctags-libexecdir]," as optwith kind and
tmpdir in "AC_ARG_ENABLE(tmpdir," as optenable kind.
These are captured as definitions tags.
This change is about reference tags for the kinds.
./configure script is invoked various places.
One of typical place is RPM spec file.
RPS spec files have a special notation (macro) for invoking
configure script: %configure ....
This change in RpmSpec parser scans the %configure lines.
If --enable-foo/--disable-bar/--with-baz/--without-bazz are
passed to %configure lines, the RpmSpec parser captures
foo/bar/baz/bazz as reference tags of optwith or optenable
kinds.
=> RpmSpec,Autoconf: parse %configure options 

Units/parser-tcl.r/signature.d/args.ctags, Units/parser-tcl.r/signature.d/expected.tags, Units/parser-tcl.r/signature.d/input.tcl, parsers/tcl.c
This change does
* capture a, b, and c in "proc f {a b c} ..." as parameter kind tags, and
* attach "signature:{a b c}" to the tag of f.
'{' as the scope separator combining proc and parameter.
=> Tcl: capture proc parameters and fill signature field

Units/parser-cxx.r/namespace-and-preprocessor.cpp.d/args.ctags, Units/parser-cxx.r/namespace-and-preprocessor.cpp.d/expected.tags, Units/parser-cxx.r/namespace-and-preprocessor.cpp.d/input.cpp, parsers/cxx/cxx_parser_namespace.c
Fixes parsing of Qt's qnamespace.h and similar.
=> CXX: Fix cpp branching in the namespace statement. 

Makefile.am, Tmain/readtags-list-pseudo-tags.d/ptag-sort-no.tags, Tmain/readtags-list-pseudo-tags.d/ptag-sort-yes.tags, Tmain/readtags-list-pseudo-tags.d/run.sh, Tmain/readtags-list-pseudo-tags.d/stdout-expected.txt, docs/news.rst, libreadtags/.circleci/config.yml, libreadtags/.gitignore, libreadtags/Makefile.am, libreadtags/configure.ac, libreadtags/libreadtags.pc.in, libreadtags/readtags.c, libreadtags/readtags.h, libreadtags/tests/Makefile.am, libreadtags/tests/api-tagsOpen-ectags.tags, libreadtags/tests/duplicated-names--sorted-foldcase.tags, libreadtags/tests/duplicated-names--sorted-no.tags, libreadtags/tests/duplicated-names--sorted-yes.tags, libreadtags/tests/duplicated-names.c, libreadtags/tests/ptag-sort-no.tags, libreadtags/tests/ptag-sort-yes.tags, libreadtags/tests/test-api-tagsFind.c, libreadtags/tests/test-api-tagsFirstPseudoTag.c, libreadtags/tests/test-api-tagsOpen.c, misc/pull-libreadtags.sh, readtags-cmd/readtags-cmd.c
This pull request adds -D option to readtags.
With -D option, readtags can dump all the pseudo tags including newly introduced ones in u-ctags.
Behind the -D option, the API of libreadtags is extended. The extended API is must for implementing multi-pass parsers.
=> readtags: extend api for pseudo tags

readtags-cmd/readtags-cmd.c
See #2471.
* reorganize -h output,
* introduce long option (like --help), and
* introduce new option --help-expression for making -h output smaller.
@AmaiKinono, this is the first shot.
About the case-insensitive operator in the Sexp, I will work on a different branch.
=> Revise readtags cmdline interface

Units/parser-ruby.r/ruby-mixin-field.d/expected.tags, Units/parser-ruby.r/ruby-mixin-field.d/input.rb, parsers/ruby.c
The solution developed in https://github.com/universal-ctags/ctags/pull/2478 is extended to deal with "prepend" and "extend" methods.
One thing I've noticed is `include`, `prepend` and `extend` are all methods, so it's valid to write:
``` ruby
class A
prepend(X)
end
``` 
But it's not handled by current scheme.
=> Ruby: extend mixin field

Units/parser-ruby.r/ruby-mixin-field.d/expected.tags, Units/parser-ruby.r/ruby-mixin-field.d/input.rb, parsers/ruby.c
=> Ruby: fix a typo in accessing elements in the mixin spec array

Units/parser-ruby.r/ruby-mixin-field.d/expected.tags, Units/parser-ruby.r/ruby-mixin-field.d/input.rb, main/nestlevel.c, main/nestlevel.h, parsers/ruby.c
* detect method style mixin as suggested in #2481, and
* ignore unnamed blocks like "while", "if", ... when detecting mixing method invocations.
=> Ruby: improve mixin detection

Units/parser-verilog.r/systemverilog-symtab.d/args.ctags, Units/parser-verilog.r/systemverilog-symtab.d/expected.tags, Units/parser-verilog.r/systemverilog-symtab.d/input.sv, main/entry.h, parsers/verilog.c
Close #2413.
The original code could not capture "a" in "mod" in the following input because
the parser didn't recognize "int32_t" before "a" is a name of type:
typedef bit[31:0] int32_t;
module mod(
input bit clk,
input int32_t a
);
endmodule
This change makes the parser look up the cork symbol table when the
parser reads a token with unknown kind. A typedef like int32_t is
stored to the symbol table when making a tag for it. As the result, the
parser can resolve the kind for the token as typedef when parsing
int32_t in "input int32_t a".
=> SystemVerilog: use the symbol table to recognize the types for ports

Units/parser-cxx.r/cxx11enum.cpp.d/expected.tags, Units/parser-cxx.r/end-field-for-prototype-kind.d/args.ctags, Units/parser-cxx.r/end-field-for-prototype-kind.d/expected.tags, Units/parser-cxx.r/end-field-for-prototype-kind.d/input.h, Units/parser-cxx.r/function-return-types.d/expected.tags, Units/parser-cxx.r/functions.cpp.d/expected.tags, parsers/cxx/cxx_parser.c
Close #2474.
```
[jet@living]~/var/ctags% ./ctags --fields=+e --kinds-C++=p -o - ./input.h
main	./input.h	/^main$/;"	p	typeref:typename:int	end:8
[jet@living]~/var/ctags% cat -n input.h                                  
1	int
2	main
3	(
4		int
5		argc,
6		char **
7		argv
8		);
[jet@living]~/var/ctags% ./ctags --fields=+e --kinds-C++=p -o - ./input.h
main	./input.h	/^main$/;"	p	typeref:typename:int	end:8
```
=> Cxx: attach the end: field to a prototype kind tag

Tmain/list-roles.d/stdout-expected.txt, Tmain/tmain-example.d/stdout-expected.txt, Units/parser-ruby.r/ruby-library.d/args.ctags, Units/parser-ruby.r/ruby-library.d/expected.tags, Units/parser-ruby.r/ruby-library.d/input.rb, parsers/ruby.c
With this change, Ruby parser can capture "foo", bar", and "baz.rb" in 
* require "foo",
* require_relative "bar", and
* load "baz.rb"
.
scope files for the tags are not filled because I wonder how they should be.
autoload is not covered in this pull request.
=> Ruby: capture required libraries as reference tags

Tmain/sql-null-tag-warning.d/input.sql, Tmain/sql-null-tag-warning.d/run.sh, Tmain/sql-null-tag-warning.d/stderr-expected.txt, parsers/sql.c
=> SQL: emit event kind tags only when token is an identifier, string, or non-reserved keyword

Units/parser-c.r/end-field-of-var.d/expected.tags, Units/parser-c.r/end-field-of-var.d/input.c, parsers/cxx/cxx_parser.c
Avoid corrupting the token chain before extracting variables when an assignment is found. This allows us to extract more variables and also to attach end-line tags properly.
=> CXX: Improve extraction of variables

Tmain/readtags-alias-for-boolean.d/input.c, Tmain/readtags-alias-for-boolean.d/output.tags, Tmain/readtags-alias-for-boolean.d/run.sh, Tmain/readtags-alias-for-boolean.d/stdout-expected.txt, dsl/dsl.c
Consider writing a client tool runs on emacs.
The tool may use -Q and -S options of readtags.
The developers of the client tool may want to pass
an S expression built-in emacs lisp to readtags
directly.
However, there was a gap in what we call S expression
in emacs and readtags.
readtags's S expression is scheme based; #t and #f is
used as representation of boolean values. These representation
is not used in emacs. Further more, `#' is special character
(prefix of a reader macro) in emacs. So, it is hard for emacs
to build an S expression passed to readtags if the expression
includes a boolean value.
To fill the gap, this change introduces `true' and `false'
values to the readtags side. So the client tool that runs on
emacs doesn't doesn't have to use #t and #f directly in S
expression …
=> dsl: introduce true and false as aliases for #t and #f

main/tokeninfo.h, parsers/dtd.c, parsers/ldscript.c, parsers/tcl.c
The orignal code uses TOKENX macro for extending tokenType.
However, it makes parsers' code a bit complicated.
This change removes the macro. Instead, the code lines using the
macros are convrted to the classical downcast technique.
e.g.
typedef struct sDtdToken {
tokenInfo base;
int scopeIndex;
} dtdToken;
#define DTD(TOKEN) ((dtdToken *)TOKEN)
static struct tokenInfoClass dtdTokenInfoClass = {
...
.extraSpace       = sizeof (dtdToken) - sizeof (tokenInfo),
DTD (token)->scopeIndex;
=> main,DTD,LdScript,Tcl: simplify the way to extend tokenInfo type

parsers/cxx/cxx_parser_template.c
The token returned from cxxTagCheckAndSetTypeField() must be freed after
calling cxxTagCommit().
The memory leak was introduced in dc4e754e0a00e90a4f57bc959a8345e629c110d1.
Close #2525.
=> Cxx: destroy the token returned from cxxTagCheckAndSetTypeField() for fixing memory leak

Units/parser-cxx.r/templates5.d/args.ctags, Units/parser-cxx.r/templates5.d/expected.tags, Units/parser-cxx.r/templates5.d/input.cpp, parsers/cxx/cxx_parser_template.c
Handle the usage of the template keyword as disambiguator for dependent names.
(hardcore C++ : see https://en.cppreference.com/w/cpp/language/dependent_name).
Fixes #2534 .
=> CXX: Allow usage of template keyword as disambiguator for dependent names

main/entry.h, main/trashbox.h, parsers/cxx/cxx_tag.c
Close #2524.
When attaching a field to a tag, the original code calls
attachParserField() wrong way. The caller must own the field value
passed to attachParserField(); the caller must free the memory
object for the value after calling makeTagEntry().
However, the original code didn't do so. As the result, the memory
object for the value was leaked.
This change introduces the parser trash box. After calling
attachParserField(), the caller puts the memory object to the trash
box; the memory object is freed when parsing the current input file is
completed.
=> Cxx: fix memory leak in field attaching

docs/man/ctags-client-tools.7.rst, docs/man/readtags.1.rst, man/ctags-client-tools.7.rst.in, man/readtags.1.rst.in
I removed the "AUTHOR" section in the stab since `man-pages(7)` says it's "strongly discouraged".
When running `$ make QUICK=1 update-docs` (as suggested in `man/README`), I got:
```
make: *** No rule to make target 'update-docs'.  Stop.
```
But seems `$ make` generates the man pages correctly.
=> Write readtags(1)

Tmain/list-params.d/stdout-expected.txt, Units/parser-cpreprocessor.r/macroexpand.d/args.ctags, Units/parser-cpreprocessor.r/macroexpand.d/expected.tags, Units/parser-cpreprocessor.r/macroexpand.d/input-0.c, Units/parser-cpreprocessor.r/macroexpand.d/input-1.c, Units/parser-cpreprocessor.r/macroexpand.d/input.c, docs/news.rst, docs/parser-cxx.rst, main/entry.c, main/entry.h, main/main.c, main/mio.c, main/mio.h, main/writer-etags.c, parsers/cpreprocessor.c, parsers/cxx/cxx.c
This one may be the biggest result of introducing the symbol table.
This pull request takes over the discussion and efforts in #2427.
Quoted from documents:
```rst
If a CPreProcessor macro defined in a C/C++/CUDA file, the macro invocation in the
SAME file can be expanded with following options:
.. code-block:: text
--param-CPreProcessor:_expand=1
--fields-C=+{macrodef}
--fields-C++=+{macrodef}
--fields-CUDA=+{macrodef}
--fields=+{signature}
Let's see an example.
input.c:
.. code-block:: C
#define DEFUN(NAME) int NAME (int x, int y)
#define BEGIN {
#define END }
DEFUN(myfunc)
BEGIN
return -1
END
The output without options:
.. code-block::
$ ctags -o - input.c
BEGIN	input.c	/^#define BEGIN /;"	d	language:C	file:
DEFUN	input.c	/^#define DEFUN(/;"	d	language:C	file:
END	input.c	/^#define END …
```
=> Cpreprocessor/C/C++/CUDA: infile macro expanding

Tmain/list-roles.d/stdout-expected.txt, parsers/r.c
This patch fix some spelling typos in r.c
Signed-off-by: Masanari Iida <standby24x7@gmail.com>
=> Fix typos in r.c

Units/parser-ruby.r/ruby-methods-for-visiblity.d/expected.tags, Units/parser-ruby.r/ruby-methods-for-visiblity.d/input.rb, parsers/ruby.c
=> Ruby: skip "public", "protected", and "private" when tagging methods

main/debug.h, main/objpool.c
objpool makes the output of valgrind difficult to be understood.
When ./ctags is built with --enable-debugging, this change disables
all objpools.
=> main: disable all objpools in debug build

docs/output-json.rst
Currently the way output rendered on https://docs.ctags.io/en/latest/output-json.html is not particularly pretty; judging by GitHub preview this PR should change that.
=> Format --list-fields output as console code block

docs/man/ctags-client-tools.7.rst, docs/man/ctags.1.rst, docs/man/readtags.1.rst, man/ctags-client-tools.7.rst.in, man/ctags.1.rst.in, man/readtags.1.rst.in
Fix spelling typos in ctags-client-tools.7.rst,
ctags.1.rst, readtags.1.rst, ctags-client-tools.7.in
ctags.1.rst.in and readtags.1.rst.in.
=> docs(man): Fix typos in man

Units/parser-vim.r/vim9-def-function.d/expected.tags, Units/parser-vim.r/vim9-def-function.d/input.vim, parsers/vim.c
This PR tries to add support for the new [`:def` functions](https://vimhelp.org/vim9.txt.html#:def) introduced in Vim9.  See issue #2589 for more information.
I briefly tested the patch, and it seems to work.  That is now `ctags(1)` correctly generates tags for `:def` functions.
But I don't know if it's really correct; I don't know C.
If it is correct, I think I could also add support for constants defined with the [`:const`](https://vimhelp.org/eval.txt.html#:const) keyword.
=> vim: support new ":def" functions of vim9

Units/parser-vim.r/vim-const.d/expected.tags, Units/parser-vim.r/vim-const.d/input.vim, parsers/vim.c
This PR tries to add support for the Vim command [`:const`](https://vimhelp.org/eval.txt.html#:const).  The latter is used in Vimscript to set a constant.
---
I did not try to create a new C function to parse the command because:
1. that's above my level
2. I don't think it's necessary.  In Vim, `:const` is equivalent to `:let` followed by `:lockvar`; it's just a variable whose value is locked so that it can't change.
---
`:const` can be shortened into `:cons`, which is why I wrote `4` and not `5` here:
else if (wordMatchLen (line, "let", 3) || wordMatchLen (line, "const", 4))
^
---
I added a simple test consisting of an input file and an expected output tags file.
I made sure all the Vim tests passed:
make units LANGUAGES=Vim
=> vim: support ":const" command which sets constants

configure.ac
introduced in 1293d03b1a38
(rbtree: introduce new ifdef condition HAVE_STATEMENT_EXPRESSION_EXT)
=> buildsys: fix a couple english spelling errors in configure.ac

Tmain/list-map-patterns.d/stdout-expected.txt, parsers/ldscript.c
Close #2603.
The original pattern "ld.\*" matches "ld.c". As a result ld.c is parsed by LdScript
parser unexpectedly.
Originally, "ld.\*" was introduced for arch/mips/boot/compressed/ld.script of linux.
Replace "ld.\*" with "ld.script" as a more strict pattern.
=> [SELF-INCOMPATIBLE]LdScript: use "ld.script" as an entry of map pattern instead of "ld.*"

autogen.sh
=> build-sys: display an error message when pkg-config or autoreconf is not found

Units/parser-rust.r/rust-test_input.d/expected.tags, Units/parser-rust.r/rust-test_input.d/input.rs, parsers/rust.c
I noticed that ctags wouldn't generate a function entry for a signature like:
```rust
fn foo(arr: [u32; 3]) {}
```
The problem was that the parser stopped as soon as a ';' was encountered, probably assuming that it would be a statement delimiter and not an array type.
The fix is to keep track of brackets and ignore ';' if we have at least one opened bracket.
While I was at it I also reject the signature if the brackets aren't balanced, which means that the parser is now a little more strict than it was before and a (broken) function like this one will now be rejected:
```rust
fn bad(p: &[u32) {}
```
=> Rust: allow arrays in function parameters

Tmain/json-output-for-broken-input.d/run.sh, Tmain/kinddef.d/run.sh, Tmain/load-conf-files-under-cwd-no-dot.d/run.sh, Tmain/load-conf-files-under-cwd.d/run.sh, Tmain/roledef.d/run.sh, Tmain/roledef.d/stderr-expected.txt, Tmain/roledef.d/stdout-expected.txt, Tmain/utils.sh, Units/option-regex-attaching-role.r/extending-existing-parser.d/args.ctags, Units/option-regex-attaching-role.r/standing-alone-line-parser.d/args.ctags, docs/man/ctags-optlib.7.rst, docs/optlib.rst, main/options.c, main/parse.c, man/ctags-optlib.7.rst.in, misc/optlib2c, optlib/elm.ctags, optlib/kconfig.ctags
Clsoe #2596.
The original form of the option was
--_roledef-<LANG>=<KIND-LETTER>.<ROLE>,<ROLE-DESCRIPTION>
This form doesn't align with the form of more popular (= use visible) option,
--roles-<LANG>.<KIND>=[+|-]<ROLE>.
For aligning the forms, this commit changes the form of --_roledef option
as following:
--_roledef-<LANG>.<KIND>=<ROLE>,<ROLE-DESCRIPTION>
=>  [SELF-INCOMPATIBLE]main: revise the form of --_roledef option 

Units/parser-tcl.r/dollar-in-regex.d/expected.tags, Units/parser-tcl.r/dollar-in-regex.d/input.tcl, Units/parser-tcl.r/escaping.d/expected.tags, Units/parser-tcl.r/escaping.d/input.tcl, parsers/tcl.c
Close #2627.
For distinguishing $ in variable expansion and $ in a regex pattern,
This change makes the way to recognize variable expansions strict.
With this change, alnum char or `{' is expected after $ for variable
expansion.
=> Tcl: strict the way to recognize variable expansions

parsers/rst.c
"rst" is the name of an editing mode for ReStructuredText in emacs.
=> ReStructuredText: add "rst" as an alias

Units/parser-verilog.r/systemverilog-2d-array.d/expected.tags, Units/parser-verilog.r/systemverilog-typed-parameter.d/expected.tags, Units/parser-verilog.r/systemverilog-typed-parameter.d/input.sv, parsers/verilog.c
A typed parameter was reported as register-kind instead of constant-kind.
For example,
```systemverilog
localparam int MY_WIDTH                  = 1;
```
MY_WIDTH was reported as register-kind.  On the line 1200, `token->kind` was overwritten K_REGISTER of `int`.
This fix the issue not to overwrite `token->kind` when it is K_CONSTANT.
=> SystemVerilog: typed parameter support

Units/parser-verilog.r/systemverilog-typedef.d/expected.tags, Units/parser-verilog.r/systemverilog-typedef.d/input.sv, parsers/verilog.c
This fixes one of issues on #2618 
```systemverilog
// src/reg/uvm_reg_model.svh
`define UVM_REG_DATA_WIDTH 8
typedef  bit unsigned [`UVM_REG_DATA_WIDTH-1:0]  uvm_reg_data_t ; // unsigned:typedef => uvm_reg_data_t:typedef
// src/base/uvm_object_globals.svh
typedef logic signed [63:0] uvm_integral_t; // signed:typedef => uvm_integral_t:typedef
```
44fc82f skips `unsigned` or `signed` in a typedef statement properly.
b4ff316 uses processStuct() for typedef for `struct`.  This is more consistent with the implementation for `enum`.
=> SystemVerilog: fix for typedef with signed/unsigned

.gitignore
forgotten when adding the new ctags-lang-python man page recently
=> gitignore: add ctags-lang-python generated manpage files

misc/units.py
=> units.py: propagate error reported by valgrind properly

main/parse.c, main/ptag.c, main/ptag_p.h
Per-parser ptags are lexically enumerated in parser.c
However, a ptag itself knows whether it is "Per-parser"
ptag or not. So the enumeration is not needed.
=> main,refactor: don't hard-code per-parser ptags when emitting

.github/workflows/tagging.yml, Tmain/input-encoding-option.d/tags-expected.txt, Tmain/interactive-mode.d/stdout-expected.txt, Tmain/interactive-option-write-to-file.d/stdout-expected.txt, Tmain/output-encoding-option.d/tags-expected.txt, Tmain/sandbox-crash.d/stdout-expected.txt, Tmain/sandbox-default-req.d/stdout-expected.txt, Tmain/sandbox-no-eager-guessing.d/stdout-expected.txt, Tmain/sandbox-with-eager-guessing.d/stdout-expected.txt, Tmain/sandbox.d/stdout-expected.txt, configure.ac, docs/man/ctags-client-tools.7.rst, docs/man/ctags-incompatibilities.7.rst, docs/man/ctags-lang-python.7.rst, docs/man/ctags-optlib.7.rst, docs/man/ctags.1.rst, docs/man/readtags.1.rst, main/ctags.h, man/ctags-lang-python.7.rst.in, misc/git-tag-maybe.sh, win32/ctags.exe.manifest, win32/ctags.rc
Partially close #1038.
~The tagging format is v5.9.YYYYMMDD.0~.
The tagging format is p5.9.YYYYMMDD.0.
=> GitHub Actions: create a tag to our repo weekly if a new change is committed since last tagging

Makefile.am, Tmain/list-fields-with-prefix.d/stdout-expected.txt, Tmain/list-fields.d/stdout-expected.txt, Units/parser-verilog.r/systemverilog-parameter.d/args.ctags, Units/parser-verilog.r/systemverilog-parameter.d/expected.tags, Units/parser-verilog.r/systemverilog-parameter.d/input.sv, configure.ac, docs/man-pages.rst, docs/man/ctags-lang-verilog.7.rst, man/Makefile, man/ctags-lang-verilog.7.rst.in, parsers/verilog.c
This is a fix for #2537.
By adding option `--fields-SystemVerilog=+{property}` ctags outputs a tag `property:parameter` on parameters which can be overridden on instantiation.
I choose a generic name `property` instead of `definedWith`.   This is because, as we discussed on #2537, what we need is not how a constant is defined with, `parameter `or `localparam`.
=> SystemVerilog: support property:parameter (update for #2537)

parsers/verilog.c
The parser has been improved by the new maintainer, and can recognize
user defined types well know.
It doesn't need the type tracker based on the symbol table anymore.
This change removes it.
=> SystemVerilog,refactor: remove unused code about type tracker

main/keyword.c, main/keyword.h, parsers/verilog.c
Introduce a new function for adding keywords having the same value in batch.
Inspired from the code in (System)Verilog parser.
I would like to use the technique used in (System)Verilog parser in Vala parser I'm working on.
@hirooih, could you review my change for (System)Verilog parser?
=> main: introduce keyword group API

.gitignore
=> gitignore: add ctags-lang-verilog generated manpage files

Units/parser-inko.r/everything.d/expected.tags, Units/parser-inko.r/everything.d/input.inko, Units/parser-inko.r/let.d/expected.tags, Units/parser-inko.r/let.d/input.inko, Units/parser-inko.r/methods.d/expected.tags, Units/parser-inko.r/methods.d/input.inko, Units/parser-inko.r/objects.d/expected.tags, Units/parser-inko.r/objects.d/input.inko, Units/parser-inko.r/traits.d/expected.tags, Units/parser-inko.r/traits.d/input.inko, optlib/inko.c, optlib/inko.ctags
This applies various fixes to the Inko regex parser, and updates my
Email address as I no longer use Gmail.
Required methods
================
Inko has a notion of required methods. These are defined without a body
like so:
trait SomeTrait {
def required_method(some_argument: Type)
}
These were not parsed properly. In this commit we fix the parser so both
regular and required methods are parsed.
Nested objects and traits
=========================
The parser had support for nested objects and traits, like so:
object A {
object B {}
}
Inko dropped support for this syntax quite some time ago, so we also
remove ctags support for this.
Attribute definitions
=====================
Inko's syntax for defining attributes changed a while ago. Instead of
using `let @foo = bar` you now define attribute …
=> Fix and tidy up the Inko parser

Units/parser-verilog.r/systemverilog-github646.d/expected.tags, Units/parser-verilog.r/systemverilog-net-var.d/expected.tags, Units/parser-verilog.r/systemverilog-net-var.d/input.sv, Units/parser-verilog.r/verilog-github624.d/expected.tags, parsers/verilog.c
`isIdentifierCharacter() ` did not handle '$` properly.
I needed to simplify token handling for the better fix of it.
Delay handling is also improved.
=> SystemVerilog: handle an identifier include '$'

docs/man/ctags-client-tools.7.rst, man/ctags-client-tools.7.rst.in
Ref: <https://github.com/universal-ctags/ctags/issues/2683#issuecomment-722644523>
The original technique introduced before doesn't deal with pattern fields that only use line numbers.
One thing I'm not sure is till now we are only dealing with `--format=2`. I think not many people will use `--format=1`, but if that's the case, this parsing technique won't work for them.
=> docs(man): correct the parsing technique in ctags-client-tools(7)

Units/parser-itcl.r/simple-itcl.d/expected.tags, parsers/itcl.c
They were mistakenly stored to implementation: field.
=> ITcl,bugfix: store protected, private, and public to access:

docs/man/readtags.1.rst, man/readtags.1.rst.in
The bug https://github.com/universal-ctags/libreadtags/issues/21 is solved now.
=> docs(man): remove a solved bug

parsers/verilog.c
Fix #2709
Suppress MSVC warning C4819. (The file contains a character that cannot
be represented in the current code page.)
=> verilog: Stop using non-ASCII chars

parsers/cxx/cxx_parser_template.c
There is a small typo in parsers/cxx/cxx_parser_template.c.
Should read `preceded` rather than `preceeded`.
=> docs: fix simple typo, preceeded -> preceded

main/parse.c
Commit
82791c20ff8d01e7055bcbbb30db4999d2c3d463
moved CTagsParser, FallbackParser and CTagsSelfTestParser above the
ifdef which made these parsers included also when using
EXTERNAL_PARSER_LIST - this is not good for Geany because these three
parsers are "invisible" for it and shift the EXTERNAL_PARSER_LIST by 3.
This patch moves the ifdef back where it was before.
=> Move EXTERNAL_PARSER_LIST ifdef to the beginnning of BuiltInParsers

Units/parser-verilog.r/systemverilog-assignment.d/expected.tags, Units/parser-verilog.r/systemverilog-class.d/expected.tags, Units/parser-verilog.r/systemverilog-constraint.d/expected.tags, Units/parser-verilog.r/systemverilog-net-var.d/expected.tags, Units/parser-verilog.r/systemverilog-package.d/expected.tags, Units/parser-verilog.r/systemverilog-package.d/input.sv, Units/parser-verilog.r/systemverilog-procedural.d/expected.tags, Units/parser-verilog.r/systemverilog-struct.d/expected.tags, Units/parser-verilog.r/systemverilog-struct.d/input.sv, Units/parser-verilog.r/systemverilog-typedef.d/expected.tags, parsers/verilog.c
Struct and union  members are emitted by this fix.
The kind "member" (w) is added.  (m and M were already used.)
Enum items are emitted in the defined order with `--sort=no` option.
=> SystemVerilog: support struct and union  member

Tmain/excmd-combine-backward.d/stdout-expected.txt, Tmain/excmd-combine.d/stdout-expected.txt, Tmain/extras-field-for-pseudo-tags.d/stdout-expected.txt, Tmain/input-encoding-option.d/tags-expected.txt, Tmain/json-output-format.d/stdout-expected.txt, Tmain/output-encoding-option.d/tags-expected.txt, Tmain/ptag-in-optlib-parser.d/stdout-expected.txt, Tmain/ptag-kind-sep.d/stdout-expected.txt, Tmain/ptag-output-excmd.d/stdout-expected.txt, docs/man/ctags.1.rst, main/writer-ctags.c, main/writer.c, man/ctags.1.rst.in
See #2691. This makes it straightforward for client tools to "search the nearest occurence of pattern around the line", making good use of both the line number and search pattern.
I'll update #2698 once this is merged.
=> main: use actual line number in combined pattern fields

parsers/verilog.c
This fix improves readability and prevents bugs showed in #2703.
I am working on similar other issues.
=> SystemVerilog,refactor: call skipWhite() at the end of skipPastMatch()

Units/parser-verilog.r/systemverilog-assertion.d/expected.tags, Units/parser-verilog.r/systemverilog-checker.d/expected.tags, Units/parser-verilog.r/systemverilog-net-var.d/expected.tags, Units/parser-verilog.r/verilog-instance.d/args.ctags, Units/parser-verilog.r/verilog-instance.d/expected.tags, Units/parser-verilog.r/verilog-instance.d/input.v, parsers/verilog.c
add a kind named K_INST
update function tagNameList to update kind from K_IDENTIFIER to K_INST
=> verilog: keep trace with instance in TAGS file

Units/parser-verilog.r/systemverilog-net-var.d/expected.tags, Units/parser-verilog.r/systemverilog-net-var.d/input.sv, parsers/verilog.c
This fix makes input character handling consistent.
Until now, character input processing has been executed in an ad hoc way.
- Each function which executes character input has argument "c" and returns "c".
- It calls skipWhite() before return.
=> SystemVerilog,refactor: consistent input character handling

Units/parser-verilog.r/systemverilog-parameter.d/expected.tags, parsers/verilog.c
- readWordToken() returns "c" instead of bool value
- updateKind() is merged into readWordToken()
- isFirstIdentifierCharacter() is rename to isWordToken() and is called before readWordToken() is called.
During this refactoring a bug in processParameterList() was found and fixed.
=> SystemVerilog: refactor readWordToken()

Units/parser-clojure.r/clojure-metadata-in-fn.d/expected.tags, Units/parser-clojure.r/clojure-metadata-in-fn.d/input.clj, parsers/clojure.c
Functions can also have metadata, but `skipMetadata` is not called for them. That causes functions like
```clj
(defn ^:private test-fn [])
```
to be parsed as `^:private` instead of `test-fn`. This PR fixes the problem.
=> Clojure: Fix skipMetadata not called for functions

parsers/verilog.c
There were 8 bugs which cause infinite loop due to lack of EOF check.
While checking loops, loops which can be refactored were found and fixed.
I do not add test cases for this issue, because we need a unit case for each loop.
=> SystemVerilog: exit loop on EOF

Units/parser-verilog.r/systemverilog-assertion.d/expected.tags, Units/parser-verilog.r/systemverilog-assertion.d/input.sv, Units/parser-verilog.r/systemverilog-checker.d/expected.tags, Units/parser-verilog.r/systemverilog-checker.d/input.sv, Units/parser-verilog.r/systemverilog-covergroup.d/expected.tags, Units/parser-verilog.r/systemverilog-covergroup.d/input.sv, parsers/verilog.c
A bug in `systemverilog-checker.d/input.sv` which has been marked as FIXME was fixed.
=> SystemVerilog: fix processAssertion() not to use skipToSemiColon()

Units/parser-verilog.r/systemverilog-covergroup.d/args.ctags, Units/parser-verilog.r/systemverilog-covergroup.d/expected.tags, Units/parser-verilog.r/systemverilog-covergroup.d/input.sv, Units/parser-verilog.r/systemverilog-package.d/args.ctags, Units/parser-verilog.r/systemverilog-package.d/expected.tags, Units/parser-verilog.r/systemverilog-package.d/input.sv, Units/parser-verilog.r/systemverilog-parameter.d/expected.tags, Units/parser-verilog.r/systemverilog-parameter.d/input.sv, Units/parser-verilog.r/systemverilog-prototype.d/args.ctags, Units/parser-verilog.r/systemverilog-prototype.d/expected.tags, Units/parser-verilog.r/systemverilog-prototype.d/input.sv, Units/parser-verilog.r/systemverilog-task-function.d/expected.tags, Units/parser-verilog.r/systemverilog-task-function.d/input.sv, parsers/verilog.c
- processDesignElement() is divided into processDesignElementL() (for module, interface, and program) and processDesignElementS() (for others).
- tagging imported functions is implemented
- skipping package import declaration is implemented
- implement "interface class" support
- implement coverage_event handling
- units tests are heavily updated
=> SystemVerilog: implement unsupported features in processDesignElement()

Units/parser-php.r/php-use.d/expected.tags, Units/parser-php.r/php-use.d/input.php, parsers/php.c
https://www.php.net/manual/en/migration72.new-features.php#migration72.new-features.trailing-comma-in-grouped-namespaces
=> php: Fix support for PHP 7.2+ trailing comma in grouped use statements

win32/appveyor.bat
Stop creating a separate debug package which includes whole documents.
Instead, create a package that includes only debug symbols.
Use `objcopy --only-keep-debug` and `objcopy --add-gnu-debuglink` to
extract debug symbols to a separate file.
How to use the debug symbols:
* Extract `*.zip` and `*.debuginfo.zip` in the same directory.
* Also put the ctags source code there.
* Use GDB to debug `ctags.exe`.
GDB will automatically load the symbols from `ctags.exe.debug`.
=> appveyor: Revise packaging of debug symbols

Tmain/epoch-field.d/run.sh, Tmain/epoch-field.d/stdout-expected.txt, Tmain/extras-field.d/run.sh, Tmain/json-output-format.d/run.sh, Tmain/json-output-format.d/stdout-expected.txt, Tmain/kinds-all-with-spec.d/run.sh, Tmain/list-fields-with-prefix.d/stdout-expected.txt, Tmain/list-fields.d/stdout-expected.txt, Tmain/ptag-in-optlib-parser.d/stdout-expected.txt, Tmain/xformat-common-fields.d/stdout-expected.txt, Units/parser-python.r/simple.py.d/args.ctags, main/entry.c, main/entry.h, main/field.c, main/field.h, main/read.c, main/read_p.h, main/routines.c, main/routines_p.h, main/writer-ctags.c, misc/units.py
*The field name is changed from "tstamp" to 'epoch".* 
main,units.py: introduce "epoch:" field for ~f~F/file kind
For implementing the feature "updating the tags file" in the future,
this change introduces "epoch:", a field which records the last
modified time of the input file. This field is enabled by default.
Example output:
$ ./ctags --extras=f --kinds-C= -o - main/main.c
main.c      main/main.c     1;"     F       language:C      epoch:1078071702
The resolution of time is second in the current implementation.
For Using higher resolution timestamp in the future, ".000000000" is suffixed.
NOTES:
The "fileScope" member of tagEntryInfo structure was not used anywhere in the
ctags source tree. So this change renames it to "timestamp".
timestamp fields in tags output makes many test cases …
=> main: add timestamp field for file kind

Units/parser-verilog.r/systemverilog-checker.d/expected.tags, Units/parser-verilog.r/systemverilog-module.d/expected.tags, Units/parser-verilog.r/systemverilog-module.d/input.sv, Units/parser-verilog.r/systemverilog-net-var.d/expected.tags, Units/parser-verilog.r/systemverilog-net-var.d/input.sv, Units/parser-verilog.r/systemverilog-typedef.d/expected.tags, Units/parser-verilog.r/systemverilog-typedef.d/input.sv, parsers/verilog.c
- fix module port tagging bugs
- net type and user-defined type ports are tagged as port.
- correctly distinguishes between ANSI port and non-ANSI port.
- merge with `processPortList()`
- define `swapToken()` for `K_WITH` handling (proposed by @masatake san)
- fixes for uncovered lines
All high-priority items are implemented by this pull-request.
=> SystemVerilog: port list fix and others

Makefile.am, circle.yml, configure.ac, docs/autotools.rst, m4/ax_prog_cc_for_build.m4
=> build-sys: fix cross-compilation failure caused by building/executing packcc

Units/parser-verilog.r/systemverilog-constraint.d/expected.tags, Units/parser-verilog.r/systemverilog-directive.d/expected.tags, Units/parser-verilog.r/systemverilog-directive.d/input.sv, Units/parser-verilog.r/systemverilog-task-function.d/expected.tags, Units/parser-verilog.r/systemverilog-task-function.d/input.sv, parsers/verilog.c
- tag constraint prototype as prototype (cf. #2750)
- fix for package scoped port identifiers
- fix for back-to-back compiler directives
- update copyright notice
- update reference URLs
- make coding style consistent
=> SystemVerilog: several bug fixes and some code clean-ups

misc/units
This is a fix to run `make chop, slap, fuzz, or noise` on macOS.
It seems that `stat` command has some variants.  I looked for better way on the Web, and this was the best one I found.
=> misc/units: change option of stat on BSD-based OSes including macOS

Tmain/epoch-field.d/run.sh, Tmain/epoch-field.d/stdout-expected.txt, main/parse.c, main/read.c, main/read_p.h
There are cases that ctags pre-opens an input file for guessing a language for it. e.g. Detecting whether .h file is for for C++ or ObjectiveC.                                                                                 
The original code didn't attach the last modified time of the file to "epcoh:" field.
=> main: attach the last modified time to epcoh: field even for pre opened file

Units/simple-kconfig.d/expected.tags, Units/simple-kconfig.d/input-4.kconfig, optlib/kconfig.c, optlib/kconfig.ctags
Qemu's minikconf.py doesn't require surrounding a file name with
double quote characters in "source" directive.
=> Kconfig: recognize sourced file name with no quotes

parsers/verilog.c
```
$ ./ctags --list-kinds-full=SystemVerilog
#LETTER NAME                                     ENABLED REFONLY NROLES MASTER DESCRIPTION
A       assert                                   yes     no      0      NONE   assertions (assert, assume, cover, restrict)
...
f       function                                 yes     no      0      NONE   functions
i       instanceinstances of module or interface yes     no      0      NONE   NO DESCRIPTION GIVEN
l       ifclass                                  yes     no      0      NONE   interface class
...
w       member                                   yes     no      0      NONE   struct and union members
$ 
```
The line for instance was broken due to a missing comma.  It has been hidden since #2703.
=> SystemVerilog: fix ctags --list-kinds-full=SystemVerilog listing

README.md, docs/README.md, docs/extending.rst, docs/index.rst, docs/internal.rst, docs/optlib.rst
- Restructure "Extending ctags" sections
- move "Extending ctags with Regex parser" (optlib.rst) to upper level, etc.
- update README.md
- move PACKCC info to docs/internal.rst, etc.
See each commit message for more information.
=> Doc: Restructure "Extending ctags" sections and update README.md

Units/parser-inko.r/everything.d/expected.tags, Units/parser-inko.r/everything.d/input.inko, Units/parser-inko.r/methods.d/expected.tags, Units/parser-inko.r/methods.d/input.inko, Units/parser-inko.r/objects.d/expected.tags, Units/parser-inko.r/objects.d/input.inko, Units/parser-inko.r/strings.d/expected.tags, Units/parser-inko.r/strings.d/input.inko, optlib/inko.c, optlib/inko.ctags
The "object" keyword has been renamed to "class". This commit updates
all Inko tests and the parser to match this change.
=> Inko: rename "object" keyword to "class"

Units/parser-julia.r/corner_cases.d/expected.tags, Units/parser-julia.r/function_scope.d/args.ctags, Units/parser-julia.r/function_scope.d/expected.tags, Units/parser-julia.r/function_scope.d/input.jl, Units/parser-julia.r/julia_test.d/expected.tags, parsers/julia.c
The idea is in the test `function_scope.d`. For a input file like:
``` julia
module MyModule
function func1() end
function func2()
function func3() end
end
end
```
The `scope` field for the functions should be:
- `func1`: module:MyModule
- `func2`: module:MyModule
- `func3`: function:func2
For now there are some things not working well. I'll write them in code reviews.
=> Julia: fill scope field for functions

Units/parser-julia.r/empty_line.d/expected.tags, Units/parser-julia.r/empty_line.d/input.jl, parsers/julia.c
... and treat TOKEN_NONE as a new line token.
rebase of #2787
If the first line is empty, valgrind gives an error.
Short functions defined in the first line are also not parsed, try the following, where fun2 is parsed but not fun1:
fun1(x) = 1
fun2(x) = 2
Solved by initializing the prev_c member to \0 and treating TOKEN_NONE as a new line TOKEN.
=> Julia: correct valgrind error initialization

.github/workflows/testing-mac.yml
We encounter the same problem reported at
https://github.community/t/macos-11-0-big-sur-builds-stalling-out/153761
.
=> GitHub Actions: temporarily disable macos-11.0

Tmain/option-extradef-in-mtable.d/input.mtextra, Tmain/option-extradef-in-mtable.d/mtextra.ctags, Tmain/option-extradef-in-mtable.d/run.sh, Tmain/option-extradef-in-mtable.d/stdout-expected.txt, main/lregex.c
Extra tags in multiline regex tables. See issue #2795.
=> Extra mtable regex

circle.yml
=> circleci: verify the architecture of the generated binary file when cross-compiling

configure.ac
add code to configure.ac to check if the `PKG_CHECK_EXISTS` macro is defined. If not defined, a fatal error thrown, tell the user to install pkg-config 0.18 or later.
Note: our project use the `PKG_CHECK_EXISTS` and `PKG_CHECK_MODULES` two macros, these two macros are provided by `pkg.m4` which is installed along with `pkg-config`. the `PKG_CHECK_EXISTS` since `0.18`, the `PKG_CHECK_MODULES` since `0.4`.
=> build-sys: fix configure syntax error near unexpected token `dummy`

.github/workflows/testing-mac.yml
=> GitHub Actions: install python@3.9 explicitly for running test cases on MacOS

m4/ax_prog_cc_for_build.m4
`AC_PROG_CC_C99` macro must be placed after `_AC_COMPILER_OBJEXT` macro,
beacuse `AC_PROG_CC_C99` uses the `ac_build_objext` variable, this
variable is assigned by `_AC_COMPILER_OBJEXT`.
=> build-sys: fixed compilation error in misc/packcc/packcc.c

.github/workflows/testing-mac.yml
Quoted from @leleliu008's comment in #2803:
GitHub Actions VM macOS10.15 macOS11.0 have pre-installed Python@3.9
via HomeBrew, the error happens when Python@3.9 can be upgraded, so we
should upgrade python@3.9 first.
=> GitHub Actions (macos): clean up package installing and updagrading steps

Units/parser-c.r/recursive-macros-2.d/README, Units/parser-c.r/recursive-macros-2.d/args.ctags, Units/parser-c.r/recursive-macros-2.d/expected.tags, Units/parser-c.r/recursive-macros-2.d/input.c, Units/parser-c.r/recursive-macros.d/args.ctags, Units/parser-c.r/recursive-macros.d/expected.tags, Units/parser-c.r/recursive-macros.d/input.c, parsers/cpreprocessor.c, parsers/cpreprocessor.h, parsers/cxx/cxx_parser_tokenizer.c
This change limits the usage of a macro definition in a recursive macro expansion up to CXX_PARSER_MAXIMUM_MACRO_USE_COUNT.
This change extends #2780.
=> Cxx,CPreProcessor: limit to use a macro in a recursive macro expansion

circle.yml
circleci: use https instead of http to access vault.centos.org
It seems that accessing via https is more stable.
=> circleci: use https for accessing vault centos org

Units/parser-julia.r/scoped_macro.d/args.ctags, Units/parser-julia.r/scoped_macro.d/expected.tags, Units/parser-julia.r/scoped_macro.d/input.jl, parsers/julia.c
```julia
@eval fun1(x) = $a
Base.@eval fun2(x) = $a
```
`fun2` is not recognized as a short function, because `Base.@eval` is not recognized as a macro (with scope).
(currently `fun1` is also not parsed but it will be corrected by #2790).
~~This is a work in progress, it should be implemented using the new cork system introduced by #2763.~~
It is working now!
=> Julia: correctly recognize Module.@macro as a macro call

m4/ax_prog_cc_for_build.m4
error message: `./configure: line 5804: test: =: unary operator expected`
this error caused by `ac_cv_c_compiler_gnu` variable is not unset
=> build-sys: fix configure unary operator expected

Units/parser-julia.r/parametric_constructor.d/expected.tags, Units/parser-julia.r/parametric_constructor.d/input.jl, parsers/julia.c
Correct three bugs with functions and constructors:
- `lenght(a) == 0` was recognized as a short function definition.
- Parametric constructors with `function` keyword were not recognized, like `function MyStruct{Int}(x) ... end`
- Inner constructors inside `struct` defined below a constructor with the `function` keyword had incorrect scope, it was considered to be below the constructor with `function`.
- [EDIT] Outer constructor, like parametric short function `func{Int}(x) = 0`, was not recognized as a short function.
=> Julia: correct bugs with struct constructor

docs/man/ctags-client-tools.7.rst, docs/man/readtags.1.rst, man/ctags-client-tools.7.rst.in, man/readtags.1.rst.in
These includes my recent experience on readtags:
- How to use filter expressions inside sorter expressions.
- How to handle missing fields in post-processor expressions.
- A simpler way to parse tagline.
- Various little fix.
=> docs(man): improve readtags(1) and ctags-client-tools(7)

misc/units
OpenBSD sh has `[[` built-in command, but it does't support `=~` operator.
=> buildsys,units: fix make check failed due to ./misc/units[779]: sytnax error: `"\$file" missing expression operator when running on OpenBSD6.8

.github/workflows/testing-netbsd.yml, .github/workflows/testing-openbsd.yml
not execute `make check` on `netbsd` and `openbsd`, because `make check` failed on `netbsd` and `openbsd`. I created a new issue([issue-2829](https://github.com/universal-ctags/ctags/issues/2829))
=> GitHub Actions: run units target on netbsd and openbsd

Units/simple-function-parameters.d/args.ctags, Units/simple-function-parameters.d/expected.tags, Units/simple-function-parameters.d/input.pl
=> Units: add a test case for FunctionParameters subparser

Tmain/tag-relative-option.d/run.sh
use `cygpath` to convert `Windows path` to `Unix path` if `cygpath` exists.
=> buildsys;units: fix make check failed on MSYS2 when MSYSTEM=MINGW32 and MSYSTEM=MINGW64

docs/contributions.rst, docs/extending.rst, docs/internal.rst, docs/man/ctags.1.rst, docs/optlib.rst, docs/other-projects.rst, docs/testing.rst, man/ctags.1.rst.in
- ctags(1) updates
- markups fixes
- 5c473165 docs: ctags(1): more consistent markups
- 0da01779 docs: ctags(1): not use Sphinx extensions
- 04e8a42c docs: ctags(1): additional markup fixes
- contents reordering
- e0fd0467 docs: ctags(1): reorder tag entries related descriptions
- contents fixes (**please review carefully**)
- 92a648ca docs: ctags(1): misc fixes
- 2f6f62bd docs: ctags(1): update TAGS FILE FORMAT and TAG ENTRIES
- dba2d592 docs: ctags(1): update OPTIONS
- docs fixes
- db6aec7a docs: update and deal with TODO list
=> docs: updates of ctags(1) and docs/ updates

Units/simple-function-parameters.d/expected.tags, Units/simple-function-parameters.d/input-0.pl, Units/simple-function-parameters.d/input.pl, parsers/perl-moose.c, parsers/perl.c, parsers/perl.h
Function::Parameters module with 'qw/:modifiers/' allows specifying a
parameter list when defining a wrapper like:
before foo($x, $y, $z) {
...
}
With this change, Moose parser can detect the use of
Function::Parameters module with 'qw/:modifiers/' and extract wrappers with the extended notation.
=> Moose: support parameter-list notation of wrappers extended by Function::Parameters module

misc/units
I forgot updating the units shell script
in c314f261c930c6407a904f6e598d646db1c0df35.
=> units: don't pass --fields=-T

.gitignore, docs/man/ctags-lang-julia.7.rst, docs/man/ctags-lang-python.7.rst, docs/man/ctags-lang-verilog.7.rst, docs/testing.rst, makefiles/testing.mak, man/ctags-lang-julia.7.rst.in, man/ctags-lang-python.7.rst.in, man/ctags-lang-verilog.7.rst.in, misc/man-test.py
`man-test` is a new test harness for testing examples in per-language man pages (man/ctags-lang-\*.7.rst.in).
If you have python3, you can run it with "make man-test."
TODO:
- ~documentation for writing a test case~
- ~running on CI/CD environment~
=> man-test: new test harness

Tmain/list-fields-fixed-field-handling.d/run.sh, Tmain/list-fields-fixed-field-handling.d/stdout-expected.txt, main/options.c
This change is a continuation of c0421c5ec596b5f2a3e1a16a61d6ee3368a68842.
The effect of the "FIXED" property of fields cannot be decided till ctags
chooses of an output writer.
c0421c5ec596b5f2a3e1a16a61d6ee3368a68842 considers beginning
of parsing is the timing of the choice.
c0421c5ec596b5f2a3e1a16a61d6ee3368a68842 misses there is one more
case: the choice is made when --list-fields option is processed.
To reflect the choice to the output of --list-fields, this
change calls writerCheckOptions at the beginning of the process.
With this change, the behavior of --list-fields option
consists with the following description of ctags(1):
``--list-fields[=language|all]``
...
FIXED
Whether this field can be disabled or not in tags output.
Some fields are printed always in tags output.
They have …
=> main: adjust states of enabled/disabled for fixed fields before listing with --list-fields

Tmain/input-encoding-option.d/run.sh, Tmain/output-encoding-option.d/run.sh, Tmain/output-encoding-option.d/tags-expected.txt
`musl-libc iconv API` dosn't support `cp932` coding but supports
`shift_jis` coding. `shift_jis` coding is also supportted by `GNU
libiconv`
although `shift_jis` coding is different from `cp932` coding, but in our
case, it can be replaced by each other.
References:
http://una.soragoto.net/topics/13.html
https://wiki.musl-libc.org/functional-differences-from-glibc.html
https://github.com/bminor/musl/blob/master/src/locale/iconv.c
https://www.gnu.org/software/libiconv
=> Tmain: using `shift_jis` instead of `cp932` coding.

.github/workflows/testing-alpine.yml
Alpine Linux is a popular Linux distribution which not built around `glibc` and `bash` but `musl-libc` and `BusyBox`.
References:
https://distrowatch.com/table.php?distribution=alpine
https://alpinelinux.org
https://hub.docker.com/_/alpine
https://www.gnu.org/software/libc
http://musl.libc.org
https://www.gnu.org/software/bash
https://busybox.net
=> GitHub Actions: run units target on AlplineLinux

Makefile.am, configure.ac
let user can set AR, RANLIB, WINDRES when running configure command.
=> buildsys: expose more configure variables: AR, RANLIB, WINDRES

Units/parser-fypp.r/emptyline.d/README, Units/parser-fypp.r/emptyline.d/input.fy, parsers/fypp.c
The original code examines input line is ended with '&' even when the
input line is empty.
=> Fypp: examine the marker for line continuation unless input is empty

docs/man/ctags-lang-verilog.7.rst, docs/man/ctags.1.rst, man/ctags-lang-verilog.7.rst.in, man/ctags.1.rst.in
- SystemVerilog first.
- add section "Supported Kinds"
- add section "Supported Language Specific Fields"
- add section "TIPS"
- add reference to IEEE Std 1800-2017 (LRM)
=> docs: updates ctags-lang-verilog(7)

circle.yml, docs/_ext/lexers.py
In addition, this change adds "cd docs; make html" to the tests running at circleci.
=> docs: fix more typos in the code for utilzing ctags optlib pygments lexer

docs/_ext/lexers.py
=> docs: as a highlighter, specify CtagsOtplibLexer instance instead of class

README.md
The badges for readthedocs are duplicated.
=> README: revert 65418fa167e972cb73be01531fdb6a8622d8f694

Units/parser-ada.r/ada-string-liteal.d/expected.tags-e, Units/parser-ada.r/ada-string-liteal.d/input.adb, parsers/ada.c
Close #2913.
Ada parser has some functions for skipping input stream.
They don't consider string literals in the stream.
#2913 reports a bug of the inconsideration.
This change fixes the bug in a very limited area.
...
package Generic1 is new Generic_G (Description => +"; " +":");
...
adaParseBlock() tries skipping to ';' from "is".  In this case, as the
result, adaParseBlock() expects the input stream points ';' at the end
of line. However, the expectation was not satisfied because there was a
string literal that included ';' between "new" and ';' at the end of
line.
This change extends skipPastLambda() to skip string literal.
adaParseBlock() calls skipPastLambda() indirectly via
skipPastKeywordOrWord(). As the result, the expectation is satisfied.
Extending other functions for skipping …
=> Ada: skip string literal in a case

.github/workflows/testing-freebsd.yml
=> GitHub Actions: use new freebsd image to avoid ntp related failures

.github/workflows/testing-mac.yml
Quoted from the build log at the platform:
==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.71.catalina.bottle.tar.gz
To upgrade to 2.71, run:
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/258a94bef23057c52818adf64d682af20bc6e09b46eac135047e2b87fc8206c7?response-content-disposition=attachment%3Bfilename%3D%22autoconf-2.71.catalina.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvMjU4YTk0YmVmMjMwNTdjNTI4MThhZGY2NGQ2ODJhZjIwYmM2ZTA5YjQ2ZWFjMTM1MDQ3ZTJiODdmYzgyMDZjNz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmF1dG9jb25mLTIuNzEuY2F0YWxpbmEuYm90dGxlLnRhci5neiUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYxNzIxOTEzM30sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXA …
=> GitHub Actions (MacOS): don't install autoconf explicitly 

Units/parser-ada.r/ada-label.d/args.ctags, Units/parser-ada.r/ada-label.d/expected.tags, Units/parser-ada.r/ada-label.d/input.adb, parsers/ada.c
```
parsers/ada.c:497:41: style: Condition 'token->prev==NULL' is always true [knownConditionTrueFalse]
parsers/ada.c:493:20: note: Assuming that condition 'token->prev!=NULL' is not redundant
parsers/ada.c:497:41: note: Condition 'token->prev==NULL' is always true
parsers/ada.c:507:41: style: Condition 'token->next==NULL' is always true [knownConditionTrueFalse]
parsers/ada.c:503:20: note: Assuming that condition 'token->next!=NULL' is not redundant
parsers/ada.c:507:41: note: Condition 'token->next==NULL' is always true
parsers/ada.c:2025:19: style: Variable 'token' is reassigned a value before the old one has been used. [redundantAssignment]
parsers/ada.c:2023:19: note: token is assigned
parsers/ada.c:2025:19: note: token is overwritten
```
Following  error is false error (The function …
=> Ada : fixed cppcheck errors + added ada-label test

Units/parser-bibtex.r/bib-simple.d/expected.tags, Units/parser-bibtex.r/bib-simple.d/input.bib, parsers/bibtex.c
BibTeX: accept ':' as a part of a name
Close #2934
The change was proposed by @berndf in #2934.
Quoted from the issue:
Since my BibTeX keys are of the form author:year (one of the more
common choices I'd say), the new bibtex parser breaks ctags for me, as
isIdentChar() does not allow a colon.
@masatake added a test case.
=> BibTeX: accept ':' as a part of a name 

win32/ctags_vs2013.sln, win32/ctags_vs2013.vcxproj
This patch adds ability to build ctags using Visual Studio project from x64 native shell
=> build-sys,visual studio: Add x64 build support

win32/appveyor.bat
automake(-1.16) indirectly run from autogen.sh reported:
Can't locate threads.pm in @INC (...  /usr/lib/perl5/5.32/x86_64-cygwin-threads ...) at \
/usr/share/automake-1.16/Automake/ChannelDefs.pm line 23.
threads.pm is listed in https://cygwin.com/packages/x86_64/perl/perl-5.32.1-1.
It is not listed in https://cygwin.com/packages/x86_64/perl_base/perl_base-5.32.1-1.
On the other hand automake requires perl_base, not perl as shown in
https://cygwin.com/packages/summary/automake1.16.html
This change is workaround for the gap.
The gap should be reported to Cygwin project (or automake?).
=> appveyor,cygwin: install perl package explicitly

Tmain/broken-json-output.d/input.f, Tmain/broken-json-output.d/run.sh, Tmain/broken-json-output.d/stdout-expected.txt, main/entry.c, main/entry_p.h, main/mio.c, main/parse.c, win32/appveyor.bat
Close #2948.
When a parser returned RESCAN_FAILED, the original code
just moved the file position.
#2948 indicated reports just moving the file position put
noise to the otuput file; file truncation is needed after
moving the position.
=> main: truncate output file when rescan is failed

Units/parser-cxx.r/template-member-forward-declaration.d/args.ctags, Units/parser-cxx.r/template-member-forward-declaration.d/expected.tags, Units/parser-cxx.r/template-member-forward-declaration.d/input.cpp, parsers/cxx/cxx_parser_block.c
=> C++: parse member variables using templates with forward declared types

.github/workflows/testing-netbsd.yml
It seems that the `NetBSD pkgin repository dependency tree` changed, `autoconf` is not installed along with `automake` now.
=> GitHub Actions(netbsd): add autoconf dependency in .github/workflows/testing-netbsd.yml

parsers/verilog.c
=> SystemVerilog: Avoid using non-ASCII characters

docs/man/ctags.1.rst, man/ctags.1.rst.in
- Use `fileScope``/``F`` instead of ``F/fileScope``.
- Introduce   ``--map-<LANG>`` in addition to ``--langmap``.
=> docs(man): minor improvements for ctags(1)

docs/man/ctags.1.rst, docs/output-json.rst, man/ctags.1.rst.in
- add link to JSON and JSON Lines.
- Now it is not experimental.
=> docs: update the description of JSON output  (#2964)

misc/man-test.py
=> buildsys;man: fix misc/man-test.py third argument can not be an absolute path

extra-cmds/optscript-repl.c
=> optscript: don't use '?" as part of an option

man/Makefile
`BSD sed` no `--version` argument.
=> buildsys;man/Makefile: fix `sed --version` report error when run on macOS

docs/man/ctags-incompatibilities.7.rst, docs/man/ctags.1.rst, main/options.c, main/options_p.h, man/ctags-incompatibilities.7.rst.in, man/ctags.1.rst.in
Close #2890.
Using these variables as source of configuration could be trouble.
Consider the following Makefile:
```
CTAGS=/usr/bin/ctags
tags: $(SOURCE_FILES)
$(CTAGS) $?
```
People can use the Makefile with the following command line:
```
$ export CTAGS=/home/yamato/bin/u-ctags
$ make CTAGS=$CTAGS
```
The user may get a strange warning message:
```
Ignoring non-option in CTAGS variable
```
It is hard for users to understand the meaning of the warning message
if the user doesn't know the variable is used ctags itself as the
source of configuration.
Even u-ctags developers take long time to understand what happened
when #2048 is reported.
=> [INCOMPATIBLE]main: don't read CTAGS and/or ETAGS environment variables 46d54fd 

dsl/qualifier.c
Close #3009.
The empty array caseus an compile error when using
Visual Studio 2017 Build Tools or Visual Studio 2019 Build Tool.
=> dls: remove an unused variable that causes an compile error

Tmain/optscript.d/dict.expected, Tmain/optscript.d/dict.ps, dsl/optscript.c
The original code supports only name type.
$ ./optscript
OPT> << (a) 1 (b) 2 (c) 3  >> (b) get ==
2
OPT>
=> optscript: accept string, integer, and boolean values as keys for a dictionary

circle.yml
https://repo.ius.io/ius-release-el6.rpm is removed.
We install the pre-build python instead.
@leleliu008 provides this solution.
=> circleci (centos6*): install the pre-build Python

autogen.sh
See #3042.
What we found were building ctags was failed with the combination
of /usr/bin/pkg-config and /usr/local/bin/aclocal.
Instead of rejecting the combination, this change reports the paths
for the tools. The reported message may help us find the root cause of
the failure.
=> build-sys: report the path for autoreconf, aclocal and pkg-config at the beginning in autogen.sh

.gitignore, Units/parser-cxx.r/operators.cpp.d/expected.tags, Units/parser-cxx.r/operators.cpp.d/input.cpp, Units/parser-cxx.r/templates-enable-if.d/args.ctags, Units/parser-cxx.r/templates-enable-if.d/expected.tags, Units/parser-cxx.r/templates-enable-if.d/input.cpp, parsers/cxx/cxx_parser_block.c, parsers/cxx/cxx_parser_tokenizer.c
Fix #2867 in a different way, so the parser doesn't get confused by unbalanced less-than/greater-than signs and the file reported in #3053 is parsed properly.
Fixes #3053
=> C++: avoid getting confused by unbalanced less-than/greater-than signs

parsers/cxx/cxx_parser_tokenizer.c
=> CXX: Avoid assert with broken input in debug builds

Units/parser-cxx.r/cxx11-user-defined-literals.d/expected.tags, Units/parser-cxx.r/cxx11-user-defined-literals.d/input.h, parsers/cxx/cxx_parser_function.c
Close #2883.
See https://en.cppreference.com/w/cpp/language/user_literal.
=> C++: extract operators for user-defined literals

Makefile.am, Units/parser-sql.r/sql_pgSQL_guest.d/args.ctags, Units/parser-sql.r/sql_pgSQL_guest.d/expected.tags, Units/parser-sql.r/sql_pgSQL_guest.d/input.sql, configure.ac, docs/man-pages.rst, docs/man/ctags-lang-sql.7.rst, main/options.c, main/parse.c, main/parse.h, main/parse_p.h, main/promise.c, main/promise.h, main/strlist.c, main/strlist.h, man/Makefile, man/ctags-lang-sql.7.rst.in, parsers/jscript.c, parsers/sql.c
Close #3017.
PostgreSQL allows users defining functions and procedures with languages other than SQL.
Languages for defining a procedures or functions are called procedural languages.
From the view point of the syntax of the base language (SQL), the definitions are
just strings.
This change recognizes the strings and LANGUAGE keywords, and runs
guest parsers on the strings if syntactical conditions are met.
=> SQL: run guest parsers on strings where procedures are defined with procedural languages

Tmain/list-kinds-full.d/stdout-expected.txt, Tmain/nested-subparsers.d/stdout-expected.txt, Units/parser-cxx.r/attribute.cpp.d/expected.tags, Units/parser-cxx.r/complex-macros.d/args.ctags, Units/parser-cxx.r/complex-macros.d/expected.tags, Units/parser-cxx.r/complex-macros.d/input.cpp, Units/parser-cxx.r/cxx11-lambdas.d/expected.tags, Units/parser-cxx.r/cxx11enum.cpp.d/expected.tags, Units/parser-cxx.r/functions.cpp.d/expected.tags, Units/parser-cxx.r/template-prototype.d/args.ctags, Units/parser-cxx.r/template-prototype.d/expected.tags, Units/parser-cxx.r/template-prototype.d/input.cc, Units/parser-cxx.r/template-specializations.d/expected.tags, parsers/cxx/cxx_debug.c, parsers/cxx/cxx_parser.c, parsers/cxx/cxx_parser_function.c, parsers/cxx/cxx_parser_internal.h, parsers/cxx/cxx_scope.c, parsers/cxx/cxx_scope.h, parsers/cxx/cxx_tag.c, parsers/cxx/cxx_token.c, parsers/cxx/cxx_token.h
Close #3045.
Parameters in functions were tagged.
This change extends it.
With this change, parameters in prototypes are tagged.
It is usual that a parameter in a prototype has no name. In such a case, this change generates an anonymous name.
=> Cxx: extract parameters in a prototype

docs/man/ctags-lang-sql.7.rst, man/ctags-lang-sql.7.rst.in
This reverts commit 5c46072da18492597296b8da5d8266a1d2eaca60.
This re-introduce commit 1469a65ff404b21e9245c39b0791c54ed0b03d7c correctly.
In 1469a65ff404b21e9245c39b0791c54ed0b03d7c, I changed docs/man/ctags-lang-sql.7.rst
directly. I should not do it. Instead, in this change, I changed man/ctags-lang.sql-7.rst.in.
=> docs(web): revert a wrong change for the SQL man page and update it in correct steps

docs/man/ctags-client-tools.7.rst, docs/man/ctags-lang-iPythonCell.7.rst, docs/optlib.rst, man/ctags-client-tools.7.rst.in, man/ctags-lang-iPythonCell.7.rst.in
See the line 510:
```
508:	// in /tmp/input.pp
509:	class foo {
510:		int bar;
511:	}
```
=> docs,man: Fix typos

configure.ac
=> build-sys: don't refer to m4 directory

Units/parser-cxx.r/function-return-types.d/expected.tags, Units/parser-cxx.r/function-return-types.d/input.cpp, Units/parser-cxx.r/keyword-in-return-type.d/args.ctags, Units/parser-cxx.r/keyword-in-return-type.d/expected.tags, Units/parser-cxx.r/keyword-in-return-type.d/input.cc, parsers/cxx/cxx_parser.c
Close #3068.
The original code could not extract f in
class X *f();
=> C++: use () to detect a function or prototype even if the statement starts with "class"

Units/parser-cxx.r/struct-keyword-not-for-defining-struct.d/args.ctags, Units/parser-cxx.r/struct-keyword-not-for-defining-struct.d/expected.tags, Units/parser-cxx.r/struct-keyword-not-for-defining-struct.d/input.cc, parsers/cxx/cxx_parser.c
Close #2840.
The original code assumed a statement startnig from struct as a
definition of a struct. This caused that the parser failed in
recognizing an operator= definition (or prototype) returning a struct typed data.
=> C++: recognize operator= even if the statement starts from struct, class or union

docs/contributions.rst
This is a fix of #3082 following @k-takata san's advices.
=> docs: Testing a PR locally before being merged  (updated)

Makefile.am
`make tmain` following `configure` fails.
```
$ make distclean
...
$ ./autogen.sh
...
$ ./configure
...
$ make tmain
...
CC       main/libctags_a-repoinfo.o
main/repoinfo.c:5:10: fatal error: main/repoinfo.h: No such file or directory
...
```
The dependency of repoinfo.o with repoinfo.h is defined, but the dependency of libctags_a-repoinfo.o with repoinfo.h is not defined.
=> build: fix repoinfo.h dependency

Tmain/lang-sequel.d/run.sh
`make distcheck` fails on Ubuntu 20.04 on Windows 10 WSL2.
These are fixes for them.
I also don't understand why `Tmain/epoch-field.d/run.sh` and  `Tmain/readtags-qualifier-begin.d/run.sh` passed on `make tmain`.
The fix of `Tmain/lang-sequel.d/args.ctags` is only for `make distcheck`.  But I don't understand why it passes on `fedora33_distcheck` CI test.
I found these issues during debugging #3054.
=> Tmain: fix fails on make distcheck (fix for #3093)

circle.yml
None in the build process removes the core file created during running
./configure. It can make "make distcheck" fail.
=> circleci(fedora33_distcheck): don't make core when running ./configure

autogen.sh
autogen.sh enabled xtrace (-x) to make remote debugging easier on #1534.
But this makes difficult local autotools debugging.  Valuable errors are hidden by verbose trace messages.
Enable xtrace when environment variable `CI` is set (cf. #3081).
Unused variable `tools` is also removed.
=> build-sys: disable xtrace unless CI is set in autogen.sh

circle.yml
Autoconf on centos6 is too old.
=> circleci(centos6): don't run the tests on centos6 anymore

.github/workflows/testing-alpine.yml, .github/workflows/testing-cygwin.yml, .github/workflows/testing-freebsd.yml, .github/workflows/testing-gnulinux.yml, .github/workflows/testing-mac.yml, .github/workflows/testing-msys2.yml, .github/workflows/testing-netbsd.yml, .github/workflows/testing-openbsd.yml, .github/workflows/testing-with-vlagrind.yml, circle.yml, makefiles/testing.mak, win32/appveyor.bat
Currently we define our own environment variables for each CI
platform: APPVEYOR, CIRCLECI, TRAIVS and GITHUBACTIONS. We don't have
to define them; we can just refer to CI environment variable.
Originally posted by @k-takata in #3080 (comment):
Most of the CI environments set the CI environment variable to
true (or True).
https://docs.github.com/actions/reference/environment-variables
https://www.appveyor.com/docs/environment-variables/
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
If we don't need to distinguish each CI environment and just want
to know whether we are running the tests on any CI environment, we
might be able to use the CI variable.
Close #3081
=> ci-env: use unified CI environment variable

misc/units, misc/units.py
This PR fixes the diff output on unit tests.
The current input file order is `diff filtered expected`.  This is not a typical order.
This PR fixes to `diff expected filtered`.
This is also consistent with the other usage of diff in the scripts as follows;
misc/unit.py
```python
1026              subprocess.run(['diff', '-U',
1027                  str(DIFF_U_NUM), '--strip-trailing-cr',
1028                  expected, actual],
1029                  stdout=f, stderr=subprocess.STDOUT)
```
misc/unit
```sh
742          diff -U 0 -I '^!_TAG' --strip-trailing-cr "${fexpected}" "${ofiltered}" > "${odiff}"
```
***
Another example of "typical order";
```diff
$ cat from
from
$ cat to
to
$ diff -u from to
--- from        2021-08-09 22:41:49.836670500 +0900
+++ to  2021-08-09 22:41:56.396670500 +0900 …
```
=> Units: change the order of input files for diff

configure.ac, main/main.c
On Windows, the shell doesn't expand wildcards.
Ctags should expand them by ourselves.
See also: https://github.com/universal-ctags/ctags/issues/3014#issuecomment-863628889
=> build-sys,main,mingw: Enable MANUAL_GLOBBING

Tmain/readtags-qualifier-op-regexp-quote.d/run.sh, Tmain/readtags-qualifier-sf-cond.d/input.c, Tmain/readtags-qualifier-sf-cond.d/output.tags, Tmain/readtags-qualifier-sf-cond.d/run.sh, Tmain/readtags-qualifier-sf-cond.d/stdout-expected.txt, dsl/dsl.c, dsl/dsl.h
In filter expression of readtags, you could use `(if ...)`.
`(cond (condtion0 expression0) (condtion1 expression1) ... )` is generic version of `if`.
`cond` will be useful when we introduce "formatter" to readtags.
Minor improvements for readtags are inclluded.
=> readtags/dsl: introduce cond special form

main/seccomp.c
Add statx to seccomp rules as a fallback for newfstatat. This is
specially important for the case where the newfstatat system call is not
available on a platform using glibc >= 2.33
This patch was created as an effort to fix FTBFS builds on Ubuntu after the glibc 2.33 migration. See https://bugs.launchpad.net/ubuntu/+source/universal-ctags/+bug/1934829 for further reference.
=> Add statx to seccomp rules

.github/workflows/testing-gnulinux.yml, circle.yml
But `fedora33_cross_aarch64` is kept as is for now.
=> circleci: use fedora34

docs/optlib.rst
This PR updates the specification of regex engine and is fix for #3034.
=> Docs: regex specification update

configure.ac
Fix for #3137 preventing glthread_lock_init() from causing a segmentation fault.
=> cygwin: disable weak reference for pthread library

Units/parser-itcl.r/itcl-3.d/expected.tags, Units/parser-itcl.r/itcl-3.d/input.tcl, Units/parser-itcl.r/no-itcl-1.d/input.tcl, parsers/itcl.c, parsers/tcl.c, parsers/tcl.h
Close #3136.
Close #3139.
The original code requires 'package require Itcl' to run Itcl
subparser from Tcl parser. However, `itcl::` can be used in
a script having no 'package require Itcl' statement.
Suggested by @bigfaceworm.
=> ITcl: don't require 'package require Itcl'

Units/parser-ttcn.r/ttcn-types.d/input.ttcn, parsers/ttcn.c
Right now comments don't get skipped all the way, leading to code like
type enumerated Enum {
/* a comment */
Value
}
or
type enumerated Enum {
// a comment
Value
}
resulting in "Value" not being present in the output, due to `getNonWhiteSpaceChar()` returning `'*'` (for `/* */`comments) or `'\n'` (for `//` comments)
=> ttcn: Skip comments correctly

parsers/lisp.c
Hello!
On latest master `clang version 10.0.0-4ubuntu1` produces following warnings:
```
parsers/lisp.c:128:7: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
if (EQN("DEFUN"))
^~~~~~~~~~~~
parsers/lisp.c:123:51: note: expanded from macro 'EQN'
#define EQN(X) strncmp(vStringValue (hint) + 4, X + 3, n) == 0
~~^~~
parsers/lisp.c:128:7: note: use array indexing to silence this warning
parsers/lisp.c:123:51: note: expanded from macro 'EQN'
#define EQN(X) strncmp(vStringValue (hint) + 4, X + 3, n) == 0
^
parsers/lisp.c:133:7: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
if (EQN("DEFVAR"))
^~~~~~~~~~~~~
parsers/lisp.c:123:51: note: expanded from macro 'EQN'
#define EQN(X) strncmp(vStringValue (hint) + 4, X + 3, n) == 0 …
```
=> Use `&X[3]` instead of `X + 3` to fix clang warnings

dsl/es.c, dsl/optscript.c
Hello!
While chasing down following warnings produced by `clang version 10.0.0-4ubuntu1` I thought we can remove the redundant code safely:
```
dsl/es.c:2241:18: warning: explicitly assigning value of variable of type 'char' to itself [-Wself-assign]
default:  c0 = c0  ; break;
~~ ^ ~~
...
dsl/optscript.c:1524:1: warning: unused function 'vm_estack_count' [-Wunused-function]
vm_estack_count (OptVM *vm)
^
```
Thanks!
=> Remove redundant code

Units/parser-cpreprocessor.r/if0-false-with-param.c.d/args.ctags, Units/parser-cpreprocessor.r/if0-true-with-param.c.d/args.ctags, Units/parser-cpreprocessor.r/macroexpand.d/args.ctags, Units/parser-cpreprocessor.r/macros-specified-with-param.c.d/args.ctags, Units/parser-fypp.r/run-alt-guest.d/args.ctags, Units/parser-ldscript.r/ld-symtab.d/args.ctags, docs/man/ctags.1.rst, docs/output-tags.rst, docs/parser-cxx.rst, main/options.c, main/parse.c, man/ctags.1.rst.in
`.' was used in the --param option like --param-Fypp:guest=....
This change replaces `.' with `:'.
There are two reasons for the replacement; (A) `:' implies a field, and
(B) `.' is used in --roledef-<LANG>.<KIND> option.
ctags still accept `.' but warns that using `.' is obsolete.
=> [SELF-INCOMPATIBLE]main,Units,docs: use `.' as the separator in --param instead of `:'

parsers/tex.c
Found by: [scan-build](https://clang-analyzer.llvm.org/scan-build)
=> Tex: add missing `break` statement

Units/simple-kconfig.d/expected.tags, optlib/kconfig.c, optlib/kconfig.ctags
Quoted from a comment in kconfig.h of Linux:
```C
/*
* IS_ENABLED(CONFIG_FOO) evaluates to 1 if CONFIG_FOO is set to 'y' or 'm',
* 0 otherwise.  Note that CONFIG_FOO=y results in "#define CONFIG_FOO 1" in
* autoconf.h, while CONFIG_FOO=m results in "#define CONFIG_FOO_MODULE 1".
*/
```
ctags already tagged CONFIG_FOO as a configPrefix extra tag for FOO.
This change exnted the extra tag.  With this change, ctags tags
CONFIG_FOO_MODULE as a configPrefix extra tag in addition to
CONFIG_FOO.
=>  Kconfig: tag CONFIG_FOO_MODULE as configPrefixed extra tag for FOO 

Units/parser-vhdl.r/vhdl-crash.d/README, Units/parser-vhdl.r/vhdl-crash.d/input.vhd, parsers/vhdl.c
=> VHDL: avoid dereferencing NULL as a tagEntryInfo

.github/workflows/cross-compile-android-ndk.yml, .github/workflows/cross-compile-mingw-w64.yml, .github/workflows/testing-gnulinux.yml
The `ubuntu-16.04` github actions environtment will
be removed on September 20, 2021. Migrate to `ubuntu18.04` or `ubuntu-latest` instead. For more details see https://github.com/actions/virtual-environments/issues/3287
=> GitHub Actions: remove the ubuntu-16.04 environment due to it will be removed 3 days later

dsl/es.h
Fix a spelling typo "lenght" in es.h.
Signed-off-by: Masanari Iida <standby24x7@gmail.com>
=> 　dsl: Fix a typo in es.h

main/lregex.c, main/options.c
If a user tries to use p/{pcre2} though one's ctags binary is not linked to pcre2, give a warning.
This change may reduce false-positive bug reports
=> main: give warning when pcre2 is not linked

Units/parser-ada.r/ada-generic-in-package.d/expected.tags-e, Units/parser-ada.r/ada-generic-in-package.d/input.ads, parsers/ada.c
Close #2925.
The original code reset the parsing mode to ROOT
at the end of generic package.
This setting causes a bug if the generic package is
not declared at the top level.
=> Ada: adjust parsing mode at the end of generic

Units/parser-ada.r/ada-generic-in-package.d/args.ctags, Units/parser-ada.r/ada-generic-in-package.d/expected.tags-e, Units/parser-ada.r/ada-generic-in-package.d/input_1.adb, Units/parser-ada.r/ada-generic-in-package.d/input_2.ads, parsers/ada.c
Improving generic procedure/function handling.
When testing https://github.com/universal-ctags/ctags/pull/2928 
I noticed formal parameters of generic procedure/functions are not  tagged.
=> Ada : Improve formal parameter tags in generic function/procedure

main/mini-geany.c
This is now needed in Geany too since the introduction of optscript
so update mini-geany accordingly.
=> mini-geany: Call initRegexOptscript() in ctagsInit()

Tmain/kind-long.d/stdout-expected.txt, Tmain/list-kinds-full.d/stdout-expected.txt, Tmain/list-roles-with-kind-names.d/stdout-expected.txt, Tmain/list-roles.d/stdout-expected.txt, Tmain/nested-subparsers.d/stdout-expected.txt, Units/parser-cpreprocessor.r/macro-condition-role.d/args.ctags, Units/parser-cpreprocessor.r/macro-condition-role.d/expected.tags, Units/parser-cpreprocessor.r/macro-condition-role.d/input.h, parsers/asm.c, parsers/c.c, parsers/cpreprocessor.c, parsers/cpreprocessor.h, parsers/cxx/cxx_parser.c, parsers/cxx/cxx_tag.c, parsers/cxx/cxx_tag.h, parsers/dts.c, parsers/ldscript.c, parsers/protobuf.c
An example session:
$ cat /tmp/foo.c
#ifdef FOO
#elif defined(BAR)
#endif
$ ./ctags --sort=no --roles-C.'{macro}'='+{condition}' --extras=+r --fields=+r -o -  /tmp/foo.c
FOO   /tmp/foo.c      /^#ifdef FOO$/;"        d       roles:condition
BAR   /tmp/foo.c      /^#elif defined(BAR)$/;"        d       roles:condition
=> CPreProcessor: extract macro names used in #if/#ifdef/#elif conditions as reference tags

Units/parser-sql.r/sql-plsql-ccflags.d/input.sql
The input file should be included in
56b419e90d4dd933cf7c417184551f1087d16df4.
=> Units(SQL): add a missing test input

docs/parser-gdscript.rst, docs/parsers.rst
Quick page written up for #3199.
=> Add gdscript entry in new parser docs

Units/parser-pascal.r/simple-pascal.d/args.ctags, Units/parser-pascal.r/simple-pascal.d/expected.tags, Units/parser-pascal.r/simple-pascal.d/input.pas, parsers/pascal.c
Parse the signatures and return type for functions and procedures in Pascal.
This features is ported from the Geany Pascal parser where we use this code already for many years and it might be useful for others too.
=> Pascal: Add parsing of function/proc signatures

parsers/pascal.c
Follow-up to #3205.
Sorry for the inconsistencies in code styling I introduced.
=> Pascal: Consistently use spaces before opening parentheses

configure.ac
On "run units target on MSYS2"/MSYS CI environment, many
Tmain cases are failed with segmentation faults as show in
in regcomp.c of gnulib.
change.
This change is a work-around. The root cause is unknown.
Close #3225, #3226, and #3227.
=> build-sys: use the regex module in gnulib in single thread mode

Tmain/list-roles.d/stdout-expected.txt, Tmain/list-subparsers-all.d/stdout-expected.txt, Units/parser-gemspec.r/simple-gemspec.d/args.ctags, Units/parser-gemspec.r/simple-gemspec.d/expected.tags, Units/parser-gemspec.r/simple-gemspec.d/input.gemspec, docs/news.rst, main/parsers_p.h, parsers/gemspec.c, source.mak, win32/ctags_vs2013.vcxproj, win32/ctags_vs2013.vcxproj.filters
Before developing subparser for rails, I'm evaluating the interface for subparsers exported from Ruby parser.
Gemspec subparser works. But scanning "do" in subparser is not a good idea, I think. scanning "do" should be done in Ruby parser, and the parser should call the method of subparsers when "do" is found.
Anyway, having a parser for Gemspec is not bad. So I made this pull request with this incomplete version.
=> GemSpec: new parser

Units/parser-tex.r/newcommand.d/expected.tags, Units/parser-tex.r/newcommand.d/input.tex, Units/parser-tex.r/newenvironment.d/expected.tags, Units/parser-tex.r/newenvironment.d/input.tex, parsers/tex.c, parsers/tex.h
In addition to the macros already parsed, the old Geany readline-based parser also parses the following latex macros which may be useful:
- `\renewcommand`, `\providecommand`
- tex `\def\cmd{param}`
- `\DeclareMathOperator`
- `\newenvironment`, `\renewenvironment`
- `\newtheorem`
This pul request adds these and introduces the corresponding kinds for them.
=> Tex: parse some more latex macros

docs/other-projects.rst
The GLSL parser is just a synonym for the C parser, see
https://github.com/geany/geany/pull/3073
The Ferite language is dead and isn't worth supporting, see
https://github.com/geany/geany/pull/3075
=> Remove GLSL and Ferite from the list of parsers in Geany

Units/parser-basic.r/simple.bas.d/expected.tags, Units/parser-basic.r/simple.bas.d/input.bas, parsers/basic.c
There were some improvements in the Geany parser, mostly related to extraction of variables in `dim` statements.
Also, the uctags parser determined the used basic dialect based on file extension which wouldn't work very well for Geany as it parses files using MIO buffer. What the parser did appears quite a non-standard approach with the file extensions and I haven't seen it in any other parser. What I did is that I basically just merged all the basic dialect keywords into one and allowed both labels like `label:` and `.label` for any kind of file - hope it's OK.
I added the `dim` extraction code as it was in Geany and then made a few commits on top of that as there were some minor problems in the code and finally made a commit to cleanup the code a bit.
=> Basic: various improvements from Geany

configure.ac
Fixes: https://github.com/universal-ctags/ctags-win32/issues/14
When static linking was used and PCRE2 was enabled, link errors occurred.
Fixed it by adding `-DPCRE2_STATIC` to CFLAGS.
=> buildsys,mingw: Fix link error with PCRE2

win32/license/LICENCE.pcre2
PCRE2 will be linked after #3256.
We should include PCRE2's LICENCE file in the Windows zip package.
=> packaging,win32: Add PCRE2's LICENCE file

configure.ac
This replaces #3228.
Weak symbols don't work also on MSYS2. Stop using the feature.
`$host` on Cygwin and MSYS2 looks like `x86_64-pc-cygwin` and
`x86_64-pc-msys`. No need to add an `*` at the end of `*-cygwin`
=> build-sys: Don't use weak symbols on MSYS2

Units/parser-kotlin.r/kotlin-backticks.d/expected.tags, Units/parser-kotlin.r/kotlin-backticks.d/input.kt, peg/kotlin_post.h
Valgrind reports the mem error.
=> Kotlin: don't delete vString before making the tag for the string

Units/parser-openapi.r/openapi.d/expected.tags, Units/parser-openapi.r/swagger.d/expected.tags, parsers/openapi.c
@segoon, #3258 is too large to review and accept at once.
I made a new pull request based on #3258.
This pull request comes from multiple commits that are in #3258 and acceptable parts.
=> OpenAPI: dissolve #3258

Tmain/list-roles.d/stdout-expected.txt, Units/parser-tex.r/xinput.d/args.ctags, Units/parser-tex.r/xinput.d/expected.tags, Units/simple-texBeamer.d/args.ctags, Units/simple-texBeamer.d/expected.tags, parsers/tex.c
In Geany we also have environment usages reported by the current parser. I'm not sure if it's interesting for uctags too - I created this pull request where I added these as reference tags. I'm not sure about whether I used the right naming for the role. Also, I made these disabled by default - not sure what the current convention enabling/disabling these kinds of tags is - please check.
=> latex: Add reference tags for environment usage introduced by \begin{MyEnv}

Units/parser-c.r/enum-bit-fields.d/args.ctags, Units/parser-c.r/enum-bit-fields.d/expected.tags, Units/parser-c.r/enum-bit-fields.d/input.c, parsers/cxx/cxx_parser.c
The original code could not extract enum-typed
structure members having bit-width like "mber"
in the input:
enum token_type {
ID, KEYWORD,
};
struct token {
enum token_type	mber : 8;
};
Close #3223.
=> Cxx: accept bit-width for enum-typed structure member

optlib/rpmMacros.c, optlib/rpmMacros.ctags
With this map (macros.\*), ctags could not choose C++ parser
when macros.h is specified as input.
(macros.\*) is too generic as a pattern.
Close #3286.
=> [SELF-INCOMPATIBLE] RpmMacros: remove (macros.*) from the map

circle.yml
Don't do 'yum install libjansson-devel' because ubi8 doesn't provide it.
=> circleci: use ubi8 instead of centos8

Units/parser-openapi.r/openapi.d/expected.tags, Units/parser-openapi.r/openapi.d/input.yaml, parsers/openapi.c, parsers/yaml.c, parsers/yaml.h
The technique used in OpenAPI may be helpful to implement another YAML subparser.
So, I moved the code implementing the technique to the YAML parser experimentally in this change.
The original code uses an array of keywords for pointing out interesting tokens.
This change uses a string for the same purpose. The routines in this change convert the string to an array of keywords.
Till a real specification and its implementation becomes available, we call the format of the string Ypath.
=> Yaml,OpenAPI: make OpenAPI parser's stack related code reusable

.gitignore, Tmain/list-roles.d/stdout-expected.txt, Units/parser-basic.r/freebasic-decls.d/args.ctags, Units/parser-basic.r/freebasic-decls.d/expected.tags, Units/parser-basic.r/freebasic-decls.d/input.bas, parsers/basic.c, peg/.gitignore
=> Basic: extract declarations as reference tags (partially derived from #3276)

Tmain/list-subparsers-all.d/stdout-expected.txt, Units/parser-markdown.r/footnotes.d/args.ctags, Units/parser-markdown.r/footnotes.d/expected.tags, Units/parser-markdown.r/footnotes.d/input.md, Units/parser-rmarkdown.r/simple-rmarkdown.d/args.ctags, Units/parser-rmarkdown.r/simple-rmarkdown.d/expected.tags, Units/parser-rmarkdown.r/simple-rmarkdown.d/input.rmd, docs/man/ctags-lang-iPythonCell.7.rst, docs/man/ctags-lang-rmarkdown.7.rst, docs/news.rst, main/parsers_p.h, man/Makefile.am, man/ctags-lang-iPythonCell.7.rst.in, man/ctags-lang-rmarkdown.7.rst.in, parsers/markdown.c, parsers/markdown.h, parsers/rmarkdown.c, source.mak, win32/ctags_vs2013.vcxproj, win32/ctags_vs2013.vcxproj.filters
The parser supports `{r label}` syntax as described in https://bookdown.org/yihui/rmarkdown/.
`{r` part is parsed to choose a guest.
`label` in `label}` part is tagged as a chunkLabel kind object.
=> RMarkdown: new parser

Tmain/list-roles.d/stdout-expected.txt, Units/parser-elm.r/elm-imports.d/expected.tags, Units/parser-elm.r/elm-namespaces.d/expected.tags, Units/parser-elm.r/elm-optlist-compatibility.d/expected.tags, docs/man/ctags-lang-elm.7.rst, man/ctags-lang-elm.7.rst.in, peg/elm.peg, peg/elm_pre.h
An imported modules still have `roles:imported`, but the items it brings in are listed as `roles:exposed`.
This has been discussed in [#PR3312](https://github.com/universal-ctags/ctags/pull/3312#issuecomment-1083372401) and issue #3319.
Strictly speaking this is a breaking change, as you will see Units/parser-elm.r/elm-optlist-compatibility.d/expected.tags has had to change. However I believe it doesn't actually break anything. The original optlib parser was designed to work with [Vim tagbar](https://github.com/preservim/tagbar). Neither that, nor [the specific configuration](https://github.com/bitterjug/vim-tagbar-ctags-elm/blob/master/ftplugin/elm/tagbar-elm.vim) referenced roles. Therefore I think this is safe to include.
However, if you think it is better to reject this pull request …
=> Elm: roles:imported -> roles:exposed for non-modules

Tmain/list-roles.d/stdout-expected.txt, peg/elm.peg, peg/elm_pre.h
@niksilver, I forgot one important thing in the last review; roles must be defined per kind.
Kinds cannot share a role definition.
```
$ ./ctags --list-roles=Elm
#KIND(L/N)     NAME     ENABLED DESCRIPTION
c/constructor  exposed  on      item exposed from a module
f/function     exposed  on      item exposed from a module
m/module       imported on      module imported
t/type         exposed  on      item exposed from a module
```
is better than
```
$ ./ctags --list-roles=Elm
#KIND(L/N)     NAME     ENABLED DESCRIPTION
c/constructor  exposed  on      item exposed from a module
c/constructor  imported on      module imported
f/function     exposed  on      item exposed from a module
f/function     imported on      module imported
m/module       exposed  on      item exposed from a module …
```
=> Elm: fix wrongly shared role definitions between kinds

.github/workflows/cross-compile-android-ndk.yml
Android NDK r23 is the latest LTS version.
versions below r23 are marked as obsolete, and they are no longer supported.
Reference:
https://developer.android.com/ndk/downloads
https://github.com/android/ndk/wiki/Unsupported-Downloads
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#environment-variables-3
=> GitHub Actions: Use Android NDK r23 to build

docs/Makefile
when user just run `make`, no action name is given, we should show help messages.
checking if sphinx-build is installed is involved in certain actions, not all,
for example, if user run `make clean` or `make help`, we do not need to check sphinx-build if is installed.
old code use `which` command, `which` command is not a builtin command in some shell. it is not pre-installed in some os.
we usually use `command` command to check if a command is exist.
`command` command is a builtin command in all different shells.
I removed many lines `@echo`, becuase per line shell code runs in a seperate shell.
I removed them let them run in one shell, it can improve performance.
=> buildsys: improve docs/Makefile

configure.ac
on FreeBSD and OpenBSD, most libs are install in /usr/local/lib, this location is not searched by linker by default.
Reference:
https://wiki.freebsd.org/WarnerLosh/UsrLocal
close #3338
=> buildsys: fix ld can not find -liconv on FreeBSD and OpenBSD

.github/workflows/testing-alpine.yml, makefiles/testing.mak, man/Makefile.am, man/build.sh
`man/Makefile.am` use `GNU make` extension syntax which is not compatible with `BSD make`.
`GNU make` support builtin functions and user defined functions, `BSD make` do not support functions.
`GNU make` Pattern-Rules syntax is not compatible with `BSD make`'s.
most `GNU make` supported Automatic Variables that `BSD make` do not support. both support `$@`, but `BSD make` do not support `$<`, `$^` which is often used.
both support `shell assignment operator`(!=), but this feature included in `GNU make` 4.0, which was released in 2013-10-09.
macOS pre-install `GNU make` version is 3.8.1
to summarize, if we want to support `BSD make`, we should do most jobs in shell script.
Makefile just act as a proxy which invoke shell script to do real jobs. …
=> buildsys: rewite man/Makefile.am

circle.yml, makefiles/testing.mak
Close #3360.
Running check-gen test target makes sense only if the test is run in
git repo.
=> check-gen: run the target only in git repo

parsers/c-based.c, parsers/c.c, parsers/vera.c, source.mak, win32/ctags_vs2013.vcxproj, win32/ctags_vs2013.vcxproj.filters
This is what I proposed in
https://github.com/universal-ctags/ctags/issues/3327
with some modifications:
1. I got a bit lazy and didn't remove any code from `c.c` which I left more or less as it was before - I could remove the extra languages if desired, I'm just not sure if it's worth the work since this file probably won't be actively maintained.
2. I also removed Vera from `c-based.c` (and use the parser from `c.c`). The language seems to be mostly dead without any proper documentation and this makes `c-based.c` hard to maintain because nobody knows properly what code is there because of Vera and what it should do. `c.c` seems to be a good graveyard for Vera to me.
I really just fixed the compilation errors and didn't go through the parser in detail - I'm pretty sure that there's some …
=> split c.c into two parts

Tmain/tag-relative-option-in-etags.d/run.sh
eb101098a6ae97785df01e372082c4be71f038f7 renamed direq defined in
utils.sh to direq_maybe. Though e-ctags-output.d used the function,
the renaming was not reflected to the test case. As a result,
the input file, run.sh deleted indirect/src/input.c unexpectedly.
=> Tmain(tag-relative-option-in-etags.d): use direq_maybe helper shell function

Units/parser-ldscript.r/lds-macro-expansion.d/args.ctags, Units/parser-ldscript.r/lds-macro-expansion.d/expected.tags, Units/parser-ldscript.r/lds-macro-expansion.d/input.lds.S, parsers/cpreprocessor.c, parsers/cpreprocessor.h, parsers/cxx/cxx_parser_tokenizer.c, parsers/fypp.c, parsers/ldscript.c
Following options are neede for expansion:
--fields=+{signature}
--fields-CPreProcessor=+{macrodef}
-D option is for defining a macro and its definiton from
command line.
If --param-CPreProcessor._expand=1 option is given, macros
defined in the same input file are expanded.
Ths code is mostly based on Cxx parser.
=> LdScript: expand C preprocessor macros

main/numarray.c, main/ptrarray.c
Calling ptrArrayDeleteItem in a situation where the allocated array is fully used
(curent-> count == current-> max) caused memmove to access outside the malloced area.
ptrArrayRemoveItem and {char,uchar,int,uint,long,ulong}ArrayDeleteItem have the same problem.
```
$ LD_PRELOAD=libefence.so EF_ALLOW_MALLOC_0=1 ctags --langmap=c:.c.h --version
Electric Fence 2.2 Copyright (C) 1987-1999 Bruce Perens <bruce@perens.com>
Segmentation fault (core dumped)
```
```
$ valgrind  ctags --langmap=c:.c.h --version
==4870== Memcheck, a memory error detector
==4870== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==4870== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==4870== Command: ctags --langmap=c:.c.h --version
==4870==
==4870== Invalid read of size 8
==4870== …
```
=> main: fix reading outside malloced area.

.gitignore, autogen.sh
Close #3378.
Inspired from #3378 reported by @Shane-XB-Qian.
It seems that aclocal.m4 generated in the last time when
autogen.sh run can be a trouble of building.
=> build-sys: force regenerating aclocal.m4

mk_mvc.mak
The `del` command doesn't accept `/` as a path separator.
The extension of object file is `.obj`, not `.o`.
=> build-sys: Fix clean target of mk_mvc.mak

Tmain/input-encoding-option.d/run.sh, Tmain/invalid-encoding-option.d/run.sh, Tmain/no-input-encoding-option.d/run.sh, Tmain/output-encoding-option.d/run.sh, Tmain/utils.sh
Though iconv command is available, there is a case
that encodings used in test cases are not available.
e.g. the ubi8 container doesn't provide shift_jis
encoding unless installing glibc-langpack-ja package.
=> Tmain: check the availability of iconv encodings

Tmain/input-encoding-option.d/run.sh, Tmain/invalid-encoding-option.d/run.sh, Tmain/no-input-encoding-option.d/run.sh, Tmain/output-encoding-option.d/run.sh, Tmain/utils.sh, Units/parser-cxx.r/variable-declarations.cpp.d/args.ctags, Units/parser-cxx.r/variable-declarations.cpp.d/expected.tags, Units/parser-cxx.r/variable-declarations.cpp.d/input.cpp, parsers/cxx/cxx_parser_tokenizer.c
=> Cxx: skip __declspec()

appveyor.yml
Currently, the Cygwin tests are failing because of this error:
```
mbox Parse Errors:  line 12: The current ini file requires at least version 2.903 of setup.
Please download a newer version from https://cygwin.com/setup-x86_64.exe
```
And, even after setup-x86_64.exe has been updated, they are failing with
this error (see #3394):
```
CHKGEN     check-genfile
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>
```
I have no ideas how to fix this.
We already run the Cygwin tests also on GitHub Actions. Running the same
tests on AppVeyor is redundant.
Disable the Cygwin tests on AppVeyor for now.
=> appveyor: Disable Cygwin tests

circle.yml, makefiles/testing.mak
Git on CentOS 7 is very old and doesn't support `eol=crlf` in `.gitattributes`.
Skip `make check-genfile` for the win32 directory.
=> CircleCI: Skip checkgen for win32 on CentOS 7

docs/windows.rst, win32/appveyor.bat
Close #3397
* Change the `mingw` build on AppVeyor to use mingw-w64 (from msys2) instead of the original version of mingw.
(Should we move the `mingw` build from AppVeyor to GitHub Actions?)
* Updated the document.
=> AppVeyor,docs: Drop support for mingw.org

.gitattributes
`.gitattributes` also affected the Visual Stdio files in `misc/packcc/`.
But, that should set in the packcc repository if needed.
Restrict the setting only for the `win32` directory.
=> win32: Set eol only for win32 directory

Units/parser-scss.r/placeholder.d/expected.tags, Units/parser-scss.r/selectors.d/expected.tags, Units/parser-scss.r/variable.d/expected.tags, optlib/scss.c, optlib/scss.ctags
=> Remove punctuation from SCSS classes & identifers

Tmain/utils.sh
"ioconv -l" of Cygwin running on Git Hub Actions reports "I/O erorr".
The message may come from https://git.savannah.gnu.org/gitweb/?p=libiconv.git;a=blob;f=src/iconv.c;h=e3932e5f18e0484972aa1f92c797e5f13ae52937;hb=HEAD#l1130 .
As far as reading the condition surrounding the code for printing the messasge,
we can ignore it.
=> tmain: suppress the error message reported when running "iconv -l" 

Units/parser-cxx.r/templates8.d/README, Units/parser-cxx.r/templates8.d/input.cpp, parsers/cxx/cxx_parser_function.c
Close #3417.
The original issue was found when parsing cuda code.
However, the bug is common between cuda and C++.
When detecting a name defined in a class is a constructor
or not, strrstr() is used. The original code assumed the
value returned from strrstr is not NULL. This wrong assumption
caused a crash.
@ijpq made efforts to find an input file causing the crash.
=> Cxx: add missing NULL check when detecting a constructor

circle.yml
=> circleci: use fedora36 instead of fedora34

parsers/jscript.c
See the review comments of #3434.
Adding ',' at the end of the last element in a list is a good practice
because a future diff adding a new element at the end of the list can
be smaller; when adding TOKEN_foo, just adding a line is what we have
to do like:
```diff
TOKEN_arrow,
+   TOKEN_foo,
```
We will not have to do like:
```diff
-    TOKEN_arrow
+    TOKEN_arrow,
+    TOKEN_foo
```
With this technique, we can make the diff two lines smaller.
Generally, smaller diff helps people understand the diff.
This is a popular technique:
* https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/netlink.h#n186
* https://sourceware.org/git/?p=glibc.git;a=blob;f=include/stdio.h;h=a6f7fd43cb664eb55f4987dfa830466bba38aa5b;hb=HEAD#l149
* …
=> JavaScript,style: add ',' at the end of the last enumerator

.github/workflows/testing-freebsd.yml, Tmain/tag-relative-option.d/run.sh
A. install python3 explicitly
B. normalize cwd when running tag-relative-option.d
On vagrant+freebsd platform, /home is a symbolic link targeting
/usr/home. tag-relative-option.d failed because --tag-relative option
of ctags and tag-relative-option.d/run.sh didn't consider the symbolic
link.
This change normalizes `pwd` before running ctags.
=> GitHub Actions(FreeBSD): catch up with the latest FreeBSD images

.github/workflows/cross-compile-android-ndk.yml, .github/workflows/cross-compile-mingw-w64.yml, .github/workflows/testing-big-endian.yml, .github/workflows/testing-gnulinux.yml
ubuntu-18.04 Actions runner image is deprecated since 2022-08-08
ubuntu-22.04 Actions runner image is available  since 2022-08-08
Reference:
https://github.com/actions/runner-images/issues/6002
https://github.com/actions/runner-images/issues/5998
=> GitHub Actions: migrate ubuntu environment from 18.04 to 22.04

.github/workflows/cross-compile-android-ndk.yml, .github/workflows/cross-compile-mingw-w64.yml, .github/workflows/testing-bsds.yml, .github/workflows/testing-freebsd.yml.bak, .github/workflows/testing-mac.yml, .github/workflows/testing-netbsd.yml.bak, .github/workflows/testing-openbsd.yml.bak
macos-10.15 Actions runner image is deprecated since 2022-05-31 and will be fully unsupported by 2022-08-31
macos-12 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Actions runner image is available  &nbsp;&nbsp;&nbsp;&nbsp;since 2022-04-27
Reference:
https://github.com/actions/runner-images/issues/5583
https://github.com/actions/runner-images/issues/5446
=> GitHub Actions: migrate macos environment from 10.15 to 12

parsers/verilog.c
I added a debug macro to debug #3457.
It was quite useful and I found another bug for which I will send a PR.
=> Verilog: introduce VERBOSE macro for internal errors

Units/parser-verilog.r/systemverilog-github3462.d/args.ctags, Units/parser-verilog.r/systemverilog-github3462.d/expected.tags, Units/parser-verilog.r/systemverilog-github3462.d/input.sv, parsers/verilog.c
This is the fix for #3462.
There were two bugs.
Some refactoring fixes are also included.
=> Verilog: fix bug caused by double colon ("::")

Units/parser-verilog.r/systemverilog-assertion.d/expected.tags, Units/parser-verilog.r/systemverilog-checker.d/expected.tags, Units/parser-verilog.r/systemverilog-net-var.d/expected.tags, Units/parser-verilog.r/verilog-instance.d/expected.tags, parsers/verilog.c
Verilog: fill typeref fields of instances
This one is partially based on
https://github.com/universal-ctags/ctags/compare/master...my2817:ctags:master
reported and written by @my2817 at #3469.
Capturing the module names of instances is also proposed in #3469.
However, it is not in the scope of this commit.
=> Verilog: fill typeref fields of instances

docs/man/ctags-lang-verilog.7.rst, man/ctags-lang-verilog.7.rst.in
=> docs(man): remove unexpected newline from the rendered verilog man page

Units/parser-rake.r/xtasks.d/expected.tags, Units/parser-rake.r/xtasks.d/input-1.rake, parsers/rake.c, parsers/ruby.c
Close #3474.
A symbol defined with single and double quote characters like :'name'
and :"name" caused a crash of the Rake prser.
The original code handled the initial character, <:> of a name like
<:name> in the Rake parser side. The Rake passed the rest of string
(<name>) to rubyParseMethodName() exported from the Ruby parser.
However, rubyParseMethodName() itself has an ability to handle the initial
character. So this commit makes the Rake parser pass whole <:name> to
rubyParseMethodName(). The single and double quote characters after <:>
is handled in rubyParseMethodName().
=> Rake: accept symbols defined with single and double quote characters

.github/workflows/testing-mac.yml
=> GitHub Actions: brew upgrade python@3.9 is not needed anymore, because python@3.9 is not pre-installed in latest macos runner image

Units/parser-powershell.r/class-powershell.d/args.ctags, Units/parser-powershell.r/class-powershell.d/expected.tags, Units/parser-powershell.r/class-powershell.d/input.ps1, parsers/powershell.c
This pull request adds functionality to the existing parser.
Previously, the PowerShell parser generated tags from functions and variables.
By merging this pull request, it will be able to generate tags from classes in addition to those.
Please note that I do not have a lot of experience contributing to the open source community. Also, this is my first time attempting to contribute to u-ctags.
Please let me know if there are any details I should address.
=> PowerShell: add tag generation from class

Tmain/list-roles.d/stdout-expected.txt, Units/parser-verilog.r/verilog-module-ref.d/args.ctags, Units/parser-verilog.r/verilog-module-ref.d/expected.tags, Units/parser-verilog.r/verilog-module-ref.d/input.v, docs/man/ctags-lang-verilog.7.rst, man/ctags-lang-verilog.7.rst.in, parsers/verilog.c
This one is conceptually based on
https://github.com/universal-ctags/ctags/compare/master...my2817:ctags:master
reported and written by @my2817 at #3469.
The test case is also taken from #3469 submitted by @my2817.
=> Verilog: extract module names used for defining instances as reference tags

Tmain/optscript.d/arrayx.expected, Tmain/optscript.d/arrayx.ps, Tmain/optscript.d/dictx.expected, Tmain/optscript.d/dictx.ps, Tmain/optscript.d/stdout-expected.txt, dsl/optscript.c, main/htable.c
There is a plan to store much more items in a hashtable (htable).
The current implementation, allocating a bucket array of a htable with the size specified when initializing the htable, doesn't fit the purpose because proper size is not predictable.
With this change, the htable itself extends the size of the array twice dynamically when the approximate filling rate of the bucket array of the htable is greater than 80%.
=> main: extend the bucket array of hashTable dynamically

.github/workflows/testing-bsds.yml
OpenBSD-6.9 has reached end-of-life.
Reference: https://endoflife.date/openbsd
=> GithubActions: migrate openbsd version from 6 to 7

Units/parser-itcl.r/simple-itcl.d/expected.tags, Units/parser-itcl.r/simple-itcl.d/input.tcl, Units/parser-tcloo.r/no-empty-line-between-classes.d/args.ctags, Units/parser-tcloo.r/no-empty-line-between-classes.d/expected.tags, Units/parser-tcloo.r/no-empty-line-between-classes.d/input.tcl, parsers/tcl.c
A subparser may consume the input upto the end of a command line (EOCL) when the subparser extracts something. So consuming input upto EOCL in the base parser, here Tcl parser, after the extraction causes unexpected skipping.
Calling skipToEndOfCmdline for consuming input should be done only when any subparser extracts nothing.
=> Tcl,TclOO: don't consume input if a subparser extracts something

.github/workflows/cross-compile-android-ndk-on-mac.yml, .github/workflows/cross-compile-android-ndk-on-ubuntu.yml, .github/workflows/cross-compile-mingw-w64-on-mac.yml, .github/workflows/cross-compile-mingw-w64-on-ubuntu.yml
It seems that brew command is not available on Ubuntu these days.
=> GitHub Actions: use apt-get instead of brew on Ubuntu

makefiles/testing.mak, misc/units
See #3498 for the needs of this change.
=> buildsys: testing.mak: provide the way to avoid (re)build executables before testing

.github/workflows/testing-big-endian.yml
origin s390x workflow is very slow, sometimes even consume time over 1 hours.
to speed up this workflow, I changed to following:
1. cross-compile s390x on build-machine, this will save about 15 minitus.
2. use prebuild dependencies.
3. only do `misc/units.py tmain` and `misc/units.py run`
=> Github Actions: speed up s390x workflow

dsl/optscript.c, extra-cmds/utiltest.c, main/htable.c, main/htable.h
The original hashTableUpdateItem() replaces not only the value but the key. So we cannot add "const" modifier to the key parameter.
This change revises the function.
The new hashTableUpdateItem() never replaces the key; if key is not found, it just returns false. So we can add the const modifier to the key parameter.
In addition we introduces a new function, hashTableUpdateOrPutItem(). hashTableUpdateOrPutItem() don't replace the key as far as the key exits in the hash table. However, we don't add the const modifier to the key parameter because the key and the value is put to the the hash table if the key doesn't exist in the hash table.
These two are tested in tutil target.
=> libutil: revise functions for updating the value for a given key

Units/parser-php.r/run-guest-nested.d/args.ctags, Units/parser-php.r/run-guest-nested.d/expected.tags, Units/parser-php.r/run-guest-nested.d/input.php, main/promise.c, parsers/html.c, parsers/php.c
The html parser needs to be able to use php as a guest parser.
=> html: parse javascript broken by php

.github/workflows/run-citre-tests.yml
Citre changed the unit test command of tags backend to `make test-tags`.
=> Update citre unit test command

Tmain/mline-no-advance.d/stderr-expected.txt, Tmain/optlib-message-flag.d/args.ctags, docs/man/ctags-optlib.7.rst, docs/optlib.rst, main/debug.h, main/lregex.c, man/ctags-optlib.7.rst.in
Close #3513.
Close #2918.
Specifying mgroup is a must if --mline-regex-<LANG>= records a tag with \[0-9].
TODO:
=> lregex: warn if mgroup= flag is not given in --mline-regex-<LANG>=

.github/workflows/testing-cygwin.yml
=> GitHubAtions: choco install -y --source cygwin is broken since chocolatey v1.2.0, so we change to the offical way to install cygwin packages

.github/workflows/testing-mac.yml
python@3.11 symlink 2to3-3.11 to /usr/local/bin/2to3-3.11, but it already exists. so we need use --overwrite option when installing python@3.11
python@3.11 is depended by gdb.
=> GitHub Actions: fix-github-actions-workflow-macos

.gitignore
The `utiltest` was not listed in the .gitginore.
Please add it to .gitignore with this pull request.
=> utiltest: update .gitignore

parsers/powershell.c
The cross-parser convention of readTags() takes TOKEN as an output parameter. 433c933ad3aa77a35579fc73b361cd026b721baa violates the convention; readTags() refers to a field of TOKEN. This can be a cause of trouble.
=> PowerShell,refactor: don't use output parameter as input

makefiles/testing.mak
See https://github.com/universal-ctags/ctags/pull/3535#discussion_r1022831854.
=> build-sys: add clean-tlib and clean-gcov to the dependecy list of clean-local

Units/parser-python.r/reserved-words.d/args.ctags, Units/parser-python.r/reserved-words.d/expected.tags, Units/parser-python.r/reserved-words.d/input.py, Units/parser-python.r/variable-annotations.d/expected.tags, parsers/python.c
The parser extacted keywords like "else" and "try" as tags.
=> Python: add more weak keywords

Units/parser-cxx.r/field-nth.d/expected.tags, Units/parser-cxx.r/field-nth.d/input.h, main/entry.c, main/entry.h, parsers/cxx/cxx_parser.c, parsers/cxx/cxx_parser_function.c, parsers/cxx/cxx_parser_lambda.c, parsers/cxx/cxx_parser_template.c, parsers/cxx/cxx_parser_typedef.c, parsers/cxx/cxx_parser_variable.c, parsers/cxx/cxx_scope.c, parsers/cxx/cxx_scope.h, parsers/cxx/cxx_tag.c, parsers/cxx/cxx_tag.h, parsers/cxx/cxx_token.c, parsers/cxx/cxx_token.h
nth: field of member kinds in C language is useful to find super-classes.
The following command line is for reporting sub-classes of GtkWidget.
```
$ ./ctags --fields=+'{nth}{scope}' -o - /usr/include/gtk-3.0/gtk/*.h  \
| ./readtags -t - \
-Q '(and (eq? $nth 0) (eq? $typeref-name "GtkWidget"))' \
-F '(list $scope-name " is a subclass of " $typeref-name #t)' \
-l
_GtkLevelBar is a subclass of GtkWidget
_GtkProgressBar is a subclass of GtkWidget
_GtkSpinner is a subclass of GtkWidget
_GtkCellView is a subclass of GtkWidget
_GtkEntry is a subclass of GtkWidget
...
```
TODO: write the above technique in readtags(1).
=> Cxx: fill  "nth:" field for  "member" and "enum" kind

Tmain/json-output-format.d/stdout-expected.txt, Tmain/list-roles.d/stdout-expected.txt, Tmain/pretend-option.d/stdout-expected.txt, Units/parser-iPythonCell.r/default-formats.d/expected.tags, Units/parser-iPythonCell.r/double-sharps.d/expected.tags, Units/parser-lisp.r/simple-lisp.d/expected.tags, Units/parser-python.r/python-dot-in-import.d/expected.tags, docs/man/ctags.1.rst, man/ctags.1.rst.in, parsers/go.c, parsers/julia.c, parsers/lisp.c, parsers/lua.c, parsers/python.c
Close #3550.
We are thinking about introducing generic reference tags in multiple languages seriously.
For the generic reference tags, "unknown" kind may use.
Making the "unknown" kind consistent will help users.
=> [SELF-INCOMPATIBLE] EmacsLisp,Go,Julia,Lisp,Lua,Python: change the kind letter for "unknown" to 'Y'

docs/man/ctags.1.rst, main/options.c, man/ctags.1.rst.in
Default optlib path list
~~~~~~~~~~~~~~~~~~~~~~~~
``$XDG_CONFIG_HOME/ctags``, or ``$HOME/.config/ctags`` if
``$XDG_CONFIG_HOME`` is not defined
(on other than MS Windows)
``$HOME/.ctags.d``
``$HOMEDRIVE$HOMEPATH/ctags.d`` (on MS Windows only)
These directories are parts of the optlib path list by default.
See "`Option File Options`_" about the optlib path list.
If you have a set of options that you want to enable
conditionally, make a directory in the path in the optlib path
list, and put the options to the files having .ctags as extensions
under the directory. ``--options=<the-directory-name>`` is for
enabling the options.
For example, consider you have some options you want to enable
only when tagging the Linux kernel source tree.  In that case,
make ``$HOME/.ctags.d/linux`` directory, …
=> main: make ~/.ctags.d as the default element for the optlib path list

Tmain/readtags-escaping-input-no-roundtrip.d/output.tags, Tmain/readtags-escaping-input-no-roundtrip.d/run.sh, Tmain/readtags-escaping-input-no-roundtrip.d/stdout-expected.txt, Tmain/readtags-escaping-input.d/run.sh, Tmain/readtags-escaping-input.d/stdout-expected.txt, Tmain/readtags-ptags-escaping.d/stdout-expected.txt, extra-cmds/printtags.c
=> readtags: print the input fields literally even if -E option is given

misc/git-tag-maybe.sh
For preparing ctags 6.0.0, disable weekly tagging temporarily.
=> GitHub Actions: disable tagging temporarily

docs/man/ctags-client-tools.7.rst, man/ctags-client-tools.7.rst.in
This PR:
- improves the readability
- makes it clear that the substitution `'` => `'"'"'` is only needed for shell commands
=> docs(man): improve the section on building readtags expressions

docs/man/tags.5.rst, man/tags.5.rst.in
In https://github.com/universal-ctags/ctags/issues/3559#issuecomment-1335183243:
> I think it's totally fine to make pseudo tags using the same pattern and same escaping rules as regular tags. It would be benefit to state this explicitly in tags(5).
This PR did this.
> The other problem of tags(5) is it only defines how the "value" part in a `{tagfield}` is escaped. `{tagname}`, `{tagfile}` and `{tagaddress}` are left. Though, in "Proposal" section, `{tagname}` is mentioned
This PR makes it more clear on `{tagname}` and `{tagaddress}`.
=> docs(man): add several comments in tags(5)

Units/parser-html.r/comment-starter-in-script.d/args.ctags, Units/parser-html.r/comment-starter-in-script.d/expected.tags, Units/parser-html.r/comment-starter-in-script.d/input.html, Units/parser-html.r/string-in-script.d/args.ctags, Units/parser-html.r/string-in-script.d/expected.tags, Units/parser-html.r/string-in-script.d/input.html, parsers/html.c
The original code used a html-aware tokenizer for reading tokens in <script>...</script> areas.
As reported in #3581 and #3597, this original code could not recognize <script>...</script> areas in some cases.
This change introduces a tokenizer specialized to script areas in addition to the original html-aware tokenizer.
Close #3581.
Close #3597.
=> HTML: introduce a specialized tokenizer for script areas

Units/parser-c.r/properties-thread.d/args.ctags, Units/parser-c.r/properties-thread.d/expected.tags, Units/parser-c.r/properties-thread.d/input.c, Units/parser-cxx.r/properties-consteval.d/args.ctags, Units/parser-cxx.r/properties-consteval.d/expected.tags, Units/parser-cxx.r/properties-consteval.d/input.cc, Units/parser-cxx.r/properties-constinit.d/args.ctags, Units/parser-cxx.r/properties-constinit.d/expected.tags, Units/parser-cxx.r/properties-constinit.d/input.cc, parsers/cxx/cxx_keyword.c, parsers/cxx/cxx_keyword.h, parsers/cxx/cxx_parser_block.c, parsers/cxx/cxx_parser_function.c, parsers/cxx/cxx_parser_internal.h, parsers/cxx/cxx_parser_variable.c, parsers/cxx/cxx_tag.c, parsers/cxx/cxx_tag.h
=> C++,C: record consteval, constinit, thread_local, and __thread to properties: field

Units/parser-c.r/properties-thread.d/expected.tags, Units/parser-c.r/properties-thread.d/input.c, parsers/cxx/cxx_keyword.c, parsers/cxx/cxx_keyword.h, parsers/cxx/cxx_parser_block.c
=> C: add _Thread_local C11 keyword

optlib/org.c, optlib/org.ctags
The Org parser is incredibly slow.
The original:
```
[yamato@dev64]~/var/ctags-github% ./ctags --totals /home/yamato/var/emacs/doc/misc/org.org
1 file, 22606 lines (802 kB) scanned in 98.8 seconds (8 kB/s)
625 tags added to tag file
625 tags sorted in 0.00 seconds
longest tag line = 127
```
With this pull request:
```
[yamato@dev64]~/var/ctags-github% ./ctags --totals /home/yamato/var/emacs/doc/misc/org.org
1 file, 22606 lines (802 kB) scanned in 0.6 seconds (1291 kB/s)
624 tags added to tag file
624 tags sorted in 0.00 seconds
longest tag line = 127
```
It becomes 150% faster with this pull request.
BTW, this parser doesn't fill scope fields.
=> Org:  optimize

Units/parser-perl.r/no-heredoc.d/args.ctags, Units/parser-perl.r/no-heredoc.d/expected.tags, Units/parser-perl.r/no-heredoc.d/input-0.pl, Units/parser-perl.r/no-heredoc.d/input.pl, Units/parser-perl.r/perl-module.d/expected.tags, Units/parser-perl.r/perl-module.d/input.pl, parsers/perl.c
Close #3588.
`q/...<<MARKER.../` is not handled in this pull request.
=> Perl: skip string literals when collecting heredoc markers

win32/GNUmakefile, win32/ctags_vs2013.vcxproj, win32/ctags_vs2013.vcxproj.in
In GNUMakefile, we had two macros specifying source code directories though we should have only one.
The two macros came from my mistake (d8f6b0edb7a13d2ab454b5cd8af792cf329f1a99). In the commit, I added "dsl" directory only two of three build-configurations.
=> build-sys(win32): unify MVC_INC_DIRS1 and MVC_INC_DIRS2

misc/review
I forgot to add this one to 0435cac8c37600c5f64466ad83c80ebcf4cfae4d.
=> misc/review,refactor: generalize functions related to show differences in Uints

Units/parser-markdown.r/code-block-under-items.d/args.ctags, Units/parser-markdown.r/code-block-under-items.d/expected.tags, Units/parser-markdown.r/code-block-under-items.d/input.md, parsers/markdown.c
=> Markdown: fix the condition to detect code blocks

Units/parser-ruby.r/ruby-curly-brackets.d/args.ctags, Units/parser-ruby.r/ruby-curly-brackets.d/expected.tags, Units/parser-ruby.r/ruby-curly-brackets.d/input-0.rb, Units/parser-ruby.r/ruby-curly-brackets.d/input-1.rb, Units/parser-ruby.r/ruby-curly-brackets.d/input-2.rb, Units/parser-ruby.r/ruby-curly-brackets.d/input.rb, parsers/ruby.c
```
Class.new {
def f2() end
}
```
With this change, ctags extracts `f2`.
=> Ruby:  handle curly bracket

parsers/cxx/cxx_tag.c
Introduced in b9249a8fc960f751bbae0430ac711f21af771eb0
=> Fix typo in conditional in C++ parser

Units/parser-verilog.r/systemverilog-basic.d/expected.tags, Units/parser-verilog.r/systemverilog-class.d/expected.tags, Units/parser-verilog.r/systemverilog-directive.d/expected.tags, Units/parser-verilog.r/systemverilog-nocontext.d/expected.tags, Units/parser-verilog.r/verilog-2001.d/expected.tags, Units/parser-verilog.r/verilog-basic.d/expected.tags, Units/parser-verilog.r/verilog-memleak.d/expected.tags, Units/parser-verilog.r/verilog-multiline-macro.d/expected.tags, Units/parser-verilog.r/verilog-nocontext.d/expected.tags, Units/parser-verilog.r/verilog-sf_bug98.d/expected.tags, Units/parser-verilog.r/verilog-sf_bug99.d/expected.tags, man/ctags-lang-verilog.7.rst.in, parsers/verilog.c
In some case,  readtags return different kind of text macro(define) and parameter is better for me.
=> Verilog: all text macro map to new kindDefinition:define 

docs/man/ctags-lang-verilog.7.rst, man/ctags-lang-verilog.7.rst.in
refer to https://github.com/universal-ctags/ctags/pull/3653
=> doc: Verilog, add new kind "define"

.github/workflows/cross-compile-android-ndk-on-mac.yml, .github/workflows/cross-compile-android-ndk-on-ubuntu.yml, .github/workflows/cross-compile-mingw-w64-on-mac.yml, .github/workflows/cross-compile-mingw-w64-on-ubuntu.yml, .github/workflows/run-citre-tests.yml, .github/workflows/tagging.yml, .github/workflows/testing-alpine.yml, .github/workflows/testing-bsds.yml.bak, .github/workflows/testing-freebsd.yml, .github/workflows/testing-gnulinux.yml, .github/workflows/testing-mac.yml, .github/workflows/testing-msys2.yml, .github/workflows/testing-netbsd.yml, .github/workflows/testing-openbsd.yml, .github/workflows/testing-with-vlagrind.yml
https://github.com/actions/checkout@v2 use node12 runtime by default 
https://github.com/actions/checkout@v3 use node16 runtime by default
Reference: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> GitHub Actions: change github actions checkout from v2 to v3

Units/parser-typescript.r/ts-class-member-init.d/args.ctags, Units/parser-typescript.r/ts-class-member-init.d/expected.tags, Units/parser-typescript.r/ts-class-member-init.d/input.ts, parsers/typescript.c
See https://github.com/geany/geany/issues/3416
Disclaimer: I don't know TypeScript so I'm trusting the input file, and it'd be great if anybody having any knowledge here could review :)
=> Typescript: Fix handling of parentheses in class property value

Units/parser-powershell.r/simple-powershell.d/expected.tags, Units/parser-powershell.r/simple-powershell.d/input.ps1, parsers/powershell.c
According to [official doc](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_special_characters?view=powershell-7.3), powershell use ` to escape string and it only works in ".
=> Powershell: fix string escape issue

main/keyword.c
Parser code like
```C
vString *str = vStringNew();
while (someCondition)
{
int c = getcFromInputFile();
vStringPut(str, c);
if (lookupCaseKeyword (vStringValue(str), some_lang))
{
do_stuff();
vStringClear(str);
}
}
```
is prone to quadratic complexity because when `someCondition` isn't satisfied in the parsed file, the string str grows by one in each iteration and in each iteration `lookupCaseKeyword()` has to go through `strlen(str)` characters to compute the hash.
Since we know the maximum length of the strings inside the keyword hash table, we can store this value and if the queried string is longer than this value, we can be sure it isn't present in the hash table and return quickly without having to compute the full hash of the string.
=> main: add quick path for looking up too long strings in the keyword table

Units/parser-sql.r/sql-plsql-selection-directive.d/args.ctags, Units/parser-sql.r/sql-plsql-selection-directive.d/expected.tags, Units/parser-sql.r/sql-plsql-selection-directive.d/input.sql, parsers/sql.c
PLSQL selection directives are of the form
```
$IF boolean_static_expression $THEN
text
[ $ELSIF boolean_static_expression $THEN
text
]...
[ $ELSE
text
]
$END
```
In addition, boolean_static_expression conditions like
```
$$MY_CUSTOM_VAR > 3
```
can appear which confuses the current parser because it
thinks `$$` is the start of dollar-quoted string and drops
the rest of the code. In addition, as the double-quoted
string is getting bigger and bigger and tested against
inquiry directives by
```
lookupCaseKeyword (vStringValue (string), Lang_sql)
```
it takes huge amount of time to perform the repeated
lookups in the hash table.
This patch skips all the code between `$IF` and `$END` because
we can't know which of the branches to take and this is the
easiest way to avoid invalid code. In …
=> SQL: Skip PL/SQL selection directives and add sanity check for inquiry directive size

Tmain/list-subparsers-all.d/stdout-expected.txt, Units/parser-quarto.r/simple.d/args.ctags, Units/parser-quarto.r/simple.d/expected.tags, Units/parser-quarto.r/simple.d/input.qmd, Units/parser-quarto.r/unexecuted-block.d/args.ctags, Units/parser-quarto.r/unexecuted-block.d/expected.tags, Units/parser-quarto.r/unexecuted-block.d/input.qmd, Units/parser-rmarkdown.r/frontmatter.d/expected.tags, Units/parser-rmarkdown.r/simple-rmarkdown.d/expected.tags, docs/news.rst, main/parsers_p.h, parsers/markdown.c, parsers/markdown.h, parsers/quarto.c, parsers/rmarkdown.c, source.mak, win32/ctags_vs2013.vcxproj, win32/ctags_vs2013.vcxproj.filters
This parser is based on the RMarkdown parser.
The way of extracting chunk labels is enhanced for Quarto.
A. recognizing unexecuted blocks like
```{{python}}
...
```
Quarto makes an anonymous tag for the code block.
B. recognizing " label: " in code blocks like
```{python}
#| label: optimization-techniques
...
```
Quarto extracts "optimization-techniques" as a tag.
=> Quarto: new parser

main/entry.c, main/entry.h
When storing a tag entry to the corkQueue, the most of members of the tag entry are duplicated for isolating the the stored tag entry from the original parsing context.
In the most of all cases, we can expect all tag entries in the corkQueue has the same value as inputFileName member. Strdup'ing the value is waste of memory resource especially when the input file name is long.
=> main: Don't strdup the inputFileName when storing a tag to the corkQueue

parsers/autoit.c
This should marginally improve performance parsing `#region`s, and (marginally, again) improve the code.
It's unlikely to make any significant change, though.  Just something that I saw looking at the code.
=> AutoIt: Slightly optimize parsing #region

main/entry.c, main/entry.h, main/lregex.c, main/read.c, main/read_p.h, parsers/cpreprocessor.c, parsers/r.c, parsers/ruby.c
Nothing is changed in semantics.
=> main: revise bit fields in tagEntryInfo

Units/parser-cxx.r/prototype-starting-from-scope-op.d/args.ctags, Units/parser-cxx.r/prototype-starting-from-scope-op.d/expected.tags, Units/parser-cxx.r/prototype-starting-from-scope-op.d/input.cpp, parsers/cxx/cxx_parser.c
Close #3693.
The original code could not extract "bar" in
```
::std::string bar();
```
=> C++: accept prototypes starting from :: operator

Units/parser-autoit.r/simple-au3.d/expected.tags, docs/man-pages.rst, docs/man/ctags-lang-autoit.7.rst, man/GNUmakefile.am, man/ctags-lang-autoit.7.rst.in, parsers/autoit.c
At least PHP, which also declares variables using `$`, such as
```
$x = 5;
```
outputs pure variable name without the `$` prefix and this patch unifies this behavior.
=> autoit: Drop $ from variable names

Units/parser-d.r/simple.d.d/expected.tags, Units/parser-d.r/simple.d.d/input.d, parsers/c-based.c
Hi,
I'm working on porting the remaining Geany D parser changes to ctags.
UDAs can precede a declaration or come after a function parameter list.
https://dlang.org/spec/attribute.html#uda
* I'm not sure if all the lines in expected.tags starting with `!_TAG_` should be there. Please let me know if there's a switch I should be using.
* I'm not sure if I add a changelog entry somewhere, please let me know.
=> D: parse user-defined attributes

Units/parser-d.r/simple.d.d/expected.tags, Units/parser-d.r/simple.d.d/input.d, parsers/c-based.c
https://dlang.org/spec/const3.html
https://dlang.org/spec/const3.html#inout
`inout` is not working yet (missing test symbol).
=> D: parse const(T), immutable, inout and shared type qualifiers

Units/parser-d.r/simple.d.d/expected.tags, Units/parser-d.r/simple.d.d/input.d, parsers/c-based.c
https://dlang.org/spec/function.html#contracts
=> D: parse contract expressions

Units/parser-d.r/simple.d.d/expected.tags, Units/parser-d.r/simple.d.d/input.d, parsers/c-based.c
Presumably this was mistakenly added instead of `override` (which is also there).
https://dlang.org/spec/lex.html#keywords
`override` only appears before a function declaration. 
https://dlang.org/spec/function.html#virtual-functions
=> D: remove `overload`, not a keyword

Units/parser-d.r/simple.d.d/expected.tags, Units/parser-d.r/simple.d.d/input.d, parsers/c-based.c
This just removes the remnants of code for fallback C parsing. `identifierCount` is never changed anywhere.
Now the test for `inout(T)` works.
=> D: fix parsing parameter with pointer

Units/parser-d.r/templates.d/expected.tags, Units/parser-d.r/templates.d/input.d, parsers/c-based.c
2 commits to parse them in either a function parameter list, or for general tokens.
https://dlang.org/spec/template.html#explicit_tmp_instantiation
=> D: parse template instance types

misc/units.py
Close #3688
See https://no-color.org/.
=> units.py: don't use color if NO_COLOR is specified

Units/parser-verilog.r/systemverilog-interface.d/expected.tags, Units/parser-verilog.r/systemverilog-interface.d/input.sv, parsers/verilog.c
`virtual interface` is a variable. But the Verilog parser mistakenly declared it as an interface.
This PR fixes the issue.
=> Verilog: support virtual interface variables

main/colprint.c
This is very theoretical though, but pleases -Wconversion.
=> colprint: Fix column width truncation

Units/parser-erlang.r/crash1.d/input.erl, parsers/erlang.c
Even if they might not exist, fix the code not to crash on them.
The issue was that the pointer to the vString buffer holding the directive name was cached at its value right after the vString creation, yet that buffer might get realloc()ated if it grows past the initial length of 32, possibly making the initial pointer invalid.
Fix this by simply getting the pointer to the value later on.
=> erlang: Fix crash parsing directives longer than 31 characters

main/lregex.c
substitute was one of the bottle neck.
It called strlen before memcpy.
We can remove the strlen invocation safely.
The original code:
$ xargs cat <  /tmp/list > /dev/null; time ./ctags -L - < /tmp/list
./ctags -L - < /tmp/list  97.39s user 4.72s system 97% cpu 1:45.09 total
With this change:
$ xargs cat <  /tmp/list > /dev/null; time ./ctags -L - < /tmp/list
./ctags -L - < /tmp/list  87.24s user 4.68s system 97% cpu 1:34.28 total
About 10% faster!
=> lregex: optimize substitute()

libreadtags/readtags.c
=> libreadtags: pull the latest version

extra-cmds/utiltest.c, main/htable.c
This seems like it should work, @masatake -- what's a good way to test this code?  There seem to be no unit tests for this.
=> htable: use precalculated list of primes

.gitignore, Units/parser-markdown.r/hashtags-utf8.d/args.ctags, Units/parser-markdown.r/hashtags-utf8.d/expected.tags, Units/parser-markdown.r/hashtags-utf8.d/input.md, Units/parser-markdown.r/section-prefixed-with-spaces.d/expected.tags, main/utf8_str.c, main/utf8_str.h, parsers/asciidoc.c, parsers/markdown.c, parsers/rst.c, source.mak, win32/ctags_vs2013.vcxproj, win32/ctags_vs2013.vcxproj.filters
Some markdown editors or plugins, such as [Obsidian](https://help.obsidian.md/Editing+and+formatting/Tags) and [VSCode markdown-hashtags](https://github.com/vanadium23/markdown-hashtags), support parsing #hashtags and navigation. I have modified the markdown parser to support hashtag syntax parsing.
=> Markdown: add hashtags functionality

.github/workflows/tagging.yml
1. use `fetch-depth: 0` with `actions/checkout@v3`, beacuse default is `fetch-depth: 1` which means only one commit is fetched and no tags and branches are fetched.
close #3754
2. It looks like someone tries to use `USER_NAME` and `USER_EMAIL` to configure git `user.name` and `user.email`, this didn't take effect. so I add following:
```bash
git config user.name  'Universal-ctags CI'
git config user.email 'Universal-ctags@users.noreply.github.com'
```
3. I removed some unsed code in this file.
=> refact github/workflows/tagging.yml

.github/workflows/testing-mac.yml
I have been paying attention to the issue of `brew update`. There is no perfect solution as far as I known till now. so , I think just do not run `brew update` as an immediate workaround.
folks keep reporting this issue to GitHub Actions Team and Homebrew Team:
https://github.com/actions/runner/issues/2677
https://github.com/Homebrew/brew/issues/15621
=> GitHub Actions: testing-mac.yml: do not run brew update, as an immediate workaround.

Tmain/list-params.d/stdout-expected.txt, parsers/asm.c
=> Fix typo in asm.c

configure.ac
I happened to see the log `/home/leleliu008/.ndk-pkg/run/3382264/uctags/src/configure: line 7427: -f: command not found`  just now. I realized that I shouldn't use  `[]` as `test` in configure.ac
=> build-sys: change shell command [] to test, because [] was recognized as quote delimiters by autoconf/m4

main/sort.c
This change fixes that ctags reports the following strange error message:
$ /usr/bin/ctags --quiet --options=NONE -o - main/*.c | no-such-command
zsh: no-such-command: command not found...
ctags: cannot sort tag file : Success
Success?
With this change, ctags reports:
./ctags --quiet --options=NONE -o - main/*.c | no-such-command
zsh: no-such-command: command not found...
ctags: cannot sort tag file
=> main: reserve errno in external sorting

Units/parser-verilog.r/systemverilog-net-var.d/expected.tags, Units/parser-verilog.r/systemverilog-net-var.d/input.sv, parsers/verilog.c
FIx to support the following code.
```
wire #10 wireA;
wire #10 wirea = wireb;
```
cf. LRM 10.3.3 Continuous assignment delays
=> Verilog: fix for continuous assignment delays

configure.ac, main/sort.c
```
$ ~/bin/ctags -o - -R ~/var/ctags-github/main |readtags __NR_read
ctags: cannot sort tag file: system ("sort -u") exited with 13 (Broken pipe?)
```
=> main: report the guessed reason if system("sort") is failed

circle.yml
Feodra 30 is too old to run newer validators.
=> CircleCI: run validate-input target on Fedora 38 instead of Fedora 30

README.md
There's an official Homebrew formula now, no need to use a custom tap.
=> update Mac installation instructions

docs/testing-parser.rst, makefiles/testing.mak, misc/units
This PR lets *validate-input* make target support the CATEGORIES variable as *units* make target does.
Some minor fixes  of input validation are also included.
=> input-validate: add CATEGORIES make variable

.github/workflows/testing-freebsd.yml, .github/workflows/testing-netbsd.yml, .github/workflows/testing-openbsd.yml
Reference: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
=> GitHub Actions: update actions/cache@v2 to v3

win32/appveyor.bat
=> Appveyor: run nmake with defining DEBUG

Units/parser-java.r/java_enum.java.d/expected.tags, Units/parser-java.r/java_enum.java.d/input.java, parsers/c-based.c, parsers/cpreprocessor.c, parsers/cpreprocessor.h, parsers/cxx/cxx_parser_tokenizer.c
where "character" returned is a symbol (> 0xff)
=> c-based: fix to handle edge case

.github/dependabot.yml
Create dependabot.yml to enable dependabot version updates.
Allow dependabot to open pull requests automatically to update depended github actions.
See:
Settings (of this repository) > Code security and analysis > Dependabot > Dependabot version updates
=> GitHub Actions: Create dependabot.yml

.github/workflows/testing-nmake.yml
Reference: https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160#vcvarsall-syntax
the first argument of vcvarsall.bat can be either amd64 or x64
=> GitHub Actions: cleanup code

.github/workflows/testing-mac.yml
`/usr/bin/cc` `/usr/bin/gcc` `/usr/bin/clang` are actually the same.
`libxml2` is a keg_only package, which means it was not linked into `/usr/local`. I removed it, because it was pre-installed on macOS.
=> GitHub Actions: cleanup code testing-mac.yml

peg/peg_common.h
References:
https://man7.org/linux/man-pages/man3/ssize_t.3type.html
https://learn.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-160#size-prefixes-for-printf-and-wprintf-format-type-specifiers
=> using %zu for printing size_t values

Units/parser-bibtex.r/bib-simple.d/expected.tags, Units/parser-bibtex.r/bib-simple.d/input.bib, parsers/bibtex.c
=> BibTeX: accept "." and "/" as parts of a bib entry

.github/workflows/cross-compile-android-ndk-on-mac.yml, .github/workflows/cross-compile-android-ndk-on-ubuntu.yml
Android NDK r25c is stable release.
Android NDK r26-rc is not stable.
Reference:
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#environment-variables-2 https://developer.android.com/ndk/downloads
=> GitHub Actions: use Android NDK r25c instead of Android NDK r26-rc

main/mini-geany.c, misc/tlib
Reverts universal-ctags/ctags#3834
The log of the original commit wrong needs to be revised.
=> Revert "main,tlib: fix wording"

README.md
=> README.md: adjust wording of the configure command

Units/parser-restructuredtext.r/code-blocks.d/args.ctags, Units/parser-restructuredtext.r/code-blocks.d/expected.tags, Units/parser-restructuredtext.r/code-blocks.d/input-0.rst, Units/parser-restructuredtext.r/code-blocks.d/input-1.rst, Units/parser-restructuredtext.r/code-blocks.d/input-2.rst, Units/parser-restructuredtext.r/code-blocks.d/input.rst, parsers/rst.c
input.rst:
```rst
C examples
------------
.. code-block:: C
int main (void)
{
return 0;
}
```
output.tags with `./ctags --extras=+g --fields=+lK -o - /tmp/input.rst`：
```
C examples	/tmp/input.rst	/^C examples$/;"	title	language:ReStructuredText
main	/tmp/input.rst	/^	int main (void)$/;"	function	language:C	typeref:typename:int
```
=> ReStructuredText: run guest parsers on code blocks

main/mini-geany.c, misc/tlib
Close #3830
Suggested by @dataf3l.
=> main,tlib: fix wording

dsl/dsl.c, dsl/sorter.c, extra-cmds/optscript-repl.c, extra-cmds/readtags-cmd.c, extra-cmds/readtags-stub.c, main/error_p.h, main/lxpath.c, main/lxpath_p.h, main/mbcs.c, main/mini-geany.c, main/options.c, main/read.c, main/trashbox.c, main/unwindi.c, parsers/asm.c, parsers/automake.c, parsers/cpreprocessor.c, parsers/cpreprocessor.h, parsers/cxx/cxx_debug.c, parsers/cxx/cxx_tag.h, parsers/gdscript.c, parsers/perl.c, parsers/python.c, parsers/sql.c, parsers/verilog.c, parsers/yaml.c
This fixes various mostly harmless warnings from GCC.  This is not everything yet, and most of it is trivial, but it still gets rid of some and helps tidy code a little.
=> Various warnings fixes

peg/kotlin.peg
There has been a few small improvements to the [Kotlin language specification](https://github.com/Kotlin/kotlin-grammar-gpl2) this year, so it's time to update the grammar for the kotlin parser.
=> Update kotlin parser

main/subparser.h, main/subparser_p.h, parsers/ansibleplaybook.c, parsers/openapi.c, parsers/yaml.c, parsers/yaml.h, parsers/yamlfrontmatter.c
The code for utilizing libyaml in the OpenAPI parser is good enough. 
This pull request moves the code to the Yaml Meta parser as Ypath API.
For evaluating the API, this pull request also applies the API to the AnsiblePlaybook parser.
This pull request is a preparation step for merging #3258.
=> Yaml: revise Ypath API

.github/workflows/testing-mac.yml
I have forgotten why leave the libxml2 package not installed. maybe because libxml2 depends on python@3.10, python@3.11, python@3.12 at the same time. It may break the environment.
https://github.com/Homebrew/homebrew-core/blob/master/Formula/lib/libxml2.rb
=> GitHub Actions: update testing-mac.yml

.github/workflows/testing-freebsd.yml, .github/workflows/testing-netbsd.yml, .github/workflows/testing-openbsd.yml
We disabled BSD workflows due to the issue
https://github.com/actions/runner-images/issues/8730, which in turn had been fixed, so let's enable these BSD workflows
=> GitHub Actions: enable BSD workflows

configure.ac
on `FreeBSD` and `OpenBSD`, the most 3rd-party libs are installed in `/usr/local/lib` directory, we need to manully add `-L/usr/local/lib` to `LDFLAGS` only when do native build.
=> buildsys: improve cross-build for freebsd and openbsd

misc/units.py
=> misc/units.py: fix invalud escape sequences in regex patterns

main/nestlevel.c, main/nestlevel.h
We need to align the user data properly not to trigger undefined behavior, which even apparently crashes on SPARC.
As `NestingLevels::levels` is actually a single allocation for all levels and their user data mapped as `[NL0|UD0|NL1|UD1|...]` (where NL is a NestingLevel, and UD a user data), we need to align twice, as we need every `NL*` and every `UD*` to align properly.
Here we align everything to `2*sizeof(size_t)`, which is a logic borrowed from GLib, which seems to have borrowed the value from glibc. This is pretty conservative in our case, because actually `NL*`s only need aligning to `int`'s requirements currently, which on some architectures is 4, not 16; but it's trickier to implement (and actually impossible with the current API) as we'd need to compute the actual alignment for …
=> nestlevel: Fix user data alignment

main/debug.c, main/entry.c, main/field.c, main/read.h, parsers/asm.c, parsers/c-based.c, parsers/cpreprocessor.c, parsers/cpreprocessor.h, parsers/cxx/cxx_parser_tokenizer.c, parsers/ldscript.c, parsers/protobuf.c, parsers/vera.c, parsers/verilog.c
=> Vera: revise the dataflow of cppGetc -> vStringPut

docs/man/ctags-client-tools.7.rst, man/ctags-client-tools.7.rst.in
=> docs(man): write about guest parsers

main/read.c, main/read.h, parsers/ruby.c
About 20% faster with this change.
Eventually, we have to switch to a token-based parser.
This is just a way to extend the life of the current parser.
Without this change:
```
[yamato@dev64]~/var/codebase% for x in Ruby ; do ./codebase ctags --ctags ~/var/ctags-github/ctags $x; done
version: e3439eb0
features: +wildcards +regex +iconv +option-directory +xpath +json +interactive +sandbox +yaml +packcc +optscript +pcre2
log: results/e3439eb0,Ruby................,..........,time......,default...,2024-01-13-07:37:44.log
tagsoutput: /dev/null
cmdline: + /home/yamato/var/ctags-github/ctags --quiet --options=NONE --sort=no --options=profile.d/maps --totals=yes --languages=Ruby -o - -R code/katello code/metasploit-framework code/puppet code/rails code/redmine code/rspec-core code/ruby …
```
=> Ruby:  optimize the parser by reducing the numbers of calling strlen

Makefile.am, configure.ac, m4/ax_check_compile_flag.m4
=> build-sys: enable LTO

Units/parser-make.r/same-line.d/args.ctags, Units/parser-make.r/same-line.d/expected.tags, Units/parser-make.r/same-line.d/input.mak, main/entry.c, parsers/make.c
For the input:
#
y: x = 1
ctags with the original code warns:
ctags: Warning: given end line (1) for the tag (y) in the file (Makefile) is smaller than its start line: 2
=>  Make: fix wrong end fields for targets having macros on the same line 

Tmain/list-roles.d/stdout-expected.txt, Units/parser-lex.r/simple-lex.d/args.ctags, Units/parser-lex.r/simple-lex.d/expected.tags, Units/parser-lex.r/simple-lex.d/input.l, docs/man-pages.rst, docs/man/ctags-lang-lex.7.rst, man/GNUmakefile.am, man/ctags-lang-lex.7.rst.in, optlib/lex.c, optlib/lex.ctags
In some lexers, all the rules for a condition are grouped together as: 
```
<COND>{
...
}
```
It is useful to be able to jump to these blocks.
Conditions used for grouping are tagged as reference tags having "grouping" role of "cond" kind. So you must add --extras=+r to your ctags cmdline for enabling this support.
Update the parser version to 1.1.
This is derrived from #3937.
=> LEX: make reference tags for the conditions used for making groups

Tmain/extras-field.d/run.sh, Tmain/extras-field.d/stdout-expected.txt, Units/parser-c.r/properties.c.d/args.ctags, Units/parser-c.r/properties.c.d/expected.tags, Units/parser-c.r/properties.c.d/input.c, Units/parser-cxx.r/properties.cpp.d/expected.tags, Units/parser-cxx.r/properties.cpp.d/input.cpp, parsers/cxx/cxx_parser.c
With this pull request, ctags can fill properties: field of `svar` and `fn` in the input like:
```
static struct S { ... } svar;
static struct T { ... } fn(...) { ... }
```
The declaration like:
``` 
static struct T { ... } fn(...);
```
is not in the scope of this pull request because of the bug reported in #3943.
=> C,C++: fix properties field for object defined or declared with structure definitions

Units/parser-terraform.r/local.d/expected.tags, Units/parser-terraform.r/local.d/input.tf, Units/parser-terraform.r/simple-terraform.d/expected.tags, Units/parser-terraform.r/simple-terraform.d/input.tf, docs/man/ctags-lang-terraform.7.rst, man/ctags-lang-terraform.7.rst.in, optlib/terraform.c, optlib/terraform.ctags
This release will fix two know bugs:
=> Terraform: fix two known bugs

main/seccomp.c
The package failed to compile at loong64 for the following detailed reasons:[https://buildd.debian.org/status/fetch.php?pkg=universal-ctags&arch=loong64&ver=5.9.20210829.0-1&stamp= 1709418146&raw=0](url)
=> add support for loongarch

Units/parser-asm.r/gas-section.d/expected.tags, Units/parser-asm.r/gas-section.d/input-1.s, parsers/asm.c
If a section name is built with a macro expansion, the following strings may appear in parts of the string:
* \param,
* \(), and/or
* \@.
The original code didn't consider the characters in the strings, so it cannot extract section names from a macro definition.
Though it is debatable to extract a string including references to macro parameters, ctags may emit the following warning message if we consider the characters as parts of a section name:
ctags: Notice: ignoring null tag ... (line: 13, language: LdScript)
By accepting the characters, we can suppress the warning messages.
=> Asm: relax the condition for accepting characters within a section name

Tmain/load-conf-files-under-default-xdg-config-home.d/run.sh, Tmain/load-conf-files-under-xdg-config-home.d/run.sh, docs/man/ctags.1.rst, docs/option-file.rst, main/options.c, man/ctags.1.rst.in
MS Windows users could benefit from honoring XDG_CONFIG_HOME environment variable as well.
Although some people might thought it was not commonly used on MS Windows.
Actually, some well-known softwares honor this environment variable, as far as I known, git honors this environment variable on all platforms including MS Windows. git introduced this feature as earlier as 2015 (git/git@ea19289) .
Many users host their personal dotfiles on a GitHub repository, they just clone their repository to XDG_CONFIG_HOME, if software do not honor this environment variable, users should do more steps.
fixed #3969
=> honor XDG_CONFIG_HOME environment variable on Windows as well

configure.ac
The lines are 78 characters long.
=> configure.ac: fix result message grammar

main/entry.c, main/general.h, main/main.c, main/options.c, main/options_p.h, main/routines.c, main/sort.c, main/strlist.c, main/writer-ctags.c, main/writer.c, main/writer_p.h, mk_mingw.mak, mk_mvc.mak
This replaces WIN32 with _WIN32 macro to check Windows platform.
The correct one is _WIN32 as documented in the official documentation.
https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros
=> build-sys: fix checking Windows platform with _WIN32 macro

main/entry.c, main/entry.h
When queuing a tagEntryInfo to the cork queue, sourceFileName was strdup'ed.  However, in many cases, the strings for entries in the queue have the same value.  We can reduce memory allocations by using the same buffer as we did in the inputFileName member.
Under massif, I measured the peek memory usage of ctags processes indexing the source tree of the Linux kernel.
Without this change, the peak is 132.7 MiB.
With this change, the peak is 121.9 MiB.
=> main: don't allocate a buffer for tagEntryInfoX::sourceFileName if possible

parsers/vera.c
Add a comment to tell the compiler the fallthrough is intentional, so it doesn't warn about it.
=> vera: Explicit fallthrough

Units/parser-javascript.r/contextual.d/expected.tags, Units/parser-javascript.r/contextual.d/input.js, Units/parser-javascript.r/qualified-contextual.d/expected.tags, Units/parser-javascript.r/qualified-contextual.d/input.js, parsers/jscript.c
As the title says, better handle contextual keywords as function, property and method identifiers.
All these are probably fairly rare, but some did appear in e.g. a minified jQuery, leading to emitting null tags.  Now, only the actually empty-named property it contains (`""://…`) leads to emitting a null tag.
This mostly builds up the `get` and `set` handling for all contextual keywords valid in these situations.
=> JavaScript: Improve support for contextual keywords as identifiers

Units/parser-powershell.r/enum-powershell.d/expected.tags, docs/man-pages.rst, docs/man/ctags-lang-powershell.7.rst, man/GNUmakefile.am, man/ctags-lang-powershell.7.rst.in, parsers/powershell.c
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_enum?view=powershell-7.4
---
:warning: Beware, I don't know anything about PowerShell!  Yet, this seemed easy and useful enough.
If anybody with actual PowerShell knowledge could give this an overview that'd be great.  @eht16 @kumarstack55 @iaalm maybe?
The thing that most likely might need changing is the kind name.  I used the "common" name for this type of construct, but maybe a more PowerShell-y one would be better, I don't know.
=> powershell: Parse enum labels

Units/parser-cxx.r/export-using.d/args.ctags, Units/parser-cxx.r/export-using.d/expected.tags, Units/parser-cxx.r/export-using.d/input.cpp, Units/parser-cxx.r/export-using.d/validator, parsers/cxx/cxx_parser_using.c
=> C++: record "export" in the property field if the keyword is put at a "using" declaration

main/entry.c
This one is for debugging #4011. However, the change is generic.
=> main: report errors when calling ftell(3) fails

main/entry.c
Suggested by @k-takata on #4012.
=> main: fix a typo in an error message

Units/parser-make.r/in-define.d/args.ctags, Units/parser-make.r/in-define.d/expected.tags, Units/parser-make.r/in-define.d/input.mak, Units/parser-make.r/make.include.d/expected.tags, parsers/automake.c, parsers/make.c, parsers/make.h
The original code doesn't extract X in:
define m
X = 1
endef
$(eval $(call m))
~TODO: record m as the scope of X.~ (done)
=> Make: parse inside define/endef

.github/workflows/building-with-pegof.yml, Makefile.am, configure.ac, docs/autotools.rst, docs/news/HEAD.rst, main/options.c, peg/.gitignore, source.mak
Pegof is a PEG grammar optimizer and formatter developed at https://github.com/dolik-rce/pegof.
This change is for utilizing pegof for optimizing our peg based parsers.
We assume pegof is installed at ${somewhere}/pegof.
$ ./autogen.sh
$ ./configure ... --with-pegof=${somewhere}/pegof ...
$ make
To verify the command line invoking pegof, pass V=1 option to make like:
$ make V=1
Makefile runs pegof to generate a .pego file from the given .peg file. Then, it runs packcc to generate .c and .h files from the .pego file. Via make command, you can generate a specified pego file directly. e.g.
$ make V=1 peg peg/varlink.pego
This may be helpful for debugging pegof.
If you successfully build ctags with pegof, you will see "pegof" in the output of ./ctags—-list-features.
TODO:
=> build-sys: utilize pegof

docs/man/ctags.1.rst, man/ctags.1.rst.in
* use backticks instead of single quotes
* use double dashes for long option name
=> Fix quotes & option syntax in manpage

.github/workflows/building-with-pegof.yml, main/options.c, main/parse.c, main/parse_p.h
NOTE: This is a hidden extension. We don't update the help messages and the description of the man pages for this extension.
This extension is for choosing parsers for testing. e.g. running test cases related to PEG-based parsers only:
make units LANGUAGES="$(./ctags --list-languages=_packcc |  tr '\n' ',')"
As the alternative to "_packcc", you can specify "_libxml" or "_libyaml" as the argument for the option.
=> main: extend --list-languages option to list only parsers using packcc

Units/parser-iniconf.r/simple-pythonLoggingConfig.d/expected.tags, Units/parser-iniconf.r/simple-pythonLoggingConfig.d/input.conf, parsers/iniconf.c
The iniconf parser can be used as a poor man's TOML parser which can contain '.' and '-' inside keys. Also, since there's no official ini specification, I can imagine some ini dialects allow this too.
I'm now aware of https://github.com/universal-ctags/ctags/pull/3509 as mentioned in https://github.com/geany/geany/pull/3934 but right now we don't use PEG parsers in Geany and we'd have to evaluate its performance so we'll probably stick with this parser for TOML for now.
=> iniconf: Allow dot and dash for ini keys

Tmain/list-mline-regex-flags.d/stdout-expected.txt, Tmain/list-mtable-regex-flags.d/stdout-expected.txt, Tmain/list-regex-flags.d/stdout-expected.txt, Tmain/option-no-such-foreign-extra.d/run.sh, Tmain/option-no-such-foreign-extra.d/stderr-expected.txt, Tmain/option-no-such-foreign-field.d/run.sh, Tmain/option-no-such-foreign-field.d/stderr-expected.txt, Tmain/parser-own-extras-for-foreign-lang.d/input-0.x1, Tmain/parser-own-extras-for-foreign-lang.d/input-1.x1, Tmain/parser-own-extras-for-foreign-lang.d/run.sh, Tmain/parser-own-extras-for-foreign-lang.d/stdout-expected.txt, Tmain/parser-own-extras-for-foreign-lang.d/x0.ctags, Tmain/parser-own-extras-for-foreign-lang.d/x1.ctags, Tmain/parser-own-fields-for-foreign-lang.d/input.unknownx, Tmain/parser-own-fields-for-foreign-lang.d/knownz.ctags, Tmain/parser-own-fields-for-foreign-lang.d/run.sh, Tmain/parser-own-fields-for-foreign-lang.d/stderr-expected.txt, Tmain/parser-own-fields-for-foreign-lang.d/stdout-expected.txt, Tmain/parser-own-fields-for-foreign-lang.d/unknownx.ctags, docs/optlib.rst, main/lregex.c
These are mergeable parts in #3960.
I'm using the feature proposed in this pull request like this:
```
--langdef=KernelConfig{_foreignLanguage=Kconfig}
--_roledef-Kconfig.{config}=set,set in .config file
--_roledef-Kconfig.{config}=unset,unset in .config file
--map-KernelConfig=.config
--regex-KernelConfig=/^CONFIG_([^=]+)/\1/c/{_language=Kconfig}{_role=set}
--regex-KernelConfig=/^(CONFIG_[^=]+)/\1/c/{_language=Kconfig}{_role=set}{_extra=configPrefixed}{exclusive}
--regex-KernelConfig=/^\# CONFIG_([^ ]+) is not set/\1/c/{_language=Kconfig}{_role=unset}{exclusive}
--regex-KernelConfig=/^\# (CONFIG_[^ ]+) is not set/\1/c/{_language=Kconfig}{_role=unset}{_extra=configPrefixed}{exclusive}
```
The KernelConfig parser extracts "CONFIG_FOO=..." from foo.config.
The definition of CONFIG_FOO is in …
=> Main:  use extras and fields in the foreign language specified in {_language=...} flag

.github/workflows/testing-on-msys2.yml
Reference: https://www.msys2.org/news/#2024-09-23-starting-to-drop-the-clang32-environment
=> GitHub Actions: drop the MSYS2/CLANG32 environment

.github/workflows/testing-on-netbsd.yml
Don't try to install libxml2. libxml2 has already been pre-installed, if we try to install it, it will result in upgrading curl and it's dependencies. we do not use curl here.
=> GitHub Actions: fix netbsd pkgin error.

Units/parser-iniconf.r/toml-support-in-geany.d/args.ctags, Units/parser-iniconf.r/toml-support-in-geany.d/expected.tags, Units/parser-iniconf.r/toml-support-in-geany.d/input.toml, parsers/iniconf.c
These two patches:
- improve parsing of TOML `[[arrays_of_tables]]`
- support `'single quoted keys' = true` and `"double quoted keys" = true`
See the individual commits for more details.
=> iniconf: some more adjustments for parsing TOML

misc/units.py
After upgrading to Fedora 41, I got:
./misc/units.py:366: DeprecationWarning: 'count' is passed as positional argument
input_expected = './Units' + re.sub(r'^.*?/Units', r'', input_actual, 1)
when running "make units".
=> units.py: pass `count' as a keyword argument

parsers/verilog.c
The list of Verilog keywords fetched from Appendix B of the Verilog standard accidentally captured the footnote "1" in keyword `unsigned¹`:
> ### List of keywords
> ... triand trior trireg **unsigned¹** use uwire vectored ...
>> ¹ **unsigned** is reserved for possible future usage
=> verilog.c: keyword "unsigned1" should be "unsigned", without the 1

Units/parser-verilog.r/systemverilog-class.d/expected.tags, Units/parser-verilog.r/systemverilog-class.d/input.sv, parsers/verilog.c
The syntax for class declaration is outdated and has been updated in the latest version of the LRM.
Please refer to latest [IEEE Std 1800-2023](https://standards.ieee.org/ieee/1800/7743/) 8.3 Syntax:
> ```
> [ virtual ] class [ final_specifier ] class_identifier [ parameter_port_list ]
>     final_specifier ::= : final
> ```
In any case, this PR just makes a very minor change to adapt it, making it as harmless as possible.
@hirooih Please Take a Look, Thanks a lot!
=> Verilog: Add final_specifier support for class parse

Units/parser-verilog.r/systemverilog-checker.d/expected.tags, Units/parser-verilog.r/systemverilog-directive.d/expected.tags, Units/parser-verilog.r/systemverilog-github3712.d/expected.tags, parsers/verilog.c
fix for #4127: do not add scope to define.
Some `expected.tags` files are also updated.
=> verilog: do not add scope to define (#4127)

Units/parser-verilog.r/systemverilog-github4056.d/expected.tags, Units/parser-verilog.r/systemverilog-github4056.d/input.sv, parsers/verilog.c
This is a fix to support the following coding style.
```verilog
typedef enum logic {
aaa,
bbb
`ifdef bar
,ccc
`endif
} ifdef2_e;
```
=> verilog: support ifdef in enum

misc/units.py
The format-NlKkFnP test starts failing after MSYS2's python has been updated from python-3.12.7-2 to python-3.12.7-3.
It seems that shutil.which() fails in python-3.12.7-3. Check the existence of the filter file on Windows.
Also, fixed a typo in CMDLINE.tmp.
Fixes #4132.
=> units.py: Fix format-NlKkFnP on Windows

.github/workflows/cross-compile-for-android-on-macos.yml, .github/workflows/cross-compile-for-windows-on-macos.yml, .github/workflows/testing-on-macos.yml
Reference: https://github.com/actions/runner-images/issues/10721
=> GitHub Actions: removing macos-12 runner due to it is fully unsupported as of 2024-12.03

Units/noext-tg-objc.d/expected.tags, Units/objc-tg-corpus.d/expected.tags, Units/parser-objectivec.r/objc-signature.d/expected.tags, Units/parser-objectivec.r/objectivec_implementation.m.d/expected.tags, Units/parser-objectivec.r/objectivec_interface.h.d/expected.tags, Units/writer-xref.r/format-NlKkFnP.d/expected.tags-x, parsers/objc.c
The original code records the line numbers of ';' or '{' at the end of method declarations or definitions.
Close #4161
=> ObjectiveC: (bugfix) extract the line numbers for methods correctly

Tmain/list-fields-with-prefix.d/stdout-expected.txt, Tmain/list-fields.d/stdout-expected.txt, Units/option-regex-attaching-role.r/extending-existing-parser.d/expected.tags, docs/man-pages.rst, docs/man/ctags-lang-clojure.7.rst, docs/man/ctags-lang-scheme.7.rst, man/GNUmakefile.am, man/ctags-lang-clojure.7.rst.in, man/ctags-lang-scheme.7.rst.in, parsers/clojure.c, parsers/lisp.c, parsers/scheme.c, parsers/x-lisp.h, source.mak, win32/ctags_vs2013.vcxproj, win32/ctags_vs2013.vcxproj.filters
This one is not S expression-based but still line-oriented. However, the meta parser supports all Lisp, EmacsLisp, Clojure, and Scheme like before.
=> Lisp: introduce version 0.0 of lisp meta parser

Units/parser-cxx.r/complex-macros.d/args.ctags, Units/parser-cxx.r/complex-macros.d/expected.tags, Units/parser-cxx.r/complex-macros.d/input.cpp, parsers/cpreprocessor.c
Consider input:
#define debug(format, args...) fprintf (stderr, format, args)
With this change,
* ctags extracts "args" with parameter kind,
* ctags extracts "debug" with "(format,args...)" as
the signature field.
The option like
-D'debug(format, args...)=fprintf (stderr, format, args)'
also works with this change.
=> CPreProcessor: support variadic macros with GNU cpp extension syntax 

docs/man-pages.rst, docs/man/ctags-lang-meson.7.rst, man/GNUmakefile.am, man/ctags-lang-meson.7.rst.in, optlib/meson.c, optlib/meson.ctags
With this change, the parser can extract "version" in the following input:
conf_data = configuration_data()
conf_data.set('version', '1.2.3')
configure_file(input : 'config.h.in',
output : 'config.h',
configuration : conf_data)
See also https://mesonbuild.com/Reference-manual_returned_cfg_data.html
=> Meson: extract config variables

Units/parser-javascript.r/js-implicit-semicolons.d/expected.tags, Units/parser-javascript.r/js-implicit-semicolons.d/input.js, parsers/jscript.c
When emitting a held token, the previous token type was not properly updated, breaking the implicit semicolon emission logic for the next token.
Fixes #4192.
=> JavaScript: Fix held tokens breaking implicit semicolon insertion

Units/parser-asm.r/asm-cpp-macro-expansion-with-multi-line-args.d/args.ctags, Units/parser-asm.r/asm-cpp-macro-expansion-with-multi-line-args.d/expected.tags, Units/parser-asm.r/asm-cpp-macro-expansion-with-multi-line-args.d/input.S, Units/parser-asm.r/asm-cpp-macro-expansion.d/expected.tags, parsers/asm.c
The patterns in expected.tags are unexpected.
Some parts of them may be fixed in #4198 I'm working on.
=> Asm: support Cpp macro arguments spanning multiple lines

Units/parser-javascript.r/simple-jsx-no-guest.d/args.ctags, Units/parser-javascript.r/simple-jsx-no-guest.d/expected.tags, Units/parser-javascript.r/simple-jsx-no-guest.d/input-0.jsx, Units/parser-javascript.r/simple-jsx-no-guest.d/input.jsx, Units/parser-javascript.r/simple-jsx.d/args.ctags, Units/parser-javascript.r/simple-jsx.d/input-0.jsx, parsers/html.c, parsers/jscript.c, parsers/x-html.h, parsers/x-jscript.h, source.mak, win32/ctags_vs2013.vcxproj, win32/ctags_vs2013.vcxproj.filters
This may fix the issue reported at
https://stackoverflow.com/questions/79395369/why-does-universal-ctags-fail-to-record-some-functions-in-the-tags-file-for-a-pr
TODO:
* add more test cases
* extract objects in JavaScript area in HTML area in JavaScript area
=> JavaScript,HTML: skip JSX elements

mk_mvc.mak
As reported in #4203, we got "multiply defined symbols" errors on the "build with Vistual Studio / NMake" check:
nl_langinfo.obj : error LNK2005: __check_arch_support already defined in regex.obj
nl_langinfo.obj : error LNK2005: __check_isa_avx10_512 already defined in regex.obj
nl_langinfo.obj : error LNK2005: __check_isa_support already defined in regex.obj
nl_langinfo.obj : error LNK2005: _get_vlen already defined in regex.obj
setlocale_null.obj : error LNK2005: __check_arch_support already defined in regex.obj
setlocale_null.obj : error LNK2005: __check_isa_avx10_512 already defined in regex.obj
setlocale_null.obj : error LNK2005: __check_isa_support already defined in regex.obj
setlocale_null.obj : error LNK2005: _get_vlen already defined in regex.obj
dynarray_resize.obj : error …
=> buildsys: (msvc) avoid "multiply defined symbols" errors

.github/workflows/cross-compile-for-android-on-ubuntu.yml, .github/workflows/cross-compile-for-windows-on-ubuntu.yml, .github/workflows/testing-on-ubuntu.yml
The Ubuntu 20.04 Actions runner image is being deprecated and will be fully unsupported by 2025-04-01
Reference: https://github.com/actions/runner-images/issues/11101
=> GitHub Actions: remove ubuntu-20.04 runner

circle.yml
In sqlite-libs 3.46.1-1, sqlite-session feature was turned off. It was turned on in 3.46.1-2.
Nodejs that we used in a validitor requires the feature.
=> Circleci:  (fedora41) update libsqlite.so explicitly

main/entry.c, main/mio.c, main/mio.h, main/promise.c, main/read.c, parsers/html.c
This is a preparation for #4212.
=> main: various minor improvements, especially about mio

Units/parser-cxx.r/cxx11-attributes.cpp.d/input.cpp, Units/parser-cxx.r/cxx11-broken-nested-attributes.cpp.d/expected.tags, Units/parser-cxx.r/cxx11-broken-nested-attributes.cpp.d/input-0.cxx, Units/parser-cxx.r/cxx11-broken-nested-attributes.cpp.d/input.cxx, parsers/cxx/cxx_parser.c, parsers/cxx/cxx_parser_internal.h, parsers/cxx/cxx_parser_tokenizer.c
Fixed #4089
An assertion failed for the input "[[[]]]".
=> C++: skip broken C++11 attributes

parsers/v.c
This change avoids the trouble reported in #4235.
=> V: don't use multi-bytes chars in debug print

.github/workflows/testing-on-alpine.yml
The tests on Qemu hung frequently.
I had to cancel them before manually restarting them. 
The timeout reduced the steps I have to take to restart.
=> GitHub Actions: set timeout to tests on Qemu

Units/parser-clojure.r/clojure-methods.b/README, Units/parser-clojure.r/clojure-methods.b/args.ctags, Units/parser-clojure.r/clojure-methods.b/expected.tags, Units/parser-clojure.r/clojure-methods.b/input.clj, Units/parser-clojure.r/clojure-vars.b/args.ctags, Units/parser-clojure.r/clojure-vars.b/expected.tags, Units/parser-clojure.r/clojure-vars.b/input.clj
Hi! Here's some Clojure tests for #4123. That's not all, but it's the most frequently used things—vars and multimethods.
=> Tests for more Clojure tags

Tmain/list-subparsers-all.d/stdout-expected.txt, Tmain/nested-subparsers.d/stdout-expected.txt, Units/parser-jni.r/broken.d/args.ctags, Units/parser-jni.r/broken.d/expected.tags, Units/parser-jni.r/broken.d/input.c, Units/parser-jni.r/simple.d/args.ctags, Units/parser-jni.r/simple.d/expected.tags, Units/parser-jni.r/simple.d/input-0.cpp, Units/parser-jni.r/simple.d/input-1.cpp, Units/parser-jni.r/simple.d/input.cpp, docs/news/HEAD.rst, main/parsers_p.h, parsers/cxx/cxx_jni.c, parsers/cxx/cxx_parser_block.c, parsers/cxx/cxx_parser_variable.c, parsers/cxx/cxx_subparser.c, parsers/cxx/cxx_subparser.h, parsers/cxx/cxx_subparser_internal.h, source.mak, win32/ctags_vs2013.vcxproj, win32/ctags_vs2013.vcxproj.filters
~This is a prototype. This must be rewritten in C when merging.~
See https://github.com/universal-ctags/citre/issues/189 about the background of this PR.
```
mkdir -p ~/tmp
$ cd ~/tmp
$ git clone https://android.googlesource.com/platform/frameworks/base
$ cd base
$ time ~/bin/ctags -o ../base.tags --sort=no --fields=+l --kinds-C++=+l --extras=+s --languages=+JNI -R 
ctags: Warning: cannot open input file "native/android/include/android/multinetwork.h" : No such file or directory
~/bin/ctags -o ../base.tags --sort=no --fields=+l --kinds-C++=+l --extras=+s   221.60s user 10.06s system 62% cpu 6:09.77 total
$ ~/bin/readtags -t ../base.tags nativeForkAndSpecialize
nativeForkAndSpecialize core/jni/com_android_internal_os_Zygote.cpp     /^        {"nativeForkAndSpecialize",$/ …
```
=>  JNI: new subparser

.github/workflows/building-with-nmake.yml
Reference: https://github.com/actions/runner-images/issues/12045
=> GitHub Actions: remove windows-19 due to it began deprecation on 2025-06-01 and will be fully unsupported by 2025-06-30

Units/parser-tcl.r/escaping.d/expected.tags, Units/parser-tcl.r/escaping.d/input-0.tcl, parsers/tcl.c
=> Tcl: consider escaping with backslash chars when reading an identifier

docs/man/ctags-lang-verilog.7.rst, man/ctags-lang-verilog.7.rst.in, parsers/verilog.c
fix for #4301,
In addition to above use `--map-SystemVerilog` instead of `--langmap=SystemVerilog` in man page.
=> verilog: map .vh to Verilog (#4301)

Units/parser-meson.r/config-inline.d/args.ctags, Units/parser-meson.r/config-inline.d/expected.tags, Units/parser-meson.r/config-inline.d/input-0.meson, Units/parser-meson.r/config-inline.d/input.meson, docs/news/HEAD.rst, optlib/meson.c, optlib/meson.ctags
I should pull this request into two.
(
This random should be removed from here:
```
input : "\n" L3781
match :'\n'            main[ 0] / ^([a-zA-Z_][a-zA-Z_0-9]*)[ \t\n]*=([^=]|$)/
match :'\n'            main[ 1] / ^project[ \t\n]*\\([ \t\n]*'([^']*[^\\\\])'[ \t\n]*/
match :'\n'            main[ 2] / ^subdir[ \t\n]*\\([ \t\n]*'([^']*[^\\\\])'[ \t\n]*/
match :'\n'            main[ 3] / ^test[ \t\n]*\\([ \t\n]*'([^']*[^\\\\])'[ \t\n]*/
match :'\n'            main[ 4] / ^[ \t\n]+/
...                   TABLE[ N] ...
result: matched 1 bytes
scope : 
action: NOP in {main}, stack: /
```
It would be helpful for optimization if ctags could report per-TABLE statistics (average N, s.d. N, max N).
)
=> Meson: extract config vars defined inside configuration_data({...})
